### ISSUE TITLE
microsoft_updates.bat fails 

### ISSUE THREAD

**Issue by marxenegls** [rapid7/metasploitable3#102]
## Issue Description
in microsoft_updates.bat the script requests servicemanager to create an A: \temp.vbs 

## Host System
* OS: win8.1
* Packer Version:0.12.3
* Vagrant Version:1.9.2
* VirtualBox Version:5.1.16

## Command Output

PS C:\Users\Administrator> net stop wuauserv
The Windows Update service is stopping.
The Windows Update service was stopped successfully.

PS C:\Users\Administrator> reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Upda
te" /v EnableFeaturedSoftware /t REG_DWORD /d 1 /f
The operation completed successfully.
PS C:\Users\Administrator> reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Upda
te" /v IncludeRecommendedUpdates /t REG_DWORD /d 1 /f
The operation completed successfully.
PS C:\Users\Administrator> echo Set ServiceManager = CreateObject("Microsoft.Update.ServiceManager") > A:\temp.vbs
out-file : Cannot find drive. A drive with the name 'A' does not exist.
At line:1 char:1
+ echo Set ServiceManager = CreateObject("Microsoft.Update.ServiceManager") > A:\t ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (A:String) [Out-File], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.OutFileCommand

Ofcoarse so would update_root_certs.bat since it uses drive A:\ as addstore for certs

**Comment by marxenegls** [comment]
It's fixed but i used a workaround which i still have to ok with vagrant . I created a 2Gb secondary master drive.vmdk named A: it mounted after running storage man wiz , i had to adapt the script a little since the  append > wrapped the code , removed the "" and threw syntax error maybe the fact that i ran it on the server itself has something to do with it , since no one else mentioned such an issue. 
I'm guess that once i launch the vbox through vagrant up it will remove the extra drive . so i have a non issue that got temp solved yet soon to be  one again ; (
 i've been fidgeting with this metasplopitable3 for days , i dont want to dump it and start over just yet , i'm too frugal with bandwidth , plus learning something even the long way round is still an experience. Im about to update the certs on that A drive . I dont get how packer missed it, it couldn't be a provisioning misstep since i doubt it could create a drive in vbox through powershell, duh ...

**Comment by Chan9390** [comment]
@marxenegls Can you download the latest code and try running the setup again ? Please comment if you find the same error with the latest code.
