### ISSUE TITLE
vagrant up - vagrant-shell.bat issue

### ISSUE THREAD

**Issue by ghebosu** [rapid7/metasploitable3#104]
## Issue Description
When running vagrant up it halts at 
vagrant-shell.bat

##Host System
* OS: Win 10 x64 
* Packer Version: 0.12.3
* Vagrant Version:1.9.2
* VirtualBox Version: 5.1.16

## Command Output
==> default: C:\Windows\system32>exit
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/configs/apply_password_settings.bat as c:\tmp\vagrant-shell.bat
==> default: C:\Windows\system32>secedit.exe /configure /db C:\Windows\securitynew.sdb /cfg C:\vagrant\resources\security_settings\secconfig.cfg /areas SECURITYPOLICY
==> default: Invalid path - C:\vagrant\resources\security_settings
==> default: Allows you to configure a system with security settings stored in a database.
==> default: The syntax of this command is:
==> default: secedit /configure /db filename [/cfg filename] [/overwrite][/areas area1 area2...] [/log filename] [/quiet]
==> default:             /db filename - Specifies the database used to perform the security configuration.
==> default:             /cfg filename - Specifies a security template to import into the database prior to configuring the computer. Security templates are created using the Security Templates snap-in.
==> default:             /overwrite - Specifies that the database should be emptied prior to importing the security template. If this parameter is not specified, the settings in the security template are accumulated into the database.  If this parameter is not specified
and there are conflicting settings in the database and the template being imported, the template settings win.
==> default:             /areas - Specifies the security areas to be applied to the system. If this parameter is not specified, all security settings defined in the database are applied to the system. To configure multiple areas, separate each area by a space.  The follo
wing security areas are supported:
==> default:                         SECURITYPOLICY - Includes Account Policies, Audit Policies, Event Log Settings and Security Options.
==> default:                         GROUP_MGMT - Includes Restricted Group settings
==> default:                         USER_RIGHTS - Includes User Rights Assignment
==> default:                         REGKEYS - Includes Registry Permissions
==> default:                         FILESTORE - Includes File System permissions
==> default:                         SERVICES - Includes System Service settings
==> default:             /log filename - Specifies a file in which to log the status of the configuration process.  If not specified, configuration processing information is logged in the scesrv.log file which is located in the %windir%\security\logs directory.
==> default:             /quiet - Specifies that the configuration process should take place without prompting the user for any confirmation.
==> default: Example:
==> default: secedit /configure /db hisecws.sdb /cfg hisecws.inf /overwrite /log hisecws.log
==> default: For all filenames, the current directory is used if no path is specified.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:

C:\Windows\system32>secedit.exe /configure /db C:\Windows\securitynew.sdb /cfg C:\vagrant\resources\security_settings\secconfig.cfg /areas SECURITYPOLICY

Invalid path - C:\vagrant\resources\security_settings

Allows you to configure a system with security settings stored in a database.

The syntax of this command is:

secedit /configure /db filename [/cfg filename] [/overwrite][/areas area1 area2...] [/log filename] [/quiet]

            /db filename - Specifies the database used to perform the security configuration.

            /cfg filename - Specifies a security template to import into the database prior to configuring the computer. Security templates are created using the Security Templates snap-in.

            /overwrite - Specifies that the database should be emptied prior to importing the security template. If this parameter is not specified, the settings in the security template are accumulated into the database.  If this parameter is not specified and there are
 conflicting settings in the database and the template being imported, the template settings win.

            /areas - Specifies the security areas to be applied to the system. If this parameter is not specified, all security settings defined in the database are applied to the system. To configure multiple areas, separate each area by a space.  The following security
 areas are supported:

                        SECURITYPOLICY - Includes Account Policies, Audit Policies, Event Log Settings and Security Options.
                        GROUP_MGMT - Includes Restricted Group settings
                        USER_RIGHTS - Includes User Rights Assignment
                        REGKEYS - Includes Registry Permissions
                        FILESTORE - Includes File System permissions
                        SERVICES - Includes System Service settings

            /log filename - Specifies a file in which to log the status of the configuration process.  If not specified, configuration processing information is logged in the scesrv.log file which is located in the %windir%\security\logs directory.

            /quiet - Specifies that the configuration process should take place without prompting the user for any confirmation.

Example:

secedit /configure /db hisecws.sdb /cfg hisecws.inf /overwrite /log hisecws.log

For all filenames, the current directory is used if no path is specified.

Stderr from the command:

**Comment by jamiereid** [comment]
I am having the same issue.
When I log into the windows vm as vagrant user I get a "Location is unavailable" error when trying to open c:\vagrant\resources in Windows Explorer
This is from a clone of the repo earlier today.
Using Vagrant 1.9.2 on arch linux.
VirtualBox version is 5.1.16 r113841

**Comment by ghebosu** [comment]
I just downgraded from vagrant 1.9.2 to 1.9.1 and virtual box from 5.1.16 to 5.1.14 and it seems doing manual build I do not get any error anymore. I think the issue is related to the virtualbox 5.1.16 version.

I will test if the image works as it should be till weekend.

**Comment by jikuja** [comment]
Virtualbox 5.1.18 fixed shared folder issues which was regression bug in 5.1.16. Update or downgrade of virtualbox should fix the problem.

**Comment by jbarnett-r7** [comment]
Upgrading to 5.1.18 is confirmed as the fix. Also mentioned here: https://github.com/rapid7/metasploitable3/issues/97

Closing...

**Comment by ike-9** [comment]
Having same issue. Cloned the repository just today.
OS: Windows 10 Home x64
Vagrant: 2.2.6
Packer:1.5.1
Virtual Box: 6.0.16
