### ISSUE TITLE
User names are miss-spelled

### ISSUE THREAD

**Issue by anance25** [rapid7/metasploitable3#105]
## Issue Description
User names are miss-spelled.  The correct spellings are:

- Leia Organa (pronounced "LAY UHH" not "LEE UHH")
- Chewbaacca

Perhaps this is intentional obfuscation, but we all know that security-by-obscurity is no security at all.  

![screen shot 2017-03-16 at 4 27 58 pm](https://cloud.githubusercontent.com/assets/17015866/24019420/ded98fdc-0a65-11e7-9850-f2ab2908c686.png)

References:

http://starwars.wikia.com/wiki/Leia_Organa
http://starwars.wikia.com/wiki/Chewbaacca

`</snark>`

**Comment by codemonkey2841** [comment]
"Chewbaacca was a clone of the legendary Wookiee warrior Chewbacca." <- http://starwars.wikia.com/wiki/Chewbaacca

**Comment by anance25** [comment]
Aww fail.  *surrenders geek card*  
I stand by the Leia correction though.

**Comment by jbarnett-r7** [comment]
You know I was looking at the other day thinking it looked funny. I failed to check Google to confirm, though. Do you mind putting up a PR to fix this critical issue?
