### ISSUE TITLE
vagrant up Unknown configuration section 'omnibus'.

### ISSUE THREAD

**Issue by gearcapitan** [rapid7/metasploitable3#113]
```
PS C:\Users\gearc\Documents\metasploitable3-master> vagrant up
Bringing machine 'win2k8' up with 'virtualbox' provider...
Bringing machine 'trusty' up with 'virtualbox' provider...
==> win2k8: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> win2k8: flag to force provisioning. Provisioners marked to run always will still run.
==> trusty: Box 'rsginc/ubuntu64-14-04-1' could not be found. Attempting to find and install...
    trusty: Box Provider: virtualbox
    trusty: Box Version: >= 0
==> trusty: Loading metadata for box 'rsginc/ubuntu64-14-04-1'
    trusty: URL: https://atlas.hashicorp.com/rsginc/ubuntu64-14-04-1
==> trusty: Adding box 'rsginc/ubuntu64-14-04-1' (v1.0.4) for provider: virtualbox
    trusty: Downloading: https://atlas.hashicorp.com/rsginc/boxes/ubuntu64-14-04-1/versions/1.0.4/providers/virtualbox.box
    trusty: Progress: 100% (Rate: 1017k/s, Estimated time remaining: --:--:--)
==> trusty: Successfully added box 'rsginc/ubuntu64-14-04-1' (v1.0.4) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:
```

Vagrant:
* Unknown configuration section 'omnibus'.

PS C:\Users\gearc\Documents\metasploitable3-master>
![sin titulo](https://cloud.githubusercontent.com/assets/13740942/24589701/c1e9bf36-17a4-11e7-8611-b89240777fb6.png)

**Comment by Soulence** [comment]
I have also replicated this issue, in the process of removing everything i have other issues but want to track this one as well.

**Comment by V-P-K** [comment]
You can fix this by running "vagrant plugin install vagrant-omnibus"

**Comment by Soulence** [comment]
Installing now, going to replicate that issue. see if it solves the issue, thank you.

**Comment by jbarnett-r7** [comment]
This is my bad. I accidentally landed code to master that contains the setup for the new Linux VM. That stuff is not ready to be in master yet, so I'm going to remove that and it should clean up the omnibus errors.

**Comment by gearcapitan** [comment]
I already fix it but now I have another major problem, it is simply impossible to create the metaspotable gives this error: #112 
@jbarnett-r7

**Comment by jbarnett-r7** [comment]
Fixed by reverting the incorrect merge.
