### ISSUE TITLE
Error: NET HELPMSG 2185 (during Vagrant) (possible glass fish issue) 

### ISSUE THREAD

**Issue by Soulence** [rapid7/metasploitable3#115]
## Issue Description
NET HELPMSG 2185, 
VM shows in virtual box, upon boot gets an RC error. 

Vagrant box list 
metasploitable3         (virtualbox, 0)
rsginc/ubuntu64-14-04-1 (virtualbox, 1.0.4)

## Host System
* OS: Win 10 64
* Packer Version: 0.12.3
* Vagrant Version: 1.9.2
* VirtualBox Version: 5.18

## Command Output
==> win2k8:         0 file(s) copied.
==> win2k8: C:\Windows\system32>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"
==> win2k8: C:\Windows\system32>net start domain1
==> win2k8: C:\Windows\system32>powershell -Command "Start-Sleep -s 5"
==> win2k8: The system cannot find the path specified.
==> win2k8: The system cannot find the path specified.
==> win2k8: The system cannot find the path specified.
==> win2k8: The system cannot find the path specified.
==> win2k8: The service name is invalid.
==> win2k8: More help is available by typing NET HELPMSG 2185.
==> win2k8: C:\Windows\system32>net stop domain1
==> win2k8: C:\Windows\system32>icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
==> win2k8: processed file: C:\glassfish
==> win2k8: Successfully processed 1 files; Failed processing 0 files
==> win2k8: C:\Windows\system32>sc config domain1 obj= "NT Authority\LOCAL SERVICE"
==> win2k8: [SC] OpenService FAILED 1060:    
==> win2k8: The specified service does not exist as an installed service.
==> win2k8: The service name is invalid.
==> win2k8: More help is available by typing NET HELPMSG 2185.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:

C:\Windows\system32>mkdir C:\glassfish

C:\Windows\system32>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')"  0<NUL

C:\Windows\system32>cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"

C:\Windows\system32>copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\admin-keyfile"
        0 file(s) copied.

C:\Windows\system32>copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\domain.xml"
        0 file(s) copied.

C:\Windows\system32>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"

C:\Windows\system32>net start domain1

C:\Windows\system32>powershell -Command "Start-Sleep -s 5"

C:\Windows\system32>net stop domain1

C:\Windows\system32>icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
processed file: C:\glassfish
Successfully processed 1 files; Failed processing 0 files

C:\Windows\system32>sc config domain1 obj= "NT Authority\LOCAL SERVICE"
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

Stderr from the command:

The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

The service name is invalid.

More help is available by typing NET HELPMSG 2185.

**Comment by Soulence** [comment]
win2k8: Running: scripts/installs/setup_glassfish.bat as c:\tmp\vagrant-shell.bat
==> win2k8: C:\Windows\system32>mkdir C:\glassfish
==> win2k8: C:\Windows\system32>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.jav
a.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')"  0<NUL
==> win2k8: C:\Windows\system32>cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glass
fish"
==> win2k8: C:\Windows\system32>copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfis
h\domains\domain1\config\admin-keyfile"
==> win2k8:         0 file(s) copied.
==> win2k8: C:\Windows\system32>copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\d
omains\domain1\config\domain.xml"
==> win2k8:         0 file(s) copied.
==> win2k8: C:\Windows\system32>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"
==> win2k8: C:\Windows\system32>net start domain1
==> win2k8: C:\Windows\system32>powershell -Command "Start-Sleep -s 5"
==> win2k8: The system cannot find the path specified.
==> win2k8: The system cannot find the path specified.
==> win2k8: The system cannot find the path specified.
==> win2k8: The system cannot find the path specified.
==> win2k8: The service name is invalid.
==> win2k8: More help is available by typing NET HELPMSG 2185.
==> win2k8: C:\Windows\system32>net stop domain1
==> win2k8: C:\Windows\system32>icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
==> win2k8: processed file: C:\glassfish
==> win2k8: Successfully processed 1 files; Failed processing 0 files
==> win2k8: C:\Windows\system32>sc config domain1 obj= "NT Authority\LOCAL SERVICE"
==> win2k8: [SC] OpenService FAILED 1060:
==> win2k8: The specified service does not exist as an installed service.
==> win2k8: The service name is invalid.
==> win2k8: More help is available by typing NET HELPMSG 2185.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:


C:\Windows\system32>mkdir C:\glassfish

C:\Windows\system32>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassf
ish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')"  0<NUL

C:\Windows\system32>cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"

C:\Windows\system32>copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfish\domains\do
main1\config\admin-keyfile"
        0 file(s) copied.

C:\Windows\system32>copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\domains\domai
n1\config\domain.xml"
        0 file(s) copied.

C:\Windows\system32>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"

C:\Windows\system32>net start domain1

C:\Windows\system32>powershell -Command "Start-Sleep -s 5"

C:\Windows\system32>net stop domain1

C:\Windows\system32>icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
processed file: C:\glassfish
Successfully processed 1 files; Failed processing 0 files

C:\Windows\system32>sc config domain1 obj= "NT Authority\LOCAL SERVICE"
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.



Stderr from the command:

The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

The service name is invalid.

More help is available by typing NET HELPMSG 2185.

PS C:\Users\Joe\Downloads\metasploitable3-master> NET HELPMSG 2185

The service name is invalid.

**Comment by jbarnett-r7** [comment]
```
==> win2k8: C:\Windows\system32>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.jav
a.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')" 0<NUL
==> win2k8: C:\Windows\system32>cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glass
fish"
==> win2k8: C:\Windows\system32>copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfis
h\domains\domain1\config\admin-keyfile"
==> win2k8: 0 file(s) copied.
==> win2k8: C:\Windows\system32>copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\d
omains\domain1\config\domain.xml"
==> win2k8: 0 file(s) copied.
==> win2k8: C:\Windows\system32>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"
```
These lines make it look like the script was unable to copy the config files from the share directory that is setup between metasploitable3 and your host PC. So one of three things happened:

1. The glassfish file didn't download properly. To check, open up the VM in VirtualBox and go to C:\Windows\Temp and see if the glassfish4.zip file is there.
2. The zip file didn't extract correctly. To check, go to C:\glassfish and make sure the files exist.
3. The shared folder isn't accessible. To check, open up the VM in VirtualBox and go to C:\vagrant\resources\glassfish and make sure the admin-keyfile and domain.xml files are present.

Can you please try those 3 steps and let me know the results?

**Comment by gearcapitan** [comment]
@jbarnett-r7 
I already made sure that all that, the error was that there was a + and - in the glassfish installer script

 mkdir C:\glassfish
 powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')" <NUL
-cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"
+cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"
 copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\admin-keyfile"
 copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\domain.xml"
 cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"


to 



 mkdir C:\glassfish
 powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')" <NUL
cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"
cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"
 copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\admin-keyfile"
 copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\domain.xml"
 cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"


And ready, basically was that, but still the vm does not start, gives me these errors, which continues?
terminal output
![sin titulo](https://cloud.githubusercontent.com/assets/13740942/24735754/137a26d6-1a4a-11e7-8a4c-16bd1d05b79c.png)
virtualbox
![sin titulo2](https://cloud.githubusercontent.com/assets/13740942/24735763/1d9a7008-1a4a-11e7-8c9b-fa3e9365a4b4.png)

**Comment by gearcapitan** [comment]
@jbarnett-r7 any advice?

**Comment by jbarnett-r7** [comment]
It seems really strange that you're all of a sudden getting the VirtualBox errors again. I thought we got passed that by downgrading. Did you VirtualBox update? Can you confirm which version you're on?

**Comment by gearcapitan** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13740942/24809329/c386830e-1b84-11e7-85f3-4df5ef6d71bb.png)
@jbarnett-r7

**Comment by jbarnett-r7** [comment]
@gearcapitan As @chan9390 mentioned in the other thread there [appears to be issues with VirtualBox and Windows 10](http://stackoverflow.com/questions/31736495/virtualbox-windows-10-64-bit-host-the-vm-session-was-aborted). I don't have a Windows 10 box to test building on to see if I can repro the issue, but we may need to make some tweaks to the Vagrant/Packer provisioning regarding the virtual IDE devices to support those OS. There are other things that are a little bit higher priority than that for me right now. Would you be willing to do some research on Vagrant/Packer and Windows 10 hosts to see if you can find the solution and put up a PR?

**Comment by Chan9390** [comment]
Added this as a general issue. Closing this issue as it is not active. Please reopen if required.
