### ISSUE TITLE
VMWare Provider Support

### ISSUE THREAD

**Issue by GabrielTK** [rapid7/metasploitable3#116]
## Issue Description
Good Evening,
Just a quick suggestion, why don't you add VMWare Provider support?? I think only the build script needs to be modified. I may submit a PR later

## Host System
* OS: -
* Packer Version: -
* Vagrant Version: -
* VirtualBox Version -:

**Comment by busterb** [comment]
It has been in there for months:  https://github.com/rapid7/metasploitable3/pull/65

The plugin is not free, which is why we don't offer it by default.

**Comment by GabrielTK** [comment]
Ok, sorry :( I'm new in this repo.

On Apr 2, 2017 11:50 PM, "Brent Cook" <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #116<https://github.com/rapid7/metasploitable3/issues/116>.

**Comment by busterb** [comment]
No worries. If you feel like adding something to the outer shell scripts that allow selecting these interactively, go for it. We'll gladly take a look at your PR.
