### ISSUE TITLE
Ubuntu Installation - All services not available

### ISSUE THREAD

**Issue by ravisankar90** [rapid7/metasploitable3#120]
## All Services are not available on Ubuntu Installation
I tried installing automatically (with build_win2008.sh) and manually in Ubuntu. The issue I am facing is not all services are running in the OS including IIS. So I logged into the system via Virtualbox & tried searching the resources folder which should be under "C:\\vagrant" But I get an error message that the target network location is not available. 
Screenshot Available.

I even tried editing the Vagrant file to include the resources folder to C:\\vagrant" but no luck.

What could be the reason ?

## Host System
* OS: Ubuntu 16.04 XENIAL
* Packer Version: 0.12.3
* Vagrant Version: 1.9.3
* VirtualBox Version: 5.1.10 r112026

![virtualbox_metasploitable3_default_1491485630364_5160_06_04_2017_19_18_16](https://cloud.githubusercontent.com/assets/21196423/24757808/e7c72278-1afd-11e7-9495-ae0cc2530114.png)

![virtualbox_kali linux_06_04_2017_19_34_17](https://cloud.githubusercontent.com/assets/21196423/24758445/110760c4-1b00-11e7-9ff6-6fab1e839c50.png)

**Comment by gearcapitan** [comment]
Are your virtual machines configured in bridge mode?

**Comment by ravisankar90** [comment]
Anyone here ?

**Comment by jbarnett-r7** [comment]
Sorry for the late reply. We've been noticing some issues here when building on newer versions of Vagrant. Can you please try [downgrading to Vagrant 1.9.1](https://releases.hashicorp.com/vagrant/1.9.1/), running `vagrant destroy`, then `vagrant up`?

**Comment by Chan9390** [comment]
Hey @ravisankar90 any updates ?

**Comment by Chan9390** [comment]
Closing the issue as there are no updates. If you still get the error, please reopen.
