### ISSUE TITLE
SSH Timeout Error

### ISSUE THREAD

**Issue by Shubhamingle82396** [rapid7/metasploitable3#122]
packer build windows_2008_r2_vmware.json
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: http://127.0.0.1/en_windows_server_2008_r2_with_sp1_x64_dvd_617601.iso
==> vmware-iso: Creating floppy disk...
    vmware-iso: Copying files flatly from floppy_files
    vmware-iso: Copying file: ./answer_files/2008_r2/Autounattend.xml
    vmware-iso: Copying file: ./scripts/configs/microsoft-updates.bat
    vmware-iso: Copying file: ./scripts/configs/win-updates.ps1
    vmware-iso: Copying file: ./scripts/installs/openssh.ps1
    vmware-iso: Copying file: ./resources/certs/oracle-cert.cer
    vmware-iso: Copying file: ./resources/certs/gdig2.crt
    vmware-iso: Copying file: ./resources/certs/comodorsadomainvalidationsecureserverca.crt
    vmware-iso: Copying file: ./resources/certs/comodorsacertificationauthority.crt
    vmware-iso: Copying file: ./resources/certs/addtrust_external_ca.cer
    vmware-iso: Copying file: ./resources/certs/baltimore_ca.cer
    vmware-iso: Copying file: ./resources/certs/digicert.cer
    vmware-iso: Copying file: ./resources/certs/equifax.cer
    vmware-iso: Copying file: ./resources/certs/globalsign.cer
    vmware-iso: Copying file: ./resources/certs/gte_cybertrust.cer
    vmware-iso: Copying file: ./resources/certs/microsoft_root_2011.cer
    vmware-iso: Copying file: ./resources/certs/thawte_primary_root.cer
    vmware-iso: Copying file: ./resources/certs/utn-userfirst.cer
    vmware-iso: Done copying files from floppy_files
    vmware-iso: Collecting paths from floppy_dirs
    vmware-iso: Resulting paths from floppy_dirs : []
    vmware-iso: Done copying paths from floppy_dirs
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting virtual machine...
    vmware-iso: The VM will be run headless, without a GUI. If you want to
    vmware-iso: view the screen of the VM, connect via VNC with the password "90eo48UX" to
    vmware-iso: vnc://127.0.0.1:5936
==> vmware-iso: Waiting 2m0s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
****==> vmware-iso: Waiting for SSH to become available...
==> vmware-iso: Timeout waiting for SSH.
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Timeout waiting for SSH.**

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Timeout waiting for SSH.**

==> Builds finished but no artifacts were created...

**Comment by x42en** [comment]
Is your firewall configured ? I've been able to avoid this issue by disabling it (even if this appears to deal with 127.0.0.1 I know :D )

**Comment by x42en** [comment]
After multiple checks it appears that my VM was using too much RAM that my virtualbox instance could handle.. so VM was simply aborted. Double check your settings, and start the generated 'packer-virtualbox...' image to start installation process... here will come ssh ;)

**Comment by Chan9390** [comment]
@Shubhamingle82396 Another solution would be to manually use rdp to login to the machine, and manually start `ssh-agent.exe` at `C:\OpenSSH\` location. Also see issue #20 for more details.

**Comment by tjsimmons** [comment]
@Chan9390 I've confirmed SSH is running on the VM (I can SSH to it from my machine); however, Vagrant still isn't able to. @rbarrett-r7 mentioned it's an issue with Vagrant/packer, but every instance I can find is related to AWS and security settings there. Don't suppose either of you have any more tips?

**Comment by Chan9390** [comment]
@tjsimmons The latest code has been modified in such a way that installation of softwares takes place in packer itself. Vagrant just starts the box (either in normal or easy mode). Till now theres no issue in packer build regarding SSH. Are you using the latest code in master branch ?

**Comment by tjsimmons** [comment]
I am! I cloned earlier today, and I'm still getting the issue.

**Comment by tjsimmons** [comment]
@Chan9390 In addition to running off the latest master.. I've tried building in both Windows 10 and macOS. Both hang at "waiting for ssh". On both I had to flip the network settings during Windows install to use a bridged adapter, otherwise OpenSSH wouldn't download at all. I've confirmed that OpenSSH has downloaded, ssh-agent is running, and the openssh-server service is running as well.

**Comment by Chan9390** [comment]
@tjsimmons Can you say me the steps / commands you used so that I could get a clear image of what you are doing?

**Comment by tjsimmons** [comment]
@Chan9390 Sure! I clone the repo (git clone https://github.com/rapid7/metasploitable3.git), cd into it, and sudo ./build_win2008.sh

When the VM comes up, I change the networking settings from "NAT" to "Bridged" so it has internet access to download OpenSSH and other things it needs. 

That's pretty much it. Same process on Win10 and my Mac. I've also tried doing a manual packer build but I get the same results.
