### ISSUE TITLE
Windows Server 2016 Version

### ISSUE THREAD

**Issue by GabrielTK** [rapid7/metasploitable3#124]
Hey Guys,
I was thinking about starting a Windows Server 2016 Version, mainly for Docker on Windows, but also to provide a newer experience, since most servers are upgrading. What do you think?? Going to start porting soon...

**Comment by busterb** [comment]
Yeah, you could probably start with an updated Win2016 packer image, maybe by modifying something from https://github.com/boxcutter/windows .

**Comment by GabrielTK** [comment]
It seems that this example doesn't provide Hyper-V / Docker. I think I'll do it from 0. Are Metasploitable puppet files available for Windows yet??

**Comment by GabrielTK** [comment]
I think it'll be better to wait to Linux version and see how thimgs get. Closing this for now.

**Comment by GabrielTK** [comment]
Would the answer files work in Windows Server 2016??
