### ISSUE TITLE
Vagrant Up stops

### ISSUE THREAD

**Issue by jrobber1** [rapid7/metasploitable3#125]
Vagrant up stops and does not complete. The VM ends up not being bootable
HlOdvn8xmts0bk5Y2qzVPb/ux0SiSTKKrf5fuNKKRwQwQ1Vk47kyolavHkYn7jYhof11UB01LF5OD23372pb/xq39mSMJv/NLPfPDhG1/6B1WRK8NAedRJX+
k5+XRnu+3aru3aru3arv3H1U4Oe6c3j3r3tSFaqOnFWx+5/8pH/0SIwh+buPjFj/+zD4TLJz85GA2wjhflnh9+zXOsSFufLEDCWNPb0YmDwz1a+/OWlSmWvr
ZPycxlrHh8eLN1LfHGTk6e0ZYV2Z6S3SAxvzE1EEp67otlk3cp8cubT92lU6itMGFQS+54UwCp7fVLnrJI3kp+e1k2XuWcrPeSXqR4lRK7ExRAvBp5vkgKo0
i8ioiE8Af2Rp0G/pF+M0690TDgT/Fq6oJesGQJkJMgHp7EagOiBUnWRIsUc/xFLVDywm1auhPG4TNmSETM+BBURcasNtyWd+dt5WjbXDA11QzFMo/oQUtuP5
QUgqFHRa9BtAokritFv0a9g2Y+Lpf06LKWNyzeY0gPtksUbLmaci0TIaEln8VJy672gqZw2IJ50EOiXpIxMbuYt70t122tf8dc0VvWY1LSo5KCULbbzHmaiP
yh2erHRn6c+yMlT2VF9rbkvdv0QGyPHA2iSp7bsNBlziTu32Gc9mtf+apeg0QAb93Re/OcWQ9ffPk17s3jFqKyydPfOg5ERlnENOdcwwP5vRQBcvutdSfZT7
JfRD1RCqYNxk3RItGnWMz1GIw5t6LPIplSQz6feMsb5MRrI1lmTW2QQZNtIh6n7MU+veQFM6IIisHiejM2KKDLdUVUhlyYBTUZhKUPAEOeZRYzvDYF0XjWyb
oSDYmI6IWE1YV3E1OjoTaEM9Lco0dU0TaEF8Rzi+eneLIFeUMxUQ1>jack_of_diamonds.png:jack_of_diamonds.txt
==> default: C:\>cmd /c ""C:\wamp\bin\mysql\mysql5.5.20\bin\mysql.exe" -u root --password=""  -e "create database cards;
""
==> default: C:\>cmd /c ""C:\wamp\bin\mysql\mysql5.5.20\bin\mysql.exe" -u root --password=""  cards < "C:\Vagrant\resour
ces\flags\queen_of_hearts.sql""
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
PS E:\metasploitable3>

**Comment by Chan9390** [comment]
Some more details required like version of Vagrant, Packer and VirtualBox installed.

**Comment by DiegoBoy** [comment]
I am hitting the same issue.

Vagrant version: 1.9.3
Packer version: 1.0.0
VirtualBox version: 5.1.18

**Comment by jrobber1** [comment]
Vagrant version: 1.9.2
Packer version: 1.0.0
VirtualBox version: 5.1.18

**Comment by Chan9390** [comment]
Try downgrading VirtualBox to 5.1.14 (as there are some issues with latest version of VirtualBox).

**Comment by jrobber1** [comment]
Same issue. I dont believe this to be a virtual box version issue. It looks like the install of the vulnerable software just stops. This is with the newest build released 8 days ago.

**Comment by DiegoBoy** [comment]
I got it working after downgrading and some manual work. Downgrading allowed provisioning a usable (bootable) and semi-provisioned VM. The reload plugin didn't work, so it shut down the VM but didn't turn it on to finish the provisioning. Here's what I did:
1. I opened the Vagrant file and luckily there was just one call to the plugin, right next to the last install command that produced output for me (_setup_ftp_site.bat_) - I most probably re-installed Java and Tomcat.
2. Turned on the VM and ran the rest of the scripts in the Vagrant file from c:\vagrant just in case a script had a relative path - this is the virtual folder for the metasploitable git directory.
3. The script _install_rails_server.bat_ had Bundler throwing an [error](http://stackoverflow.com/questions/10246023/bundle-install-fails-with-ssl-certificate-verification-error) fixed by running **gem update --system** and re-running the script afterwards.
4. The script _install_elasticsearch.bat_ failed because it couldn't "find: 64-bit". Edited the script as pointed out [here](http://stackoverflow.com/questions/28449610/elasticsearch-set-up-32bit-service-but-my-os-and-java-version-is-64), replacing the only occurrence of **find** by the full path to find.exe: _C:\Windows\System32\find.exe_ . This might be a side effect of the gem update fix applied in (4).

Bonus: #126 is related to this bug. Those are the errors thrown by VirtualBox when I tried starting the VM that failed provisioning before downgrading.

**Comment by gearcapitan** [comment]
@DiegoBoy  diego eres tu?

**Comment by jrobber1** [comment]
![fail](https://cloud.githubusercontent.com/assets/19433260/24984714/244e6260-1fbd-11e7-9240-ca3ae961e9db.PNG)

**Comment by DiegoBoy** [comment]
I don't know much about it, I'm new to Vagrant, too. The file is in the root of the git directory (same where _windows_2008_r2.json_ is). The name of the file is **Vagrant** (no extension), I got the info from [here](https://www.vagrantup.com/docs/vagrantfile/). Notice that I had a bootable VM before manually running the contents of the _Vagrant_ file - I ran them in the VM using the session for the user _vagrant_ (_vagrant_ is both the user name and the password).
You'll first need to tell Vagrant to either remove or destroy the current box. I also deleted the **windows_2008_r2_virtualbox.box** file and started the whole process from scratch after downgrading VirtualBox.

**Comment by jbarnett-r7** [comment]
I set up a Windows 10 box and am doing some testing there to see if I can reproduce this.

**Comment by jbarnett-r7** [comment]
Alright, so the build completed successfully on my machine. I'm running:

- Windows 10 64-bit (just installed the Creator's Update)
- Vagrant 1.9.2 (installed from the msi)
- Packer 1.0.0 64-bit (copied .exe to C:\Windows\System32)
- VirtualBox 5.1.18

Also of note is that I manually did the `packer build windows_2008_r2.json`, `vagrant box add windows_2008_r2_virtualbox.box --name metasploitable`, and `vagrant up` commands through the Git bash shell that can be installed along with git for Windows. I have not tried Windows' native cmd shell yet, but I will just to see if we can narrow down the problem.

**Comment by jrobber1** [comment]
Thank you. I haven't tried the manual build with with the new release. I will give it a shot, really not sure what the problem is. I'll send my windows build as well.


________________________________

**Comment by jbarnett-r7** [comment]
No problem. Thanks for the info and continuing to troubleshoot.

Also, one thing I forgot to mention, was that the output you posted in your original post indicates that the `vagrant up` command did complete successfully. The end output for me is the exact same. The issue seems to be somewhere on the VirtualBox side as Vagrant completed successfully.

**Comment by jrobber1** [comment]
Thats where I was a little confused as well. Wasn't sure if vagrant completed or not because all it said was

==> default: C:>cmd /c ""C:\wamp\bin\mysql\mysql5.5.20\bin\mysql.exe" -u root --password="" cards < "C:\Vagrant\resour
ces\flags\queen_of_hearts.sql""
==> default: Running provisioner: shell...
default: Running: inline PowerShell script
PS E:\metasploitable3>


So I was assuming that it was going to execute another script.



Jesse

________________________________

**Comment by jbarnett-r7** [comment]
I agree, the output is weird, but it's definitely done.

Also, I just re-ran the build from a normal Windows cmd shell. Everything worked fine. This leads me to believe it is something environmental, but a common enough setup that it's causing issues for quite a few people. Now we need to figure out what that commonality is.

Can you please check your installs for all of the apps above and make sure they match your OS architecture? Actually, are you on 32 or 64 bit Windows 10? Have you installed the Creator's Update? Any other ideas of differences that might pinpoint this?

**Comment by jrobber1** [comment]
The only thing I can think of is that it is my build of windows. Tt is 64bit Windows 10. I'll send you my exact version tonight as I am in office and have my remote connection shutdown.


I have vagrant 1.92 with default install path.

Packer I installed into a folder called C:\packer but I added a path var

virtual box is in the defaults except I have the virtual machine path to pointing to my ssd data drive


Pretty sure theyre all 64 bit. I usually default to that unless an app says 32 bit is more stable.


Thank you for looking into it. I'll continue to troubleshoot and let you know more tonight.


(Side note im trying to run it from my ubuntu machine now.)





________________________________

**Comment by jrobber1** [comment]
Im almost tempted to buy the vagrant vmware license to see if it is a virtual box build issue

________________________________

**Comment by jrobber1** [comment]
![capture](https://cloud.githubusercontent.com/assets/19433260/25028496/c0e07eea-2082-11e7-83a2-5ae33298d9ac.PNG)

**Comment by jbarnett-r7** [comment]
Yeah I think that the Windows version might be the problem here. I honestly haven't even heard of the "Education" edition of Windows 10, let alone an eval, pre-release copy. Do you have a full version you can install?

**Comment by jrobber1** [comment]
So the education version is the same as the enterprise. I think it may be I am signed up for the insider program which gives me the newer builds.

Jesse Roberts
________________________________

**Comment by Chan9390** [comment]
@jrobber1 That makes development/debugging hard as others cant reproduce your issue (coz they dont have your version of Windows).

**Comment by jrobber1** [comment]
I understand that. But realistically I'm not running an Unsanctioned version of windows. Plus not to mention there are other users having similar problems that are running different versions. I'm going to see if I can get a copy of ent.

Jesse Roberts
________________________________

**Comment by Chan9390** [comment]
@jrobber1 Any updates on the issue. Were you able to make a smooth setup ?

**Comment by jrobber1** [comment]
Not smooth at all.

I bought the vagrant plugin for vmware and used that to do some further troubleshooting.

I found that during the linked clone process, in both cases virtual box and vmware the windows image was becoming corrupted. So before the cloning process I ran a sysprep generalize on the windows image and everything went smooth from there.


________________________________

**Comment by Chan9390** [comment]
@jrobber1 Could you elaborate the process so that others could follow your way to set it up in your way.

**Comment by Chan9390** [comment]
Closing the issue. Please reopen if the issue isn't resolved
