### ISSUE TITLE
Failed to open session

### ISSUE THREAD

**Issue by dsolstad** [rapid7/metasploitable3#126]
## Issue Description
After I run vagrant up and try to start the vm, I get this error:
```00:00:23.962786          ERROR [COM]: aRC=VBOX_E_VM_ERROR (0x80bb0003) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={MachineWrap} aText={Failed to assign the machine to the session (E_FAIL)}, preserve=false aResultDetail=0```

## Host System
* OS: Win10
* Packer Version: 1.0.0
* Vagrant Version: 1.9.3
* VirtualBox Version: 5.1.18

I have tried to reinstall Virtualbox and rebuilding metasploitable3, but the same happens.

**Comment by Chan9390** [comment]
Lots of issues while installing and configuring metasploitable3 on Windows. (Issues: #115, #110, etc). As there are some issues with the latest VirtualBox, _please try to downgrade to previous versions_. (BTW version 5.1.14 works great for me)

**Comment by dsolstad** [comment]
Still the same error in vbox 5.1.14 here, after reinstalling everything.

**Comment by Chan9390** [comment]
Can you send a screenshot of what you are seeing ?

**Comment by dsolstad** [comment]
http://imgur.com/a/QD7Gn

**Comment by dsolstad** [comment]
I found a workaround by exporting the vm to .ova and importing it in VMware.

**Comment by Chan9390** [comment]
Does importing the .ova file in VMware work ?

**Comment by dsolstad** [comment]
Yeah, but first time I got an error, but then I tried again and it worked. I don't have any working network adaptors in the vm though. I don't know if it's supposed to be like that or that something happend during the conversion.

**Comment by DiegoBoy** [comment]
@dsolstad, I tried this approach and didn't work. Please, see thread #125.

**Comment by Chan9390** [comment]
@dsolstad Did you try vagrant up with latest code? Any updates ?
