### ISSUE TITLE
Issue on Centos

### ISSUE THREAD

**Issue by monte74** [rapid7/metasploitable3#128]
## Issue Description
Please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Centos
* Packer Version: 1.0.0
* Vagrant Version: Not downloaded yet
* VirtualBox Version:5.1.12

## Command Output
When running build_win2008.sh on the command line, it validates the version of VB and it says "skipping line 1, 2, 3...". It seems to exit the entire process.
When I run in manually using packer and calling the .json file, its the same thing.
I am sure its user error or something simple, but I cant even get past the first gate.

Thanks.

**Comment by CycleDave** [comment]
Same issue here. Running on Centos all commands (for example "packer --version" or "packer validate test.json") just result in a blank line with:

skipping line: 1
skipping line: 2
skipping line: 3

after each enter. There is no RHEL prompt, it's as if it is waiting for manually-typed input.
Centos version 1611 (latest) running in Virtual box, 64-bit. Packer latest version 1.0.0.0

**Comment by Chan9390** [comment]
Did you try `bash build_win2008.sh` ?

**Comment by gaudard** [comment]
Same issue. I'm using latest packer, 1.9.1 of vagrant. Tried both build.sh and packer build json. No status, no network traffic. When I press enter I get skipping line 1,2,3 ect.

**Comment by Chan9390** [comment]
@gaudard @CycleDave @monte74 I have installed CentOS 7 Minimal for testing the issue. `bash --version` shows that I am using version **4.2.46(1)-release (x86_64-redhat-linux-gnu)**.
Please confirm if this is the version of bash you are using.

**Comment by Chan9390** [comment]
Found that there is a inbuilt program named `packer` in Cent OS (in the location `/sbin/packer`).
This issue is also common in Fedora (Check out the official packer [issue thread](https://github.com/hashicorp/packer/issues/1117) on this).

Steps I followed to resolve `packer` issue was:
```bash
# You need to install wget and unzip for the below two commands
wget https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip
unzip packer_1.0.0_linux_amd64.zip
# after unzipping the zip folder, you will have packer executable
mkdir /packer_home
mv packer /packer_home
export PATH=/packer_home/:\$PATH
```

**Comment by Chan9390** [comment]
There is a preinstalled package called packer in the location `/sbin/packer`.
This issue is also common in Fedora. (Check out the official packer [issue thread](https://github.com/hashicorp/packer/issues/1117))

Steps I took to resolve packer issue:
```bash
# Install wget and unzip before executing the below steps
wget https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip
unzip packer_1.0.0_linux_amd64.zip
# This extracts the packer executable
mkdir /packer_home
mv packer /packer_home
export PATH=/packer_home/:$PATH
```

**Comment by gaudard** [comment]
@Chan9390 Looks like this solved the issue. It's downloading, which is further than it got before.

**Comment by Chan9390** [comment]
Closing the issue as @gaudard confirms that the issue is resolved.
@monte74 and @CycleDave Please reopen the issue if the solution doesn't work.
