### ISSUE TITLE
ERROR: The process "domain1Service.exe" not found.

### ISSUE THREAD

**Issue by clshack** [rapid7/metasploitable3#130]
## Issue Description
Running the command vagrant up I received few errors like this one:
**ERROR: The process "domain1Service.exe" not found.**

I am using the current master (16/04/2017).

## Host System
* OS: Arch
* Packer Version: 1.0.0
* Vagrant Version: 1.9.2
* VirtualBox Version: 5.1.18

## Command Output
ERROR: The process "domain1Service.exe" not found.

**Comment by jbarnett-r7** [comment]
@wchen-r7 just pushed up a fix that might resolve this. Can you please pull the latest and try building again?

**Comment by Chan9390** [comment]
@clshack Any updates ?

**Comment by clshack** [comment]
Sorry guys I cannot test in these days because I am full of work, I will let you know soon as possible.

**Comment by jbarnett-r7** [comment]
It's not a problem. This actually should be fixed by the commit here https://github.com/rapid7/metasploitable3/commit/e937c7055db94fc58b374dee0cb19c131463bdd0

I'm going to close this out. If you're still seeing issues feel free to re-open.
