### ISSUE TITLE
Multiple services missing

### ISSUE THREAD

**Issue by mbauer588** [rapid7/metasploitable3#138]
Hallo!

I try to create it and i missed multiple services. Then i did it a 2nd time and i miss multiple services again - e.g. elasticsearch, ftp, iis, etc. Vagrant does not install nothing...

I also dont see in the VM that some Software get installed. When I open the Uninstall-Dialogue of windows i see only OpenSSH get's installed and that's it... No 7zip, etc.

## Host System
* OS: OS X 10.9
* Packer Version: 1.0.0
* Vagrant Version: 1.9.4
* VirtualBox Version: 5.1.14

## Command Output

My nmap-scan looks like this:

nmap -O -sS -sV -sC -p 1-65535 -oA nmap/win2008 --stylesheet=nmap.xsl --open --reason 192.168.1.104

Starting Nmap 7.40 ( https://nmap.org ) at 2017-04-27 13:44 CEST
Nmap scan report for 192.168.1.104
Host is up, received arp-response (0.00049s latency).
Not shown: 65528 filtered ports
Some closed ports may be reported as filtered due to --defeat-rst-ratelimit
Reason: 65528 no-responses
PORT STATE SERVICE REASON VERSION
22/tcp open ssh syn-ack ttl 128 OpenSSH 7.1 (protocol 2.0)
| ssh-hostkey:
| 2048 dc:17:a5:fc:2e:19:13:62:0e:5a:2f:df:9e:5c:64:72 (RSA)
|_ 521 52:c4:78:6e:7f:fe:5a:bc:d5:16:c7:cb:ff:d6:56:ed (ECDSA)
135/tcp open msrpc syn-ack ttl 128 Microsoft Windows RPC
445/tcp open microsoft-ds syn-ack ttl 128 Windows Server 2008 R2 Standard 7601 Service Pack 1 microsoft-ds
3389/tcp open ms-wbt-server syn-ack ttl 128 Microsoft Terminal Service
| ssl-cert: Subject: commonName=metasploitable3
| Not valid before: 2017-04-25T23:40:13
|_Not valid after: 2017-10-25T23:40:13
|_ssl-date: 2017-04-27T11:47:49+00:00; +2s from scanner time.
5985/tcp open http syn-ack ttl 128 Microsoft HTTPAPI httpd 2.0 (SSDP/UPnP)
|_http-server-header: Microsoft-HTTPAPI/2.0
|_http-title: Not Found
49153/tcp open msrpc syn-ack ttl 128 Microsoft Windows RPC
49154/tcp open msrpc syn-ack ttl 128 Microsoft Windows RPC
MAC Address: 08:00:27:77:66:19 (Oracle VirtualBox virtual NIC)
Warning: OSScan results may be unreliable because we could not find at least 1 open and 1 closed port
Aggressive OS guesses: Microsoft Windows Server 2008 or 2008 Beta 3 (91%), Microsoft Windows Server 2008 (90%), Microsoft Windows Server 2008 SP1 (87%), HP-UX B.11.31 (87%), Isilon IQ 200 NAS device (87%), VMware ESXi 4.0 (87%), FreeBSD 6.2-RELEASE (86%), FreeBSD 5.5-RELEASE (86%), Microsoft Windows 7 SP1 (86%), m0nowall 1.3b16 firewall (FreeBSD 6.3-RELEASE) (85%)
No exact OS matches for host (test conditions non-ideal).
Network Distance: 1 hop
Service Info: OSs: Windows, Windows Server 2008 R2 - 2012; CPE: cpe:/o:microsoft:windows

Host script results:
|clock-skew: mean: 1s, deviation: 0s, median: 1s
| smb-os-discovery:
| OS: Windows Server 2008 R2 Standard 7601 Service Pack 1 (Windows Server 2008 R2 Standard 6.1)
| OS CPE: cpe:/o:microsoft:windows_server_2008::sp1
| Computer name: metasploitable3
| NetBIOS computer name: METASPLOITABLE3\x00
| Workgroup: WORKGROUP\x00
| System time: 2017-04-27T04:47:52-07:00
| smb-security-mode:
| account_used: guest
| authentication_level: user
| challenge_response: supported
|_ message_signing: disabled (dangerous, but default)
|_smbv2-enabled: Server supports SMBv2 protocol

OS and Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 208.95 seconds

## Vargant-Output
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'metasploitable3'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: metasploitable3-master_default_1493297999084_75136
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/markusbauer/Downloads/metasploitable3-master
==> default: Running provisioner: shell...
    default: Running: scripts/installs/chocolatey.cmd as c:\tmp\vagrant-shell.cmd
==> default: c:\tmp\vagrant-shell.cmd
==> default: Running provisioner: reload...
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/markusbauer/Downloads/metasploitable3-master
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_boxstarter.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/chocolatey_installs/7zip.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/configs/apply_password_settings.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/configs/create_users.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_iis.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_ftp_site.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/chocolatey_installs/java.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/chocolatey_installs/tomcat.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: reload...
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/markusbauer/Downloads/metasploitable3-master
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_apache_struts.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_glassfish.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/start_glassfish_service.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_jenkins.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/chocolatey_installs/vcredist2008.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_wamp.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/start_wamp.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_wordpress.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_openjdk6.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_jmx.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_ruby.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_devkit.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_rails_server.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_rails_server.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_rails_service.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_webdav.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_mysql.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_manageengine.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_axis2.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_backdoors.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/setup_snmp.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/configs/configure_firewall.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_elasticsearch.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_flags.bat as c:\tmp\vagrant-shell.bat
==> default: c:\tmp\vagrant-shell.bat
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script

**Comment by jbarnett-r7** [comment]
There appears to be a bug with vagrant 1.9.4 that is preventing it from actually running any of the install scripts. Can you please try [downgrading to vagrant 1.9.1](https://releases.hashicorp.com/vagrant/1.9.1/), run `vagrant destroy`, then `vagrant up` again?

**Comment by mbauer588** [comment]
1.9.1 did the trick... thanks :)

**Comment by Chan9390** [comment]
Closing the issue as it seems to be resolved
