### ISSUE TITLE
Windows build: Ruby update causes Vagrant script to exit

### ISSUE THREAD

**Issue by tijldeneut** [rapid7/metasploitable3#145]
## Issue Description
Simple issue: Ruby has been updated to v2.4, hence the path (which is hardcoded) has changed from "C:\tools\ruby23\bin\ruby.exe" to C:\tools\ruby24\bin\ruby.exe" ...
This isue is due to using chocolatey which always installs the latest software versions.

## Host System
* OS: Windows 10
* Packer Version: v1.0.0
* Vagrant Version: 1.9.5
* VirtualBox Version: 5.1.22

## Command Output
Error "The system cannot find the path specified", every time it is referenced, with the vagrant script finally just failing.
References are in _install_devkit.bat_, _install_rails_server.bat_ and _setup_rails_server.bat_
Fix: 
Edit 'scripts\install\install_ruby.bat' and change the first line to
_choco install -y ruby --version 2.3.0_

**Comment by Chan9390** [comment]
Thanks for the fix. I think version 2.3.3 was working fine. IMO it is best to have the latest version of Ruby 2.3.x. If this version breaks the build, please dont hesitate to comment / create another issue.
