### ISSUE TITLE
Not all the services are running also guest addons not installed.

### ISSUE THREAD

**Issue by rootb3** [rapid7/metasploitable3#148]
## Host System
* OS: Windows 10 x64
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.22

## Command Output
PS D:\Root\VM'S\metasploitable3-master> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/Root/VM'S/metasploitable3-master
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
PS D:\Root\VM'S\metasploitable3-master> vagrant up --provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Running provisioner: shell...
    default: Running: scripts/installs/chocolatey.cmd as c:\tmp\vagrant-shell.cmd
==> default: Running provisioner: reload...
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/Root/VM'S/metasploitable3-master
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_boxstarter.bat as c:\tmp\vagrant-shell.bat
==> default: C:\Windows\system32>copy /Y C:\Vagrant\resources\rails_server\gemrc C:\Users\vagrant\.gemrc
==> default:         1 file(s) copied.
==> default:
==> default: C:\Windows\system32>cmd /C "C:\tools\ruby23\bin\gem.cmd install rails -v '4.1.1' --no-ri --no-rdoc"
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C "C:\tools\ruby23\bin\gem.cmd install rake -v '11.3.0' --no-ri --no-rdoc"
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install coffee-script-source -v '1.10.0' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install execjs -v '2.7.0' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install hike -v '1.2.3' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install multi_json -v '1.12.1' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install tilt -v '1.4.1' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sass -v '3.2.19' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sqlite3 -v '1.3.11' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install turbolinks-source -v '5.0.0' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install rdoc -f -v '4.2.2' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install coffee-script -v '2.4.1' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install uglifier -v '3.0.2' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sprockets -v '2.12.4' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install turbolinks -v '5.0.1' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sdoc -v '0.4.2' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install tzinfo-data -v '1.2016.7' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install jbuilder -v '2.6.0' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install coffee-rails -v '4.0.1' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install jquery-rails -v '3.1.4' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sass-rails -v '4.0.5' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install debug_inspector -v '0.0.2' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install binding_of_caller -v '0.7.2' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install web-console -v '2.1.2' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install minitest -v '5.9.1' --no-ri --no-rdoc
==> default: The system cannot find the path specified.
==> default:
==> default:
==> default: C:\Windows\system32>copy /Y C:\Vagrant\Resources\rails_server\sqlite3-1.3.11-x64-mingw32.gemspec C:\tools\ruby23\lib\ruby\gems\2.3.0\specifications
==> default: The system cannot find the path specified.
==> default:         0 file(s) copied.
==> default:
==> default: C:\Windows\system32>C:\tools\ruby23\bin\rails.bat _4.1.1_ new "C:\Program Files\Rails_Server"
==> default: The system cannot find the path specified.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:

Stderr from the command:

**Comment by Chan9390** [comment]
From the terminal output, it seems that most of the files are not accessible on Metasploitable3. **Can you say how you set up Metasploitable 3**?
From the output, I could see that you did `vagrant up` and then `vagrant up --provision`, which means you had already run `vagrant up` before this. If that was the situation, try `vagrant destroy` and then do `vagrant up`.

**Comment by rootb3** [comment]
Did that already last night. Had to rebuild the VM twice.I think the issue is with the VBox version. I'm running VBox version 5.1.22 while in the wiki they've recommended 5.1.19/5.1.14

**Comment by Chan9390** [comment]
Just try degrading your VirtualBox and please comment if you find some errors again.

**Comment by rootb3** [comment]
Degraded my Vbox to 5.1.14 now new errors are there :--

PS D:\Root\VM'S\metasploitable3-master> Set-ExecutionPolicy Unrestricted

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help
topic at http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PS D:\Root\VM'S\metasploitable3-master> .\build_win2008.ps1
Compatible version of VirtualBox found.
Compatible version of packer found.
Compatible version of Vagrant found.
Compatible version of vagrant-reload plugin found.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
    virtualbox-iso: Download progress: 0%
==> virtualbox-iso: Interrupt received. Cancelling download...
Build 'virtualbox-iso' errored: Build was cancelled.
Cleanly cancelled builds after being interrupted.
PS D:\Root\VM'S\metasploitable3-master> .\build_win2008.ps1
Compatible version of VirtualBox found.
Compatible version of packer found.
Compatible version of Vagrant found.
Compatible version of vagrant-reload plugin found.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso

==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: ./answer_files/2008_r2/Autounattend.xml
    virtualbox-iso: Copying file: ./scripts/configs/microsoft-updates.bat
    virtualbox-iso: Copying file: ./scripts/configs/win-updates.ps1
    virtualbox-iso: Copying file: ./scripts/installs/openssh.ps1
    virtualbox-iso: Copying file: ./resources/certs/oracle-cert.cer
    virtualbox-iso: Copying file: ./resources/certs/gdig2.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsadomainvalidationsecureserverca.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsacertificationauthority.crt
    virtualbox-iso: Copying file: ./resources/certs/addtrust_external_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/baltimore_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/digicert.cer
    virtualbox-iso: Copying file: ./resources/certs/equifax.cer
    virtualbox-iso: Copying file: ./resources/certs/globalsign.cer
    virtualbox-iso: Copying file: ./resources/certs/gte_cybertrust.cer
    virtualbox-iso: Copying file: ./resources/certs/microsoft_root_2011.cer
    virtualbox-iso: Copying file: ./resources/certs/thawte_primary_root.cer
    virtualbox-iso: Copying file: ./resources/certs/utn-userfirst.cer
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 4224)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1496731553 --memory 4096
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1496731553 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: rdp://127.0.0.1:5919
==> virtualbox-iso: Waiting 10m0s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Connected to SSH!
==> virtualbox-iso: Uploading VirtualBox version info (5.1.14)
==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
==> virtualbox-iso: Provisioning with shell script: ./scripts/installs/vm-guest-tools.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if not exist "C:\Windows\Temp\7z920-x64.msi" (powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://www.7-zip.org/a/7z920-x64.msi', 'C:\Windows\Temp\7z920-x64.msi')"  0<NUL )
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>msiexec /qb /i C:\Windows\Temp\7z920-x64.msi
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if "virtualbox-iso" EQU "vmware-iso" goto :vmware
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if "virtualbox-iso" EQU "virtualbox-iso" goto :virtualbox
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>move /Y C:\Users\vagrant\VBoxGuestAdditions.iso C:\Windows\Temp
    virtualbox-iso: 1 file(s) moved.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x C:\Windows\Temp\VBoxGuestAdditions.iso -oC:\Windows\Temp\virtualbox"
    virtualbox-iso:
    virtualbox-iso: 7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
    virtualbox-iso:
    virtualbox-iso: Processing archive: C:\Windows\Temp\VBoxGuestAdditions.iso
    virtualbox-iso:
    virtualbox-iso: Extracting  32Bit
    virtualbox-iso: Extracting  32Bit\Readme.txt
    virtualbox-iso: Extracting  64Bit
    virtualbox-iso: Extracting  64Bit\Readme.txt
    virtualbox-iso: Extracting  AUTORUN.INF
    virtualbox-iso: Extracting  OS2
    virtualbox-iso: Extracting  OS2\VBoxControl.exe
    virtualbox-iso: Extracting  OS2\VBoxGuest.sys
    virtualbox-iso: Extracting  OS2\VBoxReplaceDll.exe
    virtualbox-iso: Extracting  OS2\VBoxService.exe
    virtualbox-iso: Extracting  OS2\gengradd.dll
    virtualbox-iso: Extracting  OS2\libc06.dll
    virtualbox-iso: Extracting  OS2\libc061.dll
    virtualbox-iso: Extracting  OS2\libc062.dll
    virtualbox-iso: Extracting  OS2\libc063.dll
    virtualbox-iso: Extracting  OS2\libc064.dll
    virtualbox-iso: Extracting  OS2\libc065.dll
    virtualbox-iso: Extracting  OS2\libc066.dll
    virtualbox-iso: Extracting  OS2\readme.txt
    virtualbox-iso: Extracting  OS2\vboxmouse.sys
    virtualbox-iso: Extracting  VBoxLinuxAdditions.run
    virtualbox-iso: Extracting  VBoxSolarisAdditions.pkg
    virtualbox-iso: Extracting  VBoxWindowsAdditions-amd64.exe
    virtualbox-iso: Extracting  VBoxWindowsAdditions-x86.exe
    virtualbox-iso: Extracting  VBoxWindowsAdditions.exe
    virtualbox-iso: Extracting  autorun.sh
    virtualbox-iso: Extracting  cert
    virtualbox-iso: Extracting  cert\VBoxCertUtil.exe
    virtualbox-iso: Extracting  cert\vbox-sha1.cer
    virtualbox-iso: Extracting  cert\vbox-sha256-r3.cer
    virtualbox-iso: Extracting  cert\vbox-sha256.cer
    virtualbox-iso: Extracting  runasroot.sh
    virtualbox-iso:
    virtualbox-iso: Everything is Ok
    virtualbox-iso:
    virtualbox-iso: Folders: 4
    virtualbox-iso: Files: 28
    virtualbox-iso: Size:       58956946
    virtualbox-iso: Compressed: 59369472
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "TrustedPublisher" C:\Windows\Temp\virtualbox\cert\vbox-sha1.cer
    virtualbox-iso: TrustedPublisher
    virtualbox-iso: Certificate "CN=Oracle Corporation, O=Oracle Corporation, L=Redwood Shores, S=California, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c C:\Windows\Temp\virtualbox\VBoxWindowsAdditions.exe /S
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>goto :done
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>msiexec /qb /x C:\Windows\Temp\7z920-x64.msi
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/vagrant-ssh.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if exist a:\vagrant.pub (copy a:\vagrant.pub C:\Users\vagrant\.ssh\authorized_keys )  else (powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/mitchellh/vag
.pub', 'C:\Users\vagrant\.ssh\authorized_keys')"  0<NUL )
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/disable-auto-logon.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v AutoAdminLogon /d 0 /f
    virtualbox-iso: The operation completed successfully.
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/enable-rdp.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>netsh advfirewall firewall add rule name="Open Port 3389" dir=in action=allow protocol=TCP localport=3389
    virtualbox-iso: Ok.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
    virtualbox-iso: The operation completed successfully.
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/update_root_certs.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\addtrust_external_ca.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=AddTrust External CA Root, OU=AddTrust External TTP Network, O=AddTrust AB, C=SE" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\baltimore_ca.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\digicert.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\equifax.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "OU=Equifax Secure Certificate Authority, O=Equifax, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\globalsign.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\gte_cybertrust.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=GTE CyberTrust Global Root, OU="GTE CyberTrust Solutions, Inc.", O=GTE Corporation, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\microsoft_root_2011.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\thawte_primary_root.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\utn-userfirst.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=UTN-USERFirst-Object, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, S=UT, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Error removing floppy: VBoxManage error: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
==> virtualbox-iso: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 326 of file VBoxManageStorageController.cpp
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error removing floppy: VBoxManage error: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 326 of file VBoxManageStorageController.cpp

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error removing floppy: VBoxManage error: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 326 of file VBoxManageStorageController.cpp

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At D:\Root\VM'S\metasploitable3-master\build_win2008.ps1:107 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
After a bit of searching, I found out that this is a Windows specific issue. Check out another similar issue: https://github.com/r-a-p-a/mint-dev-box/issues/3

**Comment by rootb3** [comment]
In msf3 "windows_2008_r2.json" file the value of headless is already true. What changes should i make further?

**Comment by rootb3** [comment]
Fixed finally just needed to change the "headless": true,  to "headless": false, in the "windows_2008_r2.json" file and install from scratch also remember to disable any additional AV or Firewall on your system. I had Comodo FW 10 running had to disable it completely for few hours.
