### ISSUE TITLE
'virtualbox-iso' errored: Script exited with non-zero exit status: 2

### ISSUE THREAD

**Issue by edmtorres02** [rapid7/metasploitable3#155]
## Host System
* OS: Kali 2017
* Packer Version: 0.10.2
* Vagrant Version:1.9.1
* VirtualBox Version:5.1.18

## Command Output
    virtualbox-iso: processed file: C:\glassfish\glassfish4\pkg\lib\pkg-bootstrap.jar
    virtualbox-iso: processed file: C:\glassfish\glassfish4\pkg\lib\pkg-bootstub.bat
    virtualbox-iso: processed file: C:\glassfish\glassfish4\pkg\lib\pkg-bootstub.sh
    virtualbox-iso: processed file: C:\glassfish\glassfish4\pkg\lib\pkg-client.jar
    virtualbox-iso: Successfully processed 3439 files; Failed processing 0 files
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    virtualbox-iso: [SC] ChangeServiceConfig SUCCESS
==> virtualbox-iso: Provisioning with shell script: scripts/installs/start_glassfish_service.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -command "Start-Sleep -s 5"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start "domain1"
    virtualbox-iso: The service is starting or stopping.  Please try again later.
    virtualbox-iso:
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 2

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
root@kali:~/metasploitable3#

**Comment by Chan9390** [comment]
Please change the time from 5 to 15 in `scripts/installs/start_glassfish_service.bat` and try to build it again. Please comment if you see issues even after changing.

**Comment by Chan9390** [comment]
The patch is now merged into the master branch. Please try to clone the repo and build it again.

**Comment by edmtorres02** [comment]
I did a git pull and tried it again but I got the same error.

**Comment by edmtorres02** [comment]
When I reviewed the log file again, several hundred lines before I got the error there was these lines:

Start Command:  C:\glassfish\glassfish4\glassfish\domains\domain1\bin\domain1Service.exe  start
    virtualbox-iso: Stop Command:   C:\glassfish\glassfish4\glassfish\domains\domain1\bin\domain1Service.exe  stop
    virtualbox-iso: Restart Command:  C:\glassfish\glassfish4\glassfish\domains\domain1\bin\domain1Service.exe  restart
    virtualbox-iso: Uninstall Command:  C:\glassfish\glassfish4\glassfish\domains\domain1\bin\domain1Service.exe  uninstall
    virtualbox-iso: Install Command:  C:\glassfish\glassfish4\glassfish\domains\domain1\bin\domain1Service.exe  install
    virtualbox-iso: Status Command: C:\glassfish\glassfish4\glassfish\domains\domain1\bin\domain1Service.exe status
    virtualbox-iso: You can also verify that the service is installed (or not) with sc query state= all
    virtualbox-iso: windows.services.uninstall.good=Found the Windows Service and successfully uninstalled it.
    virtualbox-iso: For your convenience this message has also been saved to this file: C:\glassfish\glassfish4\glassfish\domains\domain1\PlatformServices.log
    virtualbox-iso: Command create-service executed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start domain1
    virtualbox-iso: The domain1 GlassFish Server service is starting.
    virtualbox-iso: The domain1 GlassFish Server service was started successfully.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 10"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net stop domain1
    virtualbox-iso: **The domain1 GlassFish Server service is stopping........**
    virtualbox-iso: **The domain1 GlassFish Server service could not be stopped.**

It seems like it did not stop within 10s, and there was no error indication. So instead, I modified this line from the setup_glassfish.bat and increased 5 and changed it to 30. Changing this value helped me got pass thru this error but got another error regarding starting the service for "elastic search".

**powershell -Command "Start-Sleep -s 5**"

**Comment by edmtorres02** [comment]
I should have added the complete log when I opened this issue, apologies. 

[exitStatus2Logs.txt](https://github.com/rapid7/metasploitable3/files/1110834/exitStatus2Logs.txt)

**Comment by Chan9390** [comment]
@edmtorres02 The patch is for 15 sec. Can you try to build with the latest code? If not possible, we could change the time to 30 seconds.

**Comment by edmtorres02** [comment]
I deleted the old metasploitable3 folder and cloned the latest version and tried rebuilding it, I still got the same error: 

    virtualbox-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    virtualbox-iso: [SC] ChangeServiceConfig SUCCESS
==> virtualbox-iso: Provisioning with shell script: scripts/installs/start_glassfish_service.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -command "Start-Sleep -s 15"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start "domain1"
    virtualbox-iso: The service is starting or stopping.  Please try again later.
    virtualbox-iso:
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 2

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
Okay. So were you successful with 30 seconds delay ?

**Comment by edmtorres02** [comment]
Got pass thru this error when I changed the delay in scripts/installs/setup_glassfish.bat to 30s.

**Comment by Chan9390** [comment]
Awesome !
