### ISSUE TITLE
"elasticsearch-service-x64" start= auto OpenService FAILED 1060:

### ISSUE THREAD

**Issue by edmtorres02** [rapid7/metasploitable3#157]
## Issue Description
The error is same with #152 but in this case, the error was caused by elasticsearch-service-64

## Host System
OS: Kali 2017
Packer Version: 0.10.2
Vagrant Version:1.9.1
VirtualBox Version:5.1.18

## Command Output
 Extracting archive: C:\Windows\Temp\elasticsearch-1.1.1.zip
    virtualbox-iso: --
    virtualbox-iso: Path = C:\Windows\Temp\elasticsearch-1.1.1.zip
    virtualbox-iso: Type = zip
    virtualbox-iso: Physical Size = 22608755
    virtualbox-iso:
    virtualbox-iso: Everything is Ok
    virtualbox-iso:
    virtualbox-iso: Folders: 5
    virtualbox-iso: Files: 48
    virtualbox-iso: Size:       25590291
    virtualbox-iso: Compressed: 22608755
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" install"
    virtualbox-iso: JAVA_HOME environment variable must be set!
    virtualbox-iso: Press any key to continue . . .
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config "elasticsearch-service-x64" start= auto
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" start"
    virtualbox-iso: JAVA_HOME environment variable must be set!
    virtualbox-iso: Press any key to continue . . .
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 30"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "$req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()"
    virtualbox-iso: Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the
    virtualbox-iso: remote server"

[exitStatus1ElasticSearch.txt](https://github.com/rapid7/metasploitable3/files/1110851/exitStatus1ElasticSearch.txt)

**Comment by Chan9390** [comment]
From your logs it could be seen that jdk8 is not installed.

```
    virtualbox-iso: Installing jdk8...
    virtualbox-iso: ERROR: Running ["C:\ProgramData\chocolatey\lib\jdk8\tools\jd
k-8u131-windows-x64.exe" /s STATIC=1 ADDLOCAL="ToolsFeature,SourceFeature" ] was
 not successful. Exit code was '1603'. See log for possible error messages.
    virtualbox-iso: The install of jdk8 was NOT successful.
    virtualbox-iso: Error while running 'C:\ProgramData\chocolatey\lib\jdk8\tool
s\chocolateyInstall.ps1'.
    virtualbox-iso: See log for details.
```
Try rebuilding.

**Comment by edmtorres02** [comment]
I  got the same error when I tried running it again. I tried copy &pasting the link for the jdk8 download link [_http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-windows-x64.exe_] in a browser and this is what I got:
![image](https://user-images.githubusercontent.com/27978231/27718727-668227c8-5d13-11e7-9dd1-e3d8d30b33c7.png)

**Comment by edmtorres02** [comment]
Searching for the jdk8 download site, it seems like users now need to "Accept License Agreement".

![image](https://user-images.githubusercontent.com/27978231/27718827-1563ec4a-5d14-11e7-81d4-f3abeab6680d.png)

**Comment by Chan9390** [comment]
You dont have to manually install jdk8. `chocolatey` will handle the download and installation of it. Please try to build again.

**Comment by edmtorres02** [comment]
Oh, okay. I'm rebuilding right now.

**Comment by edmtorres02** [comment]
Ended up with the same exact error. Also, I saw this line again:

    virtualbox-iso: jdk8 v8.0.131 [Approved]
    virtualbox-iso: jdk8 package files install completed. Performing other installation steps.
    virtualbox-iso: Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-windows-x64.exe
    virtualbox-iso: Installing jdk8...
    virtualbox-iso: ERROR: Running ["C:\ProgramData\chocolatey\lib\jdk8\tools\jdk-8u131-windows-x64.exe" /s STATIC=1 ADDLOCAL="ToolsFeature,SourceFeature" ] was not successful. Exit code was '1603'. See log for possible error messages.
    virtualbox-iso: **The install of jdk8 was NOT successful.**
    virtualbox-iso: **Error while running 'C:\ProgramData\chocolatey\lib\jdk8\tools\chocolateyInstall.ps1'.
    virtualbox-iso: See log for details.**


[exitStatus2Logs_20170629.txt](https://github.com/rapid7/metasploitable3/files/1114119/exitStatus2Logs_20170629.txt)

**Comment by Chan9390** [comment]
The script is working fine. I think there is some error on your side. Please try to rebuild (without any proxy in between).

![image](https://user-images.githubusercontent.com/12944530/27762539-7b67a8aa-5e91-11e7-86f5-474828334076.png)

**Comment by edmtorres02** [comment]
Never got to this part recently, now getting error re: jenkins. Same error as described in issue #110 .

**Comment by niko95kus** [comment]
Hi, i'm having the same issue with @edmtorres02 
when running this script
cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" install"
I got the same error
JAVA_HOME environment variable must be set! 

May I know how you solve this issue? Did I miss something?

Thank you

**Comment by JurgenG** [comment]
Confirming same error...

``==> virtualbox-iso: Provisioning with shell script: /home/jurgen/git/metasploitable3/packer/templates/../../scripts/installs/install_elasticsearch.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/1.1.1/elasticsearch-1.1.1.zip', 'C:\Windows\Temp\elasticsearch-1.1.1.zip')"  0<NUL
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\elasticsearch-1.1.1.zip" -o"C:\Program Files\""
    virtualbox-iso:
    virtualbox-iso: 7-Zip 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28
    virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso: 1 file, 22608755 bytes (22 MiB)
    virtualbox-iso:
    virtualbox-iso: Extracting archive: C:\Windows\Temp\elasticsearch-1.1.1.zip
    virtualbox-iso: --
    virtualbox-iso: Path = C:\Windows\Temp\elasticsearch-1.1.1.zip
    virtualbox-iso: Type = zip
    virtualbox-iso: Physical Size = 22608755
    virtualbox-iso:
    virtualbox-iso: Everything is Ok
    virtualbox-iso:
    virtualbox-iso: Folders: 5
    virtualbox-iso: Files: 48
    virtualbox-iso: Size:       25590291
    virtualbox-iso: Compressed: 22608755
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" install"
    virtualbox-iso: JAVA_HOME environment variable must be set!
    virtualbox-iso: Press any key to continue . . .
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config "elasticsearch-service-x64" start= auto
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" start"
    virtualbox-iso: JAVA_HOME environment variable must be set!
    virtualbox-iso: Press any key to continue . . .
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 30"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "$req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()"
    virtualbox-iso: Exception calling "GetResponse" with "0" argument(s): "Unable to connect to
    virtualbox-iso: the remote server"
    virtualbox-iso: At line:1 char:108
    virtualbox-iso: + ... host:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()
    virtualbox-iso: +                                                        ~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "$body = [System.Text.Encoding]::ASCII.GetBytes('{\"user\":\"kimchy\", \"post_date\": \"2009-11-15T14:12:12\", \"message\": \"Elasticsearch\" }'); $req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.method = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()"
    virtualbox-iso: Exception calling "GetRequestStream" with "0" argument(s): "Unable to connect
    virtualbox-iso: to the remote server"
    virtualbox-iso: At line:1 char:307
    virtualbox-iso: + ... ion/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $strea ...
    virtualbox-iso: +                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso: You cannot call a method on a null-valued expression.
    virtualbox-iso: At line:1 char:342
    virtualbox-iso: + ... req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $strea ...
    virtualbox-iso: +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    virtualbox-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
    virtualbox-iso:
    virtualbox-iso: You cannot call a method on a null-valued expression.
    virtualbox-iso: At line:1 char:381
    virtualbox-iso: + ... eam(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.G ...
    virtualbox-iso: +                                                   ~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    virtualbox-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
    virtualbox-iso:
    virtualbox-iso: Exception calling "GetResponse" with "0" argument(s): "You must provide a
    virtualbox-iso: request body if you set ContentLength>0 or SendChunked==true.  Do this by
    virtualbox-iso: calling [Begin]GetRequestStream before [Begin]GetResponse."
    virtualbox-iso: At line:1 char:398
    virtualbox-iso: + ... am.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()
    virtualbox-iso: +                                                        ~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : ProtocolViolationException
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1
``
