### ISSUE TITLE
where to place proxy settings so that guest VM can access internet and do download

### ISSUE THREAD

**Issue by edmtorres02** [rapid7/metasploitable3#158]
## Issue Description
I need to supply proxy user credentials and password to access internet, it seems like my guest VM doesn't install any of the services since it's not able to connect to the internet. which script can I or do I need to modify so that my guest VM would have the proxy credentials needed to access the internet and downlaod all necessary files?

## Host System
OS: Kali 2017
Packer Version: 0.10.2
Vagrant Version:1.9.1
VirtualBox Version:5.1.18

## Command Output
N/A

**Comment by Chan9390** [comment]
As of now, theres no script which modifies proxy configurations of the VM.
