### ISSUE TITLE
Downloable Premade Metasploitable3

### ISSUE THREAD

**Issue by alxbob** [rapid7/metasploitable3#163]
Can anyone share a downloable disk of premade metasploitable 3? It will be very helpfull for everyone. I can't get build working with any version (tried both on windows and linux)

**Comment by Chan9390** [comment]
Hey @alxbob, an official prebuilt metasploitable 3 box would be made available soon.

**Comment by alxbob** [comment]
@Chan9390 Any eta? Good news thank you very much!

**Comment by Chan9390** [comment]
The release is on schedule. Most probably within 2-3 weeks.

**Comment by khuongduybui** [comment]
2 weeks passed. Are we still "on schedule"?

**Comment by Chan9390** [comment]
Kindly wait as we are busy converting the build to chef provisioning. You could see my commits at [windows_chef branch](https://github.com/rapid7/metasploitable3/tree/windows_chef). We are trying hard to stick to schedule.

**Comment by Chan9390** [comment]
Hey @alxbob , please check the branch [`pre_built_box`](https://github.com/rapid7/metasploitable3/tree/pre_built_box) for more information on downloading pre built metasploitable 3.

**Comment by TobinShields** [comment]
They there, it's been just about a year? Is there no offical .ova file?

**Comment by Seneo1** [comment]
@Chan9390 Is there any progress on the .ova files? 
same as alxbob I can't get the build working, neither on a windows nor a Linux host

**Comment by Sliim** [comment]
https://app.vagrantup.com/rapid7/

#### Virtualbox:
https://vagrantcloud.com/rapid7/boxes/metasploitable3-ub1404/versions/0.1.12-weekly/providers/virtualbox.box
https://vagrantcloud.com/rapid7/boxes/metasploitable3-win2k8/versions/0.1.0-weekly/providers/virtualbox.box

#### Vmware:
https://vagrantcloud.com/rapid7/boxes/metasploitable3-ub1404/versions/0.1.12-weekly/providers/vmware.box
https://vagrantcloud.com/rapid7/boxes/metasploitable3-win2k8/versions/0.1.0-weekly/providers/vmware.box

#### Vmware desktop:
https://vagrantcloud.com/rapid7/boxes/metasploitable3-ub1404/versions/0.1.12-weekly/providers/vmware_desktop.box
https://vagrantcloud.com/rapid7/boxes/metasploitable3-win2k8/versions/0.1.0-weekly/providers/vmware_desktop.box

**Comment by Seneo1** [comment]
Works perfect, thank you very much

**Comment by Rebeleader29** [comment]
This may very well have just saved my weekend...

**Comment by JayDutt786** [comment]
Just wasted 17 hours, over 2 days.. to come and know that the .ova file exists... I COULD'VE MASTERED METASPLOIT while wasting all this time... oh well... here we go!!!

**Comment by JayDutt786** [comment]
Where are the instructions to install it from the images provided above?

**Comment by SaoudRashed** [comment]
What are we supposed to do with those large files in the vagrantcloud links? My Vmware doesn't recognize them!

**Comment by BinaryBoxSecurity** [comment]
> Can anyone share a downloable disk of premade metasploitable 3? It will be very helpfull for everyone. I can't get build working with any version (tried both on windows and linux)

https://drive.google.com/uc?id=1-cDEpDRl5_-QWBU8Ckpp_Zep-1-9-EY4&export=download

**Comment by BinaryBoxSecurity** [comment]
https://drive.google.com/uc?id=1-cDEpDRl5_-QWBU8Ckpp_Zep-1-9-EY4&export=download

**Comment by alifa2try** [comment]
@BinaryBoxSecurity Thank you very much. What of the Metasploitable 3 Linux version, please help. Thank you.

**Comment by TechNicalBoy29** [comment]
@BinaryBoxSecurity Thank you very much. You are a life saver

**Comment by BinaryBoxSecurity** [comment]
> @BinaryBoxSecurity Thank you very much. You are a life saver

You welcome

**Comment by BinaryBoxSecurity** [comment]
> @BinaryBoxSecurity Thank you very much. What of the Metasploitable 3 Linux version, please help. Thank you.
You welcome . I  tried building the Linux version ,  but it was one difficult VM box to build .

**Comment by BinaryBoxSecurity** [comment]
@alifa2try You welcome . I tried building the Linux version , but it was a difficult box to build

**Comment by deargle** [comment]
If you use vagrant, you should be able to use the prebuilt images referenced in the [README Quickstart section](https://github.com/rapid7/metasploitable3#quick-start). Do y'all mean to say that those vagrantbox images aren't working? Any reference to not being able to build your own suggests that you are... trying to build your own, instead of using the vagrant boxes.

**Comment by SoulReaper2020** [comment]
> 
> 
> > Can anyone share a downloable disk of premade metasploitable 3? It will be very helpfull for everyone. I can't get build working with any version (tried both on windows and linux)
> 
> https://drive.google.com/uc?id=1-cDEpDRl5_-QWBU8Ckpp_Zep-1-9-EY4&export=download

Hi
thanks for this OVA.
Do u have OVA for linux?

**Comment by SoulReaper2020** [comment]
> 
> 
> > Can anyone share a downloable disk of premade metasploitable 3? It will be very helpfull for everyone. I can't get build working with any version (tried both on windows and linux)
> 
> https://drive.google.com/uc?id=1-cDEpDRl5_-QWBU8Ckpp_Zep-1-9-EY4&export=download

thanks so much
do u have ova for linux too?

**Comment by BinaryBoxSecurity** [comment]
> > > Can anyone share a downloable disk of premade metasploitable 3? It will be very helpfull for everyone. I can't get build working with any version (tried both on windows and linux)
> > 
> > 
> > https://drive.google.com/uc?id=1-cDEpDRl5_-QWBU8Ckpp_Zep-1-9-EY4&export=download
> 
> thanks so much
> do u have ova for linux too?

Nope

**Comment by suvastar** [comment]
> 
> 
> > > > Can anyone share a downloable disk of premade metasploitable 3? It will be very helpfull for everyone. I can't get build working with any version (tried both on windows and linux)
> > > 
> > > 
> > > https://drive.google.com/uc?id=1-cDEpDRl5_-QWBU8Ckpp_Zep-1-9-EY4&export=download
> > 
> > 
> > thanks so much
> > do u have ova for linux too?
> 
> Nope

I think the link is expired! Would you please share it again. Thanks in advance

**Comment by securityinmind365** [comment]
@suvastar 

https://mega.nz/file/m9xRiSCb#Q5RUHjv_iMShfqCpI50GvU24M2srwG0ooz3yfwuN-Ds

**Comment by patronplatform** [comment]
@br3akingpoint 
Would you please share it again
file not available in mega

**Comment by br3akingpoint** [comment]
Hi @patronplatform 

https://drive.google.com/file/d/1nByw5vbPdb2T4ZP0nvLTRfmoIU4oqqCa/view

**Comment by nortonofnorthamerica** [comment]
I don't know why nobody told you but when you download those files and try to extract then you get an error say can't open ... something about an archive ....
  you gotta google up that error code ... like every time you see one
in this case it will tell you the file needs a file type to be able to be opened . you need to rename the file . filename.tar for example
     If people who know things don't explain things to the news guys why even hang out on these message boards ?

**Comment by deargle** [comment]
For everyone trying to use a pre-built OVA -- -- What _isnt_ working about
a simple `vagrant up` of the pre-built box? See "new" tab on
https://app.vagrantup.com/rapid7/boxes/metasploitable3-ub1404 and
https://app.vagrantup.com/rapid7/boxes/metasploitable3-win2k8

If it's really wanted, the disk / ova could be pulled out of a downloaded
vagrant box -- a vagrant box is just a disk zipped with a meta file. But
that's not for noobs-- vagrant iS the most noob-friendly approach IMO.

**Comment by nortonofnorthamerica** [comment]
So I’m not the smartest guy or the most educated but let me see if I got this right.
  - the goal is to get some broken machines put on a hyper visor .
    - Rapid7 makes the machines available but instead of just cloning the file and then converting it to what ever you need for the hyper visor you’re using they insist on using vagrant and packer, which for reasons unknown but seemingly unnecessary if they just cloned a machine so I assume it’s spyware . 
    - then rapid7 puts on some instructions that are less than clear for windows and simply don’t work for Linux( at least yesterday)
 - you think the easy way is to put in the extra programs so you can download the file when all anybody wants is a file of a broken machine in a format they can use ?
    What is more noob friendly than a .zip file?

**Comment by bcoles** [comment]
> What is more noob friendly than a .zip file?

You can grab virtual machines here:

https://github.com/rapid7/metasploitable3/issues/163#issuecomment-538932355

I have no idea if they're up to date.

**Comment by deargle** [comment]
There's a pervasive misunderstanding, probably a shortcoming of the readme,
where users assume that packer is required. But packer is only required if
you want to *build the image yourself*. If you'd rather use pre-built ones,
you can use the boxes on vagrantcloud that I linked above and that are
linked from the readme -- no packer required. The misunderstanding probably
comes from vagrant being used in both the use-prebuilt and build-yourself
approaches. If a user is concerned about spyware, they can examine the
packer build scripts in this repo. Although malware / spyware that can jump
out of virtual machines is not very common, especially with the default vm
network settings specified in the vagrantfile IIRC.

One benefit of using vagrant is that a user does not have to specify any
virtual machine settings as one did with metasploitable2 when attaching the
disk to a new VirtualBox instance or whatever. It's literally two commands,
the second being `vagrant up`. *Assuming you're using the pre-built boxes,
which is the 'vagrant way'*

It's also easy with vagrant to throw away the box and start from a clean
slate, without having to use checkpoints.

Metasploitable2 was built on a really old Linux, and it wasn't possible to
know how certain vulns were put in place etc. This new approach is really
nice for seeing the what-where config. And, without looking, I'm pretty
sure that the anti-virus false positives come from the images running
compromised versions of certain packages. Or from them being bundled with
backdoor shells. Not all of the vulnerabilities are backdoors -- most are
just specific versions of packages that were misconfigured or that had
certain holes. The images aren't "broken" -- they're _vulnerable_. But
you're probably referring to a broken packer build process, which, a third
time, is bypassable by using pre-built vagrant boxes.

**Comment by nortonofnorthamerica** [comment]
I think the misunderstanding steams from the fact that when you follow the quick version it doesn’t work . 
  Then you go the build your own version .It doesn’t work for Linux ( at least yesterday ) Then you say “this if fucking stupid . Why didn’t they just put up pre made images? “ 
  Then you get to meet nice fellas like you

**Comment by iamaravindim** [comment]
Installation instructions:
Rename the files that @Sliim gave to .box files like metasploitable_3_ubuntu.box.
Info on box files
https://www.vagrantup.com/docs/boxes/format

Then do:
```
vagrant box add my-box name-of-the-box.box
vagrant init my-box
```
then into the Vagrant file newly generated add the following:
```
config.vm.box = "my-box"
config.vm.boot_timeout = 900
config.ssh.private_key_path = "~/.ssh/id_ed25519"
config.ssh.forward_agent = true
```

Then run:
```
vagrant up
```

Replace my-box with a different name of your choice like meta-ubuntu-box

For ubuntu you may have to ssh into the vm using
`ssh vagrant@localhost -p 2222`
while the vagrant in running with `vagrant up`

After that copy and paste the public key of your system to the destination ~/.ssh/authorized_keys
for generating ssh keys:
`ssh-keygen -t ed25519 -C "your_email@example.com"`

then do
`cat ~/.ssh/id_ed25519.pub`
copy the output

then after ssh-ing into the metasploitable ubuntu system paste it in ~/.ssh/authorized_keys and save it 

All these are doing while `vagrant up` command is running

Then the command will succeed and the vm gets built
