### ISSUE TITLE
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2

### ISSUE THREAD

**Issue by jingjinghack** [rapid7/metasploitable3#165]
## Issue Description
After running build_win2008.sh, 'virtualbox-iso' errored: Script exited with non-zero exit status: 2

## Host System
* OS: ArchLinux
* Packer Version: 0.12.2
* Vagrant Version: 1.9.7
* VirtualBox Version: 5.1.22

## Command Output
https://gist.github.com/jingjinghack/39a72d9eba0c821c5e9b7e100261fd14

**Comment by Chan9390** [comment]
Missed to resolve this issue. Sorry.
From the logs I could see that the error starts after executing the command `start /WAIT C:\Windows\Temp\ManageEngine_DesktopCentral.exe /w /s /f1C:\Vagrant\resources\manageengine\setup.iss`.
I think ManageEngine didn't download successfully. Try building metasploitable 3 again.

**Comment by jingjinghack** [comment]
It works.
