### ISSUE TITLE
'Vagrant Up' not working for vmware-iso after build and vagrant box add.

### ISSUE THREAD

**Issue by derhornspieler** [rapid7/metasploitable3#166]
hostname:metasploitable3 username$ 
<img width="781" alt="screen shot 2017-07-18 at 9 28 44 pm" src="https://user-images.githubusercontent.com/15236687/28346614-1ea00d2a-6c00-11e7-8b4d-1472c5462f13.png">
<img width="781" alt="screen shot 2017-07-18 at 9 28 44 pm" src="https://user-images.githubusercontent.com/15236687/28346621-25f97d4a-6c00-11e7-918e-13fd206e5442.png">

vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Box 'metasploitable3' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'metasploitable3' (v0) for provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Downloading: metasploitable3
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/Shared/metasploitable3/metasploitable3

**Comment by Chan9390** [comment]
What is the output for the command `vagrant box list` ?

**Comment by derhornspieler** [comment]
@Chan9390 See attached
<img width="947" alt="screen shot 2017-07-18 at 9 46 46 pm" src="https://user-images.githubusercontent.com/15236687/28347031-b0a98f50-6c02-11e7-9536-9a3ef52bfac7.png">

**Comment by derhornspieler** [comment]
@Chan9390 below is what I get with this command.

hostname:metasploitable3 username$ vagrant box list
metasploitable3 (vmware_desktop, 0)

**Comment by StevenB23** [comment]
solution?
