### ISSUE TITLE
ftp service not installed in my box 

### ISSUE THREAD

**Issue by AliBawazeEer** [rapid7/metasploitable3#171]
## Issue Description
i have the vm up and running however there is no ftp service running despite the video and tutorial i see ,
is it a failure of the installed or intentionally disabled .

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by Chan9390** [comment]
Currently, *FTP service doesnt work in some builds*. Some tests are being added to the existing code to make sure that all the mentioned vulnerable services starts.

**Comment by AliBawazeEer** [comment]
well , chan do you mean i should clone and build it again n then check ?!
or any fix i should add in my current build

**Comment by Chan9390** [comment]
This is an issue in the current master branch. The code will be updated in probably a few days.

**Comment by AliBawazeEer** [comment]
awaiting the new update , keep me posted 
thank you

**Comment by jmartin-r7** [comment]
Fixed by #368.
