### ISSUE TITLE
Ansible role for metasploitable3

### ISSUE THREAD

**Issue by tterranigma** [rapid7/metasploitable3#173]
Just in case it is of interest to you, I have created an Ansible role that installs Metasploitable on a target Windows Server 2008 R2. You can find it [here](https://github.com/tterranigma/ansible-metasploitable).

**Comment by Chan9390** [comment]
Really good and impressive work. But it is decided that metasploitable 3 uses chef for provisioning.

**Comment by tterranigma** [comment]
Let me add here (if anyone stumbles on this issue from a search engine), the Ansible role provisions a Windows Server 2008 R2 machine, while the Chef branch (currently) provisions an Ubuntu machine.

**Comment by jbarnett-r7** [comment]
Agreed, you did an amazing job. I do appreciate increasing the variety of ways someone can build Metasploitable.

You are correct that chef is currently only being used in the Ubuntu version. @Chan9390 is working on converting all of the existing Windows scripts over to Chef as we speak, so we should be using Chef for both very soon.
