### ISSUE TITLE
What is the purpose of CHANGETHISIP in wordpress db dump?

### ISSUE THREAD

**Issue by tterranigma** [rapid7/metasploitable3#175]
What is the purpose of 'CHANGETHISIP' in `resources/wordpress/wordpress.sql`? Is this supposed to be replaced at some point? I am asking because I tried to use the metasploitable scripts to install wordpress and I had to change this value to my window's instance IP to make wordpress load at http://ip:8585/wordpress.

**Comment by Chan9390** [comment]
Yes. `CHANGETHISIP` is just a reference point to make sure that there is no human error during the development process. Have a look at the script [`update_ip.ps1`](https://github.com/rapid7/metasploitable3/blob/master/resources/wordpress/update_ip.ps1), it replaces the URL address in the database.

**Comment by Chan9390** [comment]
I hope this solved your question. Closing the issue :smile:
