### ISSUE TITLE
Error removing floppy controller.

### ISSUE THREAD

**Issue by akame713** [rapid7/metasploitable3#177]
## Issue Description
I have a problem with the installation, I already read a lot of guides, not one does not help, help solve the problem, thank you in advance. Sorry for my English.
## Host System
* OS:Parrot OS
* Packer Version:1.9.7
* Vagrant Version:0.10.2
* VirtualBox Version:5.1

## Command Output
==> virtualbox-iso: Error removing floppy controller: VBoxManage error: VBoxManage: error: The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1038 of file VBoxManageStorageController.cpp
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error removing floppy controller: VBoxManage error: VBoxManage: error: The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1038 of file VBoxManageStorageController.cpp

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error removing floppy controller: VBoxManage error: VBoxManage: error: The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1038 of file VBoxManageStorageController.cpp

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
Can you please give a brief about the steps you took to setup metasploitable 3 ? Did you click on something on VirtualBox when vagrant was running ?
Please try again and report if you find the error again.

**Comment by akame713** [comment]
Standard installation by steps:
./build.sh
Then everything goes fine, there's nothing I do not touch absolutely, the program installs the packages, and in the end this is the error that climbs

**Comment by akame713** [comment]
Pls help me))

**Comment by leandroinaccio** [comment]
Hey @akame713 ,

I guess which this can solve your problem:

First, update your packer(0.11.0 or newer) and downgrade vagrant to 1.9.1(according to requirements of Metasploitable3).

In windows_2008_r2.json in virtualbox, try one of these solutions:

change 
"headless": false,
to
"headless": true,

or

add "post_shutdown_delay" = "5m", according to https://www.packer.io/docs/builders/virtualbox-iso.html#post_shutdown_delay

Reference:
https://github.com/hashicorp/packer/issues/2401
https://github.com/hashicorp/packer/issues/3744#issuecomment-256060647
https://github.com/hashicorp/packer/issues/4432
https://www.virtualbox.org/ticket/16063

**Comment by andyman212** [comment]
Hello 

Mine is currently configured like this and I still get the error, has anyone found any fixes for this ?

Thanks !

 "builders": [
    {
      "headless": true,
	  "shutdown_timeout": "1h",
	  "post_shutdown_delay": "5m", 
}

**Comment by Chan9390** [comment]
What version of Packer, vagrant and VirtualBox are you using ?

**Comment by andyman212** [comment]
Hey Chan,

Packer 0.12.0
Vagrant 1.9.1
VirtualBox 5.1.26

Thanks

**Comment by Chan9390** [comment]
Try to get the latest Packer version. Its v 1.0.4 as of now.

**Regarding the error:**
- Open `windows_2008_r2.json` file
- Goto [Line 52](https://github.com/rapid7/metasploitable3/blob/master/windows_2008_r2.json#L52)
  `"headless": false,`
- Append the following config
  ```
  "shutdown_timeout": "1h",
  "post_shutdown_delay": "5m",
  ```

So the config looks something like this:
```
"iso_checksum": "{{user `iso_checksum`}}",
"headless": false,
"shutdown_timeout": "1h",
"post_shutdown_delay": "5m",
"boot_wait": "10m",
```

**Comment by andyman212** [comment]
virtualbox-iso: C:\Users\vagrant>rmdir /S /Q C:\vagrant
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Error removing floppy controller: VBoxManage error: VBoxManage.exe: error: The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)
==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee IUnknown
==> virtualbox-iso: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1038 of file VBoxManageStorageController.cpp
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error removing floppy controller: VBoxManage error: VBoxManage.exe: error: The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1038 of file VBoxManageStorageController.cpp

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error removing floppy controller: VBoxManage error: VBoxManage.exe: error: The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1038 of file VBoxManageStorageController.cpp

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At D:\Metasploitable\metasploitable3-master\build_win2008.ps1:107 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.



Same Issue :(

**Comment by andyman212** [comment]
[json file.txt](https://github.com/rapid7/metasploitable3/files/1288169/json.file.txt)

**Comment by andyman212** [comment]
Sorry was windows 10 Coded editor thing, It was not saving the changes correctly.

Thanks for your help.

Any idea on this error now :P 

PS D:\Metasploitable\metasploitable3-master> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'metasploitable3'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: metasploitable3-master_default_1504888974284_456
==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Querying NetCfgInstanceId failed (0x00000002)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp

**Comment by Chan9390** [comment]
I think the metasploitable VM which you built previously is not deleted. Please delete the VM (remove all the files), restart the base system and retry the build.

**Comment by andyman212** [comment]
Thanks, Removed it all and got the same error. Should I start a new thread ?

**Comment by rclaborde** [comment]
Was having this same issue.  Above fixed it for me as well -- thanks!

**Comment by Chan9390** [comment]
Closing the issue as it seems to be fixed

**Comment by rclaborde** [comment]
Hi @Chan9390, new to github, so maybe I am missing something, but why mark as fixed if the current version still has the broken windows_2008_r2.json file?

**Comment by busterb** [comment]
So, suggest that we extend the timeout 5 minutes would solve it for most people?

**Comment by pdeardorff-r7** [comment]
Adding the shutdown timeout / delays fixed the build error for me.
