### ISSUE TITLE
Build fails on macOS rails/generators/app_base.rb:140:in `create_root': uninitialized constant

### ISSUE THREAD

**Issue by TomHubGit** [rapid7/metasploitable3#180]
## Issue Description
I am currently trying to build the machine on my macbook. Downloaded the latest version from GitHub and executed build_win2008.sh script.
It works until it fails at some point, seems to be related with ruby gems.

Anyone any idea what this could be? Any help is appreciated (I hope I didnt missed anything obvious...)

Thanks in advance
Tom

## Host System
* OS: macOS Sierra 10.12.16
* Packer Version: 1.0.0
* Vagrant Version: Vagrant 1.9.1
* VirtualBox Version: 5.1.26

## Command Output
virtualbox-iso: C:\Users\vagrant>C:\tools\ruby23\bin\rails.bat _4.1.1_ new "C:\Program Files\Rails_Server"
    virtualbox-iso: exist
    **virtualbox-iso: C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/app_base.rb:140:in create_root': uninitialized constant** Rails::Generators::AppBase::FileUtils (NameError)
    virtualbox-iso: Did you mean?  FileTest
    virtualbox-iso: from (eval):1:in create_root
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in run
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in invoke_command
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in block in invoke_all
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in each
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in map
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in invoke_all
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/group.rb:232:in dispatch
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/commands/application.rb:17:in `<top (required)>'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/cli.rb:14:in `<top (required)>'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/bin/rails:9:in `<top (required)>'
    virtualbox-iso: from C:/tools/ruby23/bin/rails:22:in `load'
    virtualbox-iso: from C:/tools/ruby23/bin/rails:22:in `<main>'
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...

Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the ouput above for any error messages.`

**Comment by Chan9390** [comment]
This issue is with ruby. Same as #179

**Comment by TomHubGit** [comment]
@Chan9390 thank you Chan. So if I read the issue correctly, there is currently no fix for that? Even downgrading to an earlier version of VirtualBox didnt helped

**Comment by Chan9390** [comment]
Downgrading the VirtualBox doesnt make sense in this case. I earlier thought that there was error with the VirtualBox version (just because metasploitable 3 build was not tested on the latest version). I hope this issue is temporary.

**Comment by TomHubGit** [comment]
Hope so too. I also don't see any sense in downgrading, as it is related to the ruby stuff during the setup. Do you know if anyone built a VirtualBox image that would be available for download? Just as a temporary workaround until this one is fixed and one can build his own machine again.

**Comment by Chan9390** [comment]
Yes. A prebuilt image of metasploitable 3 is available at `pre_built_box` branch (https://github.com/rapid7/metasploitable3/tree/pre_built_box). Its not yet merged.
Follow the instructions provided in the README.

**Comment by nemoo2** [comment]
This issue caused me a lot of pain, especially since the default metasploitable3 action on package is to delete and cleanup. I added `-on-error=ask` to package build; perhaps this should be the default setting for build_win2008.sh ?

**Comment by Chan9390** [comment]
Currently the setup is smooth, no much user interaction. Adding `-on-error=ask` flag to the script, may lead to incomplete metasploitable 3 build if the user decides to continue even after error.

**Comment by TomHubGit** [comment]
Thanks @Chan9390 ! Just downloaded it and set it up. Seems to work like a charm! Looking forward to play with it. You saved me a lot of time with your tipp!

**Comment by nemoo2** [comment]
My (hacky) workaround to this issue was to add the required module to app_base.rb. Its not good, but it works? Edit the `scripts/installs/install_rails_server.bat` to add these lines
```
echo require 'fileutils' > C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/app_base.rb.new                                                                                                                       
type C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/app_base.rb >> C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/app_base.rb.new                                                 
type C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/app_base.rb.new > C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/app_base.rb                                                    
                                                                                                                                                                                                                                              
C:\tools\ruby23\bin\rails.bat _4.1.1_ new "C:\Program Files\Rails_Server"                                                                                                                    
```
While I don't recommend this approach at all, I'm very new to Metaspolitable, and unsure if Railites 4.1.1 was chosen for a good reason. Future versions of railites do seem to require this module correctly.

**Comment by Chan9390** [comment]
Instead of taking immediate actions, I think its better to wait for some time. The build was successful from a long time and the error popped out just a few days back.
Thanks for the hack. Good work :smile:

**Comment by jbarnett-r7** [comment]
I've removed the rails service for now, until this can be resolved on the upstream.

**Comment by Chan9390** [comment]
Hey @TomHubGit and @nemoo2, the error is now resolved. Please pull the latest code.

**Comment by TomHubGit** [comment]
Thanks @Chan9390 
I will pull the latest version in the next couple of days and try it!
