### ISSUE TITLE
Ruby version that downloads is 2.4 but is 2.3 in the install scripts

### ISSUE THREAD

**Issue by MacR6** [rapid7/metasploitable3#181]
## Issue Description
Ruby version that downloads is 2.4 but is 2.3 in the install scripts. Check the install scripts and the install of Ruby. Can't get passed the install of Ruby.

Also, Apache Tomcat 8.5 is downloaded and installed, but the script tries to start 8.0 and fails.
## Host System
* OS: OSX
* Packer Version: 
* Vagrant Version:
* VirtualBox Version:

## Command Output
Ruby version that downloads is 2.4 but is 2.3 in the install scripts.  Check the install scripts and the install of Ruby.  Can't get passed the install of Ruby.

Also, Apache Tomcat 8.5 is downloaded and installed, but the script tries to start 8.0 and fails.

**Comment by jbarnett-r7** [comment]
I think you might be on an older checkout of this repo. We had this issue a while back but have recently pinned the versions to resolve it.

https://github.com/rapid7/metasploitable3/blob/master/scripts/installs/install_ruby.bat
https://github.com/rapid7/metasploitable3/blob/master/scripts/chocolatey_installs/tomcat.bat

Try doing a `git pull` and running the build again.

**Comment by MacR6** [comment]
Okay so I downloaded the zip the first time and ran into those problems.  Cloned it out like you said and it let me get through the install until the end.  Below is the output.  It appears that it deleted the virtual box vm.  I could just be missing something as it's late and I'm delerious

##Output:
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Preparing to export machine...
    virtualbox-iso: Deleting forwarded port mapping for the communicator (SSH, WinRM, etc) (host port 2504)
==> virtualbox-iso: Exporting virtual machine...
    virtualbox-iso: Executing: export metasploitable3-win2k8 --output output-virtualbox-iso/metasploitable3-win2k8.ovf
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Running post-processor: vagrant
==> virtualbox-iso (vagrant): Creating Vagrant box for 'virtualbox' provider
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso/metasploitable3-win2k8-disk001.vmdk
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso/metasploitable3-win2k8.ovf
    virtualbox-iso (vagrant): Renaming the OVF to box.ovf...
    virtualbox-iso (vagrant): Using custom Vagrantfile: vagrantfile-windows_2008_r2.template
    virtualbox-iso (vagrant): Compressing: Vagrantfile
    virtualbox-iso (vagrant): Compressing: box.ovf
    virtualbox-iso (vagrant): Compressing: metadata.json
    virtualbox-iso (vagrant): Compressing: metasploitable3-win2k8-disk001.vmdk
Build 'virtualbox-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: windows_2008_r2_virtualbox.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
metasploitable3 already found in Vagrant box repository. Skipping the addition to Vagrant.
NOTE: If you are having issues, try starting over by doing 'vagrant destroy' and then 'vagrant up'.
---------------------------------------------------------------------
SUCCESS: Run 'vagrant up' to provision and start metasploitable3.
NOTE: The VM will need Internet access to provision properly.

**Comment by Chan9390** [comment]
Run the command `vagrant box remove metasploitable3` and then start the
build again.

**Comment by MacR6** [comment]
Jbarnett-r7 - did that instead of just downloading the zip and I'm good.  Thanks!

Thank you Chan9390.  That worked like a charm.
