### ISSUE TITLE
disable windows update

### ISSUE THREAD

**Issue by alkampfergit** [rapid7/metasploitable3#183]
After the VM started in vmware I've noticed that the windows update service is active. I thiknk that in a machine, where we want to have vulnerabilities, it is better to leave windows update service stopped an in disabled state.

**Comment by jbarnett-r7** [comment]
Did you see that updates were actually installed? I think the service may be running but the updates are not ever scheduled to download and install. As you can see from this line in the Autounattend installation of Windows Updates is disabled. 

https://github.com/rapid7/metasploitable3/blob/master/answer_files/2008_r2/Autounattend.xml#L276

If the service is just running I don't really think it's a problem as long as the updates never get installed.

**Comment by alkampfergit** [comment]
Yes, windows update is configured not to download anything, but if it is possible it would be better to completely disable the service. I've not tried, but if I join the machine to a test domain, probably it will grab the update policy of the domain (if any) and could potentially start an  upgrade (like with internal WSUS).

Disabling completely the windows Update service will surely prevents any update from occurring.

Thanks.

**Comment by alkampfergit** [comment]
Confirmed that the VM did not checked for any update, issue closed.
