### ISSUE TITLE
Question: Does using vmware workstation requires a license for vagrant?

### ISSUE THREAD

**Issue by alkampfergit** [rapid7/metasploitable3#184]
I'm sorry for this really newbie question, but I'm really not familiar with vagrant+vmware. I have vmware workstation installed on a windows machine, I was able perfectly to create the .box virtual machine, but then when I start the machine with vagrant up i got this

![image](https://user-images.githubusercontent.com/358545/30635359-75e84b1e-9df2-11e7-8bce-1e5510f16574.png)

Clearly the error is due to the fact that it is trying to use virtualbox provider, but to use vmware it seems that I need to install a plugin that is not free.

My question is, packer build was able to use my vmware-workstation installation without any problem (I was able to login to the machine and use the machine during the build process), so it did not not require license to build the box, but it seems that I need a vmware license to use the vagrant up command, is it true or  I'm missing something?

Thanks a lot.

**Comment by alkampfergit** [comment]
It seems that the .box file is simply an archive, I unarchived all the virtual machine files and I was able to open in vmware workstation. Clearly this probably will miss any further configuration that vagrant up does, but at least the machine seems to run fine. :)

**Comment by Chan9390** [comment]
Did you execute the command `vagrant box add metasploitable3 windows_2008_r2_virtualbox.box` before doing `vagrant up`?

**Comment by alkampfergit** [comment]
Yes, I've added the box, but clearly the name is different, because it is windows_2008_r2_vmware.box, it worked, but when I try to vagrant up the machine I need to use vmware provider.

In the same host I've then configured everything with virtualbox without any problem.

Gian Maria.

**Comment by Chan9390** [comment]
Okay. Is it working now ?

**Comment by alkampfergit** [comment]
It is working like a charm in virtualbox, for vmware I've simply extracted the machine from the box, so I can use it :), but without the integration with vagrant :).

**Comment by jbarnett-r7** [comment]
@alkampfergit Yes, for some reason Hashicorp requires a paid plugin for use with VMWare. You can find more information on it here https://www.vagrantup.com/vmware/index.html

**Comment by alkampfergit** [comment]
Thanks.
