### ISSUE TITLE
Error when getting to rubydevkit 

### ISSUE THREAD

**Issue by bhaizlett123** [rapid7/metasploitable3#185]
Hello, i am trying to get metasploitable3 to work, i run the command "packer build windows_2008_r2.json" and everything seems to go good, but then it keeps erroring out on the section where it tries to install the rubydevkit.

## Host System
* OS: Windows 10 pro x64
* Packer Version: 1.1.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.28

## Command Output
virtualbox-iso: C:\Users\vagrant>refreshenv
    virtualbox-iso: Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
==> virtualbox-iso: Provisioning with shell script: scripts/installs/install_devkit.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>mkdir "C:\RubyDevKit"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe', 'C:\RubyDevKit\devkit.exe')"  0<NUL
    virtualbox-iso:
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The underlying
    virtualbox-iso: connection was closed: An unexpected error occurred on a receive."
    virtualbox-iso: At line:1 char:1
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('http://dl.bintray.com ...
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\RubyDevKit\devkit.exe" -o"C:\RubyDevKit\""
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
    virtualbox-iso:
    virtualbox-iso: C:\RubyDevKit\devkit.exe
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy /Y C:\Vagrant\resources\Rails_Server\devkit\dk.rb "C:\RubyDevKit"
    virtualbox-iso:         1 file(s) copied.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>C:\tools\ruby23\bin\ruby.exe "C:\RubyDevKit\dk.rb" init
    virtualbox-iso:
    virtualbox-iso: [INFO] found RubyInstaller v2.3.3 at C:/tools/ruby23
    virtualbox-iso: System ERROR:
    virtualbox-iso:
    virtualbox-iso: Initialization complete! Please review and modify the auto-generated
    virtualbox-iso: The system cannot find the file specified.
    virtualbox-iso: 'config.yml' file to ensure it contains the root directories to all
    virtualbox-iso: of the installed Rubies you want enhanced by the DevKit.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>C:\tools\ruby23\bin\ruby.exe "C:\RubyDevKit\dk.rb" install
    virtualbox-iso: [INFO] Updating convenience notice gem override for 'C:/tools/ruby23'
    virtualbox-iso: [INFO] Installing 'C:/tools/ruby23/lib/ruby/site_ruby/devkit.rb'
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>"C:\RubyDevKit\devkitvars.bat"
    virtualbox-iso: '"C:\RubyDevKit\devkitvars.bat"' is not recognized as an internal or external command,
    virtualbox-iso: operable program or batch file.
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1

**Comment by Chan9390** [comment]
It is clear from the log: `The underlying connection was closed: An unexpected error occurred on a receive`. I think it might me a connectivity issue. Try rebuilding the VM.

**Comment by bhaizlett123** [comment]
I tried it a few times and in order to fix it what i had to do was:

Modify the install_devkit.bat

And changed the 

powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe', 'C:\RubyDevKit\devkit.exe')" 

To

powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe', 'C:\RubyDevKit\devkit.exe')" 

So pretty much just changed it from http to https and then everything worked perfect, not sure why that was because i tried to download it manually on both http and https and it worked no issues. But if anyone else has this issue, this is what worked for me

**Comment by busterb** [comment]
Sounds like a good change even if http did work. Might be some 'helpful' proxy along the way causing trouble when using http.

**Comment by Chan9390** [comment]
Closing the issue as it is resolved.
