### ISSUE TITLE
unsuccessful install 

### ISSUE THREAD

**Issue by TroddenSapde** [rapid7/metasploitable3#186]
## Issue Description
Hi , i was trying to install metasploit 3 running this command "powershell -ExecutionPolicy ByPass -File build_win2008.ps1" it downloaded the "75e529d96d6b175622512cf0a1bc55a5d1677e6a9d3b913fe95c65b6aa41770d.iso" in "packer_cache" folder then this happened .

## Host System
* OS: windows 10
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.14

## Command Output

    virtualbox-iso: jre8 v8.0.144 [Approved]
    virtualbox-iso: jre8 package files install completed. Performing other installation steps.
    virtualbox-iso: Searching if new version exists...
    virtualbox-iso: Attempt to get headers for https://javadl.oracle.com/webapps/download/AutoDL?BundleId=225353_090f390
dda5b47b9b721c7dfaa008135 failed.
    virtualbox-iso: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://javadl.oracl
e.com/webapps/download/AutoDL?BundleId=225353_090f390dda5b47b9b721c7dfaa008135'. Exception calling "GetResponse" with "0
" argument(s): "The remote server returned an error: (403) Forbidden."
    virtualbox-iso: Downloading jre8
    virtualbox-iso: from 'https://javadl.oracle.com/webapps/download/AutoDL?BundleId=225353_090f390dda5b47b9b721c7dfaa00
8135'
    virtualbox-iso: ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://javad
l.oracle.com/webapps/download/AutoDL?BundleId=225353_090f390dda5b47b9b721c7dfaa008135'. Exception calling "GetResponse"
with "0" argument(s): "The remote server returned an error: (403) Forbidden."
    virtualbox-iso: The install of jre8 was NOT successful.
    virtualbox-iso: Error while running 'C:\ProgramData\chocolatey\lib\jre8\tools\chocolateyInstall.ps1'.
    virtualbox-iso: See log for details.
    virtualbox-iso:
    virtualbox-iso: javaruntime-platformspecific v7.0.79.20161125 [Approved]
    virtualbox-iso: javaruntime-platformspecific package files install completed. Performing other installation steps.
    virtualbox-iso: The install of javaruntime-platformspecific was successful.
    virtualbox-iso: Software install location not explicitly set, could be in package or
    virtualbox-iso: default install location if installer.
    virtualbox-iso:
    virtualbox-iso: Chocolatey installed 1/2 packages. 1 packages failed.
    virtualbox-iso: See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    virtualbox-iso:
    virtualbox-iso: Failures
    virtualbox-iso: - jre8 (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\jre8\tools\chocolateyInstal
l.ps1'.
    virtualbox-iso: See log for details.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>chocolatey feature disable -n=allowGlobalConfirmation
    virtualbox-iso: Chocolatey v0.10.8
    virtualbox-iso: Disabled allowGlobalConfirmation
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>exit
==> virtualbox-iso: Restarting Machine
==> virtualbox-iso: Waiting for machine to restart...
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: sh: /cygdrive/c/Windows/system32/shutdown.exe: Read-only file system
    virtualbox-iso: #< CLIXML
    virtualbox-iso: VAGRANT-2008R2 restarted.
    virtualbox-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" Re .........
    virtualbox-iso: 0
    virtualbox-iso: Failed to start service 'Apache Tomcat 8.0 Tomcat8 (Tomcat8)'.
    virtualbox-iso: Only an exit code of non-zero will fail the package by default. Set
    virtualbox-iso: `--failonstderr` if you want error messages to also fail a script. See
    virtualbox-iso: `choco -h` for details.
    virtualbox-iso: Environment Vars (like PATH) have changed. Close/reopen your shell to
    virtualbox-iso: see the changes (or in powershell/cmd.exe just type `refreshenv`).
    virtualbox-iso: The install of tomcat was successful.
    virtualbox-iso: Software installed to 'C:\Program Files\Apache Software Foundation\tomcat'
    virtualbox-iso:
    virtualbox-iso: Chocolatey installed 1/2 packages. 1 packages failed.
    virtualbox-iso: See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    virtualbox-iso:
    virtualbox-iso: Failures
    virtualbox-iso: - jdk8 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\jdk8\tools\chocolateyInstall
.ps1'.
    virtualbox-iso: See log for details.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>chocolatey feature disable -n=allowGlobalConfirmation
    virtualbox-iso: Chocolatey v0.10.8
    virtualbox-iso: Disabled allowGlobalConfirmation
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>exit
==> virtualbox-iso: Provisioning with shell script: scripts/installs/setup_apache_struts.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>del "C:\Program Files\Apache Software Foundation\tomcat\apache-tomcat-8.0.33\conf\t
omcat-users.xml"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\apache_struts\tomcat-users.xml "C:\Program Files\Apache S
oftware Foundation\tomcat\apache-tomcat-8.0.33\conf\tomcat-users.xml"
    virtualbox-iso: 1 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\apache_struts\server.xml "C:\Program Files\Apache Softwar
e Foundation\tomcat\apache-tomcat-8.0.33\conf"
    virtualbox-iso: 1 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config Tomcat8 start= auto
    virtualbox-iso: [SC] ChangeServiceConfig SUCCESS
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start "Apache Tomcat 8.0 Tomcat8"
    virtualbox-iso: The Apache Tomcat 8.0 Tomcat8 service could not be started.
    virtualbox-iso: The Apache Tomcat 8.0 Tomcat8 service is starting.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: A service specific error occurred: 1.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\apache_struts\struts2-rest-showcase.war "C:\Program Files
\Apache Software Foundation\tomcat\apache-tomcat-8.0.33\webapps"
    virtualbox-iso: More help is available by typing NET HELPMSG 3547.
    virtualbox-iso:
    virtualbox-iso: 1 file(s) copied.
==> virtualbox-iso: Provisioning with shell script: scripts/installs/setup_glassfish.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>mkdir C:\glassfish
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://downloa
d.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')"  0<NUL
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The remote server
    virtualbox-iso: returned an error: (403) Forbidden."
    virtualbox-iso: At line:1 char:1
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('http://download.java. ...
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso: + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso: + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\
glassfish"
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
    virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: C:\Windows\Temp\glassfish4.zip
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\gla
ssfish\domains\domain1\config\admin-keyfile"
    virtualbox-iso: 0 file(s) copied.
    virtualbox-iso: System ERROR:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassf
ish\domains\domain1\config\domain.xml"
    virtualbox-iso: The system cannot find the file specified.
    virtualbox-iso: 0 file(s) copied.
    virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"
    virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start domain1
    virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 10"
    virtualbox-iso: The service name is invalid.
    virtualbox-iso:
    virtualbox-iso: More help is available by typing NET HELPMSG 2185.
    virtualbox-iso:
    virtualbox-iso: The service name is invalid.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net stop domain1
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
    virtualbox-iso: More help is available by typing NET HELPMSG 2185.
    virtualbox-iso:
    virtualbox-iso: processed file: C:\glassfish
    virtualbox-iso: Successfully processed 1 files; Failed processing 0 files
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\Parsasam\Documents\metasploitable3-master\build_win2008.ps1:107 char:9
         throw "Error building the Vagrant box using Packer. Please ch ...
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
     FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by Chan9390** [comment]
Closing the issue as this is just an error on the users network connectivity. @TroddenSapde if you face the same problem again please reopen this issue.

BTW `choco install javaruntime-platformspecific` command works fine on my end (and it should with others too)

![image](https://user-images.githubusercontent.com/12944530/30771753-67045436-a06c-11e7-94ac-6dbabd22f3fb.png)

![image](https://user-images.githubusercontent.com/12944530/30771759-944bc988-a06c-11e7-89ff-34be9639801f.png)
