### ISSUE TITLE
packer build failure due to wamp bin

### ISSUE THREAD

**Issue by frozen352** [rapid7/metasploitable3#189]
## Issue Description
Ran:

packer build --only=virtualbox-iso windows_2008_r2.json

I receive a non-zero exit of 36 due to wamp server installation failure.
"This version of C:\Windows\Temp\wampserver2.2.d-x64.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."

## Host System
* OS: OSX 10.12.6
* Packer Version: 1.1.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.28

## Command Output
==> virtualbox-iso: Provisioning with shell script: scripts/installs/install_wamp.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://sourceforge.net/projects/wampserver/files/WampServer 2/WampServer 2.2/wampserver2.2d-x64.exe', 'C:\Windows\Temp\wampserver2.2.d-x64.exe')"  0<NUL
    virtualbox-iso: This version of C:\Windows\Temp\wampserver2.2.d-x64.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>C:\Windows\Temp\wampserver2.2.d-x64.exe /verysilent
    virtualbox-iso:
    virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\wamp\httpd.conf" "C:\wamp\bin\apache\Apache2.2.21\conf\httpd.conf"
    virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:         0 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\wamp\phpmyadmin.conf" "C:\wamp\alias\phpmyadmin.conf"
    virtualbox-iso:         0 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config wampapache start= auto
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config wampmysqld start= auto
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>icacls "C:\wamp" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
    virtualbox-iso: C:\Documents and Settings\All Users\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\*: The system cannot find the path specified.
    virtualbox-iso: Successfully processed 0 files; Failed processing 1 files
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config wampapache obj= "NT Authority\LOCAL SERVICE"
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36

==> Builds finished but no artifacts were created.

**Comment by Chan9390** [comment]
Did you manually download the Windows 2008 R2 ISO file ? If yes, check if it is a x64 Windows ISO file.

**Comment by 3lpsy** [comment]
If you look at the install for wamp, you can see the url: "https://sourceforge.net/projects/wampserver/files/WampServer 2/WampServer 2.2/wampserver2.2d-x64.exe". 

At this point in time, attempting to visit that url returns:
"The sourceforge.net website is temporarily in static offline mode.
Only a very limited set of project pages are available until the main website returns to service". I'm experiencing the same issue. Maybe give it a few hours or try again tomorrow.

**Comment by hemanthkumar98** [comment]
virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\wamp\phpmyadmin.conf" "C:\wamp\alias\phpmyadmin.conf"
virtualbox-iso: 0 file(s) copied.
virtualbox-iso:
virtualbox-iso: C:\Users\vagrant>sc config wampapache start= auto
virtualbox-iso: [SC] OpenService FAILED 1060:
virtualbox-iso:
virtualbox-iso: The specified service does not exist as an installed service.
virtualbox-iso:
virtualbox-iso:
virtualbox-iso: C:\Users\vagrant>sc config wampmysqld start= auto
virtualbox-iso: [SC] OpenService FAILED 1060:
virtualbox-iso:
virtualbox-iso: The specified service does not exist as an installed service.
virtualbox-iso:
virtualbox-iso:
virtualbox-iso: C:\Users\vagrant>icacls "C:\wamp" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
virtualbox-iso: C:\Documents and Settings\All Users\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data*: The system cannot find the path specified.
virtualbox-iso: Successfully processed 0 files; Failed processing 1 files
virtualbox-iso:
virtualbox-iso: C:\Users\vagrant>sc config wampapache obj= "NT Authority\LOCAL SERVICE"
virtualbox-iso: [SC] OpenService FAILED 1060:
virtualbox-iso:
virtualbox-iso: The specified service does not exist as an installed service.
virtualbox-iso:
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36

==> Builds finished but no artifacts were created.




I too had the same issue....!!

**Comment by Chan9390** [comment]
Hey @frozen352 ,
wampserver is now included under the `resources/wamp` folder. No external download is required during the build. 
Download the latest version / do a `git pull` and then start the build. Please comment if you face any issues.

**Comment by em0ral** [comment]
Downloaded the latest version but I am getting same errors as above.

**Comment by Chan9390** [comment]
Hey @em0ral , please provide information about your base system and the software versions. Providing the error message would be really helpful.

**Comment by Chan9390** [comment]
Closing the issue as wampserver is now added in the resources directory.
