### ISSUE TITLE
Build failed - No space left on device

### ISSUE THREAD

**Issue by fotiskfm** [rapid7/metasploitable3#191]
Host System
* OS: Fedora 25
* Packer Version: 1.1.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.28

I am trying to install metasploitable 3 on Virtualbox and it looks from the output that there is no free space left. Any suggestions about solving it? Should I use some other folder than /tmp/ and how could I achieve that?

## Command Output
==> virtualbox-iso: Provisioning with shell script: scripts/configs/packer_cleanup.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>rmdir /S /Q C:\vagrant
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Preparing to export machine...
    virtualbox-iso: Deleting forwarded port mapping for the communicator (SSH, WinRM, etc) (host port 3489)
==> virtualbox-iso: Exporting virtual machine...
    virtualbox-iso: Executing: export metasploitable3-win2k8 --output output-virtualbox-iso/metasploitable3-win2k8.ovf
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Running post-processor: vagrant
==> virtualbox-iso (vagrant): Creating Vagrant box for 'virtualbox' provider
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso/metasploitable3-win2k8-disk001.vmdk
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: write /tmp/packer651908698/metasploitable3-win2k8-disk001.vmdk: no space left on device

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 1 error(s) occurred:

* Post-processor failed: write /tmp/packer651908698/metasploitable3-win2k8-disk001.vmdk: no space left on device

==> Builds finished but no artifacts were created.

**Comment by Chan9390** [comment]
Try deleting something on your hard disk. For this setup you require atleast 15 GB of free space.

**Comment by Chan9390** [comment]
Hey @fotiskfm , any updates ?

**Comment by Chan9390** [comment]
Closing the issue as there are no updates from @fotiskfm
