### ISSUE TITLE
Metasploitable3 backup

### ISSUE THREAD

**Issue by iamalsaher** [rapid7/metasploitable3#192]
I want to backup my metasploitable3 because i am reinstalling my kali machine and i cant download that amount of data again.

Can anyone help

**Comment by jbarnett-r7** [comment]
You will need to export the VM as an appliance and then re-import it after you re-install Kali. I'm assuming you're using VirtualBox. I found this article that goes over steps on how to do that.

https://askubuntu.com/questions/588426/how-to-export-and-import-virtualbox-vm-images

**Comment by iamalsaher** [comment]
Thanks a lot man, worked perfectly
