### ISSUE TITLE
The box you're attempting to add already exists. Remove it before adding it again or add it with the `--force` flag.

### ISSUE THREAD

**Issue by repomanz** [rapid7/metasploitable3#193]
## Issue Description
Running the build 2008 power shell script i get error stating the vagrant box i'm trying to build is already present.  Note; while watching part of the code, i observed the output directory being built but then is deleted (assumed) by the power shell script when this error occurs.

## Host System
* OS: win 10 64bit
* Packer Version:  1.1.0
* Vagrant Version: 2.0.0
* VirtualBox Version: 5.1.28 r117968

## Command Output
==> virtualbox-iso: Preparing to export machine...
    virtualbox-iso: Deleting forwarded port mapping for the communicator (SSH, WinRM, etc) (host port 3391)
==> virtualbox-iso: Exporting virtual machine...
    virtualbox-iso: Executing: export metasploitable3-win2k8 --output output-virtualbox-iso\metasploitable3-win2k8.ovf
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Running post-processor: vagrant
==> virtualbox-iso (vagrant): Creating Vagrant box for 'virtualbox' provider
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso\metasploitable3-win2k8-disk001.vmdk
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso\metasploitable3-win2k8.ovf
    virtualbox-iso (vagrant): Renaming the OVF to box.ovf...
    virtualbox-iso (vagrant): Using custom Vagrantfile: vagrantfile-windows_2008_r2.template
    virtualbox-iso (vagrant): Compressing: Vagrantfile
    virtualbox-iso (vagrant): Compressing: box.ovf
    virtualbox-iso (vagrant): Compressing: metadata.json
    virtualbox-iso (vagrant): Compressing: metasploitable3-win2k8-disk001.vmdk
Build 'virtualbox-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: windows_2008_r2_virtualbox.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3' (v0) for provider:
    box: Unpacking necessary files from: file://E:/Downloads/metasploitable3/metasploitable3-master/windows_2008_r2_virt
ualbox.box
    box: Progress: 100% (Rate: 267M/s, Estimated time remaining: --:--:--)
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.

Name: metasploitable3
Provider: virtualbox
Version: 0
Error adding box to Vagrant. See the above output for any error messages.
At E:\Downloads\metasploitable3\metasploitable3-master\build_win2008.ps1:126 char:9
+         throw "Error adding box to Vagrant. See the above output for  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.

**Comment by repomanz** [comment]
reverted to vagrant 1.91. Same error below:

    virtualbox-iso: C:\Users\vagrant>rmdir /S /Q C:\vagrant
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Preparing to export machine...
    virtualbox-iso: Deleting forwarded port mapping for the communicator (SSH, WinRM, etc) (host port 3276)
==> virtualbox-iso: Exporting virtual machine...
    virtualbox-iso: Executing: export metasploitable3-win2k8 --output output-virtualbox-iso\metasploitable3-win2k8.ovf
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Running post-processor: vagrant
==> virtualbox-iso (vagrant): Creating Vagrant box for 'virtualbox' provider
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso\metasploitable3-win2k8-disk001.vmdk
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso\metasploitable3-win2k8.ovf
    virtualbox-iso (vagrant): Renaming the OVF to box.ovf...
    virtualbox-iso (vagrant): Using custom Vagrantfile: vagrantfile-windows_2008_r2.template
    virtualbox-iso (vagrant): Compressing: Vagrantfile
    virtualbox-iso (vagrant): Compressing: box.ovf
    virtualbox-iso (vagrant): Compressing: metadata.json
    virtualbox-iso (vagrant): Compressing: metasploitable3-win2k8-disk001.vmdk
Build 'virtualbox-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: windows_2008_r2_virtualbox.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3' (v0) for provider:
    box: Unpacking necessary files from: file://E:/Downloads/metasploitable3/metasploitable3-master/windows_2008_r2_vir
ualbox.box
    box: Progress: 100% (Rate: 302M/s, Estimated time remaining: --:--:--)
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.

Name: metasploitable3
Provider: virtualbox
Version: 0
Error adding box to Vagrant. See the above output for any error messages.
At E:\Downloads\metasploitable3\metasploitable3-master\build_win2008.ps1:126 char:9
+         throw "Error adding box to Vagrant. See the above output for  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.

**Comment by Chan9390** [comment]
Try the command `vagrant box remove metasploitable3` and then build it again.

**Comment by Chan9390** [comment]
I think in the `metasploitable3` folder, there exists a file named `windows_2008_r2_virtualbox.box`. If that is so, instead is starting the build from the beginning, just execute the following commands:
```
vagrant box remove metasploitable3
vagrant box add metasploitable3 windows_2008_r2_virtualbox.box
```

Then executing the command `vagrant up` will start the VM.

**Comment by repomanz** [comment]
Hi Chandrapal,

I ran the commands suggested and still have a problem.  Output below:


PS E:\> cd .\Downloads\metasploitable3\metasploitable3-master\
PS E:\Downloads\metasploitable3\metasploitable3-master> vagrant box remove metasploitable3
Box 'metasploitable3' (v0) with provider 'virtualbox' appears
to still be in use by at least one Vagrant environment. Removing
the box could corrupt the environment. We recommend destroying
these environments first:

default (ID: 4e5bd4dd3c4148d6899fa6f4e8d12232)

**Are you sure you want to remove this box? [y/N] y**
Removing box 'metasploitable3' (v0) with provider 'virtualbox'...
PS E:\Downloads\metasploitable3\metasploitable3-master> vagrant box add metasploitable3 windows_2008_r2_virtualbox.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3' (v0) for provider:
    box: Unpacking necessary files from: file://E:/Downloads/metasploitable3/metasploitable3-master/windows_2008_r2_vir
ualbox.box
    box: Progress: 100% (Rate: 208M/s, Estimated time remaining: --:--:--)
==> box: Successfully added box 'metasploitable3' (v0) for 'virtualbox'!
PS E:\Downloads\metasploitable3\metasploitable3-master> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
**==> default: Mounting shared folders...
    default: /vagrant => E:/Downloads/metasploitable3/metasploitable3-master
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.**

**Comment by jbarnett-r7** [comment]
Try running `vagrant destroy` and then `vagrant up`. Does that fix it?

**Comment by repomanz** [comment]
I tried that but I still don't see any virtualbox output within the directory structure.  I see in the directory the .box file though.

**Comment by Chan9390** [comment]
Hey @repomanz , **you have successfully set up the VM**.
The log says that *machine is already provisioned* because you have already created the VM and saved it as windows_2008_r2_virtualbox.box file.

**Comment by repomanz** [comment]
what command is required to convert the vagrant .box file over to an importable virtualbox machine?

**Comment by Chan9390** [comment]
When you use vagrant, it automatically configures a VM for you. If you want to export it, have a look at https://github.com/rapid7/metasploitable3/issues/192

**Comment by repomanz** [comment]
vagrant is not exporting / breaking during export then.  As of now, I do not have a MS3 VM in my virtualbox application.  I'll check 192.

**Comment by Chan9390** [comment]
Can you send the following: 
1. a screenshot of VirtualBox
2. output of command `vagrant box list`

**Comment by Chan9390** [comment]
You have setup the VM. Is your issue resolved ?

**Comment by repomanz** [comment]
Maybe I'm not understanding but I don't see how i get the box file into virtual box so i can start it.

**Comment by Chan9390** [comment]
Vagrant automatically installs the VM in virtualbox.

BTW There was no point of uploading a completely censored screenshot. I asked the screenshot to see if there was some VM named `metasploitable3_default`.
*Do you have VM with name `metasploitable3_default` setup ?*

If yes, click on it and then click **Show** to see the GUI interface of metasploitable 3.

**Comment by repomanz** [comment]
I do not have a VM named metasploitable3 or anything related to it within VirtualBox.   Even the directory path where the vms are stored for virtualbox does not have a directory related to metasploit.

What I do observe though:  When vagrant is building what I assume to be the virtual box output; I do see a working directory named metasploit3_default_output (or something similar) but when it's done that directory is deleted.

**Comment by Chan9390** [comment]
After that did you do `vagrant box add metasploitable3 windows_2008_r2_virtualbox.box` and then `vagrant up` ?

**Comment by repomanz** [comment]
Yes - i had performed those steps previously as well.  See screen shot.  After those two commands i'm left with a vboxheadless.exe process running.  No launched ms3 virtualbox os or is it selectable from the GUI.

![image](https://user-images.githubusercontent.com/20090451/31158150-5bdfcd8a-a885-11e7-8850-e0b6bc6771cb.png)

**Comment by repomanz** [comment]
I figured this out.  When I was building this env, the user I was running it as was not an admin user on the machine.  I changed the user type over to an admin account and got passed this error.  I now have a MS3 box.

**_Note:  I did launch power shell as admin though._**  Guessing some component during the build wasn't didn't have the proper admin credentials set through powershell admin?

**Comment by amit97911** [comment]
"vagrant box remove -f laravel/homestead" command will forefully remove the "laravel/homestead" box from your machine and you can reinstall it by "vagrant box add laravel/homestead"
