### ISSUE TITLE
Error building the Vagrant box using Packer. Please check the output above for any error messages.

### ISSUE THREAD

**Issue by WeiChunyu** [rapid7/metasploitable3#194]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:Kali rolling
* Packer Version:1.0.4
* Vagrant Version:1.9.1
* VirtualBox Version:5.1.28

## Command Output
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
The command output doesnt contain any information on what caused the build to fail.
Please comment the *complete output*.

**Comment by WeiChunyu** [comment]
vargant 1.9.0 success
and I English is very bad.

**Comment by Chan9390** [comment]
Closing the issue as it is resolved.
