### ISSUE TITLE
Issue with build for VMWare Workstation 11

### ISSUE THREAD

**Issue by michaelhiatt** [rapid7/metasploitable3#198]
## Issue Description
Followed along with build process detailed on front page of project, errors at issue of command: vagrant up
Attempted packer build commands:
- .\packer build .\windows_2008_r2.json
- .\packer build --only=vmware-iso windows_2008_r2.json

Attempted vagrant up commands:
- vagrant up
- vagrant up --provider vmware-desktop
- vagrant up --provider vmware-iso

## Host System
* OS: Windows 10
* Packer Version: 1.1.1
* Vagrant Version: 1.9.1 AND 1.9.2 (tried 1.9.1 first, then installed later version)
* VirtualBox Version: 5.1.4
* VMWare Workstation: 11.1.4 build-3848939

## Command Output
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'metasploitable3' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): file:///D:/VMWare
 Machines/Metasploitable3Build/metasploitable3/metasploitable3 (URI::InvalidURIError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/box_add.rb:475:in `metadata
_url?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/box_add.rb:81:in `block in
call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/box_add.rb:79:in `map'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/box_add.rb:79:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/handle_box.rb:82:in `handle
_box'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/handle_box.rb:42:in `block
in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/handle_box.rb:36:in `synchr
onize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:95:in `block in finalize_
action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/plugins/providers/virtualbox/action/check_virtualbox.r
b:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:225:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:200:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/environment.rb:567:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:186:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:186:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in
 run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in cre
ate_with_logging_context'

**Comment by Chan9390** [comment]
I have a few doubts.
1. Did you execute the command `vagrant box add metasploitable3 windows_2008_r2_virtualbox.box`
2. If you are using VMware, why have you installed VirtualBox
3. Have you installed Vagrant's VMware plugin (https://www.vagrantup.com/vmware/index.html)

**Comment by michaelhiatt** [comment]
Hopefully I can clear those doubts.

1. Yes I did execute the command 'vagrant box add ...' I actually seen the machine come up in VMWare Workstation in the previous steps while the script was adding packages, the script seemed to kill of that in favour of trying to build this vagrant box thing, which had me very confused. If it had of just left that VM I could have used it I would have thought.

2. I installed VirtualBox because it was listed as a requirement (the issue creation screen on github also advises me to list it), I actually want it in VMWare Workstation so I can use it with my Kali Linux VMWare workstation on the same segregated virtual network.

3. I have not installed the Vagrant VMWare plugin, pretty sure that is paid thing :-(

4. There was no 4 but I'm putting it here as additional feedback.
Metasploit 2 was a download and run VM instance.
It was dead simple to setup, you download it, and open it in VMWare workstation.
I am currently attempting to read through one of the Packt Kali books that mentions metasploit and metasploitable 3, it gives less instruction than the projects main page however.

I have found a few other resources but none of which are getting me passed the current issue.
Current resources used so far to get this to work:
- https://github.com/rapid7/metasploitable3
- http://www.hackingtutorials.org/metasploit-tutorials/setup-metasploitable-3-windows-10/
- http://windowspeople.com/cyber-security/34-tools/442-deploy-metasploitable3-on-vmware-workstation.html

I am currently trying to build specifically for virtualbox and if it passes, I have an idea to export the VM to some format that I can open within VMWare.

I feel the process is very convoluted when compared to simply downloading and running a prepared VM. I am prepared to be enlightened however.

**Comment by michaelhiatt** [comment]
And after what looked liked a successful build process, including 'vagrant up' for virtualbox (read my previous comment), I notice a VM has been created, after clicking the big green 'Start' toolbar button I receive the errors attached.

![virtualbox-erroronstart](https://user-images.githubusercontent.com/15351951/32133654-77d86b76-bc28-11e7-8c2c-ba510ec92d78.png)

**Comment by Chan9390** [comment]
`I installed VirtualBox because it was listed as a requirement` - You can go with any one.

`I have not installed the Vagrant VMWare plugin, pretty sure that is paid thing :-(` - If you are planning to use VMware with vagrant, you have to buy the plugin. Thats the reason metasploitable3 was initially targeting VirtualBox.

`Metasploit 2 was a download and run VM instance` - Metasploitable 3 can also be done that way. Please see [`pre_built_box`](https://github.com/rapid7/metasploitable3/tree/pre_built_box) branch.

`I am currently attempting to read through one of the Packt Kali books that mentions metasploit and metasploitable 3` - Please give me the link.

Regarding the VirtualBox error, either **take a screenshot of the error with DETAILS** or please do `vagrant up` and then comment the output.

**Comment by Chan9390** [comment]
Hey @michaelhiatt Any updates ?

**Comment by michaelhiatt** [comment]
As per previous comment, I couldn't even get it to build in VirtualBox, though you did mention why it would not work in VMWare (paid plugin I didn't have).

I looked in the pre built branch and couldn't see anything prepared ready to drop in to VMWare, any hints on how this should work?

The book I was working off of was: 
[https://www.amazon.com/Mastering-Linux-Advanced-Penetration-Testing/dp/1787120236](https://www.amazon.com/Mastering-Linux-Advanced-Penetration-Testing/dp/1787120236)

**Comment by Chan9390** [comment]
Okay, if you want the prebuilt version, add the box using:
`vagrant box add jbarnett-r7/metasploitable3-win2k8`

Then checkout to `pre_built_box` branch using:
`git checkout pre_built_box`

The do a `vagrant up`. **VMware version is available**, but I havent personally tested. VirtualBox version of the box works fine.

**Comment by MHMDhub** [comment]
Thanks @Chan9390This worked for me.  The instructions really need to be updated or organized or something.  I don't remember seeing having to do a 'git checkout pre_built_box' anywhere.  The instruction go from 'vagrant box add ...' to 'vagrant up'.

**Comment by Chan9390** [comment]
Hey @MHMDhub, the instructions to get the prebuilt box are put up on a different branch (https://github.com/rapid7/metasploitable3/tree/pre_built_box)

**Comment by Chan9390** [comment]
The issue is same as #253. It's a ruby bug on Windows. You have a space in your path: 
`D:/VMWare Machines/Metasploitable3Build/`. Check the mentioned issue for the solution.
