### ISSUE TITLE
Problem creating .box file from the ISO 

### ISSUE THREAD

**Issue by imparitosh** [rapid7/metasploitable3#199]
After multiple failed attempts to convert the iso file into box file using the script provided, tried the manual installation process. While attempting to use packer for file conversion, the shell dumped an error message "Unable to connect to the remote server".  

## Host System
* OS: Windows 10
* Packer Version: 1.1.1
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.2.0 

## Command Output
[metasploitable3 error message.docx](https://github.com/rapid7/metasploitable3/files/1445047/metasploitable3.error.message.docx)

**Comment by Chan9390** [comment]
Hey @imparitosh I think, elasticsearch was not completely installed. Both the commands show the error `Unable to connect to the remote server` which means either elasticsearch was not installed successfully or didnt start.

Please try to provide the output before `Press any key to continue...`

**Comment by imparitosh** [comment]
Thanks Chan . I did not press any key, the attached output is as it is from the shell prompt. 
Should I do something else to get going?

**Comment by Chan9390** [comment]
On automated builds like this, you dont have to press anything. I think there is some error during the  installation of elasticsearch.
