### ISSUE TITLE
Vagrant Up > No usable default provider could be found

### ISSUE THREAD

**Issue by imparitosh** [rapid7/metasploitable3#200]
While running Vagrant up, i get the below message. 

I have tried the following.
1. Change the environment variable as suggested https://stackoverflow.com/questions/29450437/unable-to-vagrant-up-how-to-set-providers

2. Forced the provider to be virtualbox 

but unfortunately none of it works

using vagrant up --provider=virtualbox returns the same error
## Host System
* OS: Windows 10
* Packer Version: 1.1.1
* Vagrant Version:1.9.1
* VirtualBox Version: 5.2.0

## Command Output
PS C:\Users\IT\Desktop\metasploitable3> vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
PS C:\Users\IT\Desktop\metasploitable3>

**Comment by busterb** [comment]
Either upgrade to vagrant 2.0.1, or downgrade virtualbox to 5.1

**Comment by bcook-r7** [comment]
Not a metasploitable issue, see https://github.com/hashicorp/vagrant/issues/9090

**Comment by MiraSharma8511** [comment]
Solution : **_

> You need to use VirtualBox compatible with the vagrant.

_**

**Proof :** 

C:\Users\---\m103\m103-vagrant-env>vagrant up --provider=virtualbox
The provider 'virtualbox' that was requested to back the machine
'mongod-m103' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.

**Comment by abuzarkamal** [comment]
make sue vboxdrv kernel module is loaded in case of Virtual Box , if not then run 

/sbin/vboxconfig as root  ... nce module is loaded it will detect .. 

This will load the module 
[root# sudo /sbin/vboxconfig
vboxdrv.sh: Stopping VirtualBox services.
vboxdrv.sh: Starting VirtualBox services.
vboxdrv.sh: Building VirtualBox kernel modules.
