### ISSUE TITLE
PS build script error downloading guest additions

### ISSUE THREAD

**Issue by heisenberg1977** [rapid7/metasploitable3#201]
## Host System 
* OS: Windows 10
* Packer Version: v1.1.2
* Vagrant Version: 2.0.1
* VirtualBox Version: 5.1.30

## Command Output
PS C:\Users\testusr\Downloads\Image\metasploitable3-master> .\build_win2008.ps1
Compatible version of VirtualBox found.
Compatible version of packer found.
Compatible version of Vagrant found.
Could not find a compatible version of vagrant-reload plugin. Attempting to install...
Installing the 'vagrant-reload' plugin. This can take a few minutes...
Fetching: vagrant-share-1.1.9.gem (100%)
Fetching: vagrant-reload-0.0.1.gem (100%)
Installed the plugin 'vagrant-reload (0.0.1)'!
The vagrant-reload plugin was successfully installed.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    virtualbox-iso: Error downloading: CreateFile Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: The system can
not find the path specified.
==> virtualbox-iso: Guest additions download failed.
Build 'virtualbox-iso' errored: Guest additions download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Guest additions download failed.

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\testusr\Downloads\Image\metasploitable3-master\build_win2008.ps1:107 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by heisenberg1977** [comment]
Verified that this iso exists in this location:
Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso

**Comment by Chan9390** [comment]
Try downloading and installing **VBoxGuestAdditions** manually and then re-execute the command.
Also please provide the output of `vagrant plugin list`. If *vagrant-vbguest* is not present in the output, please install it using `vagrant plugin install vagrant-vbguest`

**Comment by heisenberg1977** [comment]
Not sure what you mean by installing VBoxGuestAdditions manually. This error appears during the execution of the powershell script. I verified that the VBoxGuestAdditions.iso file is located where it should be.

**Comment by heisenberg1977** [comment]
C:\WINDOWS\system32>vagrant plugin install vagrat-vbguest
Installing the 'vagrat-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrat-vbguest (> 0)'

C:\WINDOWS\system32>vagrant plugin list
vagrant-reload (0.0.1)
vagrant-share (1.1.9, system)

C:\WINDOWS\system32>vagrant plugin install vagrat-vbguest
Installing the 'vagrat-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrat-vbguest (> 0)'

**Comment by heisenberg1977** [comment]
I am reading on various sites that I need specific versions of Packer, Vagrant and Virtualbox. Is that the case?

**Comment by Chan9390** [comment]
Try using the recommended versions of the software as per the readme file

**Comment by z3ndrag0n** [comment]
Have you tried: vagrant plugin install vagrant-vbguest (as it appears there is a typo in your manual install command below)

**Comment by sg84** [comment]
I had the same problem. Downgrading packer to 1.0.4 fixed the problem for me on Windows 10.

**Comment by dverstap** [comment]
I have the same problem with the same host system:

    OS: Windows 10 (Anniversary Update for me)
    Packer Version: v1.1.2
    Vagrant Version: 2.0.1
    VirtualBox Version: 5.1.30

Downgrading to packer 1.1.1 works for me.

**Comment by dwickern** [comment]
Downgrading from packer 1.1.2 to 1.1.1 worked for me

**Comment by KyleGW** [comment]
1.1.1 also worked here.

Quicklink for others with same issue:
https://releases.hashicorp.com/packer/1.1.1/

**Comment by Chan9390** [comment]
Closing the issue as downgrading packer to version 1.1.1 resolves it.
