### ISSUE TITLE
error in building vmware

### ISSUE THREAD

**Issue by sanwar0301** [rapid7/metasploitable3#202]
## Hello - please help, I'm running the below command via powershell. I have the  VBoxGuestAdditions installed, so I'm not sure why it's pointing in that error.

Thank you very much!

## Host System
* OS: Windows 10
* Packer Version: 1.1.2_windows_amd64
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.2.0

## Command Output
Command Input: metasploitable3> packer build .\windows_2008_r2.json
Command Output:
virtualbox-iso output will be in this color.
vmware-iso output will be in this color.
Build 'vmware-iso' errored: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors from each driver are shown below. Please fix at least one driver to continue:
* VMware application not found:
* VMware application not found:
* VMware application not found:
* VMware application not found:
==> virtualbox-iso: Downloading or copying Guest additions
virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
virtualbox-iso: Error downloading: CreateFile Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: The system can not find the path specified.
==> virtualbox-iso: Guest additions download failed.
Build 'virtualbox-iso' errored: Guest additions download failed.
==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* VMware application not found:
* VMware application not found:
* VMware application not found:
* VMware application not found:

--> virtualbox-iso: Guest additions download failed.
==> Builds finished but no artifacts were created.

**Comment by byinarie** [comment]
I've had a similar problem with the same error message, I fixed mine by deleting VBoxGuestAdditions.iso from the virtualbox install directory and running the build again. The error happens because the script is pulling down the guest additions iso to the C:\Program Files\Oracle\VirtualBox directory when the iso already exists.

**Comment by sanwar0301** [comment]
I fixed mine as well - I re-installed an older version of my vagrant and vbox. Seems like the new version has some problems with it. Thanks man!
