### ISSUE TITLE
Error in building metasploitable box from downloaded iso. 

### ISSUE THREAD

**Issue by adgpt** [rapid7/metasploitable3#203]
## Host System
* OS: Windows 10 64 bit | OS build 16299.64
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.14

## Command Output
I tried installing the Metasploitable 3 using the steps specified. 
The ISO file gets downloaded successfully, however, the VBoxManage action fails to start the virtual machine.
Here's the error snippet:

`virtualbox-iso: Starting the virtual machine...                                                                                                                     ==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: The virtual machine 'metasploitable3-win2k8' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\<Username>\VirtualBox VMs\metasploitable3-win2k8\Logs\VBoxHardening.log'                                 ==> virtualbox-iso: VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface `
 
I've **disabled the AV**, **the virtualization is enabled**, but I couldn't specifically understand what the error meant. 
Attached the error report and the VBoxHardening.log files. 

[metasploitable_Error_Report.txt](https://github.com/rapid7/metasploitable3/files/1484380/metasploitable_Error_Report.txt)
[vBoxHardening.log](https://github.com/rapid7/metasploitable3/files/1484381/vBoxHardening.log)

**Comment by RikJonAtk** [comment]
I had exactly this - Same OS, same software, same problems... upgrading to VirtualBox 5.2.2 fixed it for me.

**Comment by Chan9390** [comment]
Hey @adgpt , I think installation of Virtualbox was not proper. Check this [answer on StackOverflow](https://stackoverflow.com/questions/31461645/virtualbox-virtual-machine-terminates-at-startup-with-exit-code-1) to reinstall VirtualBox drivers.

**Comment by adgpt** [comment]
@RikJonAtk , 
Did you change the versions of Vagrant and packer versions too?

**Comment by adgpt** [comment]
- OS: Windows 10 64 bit | OS build 16299.64
- Packer Version: 1.0.0
- Vagrant Version: 1.9.1
- VirtualBox Version: 5.2.2

======================================
@RikJonAtk , As suggested, I've tried with the above configs. 

However, the installation got an error at **install_wamp.bat**. Furthermore, when I visited the specified link in the .bat file, 

> **https://sourceforge.net/projects/wampserver/files/WampServer%202/WampServer%202.2/wampserver2.2d-x64.exe',%20'C:/Windows/Temp/wampserver2.2.d-x64.exe**

I found the error as shown in the attached image. 
Any suggestions/help is highly appreciated. 
Attached the full installation and error report files.
[Error_log_full.txt](https://github.com/rapid7/metasploitable3/files/1571756/Error_log_full.txt)
[Error_log_specific.txt](https://github.com/rapid7/metasploitable3/files/1571757/Error_log_specific.txt)
![sourceforge_result](https://user-images.githubusercontent.com/33773342/34158925-58a47fcc-e4ed-11e7-8477-fcc169aa7f18.JPG)

**Comment by Chan9390** [comment]
Hey @adgpt ,
1. The URL is **https://sourceforge.net/projects/wampserver/files/WampServer%202/WampServer%202.2/wampserver2.2d-x64.exe** and its working fine
2. 503 error is something related to SourceForge. Please retry. If you get the same error, please report.

**Comment by adgpt** [comment]
Yeah. That worked. 
Apparently, there was a connection issue from my end. 
Finally, it worked with the latest version of Vagrant and VirtualBox.
