### ISSUE TITLE
VirtualBox  - Error (Host Memory Low)

### ISSUE THREAD

**Issue by sanwar0301** [rapid7/metasploitable3#204]
Command Input (runned in PowerShell): packer build --only=virtualbox-iso windows_2008_r2.json

After a couple of hours, the VirtualBox for the server came up - but would not proceed with the "Starting Windows" view due to an error. The error detail is "Unable to allocate and lock memory. The virtual machine will be paused. Please close applications to free up memory or close the VM. Error ID: Host Memory Low, Severity: Non-Fatal Error".

I still got 400GB free space in my local disk - my RAM has 4GB capacity. Also, when I'm checking the settings of the VirtualBox, I cant modify the settings for the Motherboard. Its currently eating 4GB in my RAM. That could be the reason why its not booting.

## Host System
* OS: Windows 10
* Packer Version: 1.0.0
* Vagrant Version: 2.0.1
* VirtualBox Version: 5.1.14

## Command Output
Command is still running, but it no longer moved as it is waiting for the Virtual Box to boot.

**Comment by Chan9390** [comment]
Hey @sanwar0301 , by default the **build of Metasploitable 3 requires 4 GB of RAM**. As you are using Windows 10, it takes around 1-2 GB for the base machine itself. So it is not possible to build Metasploitable 3 as such. Instead, try changing the setting in `windows_2008_r2.json` ([vmware](https://github.com/rapid7/metasploitable3/blob/master/windows_2008_r2.json#L42) or [virtualbox](https://github.com/rapid7/metasploitable3/blob/master/windows_2008_r2.json#L88)) to 2048.

After building, the machine requires 2GB to run by default, which means you require extra memory if you want to run Kali VM.

**Comment by jmartin-r7** [comment]
Closing issue as hardware minimum requirements related.  Tested virtualbox build in working on master with requirements met.
