### ISSUE TITLE
Cannot install metasploitable3 on Windows 8.1

### ISSUE THREAD

**Issue by halfluke** [rapid7/metasploitable3#205]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Windows 8.1 64 bit SPANISH
* Packer Version: 1.1.2
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.30

## Command Output
PS E:\documenti Luca\MCDST_MCSA_MCSE\OSCP\metasploitable3-master> .\build_win2008.ps1
Compatible version of VirtualBox found.
Compatible version of packer found.
Compatible version of Vagrant found.
Compatible version of vagrant-reload plugin found.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    virtualbox-iso: Error downloading: CreateFile Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: El sistema no
puede encontrar la ruta especificada. -> it means system cannot find the path specified
==> virtualbox-iso: Guest additions download failed.
Build 'virtualbox-iso' errored: Guest additions download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Guest additions download failed.

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
En E:\documenti Luca\MCDST_MCSA_MCSE\OSCP\metasploitable3-master\build_win2008.ps1: 107 Carácter: 9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

Additionally, it fails as well with VMWARE WORKSTATION: it installs but it fails after a failed attempt to install vmware tools and a reboot (VMWARE Workstation 14):
    vmware-iso: The interface is unknown.(1717)
    vmware-iso: The interface is unknown.(1717)
    vmware-iso: The interface is unknown.(1717)
    vmware-iso: The interface is unknown.(1717)
==> vmware-iso: Timeout waiting for machine to restart.
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Timeout waiting for machine to restart.

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Timeout waiting for machine to restart.

==> Builds finished but no artifacts were created.

**Comment by halfluke** [comment]
Solution here for virtualbox!
https://github.com/rapid7/metasploitable3/issues/201

Now I would like to know why metasploitable3 doesn't come as a vm and they made things so complicated...

**Comment by pbarry-r7** [comment]
You can blame Windows licensing for the current solution, @halfluke.  There are plans for offering the Linux Metasploitable3 (coming soon) in easier-to-use technologies.

**Comment by busterb** [comment]
And of course you can browse vagrant cloud and find a few ready-to-use VMs as well.
