### ISSUE TITLE
Unsuccessful Build using .sh script

### ISSUE THREAD

**Issue by derhornspieler** [rapid7/metasploitable3#211]
## Issue Description
Unsuccessful installation from .sh script file provided.

## Host System
* OS: Mac OS Sierra High
* Packer Version: 1.1.2
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.2.2 r119230 (Qt5.6.3)

## Command Output
    virtualbox-iso: C:\Users\vagrant>"C:\RubyDevKit\devkitvars.bat"
    virtualbox-iso: Adding the DevKit to PATH...
==> virtualbox-iso: Restarting Machine
==> virtualbox-iso: Waiting for machine to restart...
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
    virtualbox-iso: The interface is unknown.(1717)
**==> virtualbox-iso: Timeout waiting for machine to restart.
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Timeout waiting for machine to restart.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Timeout waiting for machine to restart.

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.**

**Comment by david531** [comment]
I'm also getting the same issue on Ubuntu 17.10. Everything runs and installs good up until this part:

    virtualbox-iso: C:\Users\vagrant>"C:\RubyDevKit\devkitvars.bat"
    virtualbox-iso: Adding the DevKit to PATH...

Then the VM restarts and boots up without any issue. That's when the script times out like what you see in the screenshot. 

![issue](https://user-images.githubusercontent.com/29909705/33736743-958ce23e-db48-11e7-81da-a22fa0cf7a15.png)

**Comment by Chan9390** [comment]
Hey, I think the setup took more than 5 min to restart, so packer automatically deleted the VM. Try adding the `restart_timeout` variable to `windows_2008_r2.json` file.

For @derhornspieler's error, change from:

![image](https://user-images.githubusercontent.com/12944530/33974382-29a7fcaa-e0ae-11e7-807b-6376cd0a391d.png)

To : 

```
    {
      "type": "windows-restart",
      "restart_timeout": "10m"
    },
```
You can increase the time if 10 min doesnt work for you.

**Comment by david531** [comment]
Hello,
I added the "restart_timeout" variable with "15m" and it was able to detect the restart and proceed with the setup. 

Thank you @Chan9390

**Comment by Chan9390** [comment]
Hey @derhornspieler , any updates ?

**Comment by Chan9390** [comment]
Closing the issue as increasing the value of `restart_timeout` variable resolves it.
