### ISSUE TITLE
VM fails when it trys to install jenkins

### ISSUE THREAD

**Issue by rward2801** [rapid7/metasploitable3#213]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

![image](https://user-images.githubusercontent.com/31939879/34367292-635d085e-ea6e-11e7-86d4-b121ce2506b8.png)

**Comment by hersh86** [comment]
I was having that issue as well.  Turns out my antivirus was flagging that as a Trojan and putting it into quarantine.  Check your alerts from the antivirus and you should be able to whitelist it.

**Comment by Chan9390** [comment]
Hey @rward2801 did you try whitelisting jenkins as @hersh86 suggested ? Did that work ?

**Comment by snaex** [comment]
I just recently fixed this issue. I turned off Windows Defender in Group Policy. Check out this link [https://windowsreport.com/operation-did-not-complete-virus/](url) and scroll down to the group policy section. Clone or download the master and you'll be able to use the jenkins.exe with the repo

**Comment by Chan9390** [comment]
Hey @rward2801 , any updates ?

**Comment by Chan9390** [comment]
Closing the issue as turning off Windows Defender or any other antivirus solution, and redownloading metasploitable 3 scripts resolves it.
