### ISSUE TITLE
fail to vagrant up vmware :(

### ISSUE THREAD

**Issue by gearcapitan** [rapid7/metasploitable3#214]
## Issue Description
it seems as if vagrant confuses vmware to hyper-v
step 1 packer build --only = vmware-iso windows_2008_r2.json

step 2 vagrant box add windows_2008_r2_vmware.box --name = metasploitable3

step 3 vagrant plugin install vagrant-reload

Step 4 Vagrant up ----------- fail !!!!

## Host System
* OS: windows 10
* Packer Version: last
* Vagrant Version: last
* Vmware Version: last

## Command Output
PS C:\Users\gearc\Documents> vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
The Hyper-V cmdlets for PowerShell are not available! Vagrant
requires these to control Hyper-V. Please enable them in the
"Windows Features" control panel and try again.

**Comment by jschulist** [comment]
Have you tried using the [--provider=vmware](https://www.vagrantup.com/docs/cli/up.html) option or setting your default provider using the environmental variable ([VAGRANT_DEFAULT_PROVIDER](https://www.vagrantup.com/docs/providers/default.html))?

**Comment by arunmk108** [comment]
install virtual box from below link and retry vagrant up command. It will work. To me its worked.

**Comment by arunmk108** [comment]
https://www.virtualbox.org/wiki/Downloads
