### ISSUE TITLE
openjdk‘s download is forbidden

### ISSUE THREAD

**Issue by zhang-yun912** [rapid7/metasploitable3#218]
## Issue Description
 virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')"  0<NUL
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to
    virtualbox-iso: the remote server"
    virtualbox-iso: At line:1 char:1
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('https://github.com/do ...
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso: + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso: + FullyQualifiedErrorId : WebException

## Host System
* OS:windows
* Packer Version:1.0.0
* Vagrant Version:1.9.1
* VirtualBox Version:5.1.14

## Command Output
 virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"
    virtualbox-iso:
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip
    virtualbox-iso:
    virtualbox-iso: 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
    virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: System ERROR:
    virtualbox-iso: The system cannot find the file specified.
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 2

**Comment by zhang-yun912** [comment]
I open the link （https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip）directly through the browser.Browser Tip: it has been banned.

**Comment by Chan9390** [comment]
Hey @zhang-yun912 , I am able to download it. Check if you are having some firewall issues.

**Comment by zhang-yun912** [comment]
I have turned off the firewall，I will try again

**Comment by zhang-yun912** [comment]
Yes, it is my own question
