### ISSUE TITLE
VM fails when it trys to install openjdk6

### ISSUE THREAD

**Issue by ice-doom** [rapid7/metasploitable3#219]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: win10
* Packer Version: 1.1.3
* Vagrant Version: 2.0.1
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

![image](https://user-images.githubusercontent.com/25363717/35179535-1f0c1c36-fdd7-11e7-9254-c66c0a8b3057.png)

**Comment by Chan9390** [comment]
Hey @ice-doom , I think there was a problem when downloading OpenJDK from GitHub. Check if you are having a good internet connection and make sure github is accessible (ie. no firewall is blocking it). Please retry and comment if you see the issue again.

**Comment by Chan9390** [comment]
Hey @ice-doom , any updates ?

**Comment by SpaceShipDev** [comment]
Got something similar, retrying now. https://gist.github.com/SpaceShipDev/6a742eddc2106b1b2dab55de42cfc284

**Comment by thadamski** [comment]
I've run into this similar issue on two consecutive attempts at running `build_win2008.sh`. I'm able to download the file [openjdk-1.6.0-unofficial-b27-windows-amd64.zip](https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip) directly from my browser, but provisioning with the shell script continually aborts with the message `Could not create SSL/TLS secure channel`: 
```
==> virtualbox-iso: Provisioning with shell script: scripts/installs/install_openjdk6.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')"  0<NUL
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The request was
    virtualbox-iso: aborted: Could not create SSL/TLS secure channel."
    virtualbox-iso: At line:1 char:1
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('https://github.com/do ...
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip
```
OS: macOS 10.13.3
VirtualBox: 5.2.6 r120293 (Qt5.6.3)
Vagrant: 2.0.2
Packer: 1.1.3
Internet connection: wi-fi

**Comment by joseph-ntl** [comment]
I ran into the same issue.

As a workaround, I downloaded the file and placed it into `resources/open-jdk`.

I then changed the first line of `scripts/installs/install_openjdk6.bat` to:
`copy /Y "C:\vagrant\resources\open-jdk\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip"`

**Comment by mrpapercut** [comment]
I've had the same problem too, and [joseph-ntl](https://github.com/rapid7/metasploitable3/issues/219#issuecomment-367979971)'s workaround worked for me.
Please note though: regardless of where your metasploitable3-dir resides, you need to use the path "C:\vagrant\resources\" etc, not the local path to the metasploitable3 directory

**Comment by joseph-ntl** [comment]
@mrpapercut Thank you for mentioning that, I didn't consider that people might get confused on that point as I was building it on Linux. I'll update the workaround to make it more clear.

**Comment by Hlynrkjaer** [comment]
Hello,

So, I'm also with such experience (with each of tries). But my **workaround-fix** was next one:

I made an addition to `scripts/installs/install_openjdk6.bat`, so entire .bat-file with next look:

`powershell -Command "[Net.ServicePointManager]::SecurityProtocol = 'tls12, tls11, tls'; (New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')" <NULcmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"`

Where 
> [Net.ServicePointManager]::SecurityProtocol = 'tls12, tls11, tls';

Is addition.

My thoughts are based on next feelings:

- even with Windows 10 (Internet Exporer 11 normal mode) such direct URL with 'delay' - if SmartScreen is enabled (and, did not check enough - but maybe if TLS1.0, TLS1.1 and SSL are disabled). Or some other configuration-options (I tried to restore all settings to default state);
- file is downloaded (in fact) from github.s3.amazonaws.com

So, I tried to research about steps to allow all (other than TLS1.2) TLS connections with powershell. Then as double-check that such connection marked as trusted (possible to establish noted SSL/TLS connection).
Most likely, there it is not a perfect-enough workaround-fix - but such addition will allow to use this URL-example with powershell (directly and from .bat).
Also, I'm not sure what is trouble indeed (github-page configuration, their amazon storage configuration or system configuration and its settings about TLS usage; or even powershell abilities or default configuration with certain version).

Thanks!

**Comment by spinkham** [comment]
The comments for the past few days seem to be due to this change: https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/
@Hlynrkjaer, you should make a pull request with your fix.

**Comment by Hlynrkjaer** [comment]
Hello,

@spinkham, thanks for your comment! Indeed sounds that such changes are reason.

What about potential pull request: I have to recheck the ability to use more 'suggested/recommended' structure or even proper documentation (for example, under social.technet.microsoft pages was an example like `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`).
And recheck how it works with other systems (my own fix-workaround was checked only in one Windows 10 build; and maybe only with certain Powershell version). 

Thus, if someone wants (or is able to do) - I feel OK if he makes a pull request with noted potentially proposed changes on subject (if my own activity will be with delay)

Thanks!

**Comment by kieran1998** [comment]
hi how do you change the files in open jdk , i tried but got confused with what to add. my metasploitable folder is in desktop so could anyone give me an example to use please thanks

**Comment by joseph-ntl** [comment]
@kieran1998

I'll give you clear step by step instructions.

In the metasploitable folder on your desktop, there should be a folder called resources?

Create a folder called "open-jdk“ inside resources.

Go to this link here: https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip

The file should download and once it's done, put it in the open-jdk folder you made. 

Now, in your metasploitable folder on your desktop, you should see a folder called scripts? 

And a folder inside that called installs? 

Inside that you should find install_openjdk6.bat. 

Open that file in a text editor like notepad, (Notepad++ is better). 

Change the first line of that file to the command below:

`copy /Y "C:\vagrant\resources\open-jdk\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip"`

Once you re-run the build scripts for metasploitable, they should now work. 


Now, based on your username containing 1998 and your grammar and language, I deduce that you are young and just getting started in security work as a hobby?

If so, I implore you to discover *why* my fix works (and every other fix you google for in everything you ever do), learn about vagrant, packer and virtual machines in depth and on a technical level.

Sorry for comedering the last half of my instructions to give you advice, but hopefully it's useful.

**Comment by Chan9390** [comment]
This issue is resolved now. Please pull the latest code. If you face the problem again please reopen this issue.
