### ISSUE TITLE
Build 'virtualbox-iso' error message / VBoxManager: error: 

### ISSUE THREAD

**Issue by vsardarian7** [rapid7/metasploitable3#222]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Debian 9
* Packer Version: 0.10.2+dfsg-6
* Vagrant Version: 1.9.1+dfsg-1
* VirtualBox Version: 5.2.6 r120293 (Qt5.7.1)
[build error message.txt](https://github.com/rapid7/metasploitable3/files/1694195/build.error.message.txt)

## Command Output
Copy the relevant command output here.  In the attached text document the error message is shown at the button of the page. I don't know if these is normal and I should just go ahead and use the created VM? 
 
Build 'virtualbox-iso' errored: Error removing floppy controller: VBoxManage error: VBoxManage: error: The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1048 of file VBoxManageStorageController.cpp

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error removing floppy controller: VBoxManage error: VBoxManage: error: The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1048 of file VBoxManageStorageController.cpp

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
david@debian:~/Downloads/metasploitable3-master$

**Comment by Chan9390** [comment]
Hey @vsardarian7 , any updates on this issue ?

**Comment by Dipraj** [comment]
Build 'virtualbox-iso' errored: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in %PATH%

**Comment by jmartin-r7** [comment]
> The machine 'metasploitable3-win2k8' is already locked for a session (or being unlocked)

This is an indicator of a VM already existing and running with the name required for build.  Closing this as env cleanup needed.
