### ISSUE TITLE
Vmware Workstation 14.1.1 and Ethernet card not detected

### ISSUE THREAD

**Issue by omerfsen** [rapid7/metasploitable3#223]
## Issue Description

Importing generated ovf/vmdk file gives a warning message (incompatible virtual image) and after that E1000 interface (ethernet) is not deteced for Vmware Workstation 14.X

## Host System
* OS: Centos7.4
* Packer Version:  1.1.3
* Vagrant Version: Vagrant 2.0.2
* VirtualBox Version: VirtualBox-5.2-5.2.6_120293_el7-1.x86_64

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by modpr0be** [comment]
I had the same issue but it's now solved. I changed the e1000 ethernet adapter to vmxnet3 as suggested by VMware ([https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=Software&productid=11137&vcl=true&supRel=13,24,31,34,71,72,74,76,77,78,79,80,81,85,86,90,148,155,158,162,163,164,165,168,171,172,179,182,187,196,199,201,202,217,218,243,258,259,260,270,271,273,295,301,326,327&testConfig=16](https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=Software&productid=11137&vcl=true&supRel=13,24,31,34,71,72,74,76,77,78,79,80,81,85,86,90,148,155,158,162,163,164,165,168,171,172,179,182,187,196,199,201,202,217,218,243,258,259,260,270,271,273,295,301,326,327&testConfig=16)).

You can change it by modify the .vmx, look for e1000 and change it to vmxnet3.

**Comment by jmartin-r7** [comment]
The report suggests the build we performed with `VirtualBox-5.2-5.2.6_120293_el7-1.x86_64` and is being imported into VMWare.  VMware platform support is supplied thru a capability to build the VM directly on VMware products using `packer`.  This is not considered a bug in Metasploitable3.
