### ISSUE TITLE
[SC] OpenService FAILED 1060:

### ISSUE THREAD

**Issue by hemanthkumar98** [rapid7/metasploitable3#227]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:Windows 10 Pro
* Packer Version:1.1.1
* Vagrant Version:2.0.2
* VirtualBox Version: 5.2.6r  Vmware Version:14.0

## Command Output
 vmware-iso: C:\Users\vagrant>net start "domain1"
    vmware-iso: The domain1 GlassFish Server service is starting.
    vmware-iso: The domain1 GlassFish Server service was started successfully.
    vmware-iso:
    vmware-iso:
    vmware-iso: C:\Users\vagrant>exit 0
==> vmware-iso: Provisioning with shell script: scripts/installs/setup_jenkins.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>mkdir "C:\Program Files\jenkins"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>copy C:\vagrant\resources\jenkins\jenkins.war "
C:\Program Files\jenkins"
    vmware-iso:         1 file(s) copied.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>copy C:\vagrant\resources\jenkins\jenkins.exe "
C:\Program Files\jenkins"
    vmware-iso:         1 file(s) copied.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>"C:\Program Files\jenkins\jenkins.exe" -Service
 Install
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config jenkins start= auto
    vmware-iso: [SC] ChangeServiceConfig SUCCESS
==> vmware-iso: Provisioning with shell script: scripts/chocolatey_installs/vcredist2008.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>chocolatey feature enable -n=allowGlobalConfirmation
    vmware-iso: Chocolatey v0.10.8
    vmware-iso: Enabled allowGlobalConfirmation
    vmware-iso:
    vmware-iso: C:\Users\vagrant>choco install vcredist2008
    vmware-iso: Chocolatey v0.10.8
    vmware-iso: Installing the following packages:
    vmware-iso: vcredist2008
    vmware-iso: By installing you accept licenses for the packages.
    vmware-iso: Progress: Downloading vcredist2008 9.0.30729.6161... 100%
    vmware-iso:
    vmware-iso: vcredist2008 v9.0.30729.6161 [Approved]
    vmware-iso: vcredist2008 package files install completed. Performing other installation steps.
    vmware-iso: Downloading vcredist2008 64 bit
    vmware-iso:   from 'https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x64.exe'
    vmware-iso: Progress: 100% - Completed download of C:\Windows\Temp\chocolatey\vcredist2008\9.0.30729.6161\vcredist_x64.exe (4.97 MB).
    vmware-iso: Download of vcredist_x64.exe (4.97 MB) completed.
    vmware-iso: Hashes match.
    vmware-iso: Installing vcredist2008...
    vmware-iso: vcredist2008 has been installed.
    vmware-iso: Downloading vcredist2008
    vmware-iso:   from 'https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe'
    vmware-iso: Progress: 100% - Completed download of C:\Windows\Temp\chocolatey\vcredist2008\9.0.30729.6161\vcredist_x86.exe (4.27 MB).
    vmware-iso: Download of vcredist_x86.exe (4.27 MB) completed.
    vmware-iso: Hashes match.
    vmware-iso: Installing vcredist2008...
    vmware-iso: vcredist2008 has been installed.
    vmware-iso:   vcredist2008 may be able to be automatically uninstalled.
    vmware-iso:  The install of vcredist2008 was successful.
    vmware-iso:   Software installed as 'exe', install location is likely default.
    vmware-iso:
    vmware-iso: Chocolatey installed 1/1 packages.
    vmware-iso:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    vmware-iso:
    vmware-iso: C:\Users\vagrant>chocolatey feature disable -n=allowGlobalConfirmation
    vmware-iso: Chocolatey v0.10.8
    vmware-iso: Disabled allowGlobalConfirmation
    vmware-iso:
    vmware-iso: C:\Users\vagrant>exit
==> vmware-iso: Provisioning with shell script: scripts/installs/install_wamp.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://sourceforge.net/projects/wampserver/files/WampServer 2/WampServer 2.2/wampserver2.2d-x64.exe', 'C:\Windows\Temp\wampserver2.2.d-x64.exe')"  0<NUL
    vmware-iso: Exception calling "DownloadFile" with "2" argument(s): "The request was
    vmware-iso: aborted: Could not create SSL/TLS secure channel."
    vmware-iso: At line:1 char:1
    vmware-iso: + (New-Object System.Net.WebClient).DownloadFile('https://sourceforge.n ...
    vmware-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    vmware-iso:     + FullyQualifiedErrorId : WebException
    vmware-iso:
    vmware-iso: 'C:\Windows\Temp\wampserver2.2.d-x64.exe' is not recognized as an internal or external command,
    vmware-iso: operable program or batch file.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>C:\Windows\Temp\wampserver2.2.d-x64.exe /verysilent
    vmware-iso:
    vmware-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\wamp\httpd.conf" "C:\wamp\bin\apache\Apache2.2.21\conf\httpd.conf"
    vmware-iso: The system cannot find the path specified.
    vmware-iso: The system cannot find the path specified.
    vmware-iso:         0 file(s) copied.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\wamp\phpmyadmin.conf" "C:\wamp\alias\phpmyadmin.conf"
    vmware-iso:         0 file(s) copied.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config wampapache start= auto
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config wampmysqld start= auto
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
    vmware-iso:
    vmware-iso: C:\Users\vagrant>icacls "C:\wamp" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
    vmware-iso: C:\Documents and Settings\All Users\Application Data\ApplicationData\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\*: The system cannot find thepath specified.
    vmware-iso: Successfully processed 0 files; Failed processing 1 files
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config wampapache obj= "NT Authority\LOCAL SERVICE"
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 36
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Build was cancelled.
Cleanly cancelled builds after being interrupted.

The same error occurs on both the vmware and virtualBox i tried multiple times and fed up with these 
i disabled all the firewalls and antivirus installed in the system and every data was present i.e data cloned form the repository was not deleted there was no loss of any data..!!!

**Comment by schrodyn** [comment]
Just ran into the same issue. As a work around I changed the powershell command in the file "scripts/installs/install_wamp.bat" to this:

`powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://sourceforge.net/projects/wampserver/files/WampServer 2/WampServer 2.2/wampserver2.2d-x64.exe', 'C:\Windows\Temp\wampserver2.2.d-x64.exe')" <NUL `

**Comment by hemanthkumar98** [comment]
virtualbox-iso: C:\Users\vagrant>exit
==> virtualbox-iso: Provisioning with shell script: scripts/installs/install_wamp.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://sourceforge.net/projects/wampserver/files/WampServer 2/WampServer 2.2/wampserver2.2d-x64.exe', 'C:\Windows\Temp\wampserver2.2.d-x64.exe')"  0<NUL
==> virtualbox-iso: Provisioning with shell script: scripts/installs/start_wamp.bat
    virtualbox-iso: The service name is invalid.
    virtualbox-iso:
    virtualbox-iso: More help is available by typing NET HELPMSG 2185.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start wampapache
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start wampmysqld
    virtualbox-iso: The service name is invalid.
    virtualbox-iso:
    virtualbox-iso: More help is available by typing NET HELPMSG 2185.
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 2

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\Hemanth Kumar\Desktop\metasploitable3-master\build_win2008.ps1:107 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by Chan9390** [comment]
Hey folks, wampserver is now included under the `resources/wamp` folder. No external download is required during the build. Download the latest version / do a git pull and then start the build.

If you face some issues with the temporary patch, please feel free to reopen the issue.

**Comment by hemanthkumar98** [comment]
virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')"  0<NUL

    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The request was
    virtualbox-iso: aborted: Could not create SSL/TLS secure channel."
    virtualbox-iso: At line:1 char:1
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('https://github.com/do ...
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: 7-Zip 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso:
    virtualbox-iso: System ERROR:
    virtualbox-iso: The system cannot find the file specified.
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 2

==> Builds finished but no artifacts were created.

**Comment by heidariahmed** [comment]
can anyone please help me? i downloaded the latest git, so i  got wamp folder but still get this error..

==> virtualbox-iso: System ERROR:
==> virtualbox-iso: The system cannot find the file specified.
    virtualbox-iso: 7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
==> virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\admin-keyfile"
==> virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:         0 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\domain.xml"
    virtualbox-iso:         0 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"
==> virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:
==> virtualbox-iso: The service name is invalid.
==> virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start domain1
==> virtualbox-iso: More help is available by typing NET HELPMSG 2185.
==> virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 10"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net stop domain1
==> virtualbox-iso: The service name is invalid.
==> virtualbox-iso:
==> virtualbox-iso: More help is available by typing NET HELPMSG 2185.
==> virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
    virtualbox-iso: processed file: C:\glassfish
    virtualbox-iso: Successfully processed 1 files; Failed processing 0 files
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
