### ISSUE TITLE
WAMP Server download fails

### ISSUE THREAD

**Issue by ricobandy** [rapid7/metasploitable3#229]
## Issue Description
WAMP download failed on VM and this deleted the installed machine. Below is the logs

## Host System
* OS: Windows 10
* Packer Version: 1.2.0
* Vagrant Version: 2.0.1
* VMware version:

## Command Output
==> vmware-iso: Provisioning with shell script: scripts/installs/install_wamp.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://sourceforge.net/projects/wampserver/files/WampServer 2/WampServer 2.2/wampserver2.2d-x64.exe', 'C:\Windows\Temp\wampserver2.2.d-x64.exe')"  0<NUL
    vmware-iso: Exception calling "DownloadFile" with "2" argument(s): "The underlying connecti
    vmware-iso: on was closed: An unexpected error occurred on a send."
    vmware-iso: At line:1 char:47
    vmware-iso: + (New-Object System.Net.WebClient).DownloadFile <<<< ('https://sourceforge.net
    vmware-iso: /projects/wampserver/files/WampServer 2/WampServer 2.2/wampserver2.2d-x64.exe',
    vmware-iso:  'C:\Windows\Temp\wampserver2.2.d-x64.exe')
    vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    vmware-iso:     + FullyQualifiedErrorId : DotNetMethodException
    vmware-iso:
    vmware-iso: 'C:\Windows\Temp\wampserver2.2.d-x64.exe' is not recognized as an internal or external command,
    vmware-iso: operable program or batch file.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>C:\Windows\Temp\wampserver2.2.d-x64.exe /verysilent
    vmware-iso:
    vmware-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\wamp\httpd.conf" "C:\wamp\bin\apache\Apache2.2.21\conf\httpd.conf"
    vmware-iso:         0 file(s) copied.
    vmware-iso:
    vmware-iso: The system cannot find the path specified.
    vmware-iso: The system cannot find the path specified.
    vmware-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\wamp\phpmyadmin.conf" "C:\wamp\alias\phpmyadmin.conf"
    vmware-iso:         0 file(s) copied.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config wampapache start= auto
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config wampmysqld start= auto
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
    vmware-iso:
    vmware-iso: C:\Users\vagrant>icacls "C:\wamp" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
    vmware-iso: Successfully processed 0 files; Failed processing 1 files
    vmware-iso:
    vmware-iso: C:\Documents and Settings\All Users\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\*: The system cannot find the path specified.
    vmware-iso: C:\Users\vagrant>sc config wampapache obj= "NT Authority\LOCAL SERVICE"
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 36

==> Builds finished but no artifacts were created.

**Comment by Chan9390** [comment]
Hey @ricobandy, 
wampserver is now included under the `resources/wamp` folder. No external download is required during the build.
Download the latest version / do a `git pull` and then start the build. Please reopen the issue if you face any other errors.
