### ISSUE TITLE
Packer version check not working

### ISSUE THREAD

**Issue by dirtyfurnace** [rapid7/metasploitable3#233]
## Issue Description
After editing the build_win2008.sh script to point to the location that I have VBox installed, and adding my location of Packer to my environment path, I am getting an error about a null-valued expression whn checking the "actual-version" of packer.

## Host System
* OS: Windows 10
* Packer Version: 1.2.1
* Vagrant Version: 2.0.2
* VirtualBox Version: 5.2.6

## Command Output
```
You cannot call a method on a null-valued expression.
At G:\VirtualBox\VDI\Metasploitable3-Windows\build_win2008.ps1:18 char:5
+     $actualVersion = $actualVersion.split(".")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

```

**Comment by DanMcInerney** [comment]
Getting this too.

**Comment by DanMcInerney** [comment]
I just made that function return true and it worked.

```
function CompareVersions ($actualVersion, $expectedVersion, $exactMatch = $False) {
    return $True
}
```

**Comment by Chan9390** [comment]
Hey @dirtyfurnace , any updates on this issue ?

**Comment by jalvarez-outburst** [comment]
I had the same problem, and it was because Vagrant was not install. Once I install it everything works, if  you change the path were Vagrant is installed you need to modify it on the script.

**Comment by CarminKern** [comment]
I had the same error message. For me it was because I have not installed the program "Vagrant" in the default path.
If you change in the build the paths for "Vagrant" it works ...

**Comment by jmartin-r7** [comment]
This script has been renamed and had major overhauls since this was reported, closing for now.

Assumptions about installation locations are currently [made](https://github.com/rapid7/metasploitable3/blob/6b0bac0626bbd5895b23459d66e57882c44aed2e/build.ps1#L78), PRs are welcome to add better detection.
