### ISSUE TITLE
build_win2008.sh exception

### ISSUE THREAD

**Issue by msmaldi** [rapid7/metasploitable3#235]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Deepin Linux
* Packer Version: 0.10.2
* Vagrant Version: 1.9.1
* VirtualBox Version:

## Command Output
`==> virtualbox-iso: Provisioning with shell script: scripts/installs/install_openjdk6.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')"  0<NUL
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The request was
    virtualbox-iso: aborted: Could not create SSL/TLS secure channel."
    virtualbox-iso: At line:1 char:1
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('https://github.com/do ...
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso: + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso: + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"
    virtualbox-iso:
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso:
    virtualbox-iso: 7-Zip 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28
    virtualbox-iso: C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso: System ERROR:
    virtualbox-iso: The system cannot find the file specified.
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2
`
running build_win2008.sh i get this exception 2 times

**Comment by Hlynrkjaer** [comment]
Hello,

Sounds that your experience is about such trouble (part of discussion):
https://github.com/rapid7/metasploitable3/issues/219

Where, for example, my **own potential workaround-fix** is next one:
https://github.com/rapid7/metasploitable3/pull/234

- - - -
Even though I think that such workarounds are valuable only until such changes (maybe):
https://github.com/rapid7/metasploitable3/pull/176

Thanks!

**Comment by Chan9390** [comment]
This issue is resolved now. Please pull the latest code. If you face the problem again please reopen this issue.
