### ISSUE TITLE
metasploitable3  : cant find open-jdk files 

### ISSUE THREAD

**Issue by kieran1998** [rapid7/metasploitable3#237]
## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

 C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')"  0<NUL
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The request was
    virtualbox-iso: aborted: Could not create SSL/TLS secure channel."
    virtualbox-iso: At line:1 char:1
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('https://github.com/do ...
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip
    virtualbox-iso: 7-Zip 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: System ERROR:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso: The system cannot find the file specified.
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* VMware application not found:
* VMware application not found:
* VMware application not found:
* VMware application not found:

--> virtualbox-iso: Script exited with non-zero exit status: 2

==> Builds finished but no artifacts were created.

**Comment by Hlynrkjaer** [comment]
Hello,

Sounds that your experience is about such kind of trouble (discussed as part of): https://github.com/rapid7/metasploitable3/issues/219
And next ones related discussions: https://github.com/rapid7/metasploitable3/issues/235, https://github.com/rapid7/metasploitable3/issues/236

My own potential **workaround-fix** is next one: **https://github.com/rapid7/metasploitable3/pull/234**

- - - -
But I think that such workarounds are valuable only until such changes (potentially): https://github.com/rapid7/metasploitable3/pull/176

Thanks!

**Comment by kieran1998** [comment]
hi it says about changing the lines of the open jdk script  which i tried but got confused where and what to put

**Comment by kieran1998** [comment]
any help with writing the file and changing it , my metasploitable folder is in desktop if you could tell me what to write and where would be greatly appreciated. thanks

**Comment by Hlynrkjaer** [comment]
Hello,

I am also only user who tried to install metasploitable3, but I will try to provide some help:
- In general, you have to locate **.bat file** with filename "**install_openjdk6.bat**" in your filesystem;
potential path is "your_drive\your_path_for_metasploitable3_folder_with_content\scripts\installs\install_openjdk6.bat".
-  then, for example, open .bat-file with text-editor (like Notepad). If some help-steps are needed with this step: good to re-ask.
- with such state should be visible original content of .bat-file (install_openjdk6) under editor:
Possible to **re-place entire content to next one:**
`powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')" <NUL
cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"`
**OR** to add only next string (after |-Command "| and before |(New-Object|) with original content:
`"[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;`
As example, visual view of changes: https://github.com/rapid7/metasploitable3/pull/234/files
- - - -
Another option(?) is to download 'patch-branch':
https://github.com/Hlynrkjaer/metasploitable3/tree/patch-1
and it will be saved with already implemented workaround-fix. All other content are not modified.
Possible to try install metasploitable3 from this metasploitable3 folder.

Likely that my help is not clear; and if so good to ask more (maybe someone else will create proper advice).
Also, good to provide feedback about.

Thanks!

**Comment by kieran1998** [comment]
hi thanks that got me past the step at last but when gong to  the next step with vagrant up i get an issue 
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'metasploitable3'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: metasploitable3-patch-1_default_1520864603840_47277
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "6d33748e-575a-4d07-921a-af8627cfff70", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'metasploitable3-patch-1_default_1520864603840_47277' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\kiera\VirtualBox VMs\metasploitable3-patch-1_default_1520864603840_47277\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

**Comment by kieran1998** [comment]
also i tried building with vmware but got this issue , any help greatly appreciated 


 C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\globalsign.cer
    vmware-iso: Root
    vmware-iso: Signature matches Public Key
    vmware-iso: Certificate "CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE" added to store.
    vmware-iso: CertUtil: -addstore command completed successfully.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\gte_cybertrust.cer
    vmware-iso: Root
    vmware-iso: Signature matches Public Key
    vmware-iso: Certificate "CN=GTE CyberTrust Global Root, OU="GTE CyberTrust Solutions, Inc.", O=GTE Corporation, C=US" added to store.
    vmware-iso: CertUtil: -addstore command completed successfully.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\microsoft_root_2011.cer
    vmware-iso: Root
    vmware-iso: Signature matches Public Key
    vmware-iso: Certificate "CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" added to store.
    vmware-iso: CertUtil: -addstore command completed successfully.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\thawte_primary_root.cer
    vmware-iso: Root
    vmware-iso: Signature matches Public Key
    vmware-iso: Certificate "CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US" added to store.
    vmware-iso: CertUtil: -addstore command completed successfully.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\utn-userfirst.cer
    vmware-iso: Root
    vmware-iso: Signature matches Public Key
    vmware-iso: Certificate "CN=UTN-USERFirst-Object, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, S=UT, C=US" added to store.
    vmware-iso: CertUtil: -addstore command completed successfully.
==> vmware-iso: Provisioning with shell script: ./scripts/installs/vm-guest-tools.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>if not exist "C:\Windows\Temp\7z920-x64.msi" (powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://www.7-zip.org/a/7z920-x64.msi', 'C:\Windows\Temp\7z920-x64.msi')"  0<NUL )
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script disconnected unexpectedly. If you expected your script to disconnect, i.e. from a restart, you can try adding `"expect_disconnect": true` to the shell provisioner parameters.

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script disconnected unexpectedly. If you expected your script to disconnect, i.e. from a restart, you can try adding `"expect_disconnect": true` to the shell provisioner parameters.

==> Builds finished but no artifacts were created.

**Comment by Hlynrkjaer** [comment]
Hello,

If your situation is still actual.
Concerned your first log. Sounds that it is trouble with Vagrant/VirtualBox and my own potential steps with such potential situation are some of next tries:
- restart your main system; check does it sort stuck or not;
- maybe it is possible to check that VirtualBox with good enough state; or reinstall it anyway; check does it sort stuck or not;

Also, it is good option to read content of "VBoxHardening.log'". And then double check about potential options with Vagrant CLI/packer (but only after noted potential common steps and it if it not helpful).

Thanks!

**Comment by kieran1998** [comment]
thanks now when vagrant up is used just get it saying everything is OK but there is no virtualmachine in virtualbox and when there is one it is inaccessible. 


: C:\Users\vagrant>rmdir /S /Q C:\vagrant
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Preparing to export machine...
    virtualbox-iso: Deleting forwarded port mapping for the communicator (SSH, WinRM, etc) (host port 2264)
==> virtualbox-iso: Exporting virtual machine...
    virtualbox-iso: Executing: export metasploitable3-win2k8 --output output-virtualbox-iso\metasploitable3-win2k8.ovf

==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Running post-processor: vagrant
==> virtualbox-iso (vagrant): Creating Vagrant box for 'virtualbox' provider
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso\metasploitable3-win2k8-disk001.vmdk

    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso\metasploitable3-win2k8.ovf
    virtualbox-iso (vagrant): Renaming the OVF to box.ovf...
    virtualbox-iso (vagrant): Using custom Vagrantfile: vagrantfile-windows_2008_r2.template
    virtualbox-iso (vagrant): Compressing: Vagrantfile
    virtualbox-iso (vagrant): Compressing: box.ovf
    virtualbox-iso (vagrant): Compressing: metadata.json
    virtualbox-iso (vagrant): Compressing: metasploitable3-win2k8-disk001.vmdk

Build 'virtualbox-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: windows_2008_r2_virtualbox.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3' (v0) for provider:
    box: Unpacking necessary files from: file://C:/Users/kiera/Desktop/metasploitable3-patch-1/metasploitable3-patch-1/windows_2008_r2_virtualbox.box
    box: Progress: 100% (Rate: 39.1M/s, Estimated time remaining: --:--:--)
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.

Name: metasploitable3
Provider: virtualbox
Version: 0
Error adding box to Vagrant. See the above output for any error messages.
At C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1\build_win2008.ps1:127 char:9
+         throw "Error adding box to Vagrant. See the above output for  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.

PS C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
Your VM has become "inaccessible." Unfortunately, this is a critical error
with VirtualBox that Vagrant can not cleanly recover from. Please open VirtualBox
and clear out your inaccessible virtual machines or find a way to fix
them.
PS C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'metasploitable3'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: metasploitable3-patch-1_default_1520886092942_97278
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/kiera/Desktop/metasploitable3-patch-1/metasploitable3-patch-1
==> default: Running provisioner: shell...
    default: Running: scripts/configs/enable_firewall.bat as c:\tmp\vagrant-shell.bat
    default: Ok.
==> default: Running provisioner: shell...
    default: Running: scripts/configs/configure_firewall.bat as c:\tmp\vagrant-shell.bat
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
PS C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
PS C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1>
PS C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1>
PS C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1>
PS C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1> vagrant provision
==> default: Running provisioner: shell...
    default: Running: scripts/configs/enable_firewall.bat as c:\tmp\vagrant-shell.bat
    default: Ok.
==> default: Running provisioner: shell...
    default: Running: scripts/configs/configure_firewall.bat as c:\tmp\vagrant-shell.bat
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
PS C:\Users\kiera\Desktop\metasploitable3-patch-1\metasploitable3-patch-1>

**Comment by kieran1998** [comment]
Callee RC: | E_FAIL (0x80004005)
-- | --
 

get this and saying cant open session for the virtual machine when the virtual machine is there.

**Comment by kieran1998** [comment]
this is the log file as well , not sure what it means 


:28.910340 VMMDev: Guest Additions capability report: (0x0 -> 0x0) seamless: no, hostWindowMapping: no, graphics: no
00:05:41.951395 GIM: HyperV: Reset initiated through MSR
00:05:41.965888 Changing the VM state from 'RUNNING' to 'RESETTING'
00:05:42.026290 GIM: HyperV: Resetting MMIO2 regions and MSRs
00:05:42.026453 PIT: mode=3 count=0x10000 (65536) - 18.20 Hz (ch=0)
00:05:42.039895 PIIX3 ATA: Ctl#0: finished processing RESET
00:05:42.039928 AC97: Reset
00:05:42.039945 PIIX3 ATA: Ctl#1: finished processing RESET
00:05:42.039956 PDMR3Reset: after    13 ms, 1 loops: 1 async tasks - piix3ide/0
00:05:42.057356 TM: Switching TSC mode from 'RealTscOffset' to 'VirtTscEmulated'
00:05:42.077888 Changing the VM state from 'RESETTING' to 'RUNNING'
00:05:42.080278 VMMDev: Guest Log: BIOS: VirtualBox 5.2.8
00:05:42.080372 PCI: setting up resources and interrupts
00:05:42.080625 PIT: mode=2 count=0x10000 (65536) - 18.20 Hz (ch=0)
00:05:42.097482 Display::handleDisplayResize: uScreenId=0 pvVRAM=0000000000000000 w=720 h=400 bpp=0 cbLine=0x0 flags=0x0
00:05:42.097843 VMMDev: Guest Log: CPUID EDX: 0x178bfbff
00:05:42.097889 PIIX3 ATA: Ctl#0: RESET, DevSel=0 AIOIf=0 CmdIf0=0xc8 (-1 usec ago) CmdIf1=0x00 (-1 usec ago)
00:05:42.097923 PIIX3 ATA: Ctl#0: finished processing RESET
00:05:42.098429 VMMDev: Guest Log: BIOS: ata0-0: PCHS=16383/16/63 LCHS=1024/255/63
00:05:42.100371 PIIX3 ATA: Ctl#0: RESET, DevSel=1 AIOIf=0 CmdIf0=0xec (-1 usec ago) CmdIf1=0x00 (-1 usec ago)
00:05:42.100418 PIIX3 ATA: Ctl#0: finished processing RESET
00:05:42.109320 PIT: mode=2 count=0x48d3 (18643) - 64.00 Hz (ch=0)
00:05:42.128798 Display::handleDisplayResize: uScreenId=0 pvVRAM=000000000b0d0000 w=640 h=480 bpp=32 cbLine=0xA00 flags=0x0
00:05:44.587679 Display::handleDisplayResize: uScreenId=0 pvVRAM=0000000000000000 w=720 h=400 bpp=0 cbLine=0x0 flags=0x0
00:05:44.619725 PIT: mode=2 count=0x10000 (65536) - 18.20 Hz (ch=0)
00:05:44.619992 VMMDev: Guest Log: BIOS: Boot : bseqnr=1, bootseq=0032
00:05:44.645795 VMMDev: Guest Log: BIOS: Booting from Hard Disk...
00:05:44.824510 Display::handleDisplayResize: uScreenId=0 pvVRAM=000000000b0d0000 w=1024 h=768 bpp=24 cbLine=0xC00 flags=0x0
00:05:48.093711 GIM: HyperV: Guest OS reported ID 0x1040601011db1
00:05:48.093744 GIM: HyperV: Open-source=false Vendor=0x1 OS=0x4 (Windows NT or derivative) Major=6 Minor=1 ServicePack=1 Build=7601
00:05:48.093779 GIM: HyperV: Enabled hypercall page at 0x00000000041f0000
00:05:48.093809 GIM: HyperV: Enabled TSC page at 0x00000000041f1000 - u64TscScale=0x106bd6900000000 u64TscKHz=0x260f7a (2 494 330) Seq=1
00:05:48.093840 TM: Switching TSC mode from 'VirtTscEmulated' to 'RealTscOffset'
00:05:48.101795 Display::handleDisplayResize: uScreenId=0 pvVRAM=000000000b0d0000 w=640 h=480 bpp=0 cbLine=0x140 flags=0x0
00:05:49.905688 VMMDev: Guest Log: VBoxGuest: Windows version 6.1, build 7601
00:05:49.911697 VMMDev: Guest Additions information report: Version 5.2.8 r121009 '5.2.8'
00:05:49.911754 VMMDev: Guest Additions information report: Interface = 0x00010004 osType = 0x00037100 (Windows 7, 64-bit)
00:05:49.911838 VMMDev: Guest Additions capability report: (0x0 -> 0x0) seamless: no, hostWindowMapping: no, graphics: no
00:05:49.911943 VMMDev: Guest reported fixed hypervisor window at 00002c00000 LB 0xc00000 (rc=VINF_SUCCESS)
00:05:49.911964 VMMDev: Heartbeat checking timer has been stopped (rc=VINF_SUCCESS)
00:05:49.911981 VMMDev: Heartbeat flatline timer set to trigger after 4 000 000 000 ns
00:05:51.334300 VMMDev: Guest Log: VBoxMouse::DriverEntry: DriverEntry:
00:05:52.182329 VMMDev: Guest Log: VBoxMP::DriverEntry: VBox XPDM Driver for Windows version 5.2.8r121009, 64 bit; Built Feb 26 2018 15:06:46
00:05:53.383891 VMMDev: Guest Log: VBoxMP::VBoxDrvFindAdapter: using HGSMI
00:05:55.476521 NAT: Link up
00:05:55.907140 VMMDev: Guest Log: VBoxDisp[0]: VBVA enabled
00:05:55.907173 VBVA: InfoScreen: [0] @0,0 1024x768, line 0x1000, BPP 32, flags 0x1
00:05:55.907184 Display::handleDisplayResize: uScreenId=0 pvVRAM=000000000b0d0000 w=1024 h=768 bpp=32 cbLine=0x1000 flags=0x1
00:06:05.378933 NAT: DHCP offered IP address 10.0.2.15
00:06:34.056093 RTC: period=0x20 (32) 1024 Hz
00:06:34.070460 RTC: period=0x200 (512) 64 Hz
00:06:36.290238 RTC: period=0x20 (32) 1024 Hz
00:06:36.304381 RTC: period=0x200 (512) 64 Hz
00:07:19.024556 RTC: period=0x20 (32) 1024 Hz
00:07:19.038694 RTC: period=0x200 (512) 64 Hz
00:07:25.712764 RTC: period=0x20 (32) 1024 Hz
00:07:25.726728 RTC: period=0x200 (512) 64 Hz
00:07:48.525856 RTC: period=0x20 (32) 1024 Hz
00:07:48.539112 RTC: period=0x200 (512) 64 Hz
00:08:02.286381 NAT: DHCP offered IP address 10.0.2.15
00:09:25.774204 RTC: period=0x20 (32) 1024 Hz
00:09:25.789270 RTC: period=0x200 (512) 64 Hz
00:09:26.039989 RTC: period=0x20 (32) 1024 Hz
00:09:26.055155 RTC: period=0x200 (512) 64 Hz
00:09:33.399181 RTC: period=0x20 (32) 1024 Hz
00:09:33.414619 RTC: period=0x200 (512) 64 Hz
00:09:33.525031 RTC: period=0x20 (32) 1024 Hz
00:09:33.538815 RTC: period=0x200 (512) 64 Hz
00:09:34.320855 RTC: period=0x20 (32) 1024 Hz
00:09:34.336388 RTC: period=0x200 (512) 64 Hz
00:09:37.072158 RTC: period=0x20 (32) 1024 Hz
00:09:37.085840 RTC: period=0x200 (512) 64 Hz
00:09:37.102457 RTC: period=0x20 (32) 1024 Hz
00:09:37.117118 RTC: period=0x200 (512) 64 Hz
00:09:44.010301 VMMDev: Guest Additions capability report: (0x0 -> 0x0) seamless: no, hostWindowMapping: no, graphics: no
00:09:47.914720 RTC: period=0x20 (32) 1024 Hz
00:09:47.929405 RTC: period=0x200 (512) 64 Hz
00:11:10.618790 RTC: period=0x20 (32) 1024 Hz
00:11:10.632468 RTC: period=0x200 (512) 64 Hz
00:11:12.524651 RTC: period=0x20 (32) 1024 Hz
00:11:12.539060 RTC: period=0x200 (512) 64 Hz
00:11:12.852916 RTC: period=0x20 (32) 1024 Hz
00:11:12.867851 RTC: period=0x200 (512) 64 Hz
00:11:12.884028 RTC: period=0x20 (32) 1024 Hz

**Comment by Hlynrkjaer** [comment]
Hello,

Just as reminder - I am also only user who tried to set up metasploitable3 previously. So, it is kind of unofficial help. Likely that proper steps (to troubleshoot) are another one.
I will suggest to read entire comment and then to try perform some steps (maybe not all of my suggestions are valid for your certain situation).
- - - -
Does your recent experience is about state after restart system or after restart system/reinstall Virtualbox? Or it is not related with my previous suggestion?

In general, your first log with such strings:
`The box you're attempting to add already exists. Remove it before
 adding it again or add it with the --force flag.`
Some workarounds are needed; or completely fresh 'set up' for metasploitable3.
Thus, maybe it is an option to try next with your command line (command prompt):
`vagrant box list`
check what is output; if there is metaslpoitable3-box is listed - maybe good to remove/destroy it.
For example, like this (if 'box'-name is metasploitable3):
`vagrant box remove metasploitable3` 
or maybe some IDs are needed (command line should be with proper tips).

Maybe .box-file is placed under your file system. If so - good to try find it with your metasploitable3-folder. And then add it (as box):
`vagrant box add _your_filename_of_metasploitable3_for_virtualbox.box`
It will save time and avoid entire 'set up'...
In fact, your further log with strings about 'provisioned'-state. And I decided to try search something about such output during installing - sounds that your situation is partly(?) related with such discussion:
https://github.com/rapid7/metasploitable3/issues/193

Where possible to find official response and further advice (or even more - solution by user). But if not - possible back with reply and discuss there. I just do not able to check situation with my own systems for own check about potential suggestions.

Thanks!

**Comment by kieran1998** [comment]
thanks it now allows me to open the virtual machine but there is no vulnerable software on there?

**Comment by kieran1998** [comment]
says this aswell


The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'unknown' state. Please verify everything is configured
properly and try again.

**Comment by Hlynrkjaer** [comment]
Hello,

If your stuck is still actual:

does it proper view of your current situation(?):
- VirtualBox with visible 'metasploitable3_' VM system.
It is possible to launch it and to login.
but any vulnerable software are not installed?

- did you try to follow any recommendations of Vagrant/packer/vagrant-plugin? For example, I did not remember proper instructions - but it should possible to find them with metasploitable3 FAQ or Vagrant/packer pages.

Your noted 'output' sounds as POTENTIAL incompatibility with something. 
Or requirements with additional things like repair vagrant plugin or to use something like vagrant reload (or to do re-provision):
https://www.vagrantup.com/docs/cli/reload.html
- - - -
Also I feel that it is good option to create another topic with recent stuck - because more experienced users could find it and to help with proper advice (based on their experience with definitely such stuck).

As my own suggestion: possible to try entire doublecheck with clearing previous tries to configure metasploitable3 (include 'vagrant destroy _ _', reload plugin and re-run entire process). But I suggest it only because I do not able to check your meanings with my own system (currently).

Thanks!

**Comment by Chan9390** [comment]
The original issue "cant find open-jdk files" is resolved now. Please pull the latest code. If you face the problem again please reopen this issue.
