### ISSUE TITLE
Error on openjdk over https

### ISSUE THREAD

**Issue by PhilDunphy** [rapid7/metasploitable3#238]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Windows 7
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.14

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

Hi.
So I'm encountering the following issue when building Metasploitable 3. It seems that the connection over https is not being made for the jdk. The file is definitely there. 
https://gist.github.com/PhilDunphy/b4a52569606b2fa3eefd48b1a52934f8

I might be doing something stupid. I've been trying for a few builds and everytime I'm ending up with no artefacts and the vm is deleted.

Thanks

**Comment by Hlynrkjaer** [comment]
Hello,

Sounds that your experience is also about such kind of trouble (discussed as part of): #219
And next ones related discussions: #235, #236, https://github.com/rapid7/metasploitable3/issues/237

My own potential **workaround-fix** is next one: **#234**
- - - -
But I think that such workarounds are valuable only until such changes (potentially): #176

Thanks!

**Comment by PhilDunphy** [comment]
@Hlynrkjaer Thanks for your reply. Trying out workaround now.
Will let you know if it works.
Thanks

**Comment by PhilDunphy** [comment]
@Hlynrkjaer  Worked. Gont another issue now. Thanks
