### ISSUE TITLE
Metasploitable build failure with VMWare during script provisioning

### ISSUE THREAD

**Issue by PhilDunphy** [rapid7/metasploitable3#240]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System 
* OS: Win 7
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version: N/A
* VMware Workstation Version: 12

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

Hi,
When running the build with the following
packer build --only=vmware-iso windows_2008_r2.json

I get
https://gist.github.com/PhilDunphy/d83ec926751a4bb94dc0441fcab6be3e

Not sure if the issue is chocolatey or packer

**Comment by Chan9390** [comment]
Hey @PhilDunphy , can you ensure if `scripts/installs/setup_apache_struts.bat` is present in the metasploitable 3 folder ?

**Comment by PhilDunphy** [comment]
@Chan9390 Yes it is there.
![scripts](https://user-images.githubusercontent.com/2584883/37336712-205c6f18-26aa-11e8-844a-bc90a60c9a1e.PNG)

**Comment by Chan9390** [comment]
Is `resources\apache_struts\tomcat-users.xml` present ?

**Comment by PhilDunphy** [comment]
@Chan9390  Yes that is also there

**Comment by PhilDunphy** [comment]
Could this be a permissions issue? Although other scripts have run so I dont think it could be this.

**Comment by Chan9390** [comment]
I think `tomcat` was not successfully installed. 

Reason: `sc config Tomcat8 start= auto` returns a FAILED status. Also the script `scripts/installs/setup_apache_struts.bat` tries to delete `\conf\tomcat-users.xml` which is not present, it creates an error.

Can you retry the build ?
Please let me know if you are facing the same issue.

**Comment by PhilDunphy** [comment]
@Chan9390  Same issue.    I also caught this before the provisioning.

vmware-iso: The entered computer name is not valid or remote shutdown is not supported on the target computer. Check the name and then try again or contact
your system administrator.(53)

**Comment by PhilDunphy** [comment]
I got a successful build with VirtualBox but the exporting to VMware didnt work as when I turn on VM there is no NICs, hence the reason I'm trying a VMware specific build

**Comment by PhilDunphy** [comment]
@Chan9390 I changed from using cmd with Admin rights to using powershell on admin and the build ran all the provisioning but timed out while waiting for machine to shutdown. CMD worked fine on VBox. I will close this issue and open a new one.
