### ISSUE TITLE
vagrant : An error occurred while downloading the remote file. The error

### ISSUE THREAD

**Issue by gmeghab** [rapid7/metasploitable3#248]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Box 'metasploitable3-ub1404' could not be found. Attempting to find and install...
    ub1404: Box Provider: virtualbox
    ub1404: Box Version: >= 0
==> ub1404: Box file was not detected as metadata. Adding it directly...
==> ub1404: Adding box 'metasploitable3-ub1404' (v0) for provider: virtualbox
    ub1404: Downloading: metasploitable3-ub1404

[K    ub1404: 
vagrant : An error occurred while downloading the remote file. The error
At line:1 char:1
+ vagrant up
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...file. The error:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
message, if any, is reproduced below. Please fix this error and try
again.
Couldn't open file /C:/users/gmeghabghab/downloads/metasploitable3-master/metasploitable3-master/metasploitable3-ub1404

**Comment by Chan9390** [comment]
You havent added the linux box. Instead try using the command `vagrant up win2k8`.

**Comment by jmartin-r7** [comment]
Please try latest `master` or quick-start method provided in README.md.
