### ISSUE TITLE
build fails with bad floppy error

### ISSUE THREAD

**Issue by 0-d-0** [rapid7/metasploitable3#249]
## Issue Description
build fails

## Host System
* OS: Windows 10 64-bit
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.14

## Command Output
Compatible version of VirtualBox found.
Compatible version of packer found.
Compatible version of Vagrant found.
Compatible version of vagrant-reload plugin found.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

5 error(s) occurred:

* Bad Floppy disk file 'E:\metasploitable3-master\packer\templates/../../scripts/configs/microsoft-updates.bat': GetFileAttributesEx E:\metasploitable3-master\packer\templates/../../scripts/configs/microsoft-updates.bat: The system cannot find the path specified.
* Bad Floppy disk file 'E:\metasploitable3-master\packer\templates/../../scripts/configs/win-updates.ps1': GetFileAttributesEx E:\metasploitable3-master\packer\templates/../../scripts/configs/win-updates.ps1: The system cannot find the path specified.
* Bad Floppy disk file 'E:\metasploitable3-master\packer\templates/../../scripts/installs/openssh.ps1': GetFileAttributesEx E:\metasploitable3-master\packer\templates/../../scripts/installs/openssh.ps1: The system cannot find the path specified.
* Bad Floppy disk file 'E:\metasploitable3-master\packer\templates/../../scripts/installs/install_dotnet45.ps1': GetFileAttributesEx E:\metasploitable3-master\packer\templates/../../scripts/installs/install_dotnet45.ps1: The system cannot find the path specified.
* Bad Floppy disk file 'E:\metasploitable3-master\packer\templates/../../scripts/installs/install_wmf.ps1': GetFileAttributesEx E:\metasploitable3-master\packer\templates/../../scripts/installs/install_wmf.ps1: The system cannot find the path specified.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At E:\metasploitable3-master\build_win2008.ps1:108 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by DanMcInerney** [comment]
I edited windows_2008_r2.json like rawk77 said and it worked. Prior to that I was getting this same floppy disk error. To be clearer:

Open .../metasploitable3-master/packer/templates/windows_2008_r2.json
Edit lines 216, 217, and 218 to point to the full path to each directory. For example:

```
"autounattend": "C:/Users/your-username/whatever-path-here/metasploitable3-master/packer/answer_files/2008_r2/Autounattend.xml",
"scripts_dir": "C:/Users/your-username/whatever-path-here/metasploitable3-master/scripts",
"resources_dir": "C:/Users/your-username/whatever-path-here/metasploitable3-master/resources",
```

**Comment by Chan9390** [comment]
Hey @0-d-0 , any updates ?

**Comment by mertakmese** [comment]
Exact Solution it worked:

If  vagrant plugin install vagrant-reload is not working follow the steps;

1-metasploitable3-master>windows_2008_r2.json
 (Sometimes metasploitable3-master>packer>templates>windows_2008_r2.json )

2-Open windows_2008_r2.json with Windows PowerShell ISE
(if you dont know how to open PowerShell ISE - write to search Windows PowerShell ISE)

3-After you open windows_2008_r2.json with Windows PowerShell ISE , 
Note :   Be careful  slash ( \ and /)
  Edit lines      
  .....                                          
  .....                                             
 216   "autounattend": "C:/Users/your-username/whatever-path-here/metasploitable3- master/packer/answer_files/2008_r2/Autounattend
 
  217  "scripts_dir": "C:/Users/your-username/whatever-path-here/metasploitable3-master/scripts",

  218 "resources_dir": "C:/Users/your-username/whatever-path-here/metasploitable3-master/resources",
  .....
  
 then cmd>vagrant plugin install vagrant-reload it worked 👍
