### ISSUE TITLE
error with pre-built-box 404

### ISSUE THREAD

**Issue by 0-d-0** [rapid7/metasploitable3#250]
## Issue Description
pre-built box does not work

## Host System
* OS: Windows 10 64-bit
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.14

## Command Output
Compatible version of VirtualBox found.
Compatible version of Vagrant found.
All requirements found. Proceeding...
Attempting to add the box to Vagrant. This may take a while...
The box 'jbarnett-r7/metasploitable3-win2k8' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/jbarnett-r7/metasploitable3-win2k8"]
Error: The requested URL returned error: 404 Not Found
Error adding box to Vagrant. See the above output for any error messages.
At E:\metasploitable3-pre_built_box\build_win2008.ps1:76 char:9
+         throw "Error adding box to Vagrant. See the above output for  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.

**Comment by Chan9390** [comment]
Hey @0-d-0 please try adding the box using the command:
`vagrant box add jbarnett-r7/metasploitable3-win2k8`

**Comment by Chan9390** [comment]
Hey @0-d-0 , any updates on this issue ?

I tried the same command (`vagrant box add jbarnett-r7/metasploitable3-win2k8`) and I got the following output:
```
==> box: Loading metadata for box 'jbarnett-r7/metasploitable3-win2k8'
    box: URL: https://vagrantcloud.com/jbarnett-r7/metasploitable3-win2k8
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) virtualbox
2) vmware

Enter your choice: 1
==> box: Adding box 'jbarnett-r7/metasploitable3-win2k8' (v0.1.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/jbarnett-r7/boxes/metasploitable3-win2k8/versions/0.1.0/providers/virtualbox.box
```
If you still face issue, please comment the output of the error.

**Comment by jmartin-r7** [comment]
Please see updated quick-start in readme.  New boxes are available.
