### ISSUE TITLE
Build Errors Out on chef-zero Install

### ISSUE THREAD

**Issue by jeffdougherty** [rapid7/metasploitable3#251]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Mac OS High Sierra, v 10.13.3
* Packer Version: 1.2.1
* Vagrant Version: 2.0.3
* VirtualBox Version: 5.2.6

## Steps
Attempting to install, first with build.sh script and later manually with packer as described in README.md.  Error message is similar for both approaches.

Packer builds and sets up the VM properly, I go through Ubuntu setup steps, then shut the machine down and add a host-only adapter so it has the IP address Vagrant expects.  Reboot the machine, Vagrant recognizes and logs into SSH, begins provisioning with chef-solo.  Installation step errors, then everything gets deleted.

What's maddening is that I have successfully set up this exact VM, using the same software, on the same host computer, and it works fine!  I can't for the life of me figure out why making another suddenly doesn't work.

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

building ubuntu 1404
Compatible version of VirtualBox found.
Compatible version of packer/packer was found.
Correct version of vagrant was found.
Compatible version of vagrant-reload plugin was found.
All requirements found. Proceeding...
ls: packer/builds: No such file or directory
Building the Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://old-releases.ubuntu.com/releases/14.04.1/ubuntu-14.04.1-server-amd64.iso
[...]
 virtualbox-iso: Download progress: 99%
==> virtualbox-iso: Starting HTTP server on port 9001
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3998)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm metasploitable3-ub1404 --memory 4096
    virtualbox-iso: Executing: modifyvm metasploitable3-ub1404 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 20s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Connected to SSH!
==> virtualbox-iso: Uploading VirtualBox version info (5.2.6)
==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
==> virtualbox-iso: Provisioning with chef-solo
    virtualbox-iso: Installing Chef...
    virtualbox-iso: sudo: no tty present and no askpass program specified
    virtualbox-iso:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    virtualbox-iso:                                  Dload  Upload   Total   Spent    Left  Speed
    virtualbox-iso:  21 23425   21  5100    0     0   8521      0  0:00:02 --:--:--  0:00:02  8514
    virtualbox-iso: curl: (23) Failed writing body (1755 != 2759)
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error installing Chef: Install script exited with non-zero exit status 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error installing Chef: Install script exited with non-zero exit status 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by qingsword** [comment]
OS：ubuntu16.04

I had the same mistake.
====================
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error executing Chef: Non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error executing Chef: Non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
Hey @jeffdougherty , did you try to build it again ? I think that was a network issue as I could see `curl: (23) Failed writing body (1755 != 2759)` (it means that chef cannot be downloaded successfully). Try building it again if you haven't.

Hey @qingsword , **I don't think its the same issue**. I could see from the log that your error was: **`Error executing Chef: Non-zero exit status: 1`**, but the issue here was **`Error installing Chef`**. Kindly try to rebuild. If you face the same issue, try opening a new issue.

**Comment by jeffdougherty** [comment]
@Chan9390 I tried building several times, got the same error each time. I think the problem had to do with the IP address the VM was being assigned by my VB's NAT network not matching the one it expected, but I'm not sure how to resolve that. Is the IP address specified in the Vagrantfile, or elsewhere? 

Regardless, I'm pretty sure this was a Metasploitable error since I was able to retrieve Internet resources immediately before and after using other programs.

Thanks for the suggestion, though.

**Comment by Chan9390** [comment]
Metasploitable3 has NAT adapter enabled but doesnt specify any IP address. I have 2 questions: 
1. Do you have any firewall enabled (which has restrictions on the download size) ?
2. Does the error always show `curl: (23) Failed writing body (1755 != 2759)` ? (Is it the same number or changes?)

**Comment by jeffdougherty** [comment]
1. Nope. Home connection, so no limits on download size.
2. To the best of my recollection, yes. Can't be sure since it's been a few weeks since I tried this, but I remember the error message being identical down to characters each time.

The reason I mentioned the Vagrantfile was that while looking through the source, I noticed the Vagrantfile has the following line:  `ub1404.vm.network "private_network", ip: '172.28.128.3'`.  Does that mean it's expecting only a private network adapter when building in Ubuntu 14.04? (Just for clarity's sake, all my failed build attempts have been at building the Ubuntu version.)

**Comment by jeffdougherty** [comment]
Edit to add: Tried it again today on a different host, different network,
all new files, got the same error down to the same numbers.

**Comment by jeffdougherty** [comment]
And another edit: Took another look. There's another error right before the
curl message:

sudo: no tty present and no askpass program specified

**Comment by JamesKBowler** [comment]
I am having the same issue now.
