### ISSUE TITLE
Metasploitable 3 build failure

### ISSUE THREAD

**Issue by wonkastocks** [rapid7/metasploitable3#252]
## Issue Description
build doesnt finsish

## Host System
* OS: WIndows 10
* Packer Version:

1.21

* Vagrant Version:

1.91

* VirtualBox Version:

5.28r2

## Command Output

virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start wampapache
    virtualbox-iso: The wampapache service is starting.
    virtualbox-iso: The wampapache service was started successfully.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start wampmysqld
    virtualbox-iso: The wampmysqld service is starting.
    virtualbox-iso: The wampmysqld service was started successfully.
    virtualbox-iso:
==> virtualbox-iso: Provisioning with shell script: C:\Users\jsmith\build2\metasploitable3\packer\templates/../../scripts/installs/install_wordpress.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>mkdir "C:\Program Files\wordpress"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\wordpress\update_ip.ps1 "C:\Program Files\wordpress\update_ip.ps1"
    virtualbox-iso:         1 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x C:\vagrant\resources\wordpress\wordpress.zip -oC:\wamp\www\"
    virtualbox-iso:
    virtualbox-iso: 7-Zip 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28
    virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso: 1 file, 12685504 bytes (13 MiB)
    virtualbox-iso:
    virtualbox-iso: Extracting archive: C:\vagrant\resources\wordpress\wordpress.zip
    virtualbox-iso: --
    virtualbox-iso: Path = C:\vagrant\resources\wordpress\wordpress.zip
    virtualbox-iso: Type = zip
    virtualbox-iso: Physical Size = 12685504
    virtualbox-iso:
    virtualbox-iso: Everything is Ok
    virtualbox-iso:
    virtualbox-iso: Folders: 239
    virtualbox-iso: Files: 2202
    virtualbox-iso: Size:       32174960
    virtualbox-iso: Compressed: 12685504
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\wamp\bin\mysql\mysql5.5.20\bin\mysql.exe" -u root --password=""  -e "create database wordpress;""
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\wamp\bin\mysql\mysql5.5.20\bin\mysql.exe" -u root --password=""  wordpress < "C:\Vagrant\resources\wordpress\wordpress.sql""
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>schtasks /create /tn "update_wp_db" /tr "\"cmd.exe\" /c powershell -File \"C:\Program Files\wordpress\update_ip.ps1\"" /sc onstart /NP /ru "SYSTEM"
    virtualbox-iso: SUCCESS: The scheduled task "update_wp_db" has successfully been created.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -File "C:\Program Files\wordpress\update_ip.ps1"
    virtualbox-iso: Updating Wordpress IP to 10.0.2.15
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>attrib -r +s C:\wamp\www\wordpress
==> virtualbox-iso: Provisioning with shell script: C:\Users\jsmith\build2\metasploitable3\packer\templates/../../scripts/installs/install_openjdk6.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')"  cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6" 0<NUL
    virtualbox-iso: At line:1 char:324
    virtualbox-iso: + ... ows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip') cmd /c C:\P ...
    virtualbox-iso: +                                                               ~~~
    virtualbox-iso: Unexpected token 'cmd' in expression or statement.
    virtualbox-iso:     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
    virtualbox-iso:    ception
    virtualbox-iso:     + FullyQualifiedErrorId : UnexpectedToken
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\jsmith\build2\metasploitable3\build_win2008.ps1:108 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by Chan9390** [comment]
Hey @wonkastocks, please pull the latest metasploitable3 code.

**Comment by wonkastocks** [comment]
it seems to go futher now i get  this error message,
==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: C:\Users\jsmith\build3\metasploitable3\packer\templates/../builds/windows_2008_r2_virtualbox_0.1.0.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3-win2k8' (v0) for provider:
    box: Downloading: packer/builds/windows_2008_r2_virtualbox.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/jsmith/build3/metasploitable3/packer/builds/windows_2008_r2_virtualbox.box
Error adding box to Vagrant. See the above output for any error messages.
At C:\Users\wbarr\build3\metasploitable3\build_win2008.ps1:127 char:9
+         throw "Error adding box to Vagrant. See the above output for  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.

**Comment by Hlynrkjaer** [comment]
Hello,

If your situation is still actual.
Sounds that something unexpected there (maybe based on custom things). 
I am not sure about proper output (I am also only user who tried to install metasploitable3) - but for example: https://github.com/rapid7/metasploitable3/issues/193#issuecomment-333613837 - discussion with some examples of manual 'find and add' box to Vagrant (before further 'up'). Maybe it can be useful with your situation. If not - good if someone will advice about your current stuck and potential proper fix.

Thanks!
