### ISSUE TITLE
Couldn't open file <path>/metasploitable3-master/packer/builds/windows_2008_r2_virtualbox.box

### ISSUE THREAD

**Issue by DanMcInerney** [rapid7/metasploitable3#254]
## Issue Description
Running .\build_win2008.ps1 eventually leads to:

"Couldn't open file /C:/<path>/metasploitable3-master/packer/builds/windows_2008_r2_virtualbox.box"

## Host System
* OS: Windows 10
* Packer Version: 1.2.2
* Vagrant Version: 2.0.3
* VirtualBox Version: 5.1

## Details
In build_win2008.ps1 the name of the packer build is hardcoded as windows_2008_r2_virtualbox.box but when its built, it's named windows_2008_r2_virtualbox_0.1.0.box. So you just gotta edit line 102 of the build script to point to the right place.

**Comment by DanMcInerney** [comment]
Details on fixing this are above.

**Comment by jmartin-r7** [comment]
Fixed in #277
