### ISSUE TITLE
install_openjdk6.bat  Download via Powershell WebClient fails

### ISSUE THREAD

**Issue by tmarchst** [rapid7/metasploitable3#255]
## Issue Description
It seems the Powershell WebClient expects a SSL certificate for github.com since the URL passed points to a ressource on github.com.
The URL redirects to https://github.s3.amazonaws.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip
If the amazonws.com link is passed instead the build runs throug just fine.

## Host System
* OS: Arch 4.15.13
* Packer Version: 1.2.2
* Vagrant Version: 2.0.3
* VirtualBox Version: none (libvirt Build with PR 232 )

## Command Output
==> qemu: Provisioning with shell script: scripts/installs/install_openjdk6.bat
    qemu:
    qemu: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')"  0<NUL
    qemu: Exception calling "DownloadFile" with "2" argument(s): "The request was
    qemu: aborted: Could not create SSL/TLS secure channel."
    qemu: At line:1 char:1
    qemu: + (New-Object System.Net.WebClient).DownloadFile('https://github.com/do ...
    qemu: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    qemu:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    qemu:     + FullyQualifiedErrorId : WebException
    qemu:
    qemu:
    qemu: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"
    qemu:
    qemu: ERROR: The system cannot find the file specified.
    qemu: C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip
    qemu:
    qemu:
    qemu: 7-Zip 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28
    qemu:
    qemu:
    qemu:
    qemu: Scanning the drive for archives:
    qemu: System ERROR:
    qemu: The system cannot find the file specified.
==> qemu: Deleting output directory...
Build 'qemu' errored: Script exited with non-zero exit status: 2

**Comment by Chan9390** [comment]
Hey @tmarchst , the command in `install_openjdk6.bat` has been updated.

https://github.com/rapid7/metasploitable3/blob/1dc344bc3036f7ae42dec41fbc56e3b8f105d541/scripts/installs/install_openjdk6.bat#L1)

Please pull the latest code. Also comment if you face any further issues.

**Comment by tmarchst** [comment]
Hey @Chan9390 ,
you're right, I fetched the latest commit and both boxes build just fine.
Guess i pulled in some old code with that PR.
