### ISSUE TITLE
Metasploitable 3 VM Build Fail

### ISSUE THREAD

**Issue by duncan426** [rapid7/metasploitable3#257]
## Issue Description
Build fails after Chocolatey installs.  I am new to scripting so I spent 5 hours yesterday trying different versions of packer and vagrant, but no luck.  Appreciate any help.

## Host System
* OS: Windows 10 Pro
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.34

## Command Output
virtualbox-iso: Getting latest version of the Chocolatey package for download.
    virtualbox-iso: Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.9.
    virtualbox-iso: Downloading 7-Zip commandline tool prior to extraction.
    virtualbox-iso: Extracting C:\Windows\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Windows\Temp\chocolatey\chocInstall...
    virtualbox-iso: Installing chocolatey on this machine
    virtualbox-iso: Creating ChocolateyInstall as an environment variable (targeting 'Machine')
    virtualbox-iso: Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
    virtualbox-iso: WARNING: It's very likely you will need to close and reopen your shell
    virtualbox-iso: before you can use choco.
    virtualbox-iso: Restricting write permissions to Administrators
    virtualbox-iso: We are setting up the Chocolatey package repository.
    virtualbox-iso: The packages themselves go to 'C:\ProgramData\chocolatey\lib'
    virtualbox-iso: (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
    virtualbox-iso: A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
    virtualbox-iso: and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.
    virtualbox-iso:
    virtualbox-iso: Creating Chocolatey folders if they do not already exist.
    virtualbox-iso:
    virtualbox-iso: WARNING: You can safely ignore errors related to missing log files when
    virtualbox-iso: upgrading from a version of Chocolatey less than 0.9.9.
    virtualbox-iso: 'Batch file could not be found' is also safe to ignore.
    virtualbox-iso: 'The system cannot find the file specified' - also safe.
    virtualbox-iso: chocolatey.nupkg file not installed in lib.
    virtualbox-iso: Attempting to locate it from bootstrapper.
    virtualbox-iso: PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
    virtualbox-iso: Chocolatey (choco.exe) is now ready.
    virtualbox-iso: You can call choco from anywhere, command line or powershell by typing choco.
    virtualbox-iso: Run choco /? for a list of functions.
    virtualbox-iso: You may need to shut down and restart powershell and/or consoles
    virtualbox-iso: first prior to using choco.
    virtualbox-iso: Ensuring chocolatey commands are on the path
    virtualbox-iso: Ensuring chocolatey.nupkg is in the lib folder
    virtualbox-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="information" RefId="1"><TN RefId="1"><T>System.Management.Automation.InformationRecord</T><T>System.Object</T></TN><ToString>WARNING: It's very likely you will need to close and reopen your shell _x000A_  before you can use choco.</ToString><Props><Obj N="MessageData" RefId="2"><TN RefId="2"><T>System.Management.Automation.HostInformationMessage</T><T>System.Object</T></TN><ToString>WARNING: It's very likely you will need to close and reopen your shell _x000A_  before you can use choco.</ToString><Props><S N="Message">WARNING: It's very likely you will need to close and reopen your shell _x000A_  before you can use choco.</S><B N="NoNewLine">false</B><S N="ForegroundColor">Yellow</S><S N="BackgroundColor">Black</S></Props></Obj><S N="Source">C:\Windows\Temp\chocolatey\chocInstall\tools\chocolateysetup.psm1</S><DT N="TimeGenerated">2018-04-01T09:55:45.9205-07:00</DT><Obj N="Tags" RefId="3"><TN RefId="3"><T>System.Collections.Generic.List`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]</T><T>System.Object</T></TN><LST><S>PSHOST</S></LST></Obj><S N="User">VAGRANT-2008R2\sshd_server</S><S N="Computer">vagrant-2008R2</S><U32 N="ProcessId">1608</U32><U32 N="NativeThreadId">1452</U32><U32 N="ManagedThreadId">5</U32></Props></Obj><Obj S="information" RefId="4"><TNRef RefId="1" /><ToString>WARNING: You can safely ignore errors related to missing log files when _x000A_  upgrading from a version of Chocolatey less than 0.9.9. _x000A_  'Batch file could not be found' is also safe to ignore. _x000A_  'The system cannot find the file specified' - also safe.</ToString><Props><Obj N="MessageData" RefId="5"><TNRef RefId="2" /><ToString>WARNING: You can safely ignore errors related to missing log files when _x000A_  upgrading from a version of Chocolatey less than 0.9.9. _x000A_  'Batch file could not be found' is also safe to ignore. _x000A_  'The system cannot find the file specified' - also safe.</ToString><Props><S N="Message">WARNING: You can safely ignore errors related to missing log files when _x000A_  upgrading from a version of Chocolatey less than 0.9.9. _x000A_  'Batch file could not be found' is also safe to ignore. _x000A_  'The system cannot find the file specified' - also safe.</S><B N="NoNewLine">false</B><S N="ForegroundColor">Yellow</S><S N="BackgroundColor">Black</S></Props></Obj><S N="Source">C:\Windows\Temp\chocolatey\chocInstall\tools\chocolateysetup.psm1</S><DT N="TimeGenerated">2018-04-01T09:55:46.529875-07:00</DT><Obj N="Tags" RefId="6"><TNRef RefId="3" /><LST><S>PSHOST</S></LST></Obj><S N="User">VAGRANT-2008R2\sshd_server</S><S N="Computer">vagrant-2008R2</S><U32 N="ProcessId">1608</U32><U32 N="NativeThreadId">1452</U32><U32 N="ManagedThreadId">5</U32></Props></Obj><Obj S="information" RefId="7"><TNRef RefId="1" /><ToString>PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...</ToString><Props><Obj N="MessageData" RefId="8"><TNRef RefId="2" /><ToString>PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...</ToString><Props><S N="Message">PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...</S><B N="NoNewLine">false</B><S N="ForegroundColor">Gray</S><S N="BackgroundColor">Black</S></Props></Obj><S N="Source">C:\Windows\Temp\chocolatey\chocInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyPath.ps1</S><DT N="TimeGenerated">2018-04-01T09:55:46.686125-07:00</DT><Obj N="Tags" RefId="9"><TNRef RefId="3" /><LST><S>PSHOST</S></LST></Obj><S N="User">VAGRANT-2008R2\sshd_server</S><S N="Computer">vagrant-2008R2</S><U32 N="ProcessId">1608</U32><U32 N="NativeThreadId">1452</U32><U32 N="ManagedThreadId">5</U32></Props></Obj><S S="warning">Not setting tab completion: Profile file does not exist at 'C:\Users\vagrant\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.</S></Objs>
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\dunca\Documents\GitHub\metasploitable3\build_win2008.ps1:108 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by sebdooris** [comment]
looks like my issue #256 is the same but on a different platform.

**Comment by sebdooris** [comment]
It looks like I just resolved my issue by updating my build environment. 

Try installing the following 

Packer Version: 1.2.2
https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_windows_amd64.zip

Vagrant Version: 2.0.3
https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.msi

VirtualBox Version: 5.2.8
https://download.virtualbox.org/virtualbox/5.2.8/VirtualBox-5.2.8-121009-Win.exe

**Comment by duncan426** [comment]
Are  you using the Master repository and running the build_win2008ps1 script?

**Comment by sebdooris** [comment]
Yes was using master cloned today and built on Ubuntu 16.04 and Kali 2018.1. As the errors were identical it's worth a try to upgrade on windows.

**Comment by duncan426** [comment]
ok.  Well I got the box file created.  I move to the directory where the box file is located (/packer/builds).  I then ran "vagrant box add .\windows_2008_r2_virtualbox_0.1.0.box -name=metasploitable3" .  
I get Successfully added box 'metasploitable3' (v0) for 'virtualbox'!
run vagrant up and get:
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Box 'metasploitable3-ub1404' could not be found. Attempting to find and install...
    ub1404: Box Provider: virtualbox
    ub1404: Box Version: >= 0
==> ub1404: Box file was not detected as metadata. Adding it directly...
==> ub1404: Adding box 'metasploitable3-ub1404' (v0) for provider: virtualbox
    ub1404: Downloading: metasploitable3-ub1404
    ub1404:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
couldn't open file /C:/Users/***/Documents/metasploitable3-master/packer/builds/metasploitable3-ub1404

**Comment by duncan426** [comment]
I successfully added it to vagrant, but I run Vagrant up and this happens.  What did I do wrong?  Do I need to go to the .vagrant.d folder and run vagrant up from there?  Thanks

Box successfully added to Vagrant.
SUCCESS: Run 'vagrant up' to provision and start metasploitable3.
NOTE: The VM will need Internet access to provision properly.
PS C:\Users\dunca\Documents\metasploitable3-master> vagrant up
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Box 'metasploitable3-ub1404' could not be found. Attempting to find and install...
    ub1404: Box Provider: virtualbox
    ub1404: Box Version: >= 0
==> ub1404: Box file was not detected as metadata. Adding it directly...
==> ub1404: Adding box 'metasploitable3-ub1404' (v0) for provider: virtualbox
    ub1404: Downloading: metasploitable3-ub1404
    ub1404:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/dunca/Documents/metasploitable3-master/metasploitable3-ub1404

**Comment by paravindkumar** [comment]
Try adding manually to vagrant box
vagrant box add metasploitable3-ub1404 .\packer\builds\windows_2008_r2_virtualbox_0.1.0.box

**Comment by JordonLovik** [comment]
Manually adding the other VM respectively also works. I had do do both manually to get mine up. @paravindkumar thanks for the idea.

vagrant box add metasploitable3-win2k8 .\packer\builds\windows_2008_r2_virtualbox_0.1.0.box

**Comment by S0U1SB4N3** [comment]
i ran vmware-iso and it fails halfway through , it brings up the vm and i can see it building the server and watch the vm reboot several times but then it dies and deletes the vm.
