### ISSUE TITLE
Bridge not woking

### ISSUE THREAD

**Issue by bandrea96** [rapid7/metasploitable3#259]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Arch Linux
* Packer Version: 1.1.3
* Vagrant Version: 2.0.3
* VirtualBox Version: 5.2.8

The NAT works correctly but (obv) I can't connect from my host machine and the bridged connection get the ip 192.168.54.1 when my host is 10.10.10.82

**Comment by busterb** [comment]
This is unrelated to Metasploit.
