### ISSUE TITLE
Error executing action `create` on resource 'mysql_service[default]'

### ISSUE THREAD

**Issue by matthiashammerschmidt** [rapid7/metasploitable3#262]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: macOS 10.13.4
* Packer Version: 1.2.2
* Vagrant Version: 2.0.3
* VirtualBox Version: 5.2.8 r121009 (Qt5.6.3)

## Command 
./build.sh ubuntu1404

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

    virtualbox-iso: Recipe: metasploitable::mysql
    virtualbox-iso:   * execute[apt-get update] action run
    virtualbox-iso:     - execute apt-get update
    virtualbox-iso:   * mysql_service[default] action create
    virtualbox-iso:
    virtualbox-iso:     ================================================================================
    virtualbox-iso:     Error executing action `create` on resource 'mysql_service[default]'
    virtualbox-iso:     ================================================================================
    virtualbox-iso:
    virtualbox-iso:     NameError
    virtualbox-iso:     ---------
    virtualbox-iso:     undefined local variable or method `install_method' for #<#<Class:0x0000000005d79218>:0x0000000005b40168>
    virtualbox-iso:
    virtualbox-iso:     Cookbook Trace:
    virtualbox-iso:     ---------------
    virtualbox-iso:     /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/mysql/libraries/mysql_service.rb:34:in `installation'
    virtualbox-iso:     /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/mysql/libraries/mysql_service.rb:68:in `block in <class:MysqlService>'
    virtualbox-iso:
    virtualbox-iso:     Resource Declaration:
    virtualbox-iso:     ---------------------
    virtualbox-iso:     # In /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/mysql.rb
    virtualbox-iso:
    virtualbox-iso:      11: mysql_service 'default' do
    virtualbox-iso:      12:   initial_root_password 'sploitme'
    virtualbox-iso:      13:   bind_address '0.0.0.0'
    virtualbox-iso:      14:   port '3306'
    virtualbox-iso:      15:   action [:create, :start]
    virtualbox-iso:      16: end
    virtualbox-iso:
    virtualbox-iso:     Compiled Resource:
    virtualbox-iso:     ------------------
    virtualbox-iso:     # Declared in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/mysql.rb:11:in `from_file'
    virtualbox-iso:
    virtualbox-iso:     mysql_service("default") do
    virtualbox-iso:       action [:create, :start]
    virtualbox-iso:       default_guard_interpreter :default
    virtualbox-iso:       declared_type :mysql_service
    virtualbox-iso:       cookbook_name "metasploitable"
    virtualbox-iso:       recipe_name "mysql"
    virtualbox-iso:       initial_root_password "sploitme"
    virtualbox-iso:       bind_address "0.0.0.0"
    virtualbox-iso:       port "3306"
    virtualbox-iso:     end
    virtualbox-iso:
    virtualbox-iso:     System Info:
    virtualbox-iso:     ------------
    virtualbox-iso:     chef_version=14.0.190
    virtualbox-iso:     platform=ubuntu
    virtualbox-iso:     platform_version=14.04
    virtualbox-iso:     ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    virtualbox-iso:     program_name=/usr/bin/chef-solo
    virtualbox-iso:     executable=/opt/chef/bin/chef-solo
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Running handlers:
    virtualbox-iso: [2018-04-04T19:27:09+00:00] ERROR: Running exception handlers
    virtualbox-iso: [2018-04-04T19:27:09+00:00] ERROR: Running exception handlers
    virtualbox-iso: Running handlers complete
    virtualbox-iso: [2018-04-04T19:27:09+00:00] ERROR: Exception handlers complete
    virtualbox-iso: [2018-04-04T19:27:09+00:00] ERROR: Exception handlers complete
    virtualbox-iso: Chef Client failed. 18 resources updated in 38 seconds
    virtualbox-iso: [2018-04-04T19:27:09+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-04-04T19:27:09+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-04-04T19:27:09+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-04-04T19:27:09+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-04-04T19:27:09+00:00] FATAL: NameError: mysql_service[default] (metasploitable::mysql line 11) had an error: NameError: undefined local variable or method `install_method' for #<#<Class:0x0000000005d79218>:0x0000000005b40168>
    virtualbox-iso: [2018-04-04T19:27:09+00:00] FATAL: NameError: mysql_service[default] (metasploitable::mysql line 11) had an error: NameError: undefined local variable or method `install_method' for #<#<Class:0x0000000005d79218>:0x0000000005b40168>

**Comment by darist21** [comment]
I have exactly the same problem. I tried to build with older versions of Packer and Vagrant, but the result was the same. When I tried with older versions of VirtualBox (5.1.14 & 5.1.18) I got a VBoxManage error (exit with code 1) when starting the virtual machine (#203 ).
  
## Host System
* OS: Windows 10 - 64bit
* Packer Version: 1.2.2 & 1.0.0 (tested with both versions)
* Vagrant Version: 2.0.3 & (1.9.1) (tested with both versions)
* VirtualBox Version: 5.2.8
  
## Command
packer build --only=virtualbox-iso packer\templates\ubuntu_1404.json

**Comment by Chan9390** [comment]
Hey @matthiashammerschmidt , the issue is now resolved. Please retry building metasploitable3 after pulling the latest code.

**Comment by deargle** [comment]
Upgrading the mysql chef cookbook fixes this, too. I'm working on a PR that will include this.
