### ISSUE TITLE
Build 'virtualbox-iso' errored: Error executing Chef: Non-zero exit status: 1

### ISSUE THREAD

**Issue by qingsword** [rapid7/metasploitable3#263]
An error occurred while building on ubuntu.

## Host System
* OS:ubuntu 16.04
* Packer Version:1.22
* Vagrant Version: 2.0.3
* VirtualBox Version:5.2.8

## Command Output

    virtualbox-iso:     program_name=/usr/bin/chef-solo
    virtualbox-iso:     executable=/opt/chef/bin/chef-solo
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Running handlers:
    virtualbox-iso: [2018-04-06T04:47:02+00:00] ERROR: Running exception handlers
    virtualbox-iso: [2018-04-06T04:47:02+00:00] ERROR: Running exception handlers
    virtualbox-iso: Running handlers complete
    virtualbox-iso: [2018-04-06T04:47:02+00:00] ERROR: Exception handlers complete
    virtualbox-iso: [2018-04-06T04:47:02+00:00] ERROR: Exception handlers complete
    virtualbox-iso: Chef Client failed. 18 resources updated in 01 minutes 00 seconds
    virtualbox-iso: [2018-04-06T04:47:03+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-04-06T04:47:03+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-04-06T04:47:03+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-04-06T04:47:03+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-04-06T04:47:03+00:00] FATAL: NameError: mysql_service[default] (metasploitable::mysql line 11) had an error: NameError: undefined local variable or method `install_method' for #<#<Class:0x0000000004f43c98>:0x00000000042af928>
    virtualbox-iso: [2018-04-06T04:47:03+00:00] FATAL: NameError: mysql_service[default] (metasploitable::mysql line 11) had an error: NameError: undefined local variable or method `install_method' for #<#<Class:0x0000000004f43c98>:0x00000000042af928>
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
**Build 'virtualbox-iso' errored: Error executing Chef: Non-zero exit status: 1**

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error executing Chef: Non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
I was able to reproduce the issue.
(Vagrant - 2.0.2, Packer - 1.1.3, VBox - 5.2.8)
Working on it.

**Comment by qingsword** [comment]
Hey @Chan9390 ，Add a line in packer/templates/ubuntu_1404.json，and the problem is solved perfectly.
Thank you very much！

**Comment by qingsword** [comment]
Hey，@Chan9390 , Add a line in packer/templates/ubuntu_1404.json and the following error is encountered while building.
---------------------
  virtualbox-iso:     System Info:
    virtualbox-iso:     ------------
    virtualbox-iso:     chef_version=13.8.5
    virtualbox-iso:     platform=ubuntu
    virtualbox-iso:     platform_version=14.04
    virtualbox-iso:     ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    virtualbox-iso:     program_name=chef-solo worker: ppid=1102;start=07:44:04;
    virtualbox-iso:     executable=/opt/chef/bin/chef-solo
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Running handlers:
    virtualbox-iso: [2018-04-07T08:28:23+00:00] ERROR: Running exception handlers
    virtualbox-iso: [2018-04-07T08:28:23+00:00] ERROR: Running exception handlers
    virtualbox-iso: Running handlers complete
    virtualbox-iso: [2018-04-07T08:28:23+00:00] ERROR: Exception handlers complete
    virtualbox-iso: [2018-04-07T08:28:23+00:00] ERROR: Exception handlers complete
    virtualbox-iso: Chef Client failed. 81 resources updated in 44 minutes 19 seconds
    virtualbox-iso: [2018-04-07T08:28:23+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-04-07T08:28:23+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-04-07T08:28:23+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-04-07T08:28:23+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-04-07T08:28:23+00:00] ERROR: Net::ReadTimeout
    virtualbox-iso: [2018-04-07T08:28:23+00:00] ERROR: Net::ReadTimeout
    virtualbox-iso: [2018-04-07T08:28:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    virtualbox-iso: [2018-04-07T08:28:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error executing Chef: Non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error executing Chef: Non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
Hey @qingsword, the error log is incomplete. Can you give the output just before `System Info:` ?

**Comment by qingsword** [comment]
Hey @Chan9390 
    virtualbox-iso:     +<?php
    virtualbox-iso:     +/*
    virtualbox-iso:     + * Generated configuration file
    virtualbox-iso:     + * Generated by: phpMyAdmin 3.5.8 setup script
    virtualbox-iso:     + * Date: Mon, 20 Mar 2017 17:50:57 +0000
    virtualbox-iso:     + */
    virtualbox-iso:     +
    virtualbox-iso:     +/* Servers configuration */
    virtualbox-iso:     +$i = 0;
    virtualbox-iso:     +
    virtualbox-iso:     +/* Server: metasploitable [1] */
    virtualbox-iso:     +$i++;
    virtualbox-iso:     +$cfg['Servers'][$i]['verbose'] = 'metasploitable';
    virtualbox-iso:     +$cfg['Servers'][$i]['host'] = '127.0.0.1';
    virtualbox-iso:     +$cfg['Servers'][$i]['port'] = '';
    virtualbox-iso:     +$cfg['Servers'][$i]['socket'] = '';
    virtualbox-iso:     +$cfg['Servers'][$i]['connect_type'] = 'tcp';
    virtualbox-iso:     +$cfg['Servers'][$i]['extension'] = 'mysqli';
    virtualbox-iso:     +$cfg['Servers'][$i]['auth_type'] = 'cookie';
    virtualbox-iso:     +$cfg['Servers'][$i]['user'] = 'root';
    virtualbox-iso:     +$cfg['Servers'][$i]['password'] = 'sploitme';
    virtualbox-iso:     +
    virtualbox-iso:     +/* End of servers configuration */
    virtualbox-iso:     +
    virtualbox-iso:     +$cfg['blowfish_secret'] = '58d0142a394148.57231469';
    virtualbox-iso:     +$cfg['DefaultLang'] = 'en';
    virtualbox-iso:     +$cfg['ServerDefault'] = 1;
    virtualbox-iso:     +$cfg['UploadDir'] = '';
    virtualbox-iso:     +$cfg['SaveDir'] = '';
    virtualbox-iso:     +?>
    virtualbox-iso:   * service[apache2] action restart
    virtualbox-iso:     - restart service service[apache2]
    virtualbox-iso: Recipe: metasploitable::proftpd
    virtualbox-iso:   * remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz] action create[2018-04-07T12:51:27+00:00] WARN: remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz] cannot be downloaded from ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz: Net::ReadTimeout
    virtualbox-iso: [2018-04-07T12:51:27+00:00] WARN: remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz] cannot be downloaded from ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz: Net::ReadTimeout
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:     ================================================================================
    virtualbox-iso:     Error executing action `create` on resource 'remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz]'
    virtualbox-iso:     ================================================================================
    virtualbox-iso:
    virtualbox-iso:     Net::ReadTimeout
    virtualbox-iso:     ----------------
    virtualbox-iso:     Net::ReadTimeout
    virtualbox-iso:
    virtualbox-iso:     Resource Declaration:
    virtualbox-iso:     ---------------------
    virtualbox-iso:     # In /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/proftpd.rb
    virtualbox-iso:
    virtualbox-iso:      13: remote_file "#{Chef::Config[:file_cache_path]}/#{proftpd_tar}" do
    virtualbox-iso:      14:   source "#{node[:proftpd][:download_url]}/#{proftpd_tar}"
    virtualbox-iso:      15:   mode '0644'
    virtualbox-iso:      16: end
    virtualbox-iso:      17:
    virtualbox-iso:
    virtualbox-iso:     Compiled Resource:
    virtualbox-iso:     ------------------
    virtualbox-iso:     # Declared in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/proftpd.rb:13:in `from_file'
    virtualbox-iso:
    virtualbox-iso:     remote_file("/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz") do
    virtualbox-iso:       provider Chef::Provider::RemoteFile
    virtualbox-iso:       action [:create]
    virtualbox-iso:       default_guard_interpreter :default
    virtualbox-iso:       source ["ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz"]
    virtualbox-iso:       use_etag true
    virtualbox-iso:       use_last_modified true
    virtualbox-iso:       declared_type :remote_file
    virtualbox-iso:       cookbook_name "metasploitable"
    virtualbox-iso:       recipe_name "proftpd"
    virtualbox-iso:       mode "0644"
    virtualbox-iso:       remote_domain nil
    virtualbox-iso:       remote_user nil
    virtualbox-iso:       path "/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz"
    virtualbox-iso:       owner nil
    virtualbox-iso:       group nil
    virtualbox-iso:       checksum nil
    virtualbox-iso:       verifications []
    virtualbox-iso:     end
    virtualbox-iso:
    virtualbox-iso:     System Info:
    virtualbox-iso:     ------------
    virtualbox-iso:     chef_version=13.8.5
    virtualbox-iso:     platform=ubuntu
    virtualbox-iso:     platform_version=14.04
    virtualbox-iso:     ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    virtualbox-iso:     program_name=chef-solo worker: ppid=1098;start=12:05:19;
    virtualbox-iso:     executable=/opt/chef/bin/chef-solo
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Running handlers:
    virtualbox-iso: [2018-04-07T12:51:27+00:00] ERROR: Running exception handlers
    virtualbox-iso: [2018-04-07T12:51:27+00:00] ERROR: Running exception handlers
    virtualbox-iso: Running handlers complete
    virtualbox-iso: [2018-04-07T12:51:27+00:00] ERROR: Exception handlers complete
    virtualbox-iso: [2018-04-07T12:51:27+00:00] ERROR: Exception handlers complete
    virtualbox-iso: Chef Client failed. 81 resources updated in 46 minutes 07 seconds
    virtualbox-iso: [2018-04-07T12:51:27+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-04-07T12:51:27+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-04-07T12:51:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-04-07T12:51:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-04-07T12:51:27+00:00] ERROR: Net::ReadTimeout
    virtualbox-iso: [2018-04-07T12:51:27+00:00] ERROR: Net::ReadTimeout
    virtualbox-iso: [2018-04-07T12:51:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    virtualbox-iso: [2018-04-07T12:51:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error executing Chef: Non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error executing Chef: Non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
The issue is with the internet connection. From the logs I can see `cannot be downloaded from ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz` which means there was some network issue when downloading the file.

Please retry the build.

**Comment by qingsword** [comment]
Hey @Chan9390 ，thank you!

I downloaded this component and put it in the  ‘/tmp/packer-chef-solo/local-mode-cache/cache’  directory, which was built successfully.

**Comment by Helenbj** [comment]
@qingsword I cannot find the directory  ‘/tmp/packer-chef-solo/local-mode-cache/cache’ in my physical host, if it is is in the vm.box which was built?

**Comment by qingsword** [comment]
@Helenbj Do you see this directory in the error output? I am not sure if the directories are the same.

**Comment by Helenbj** [comment]
@qingsword thanks for your reply, I just walk across my problem.

**Comment by sohrabsaa** [comment]
packer 1.7.2
vagrant 2.2.16
-------------------------------------------------------------------
 virtualbox-iso: Creating directory: /tmp/packer-chef-solo
    virtualbox-iso: Creating directory: /tmp/packer-chef-solo/cookbooks-0
    virtualbox-iso: Creating configuration file 'solo.rb'
    virtualbox-iso: Creating JSON attribute file
    virtualbox-iso: Executing Chef: sudo chef-solo --no-color -c /tmp/packer-chef-solo/solo.rb -j /tmp/packer-chef-solo/node.json
==> virtualbox-iso: sudo: chef-solo: command not found
==> virtualbox-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> virtualbox-iso: Cleaning up floppy disk...
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored after 24 minutes 17 seconds: Error executing Chef: Non-zero exit status: 1

==> Wait completed after 24 minutes 17 seconds

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error executing Chef: Non-zero exit status: 1
------------------------------------------------------------------------
this is the error I get apparently it can't fine (chef-solo) command.
I would appreciate if someone can help me whit it.
