### ISSUE TITLE
Error starting and provisioning win2k8 on OS X

### ISSUE THREAD

**Issue by gcraenen** [rapid7/metasploitable3#267]
## Issue Description
Error when starting win2k8 of metasploitable3 on OS X, after succesfull build.

## Host System
* OS: OS X High Sierra 10.13.4
* Packer Version: 1.2.2
* Vagrant Version: 2.0.3
* VirtualBox Version: 5.2.8 r121009

## Command Output
vagrant up win2k8
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> win2k8: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp

**Comment by Chan9390** [comment]
Closing this issue as it is an error on the user machine and not metasploitable3.
