### ISSUE TITLE
Error in the last step ( vrgarant up ) please help 

### ISSUE THREAD

**Issue by secdecmso** [rapid7/metasploitable3#271]
## Issue Description
i did all the steps and all good but in the last step ( vagrant up ) this error appeard 
please help me 

## Host System
* OS: win10
* Packer Version: 1.1.1
* Vagrant Version: (2.0.3)
* VirtualBox Version:  5.2.8 

## Command Output

PS C:\Users\mrx\documents\metasploitable3-master\metasploitable3-master\packer\templates> vagrant up
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Box 'metasploitable3-ub1404' could not be found. Attempting to find and install...
    ub1404: Box Provider: virtualbox
    ub1404: Box Version: >= 0
==> ub1404: Box file was not detected as metadata. Adding it directly...
==> ub1404: Adding box 'metasploitable3-ub1404' (v0) for provider: virtualbox
    ub1404: Downloading: metasploitable3-ub1404
    ub1404:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/mrx/documents/metasploitable3-master/metasploitable3-master/packer/templates/metasploitable3-ub1404
PS C:\Users\mrx\documents\metasploitable3-master\metasploitable3-master\packer\templates>

NOTE :  the build is done and all good 

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: C:\Users\mrx\documents\metasploitable3-master\metasploitable3-master\packer\templates/.
./builds/windows_2008_r2_virtualbox_0.1.0.box

and after that I runned the command to add the box to VB its said  I will find machine metaplsoitable3 but when I open VB I dont find it.

**Comment by idrissbellil** [comment]
You built windows2008 and are trying to "vagrant up" both, 
run just "vagrant up win2k8"

**Comment by secdecmso** [comment]
when I run vagrant up win2k8 I go this : 
 PS C:\Users\mrx\documents\metasploitable3-master\metasploitable3-master> vagrant up win2k8
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> win2k8: Box 'metasploitable3-win2k8' could not be found. Attempting to find and install...
    win2k8: Box Provider: virtualbox
    win2k8: Box Version: >= 0
==> win2k8: Box file was not detected as metadata. Adding it directly...
==> win2k8: Adding box 'metasploitable3-win2k8' (v0) for provider: virtualbox
    win2k8: Downloading: metasploitable3-win2k8
    win2k8:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/mrx/documents/metasploitable3-master/metasploitable3-master/metasploitable3-win2k8
PS C:\Users\mrx\documents\metasploitable3-master\metasploitable3-master>

**Comment by jmartin-r7** [comment]
While the complete build is not yet working on windows due to #326, you can pull the latest code and use `vagrant up` to get builds from VagrantCloud.
