### ISSUE TITLE
build linux metasploitable on windows

### ISSUE THREAD

**Issue by aoighost** [rapid7/metasploitable3#272]
## Issue Description
I notice there is a linux version of metasploitable 3 now, however there is no build command to build the Linux version on Windows. Please add a Linux builder for windows hosts.

**Comment by KennyStevens** [comment]
Hey, maybe this helps:[https://www.howtogeek.com/265900/everything-you-can-do-with-windows-10s-new-bash-shell/](url)
this is a how to for newer Windows systems, it allows you to use Linux on WIndows.

**Comment by AmatureHacker** [comment]
@aoighost Try using the following command 
packer build --only=**vmware-iso** ./packer/templates/ubuntu_1404.json

In case of Virtual box, replace **vmware-iso** with **virtualbox-iso**

It should work though ... Do give a try and let me know if you receive any error similar to the attached 
[Powershell enteries.txt](https://github.com/rapid7/metasploitable3/files/2664351/Powershell.enteries.txt)

**Comment by jmartin-r7** [comment]
This was added with #277.
