### ISSUE TITLE
Default PS script fails to build the VM on windows 10

### ISSUE THREAD

**Issue by dukeofdisaster** [rapid7/metasploitable3#276]
## Host System
* OS: Windows 10 Pro 1709- 64-Bit 
* Packer Version: 1.0.0
* Vagrant Version: 2.0.3
* VirtualBox Version: 5.2.8 r121009 

## Command Output
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36
==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36
==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\user\Documents\GitProjects\metasploitable3\build_win2008.ps1:108 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by Chan9390** [comment]
Hey @dukeofdisaster , please comment the full output.

**Comment by dukeofdisaster** [comment]
https://pastebin.com/SDi9U71g

**Comment by dukeofdisaster** [comment]
I don't think it was, i forgot my antivirus was on and probably quarantined it... deleted the repo and recloned it just now,, this time with antivirus off... trying to rebuild now.

**Comment by Chan9390** [comment]
Please close the issue if you dont face any issue

**Comment by dukeofdisaster** [comment]
Will do....

**Comment by dukeofdisaster** [comment]
==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: C:\Users\user\Documents\GitProjects\metasploitable3\packer\templates/../builds/windows_2008_r2_virtualbox_0.1.0.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3-win2k8' (v0) for provider:
    box: Downloading: packer/builds/windows_2008_r2_virtualbox.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/user/Documents/GitProjects/metasploitable3/packer/builds/windows_2008_r2_virtualbox.box
Error adding box to Vagrant. See the above output for any error messages.
At C:\Users\user\Documents\GitProjects\metasploitable3\build_win2008.ps1:127 char:9
+         throw "Error adding box to Vagrant. See the above output for  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.

PS C:\Users\user\Documents\GitProjects\metasploitable3>

**Comment by Chan9390** [comment]
Currently you have not built the Linux box. So you could try `vagrant up win2k8` which only starts the Windows machine. 

(PR #277 introduces a new `build.ps1` powershell script which allows the build of Linux box. You can use it once its merged)

**Comment by Chan9390** [comment]
BTW what did you do to resolve the above mentioned error ?

**Comment by dukeofdisaster** [comment]
Nope... it failed miserably... as did trying vagrant up win2k8. Killed the repo... reinstalling vagrant... gonna try again from scratch to build the windows box. Haven't been able to find any recent success stories/guides on building it. One from February already seems outdated..

**Comment by dukeofdisaster** [comment]
BTW, trying from your fork.

**Comment by dukeofdisaster** [comment]
Kill it with fire
