### ISSUE TITLE
Failed to parse template: open packer/templates/windows_2008_r2.json: no such file or directory

### ISSUE THREAD

**Issue by MechanicalType** [rapid7/metasploitable3#278]
## Issue Description
Keep getting a parsing error when trying to build vagrant box. Stating packer/templates/windows_2008_r2.json: no such file or directory

I can check the /packer/templates directory and I see windows_2008_r2.json file. I've tried changing permissions, modifying a copy of the build.sh to point straight at a file instead of using the $os_full variable and changed the packer_bin path as well with no luck.

## Host System
* OS: Linux Ubuntu/GNOME 16.04
* Packer Version: 1.2.2
* Vagrant Version: 2.0.4
* VirtualBox Version: 5.1.34_Ubuntu r1212010

## Command Output
: sudo ./build.sh windows2008
....
All requirements found. Proceeding...
Building the Vagrant box...
Failed to parse template: open packer/templates/windows_2008_r2.json: no such file or directory
Error building the Vagrant box using Packer. Please check the output above for any error messages.

## Apology:
My apologies if I did something wrong here, this is my first time posting an issue on GitHub.

**Comment by jmartin-r7** [comment]
You should not need the `sudo` here.  Your standard user should be in the virtualbox of vmware permissions group have right to execute `packer`.  Given this I would expect your issue is that sudo is changing something in env that caused the failure.

**Comment by MechanicalType** [comment]
You nailed it. I moved it to a different directory (in my home folder) and it went through without a hiccup. Thanks!!
