### ISSUE TITLE
unable to install Metasploitable 3 on my 2016 VM.

### ISSUE THREAD

**Issue by Dieseldrinkingrat** [rapid7/metasploitable3#282]
## Issue Description
I am unable to install Metasploitable 3 on my 2016 VM. I have updated and downgraded packer based on other forum postings. I have also tried the clone of MS3 so it comes with the .json files. However still the system will not build and fails. 

## Host System
* OS: Windows Server 2016
* Packer Version: 1.1.1
* Vagrant Version: 2.0.4
* VirtualBox Version: Version 5.2.8 r121009 (Qt5.6.2)

## Command Output .\build_win2008.ps1
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
==> virtualbox-iso: VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage.exe: error: VT-x is not available (VERR_
VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\Administrator\Desktop\metasploitable3\build_win2008.ps1:107 char:9
+         throw "Error building the Vagrant box using Packer. Please ch ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by busterb** [comment]
You cannot run a virtual machine within a virtual machine with Virtualbox. Remove one layer of abstraction and provision it on the physical machine.
