### ISSUE TITLE
Output from Packer build is different from the file name attempted to add to Vagrant.

### ISSUE THREAD

**Issue by jersalamon** [rapid7/metasploitable3#283]
## Issue Description
Output from Packer build is different from the file name attempted to add to Vagrant.

Packer output:
.\packer\templates/../builds/windows_2008_r2_virtualbox_0.1.0.box

Vagrant Add (build_win2008.ps1 line 122)
.\packer/builds/windows_2008_r2_virtualbox.box

## Host System
* OS: 2012R2 
* Packer Version: 1.2.3
* Vagrant Version: 2.0.4
* VirtualBox Version: 5.2.10

## Command Output
--> virtualbox-iso: 'virtualbox' provider box: C:\Users\administrator.lab\Desktop\metasploitable3-master\packer\template
s/../builds/windows_2008_r2_virtualbox_0.1.0.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3-win2k8' (v0) for provider:
    box: Downloading: packer/builds/windows_2008_r2_virtualbox.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/administrator.lab/Desktop/metasploitable3-master/packer/builds/windows_2008_r2_virtualbox.b
ox
Error adding box to Vagrant. See the above output for any error messages.
At C:\Users\administrator.lab\Desktop\metasploitable3-master\build_win2008.ps1:127 char:9
+         throw "Error adding box to Vagrant. See the above output for any error m ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.

**Comment by jmartin-r7** [comment]
This should be addressed with #277
