### ISSUE TITLE
Idea - build with ReactOS?

### ISSUE THREAD

**Issue by sctlfb** [rapid7/metasploitable3#288]
Hi,
     an idea: could MS3 be built with ReactOS?

Does anyone have any experience with this or ideas on how it could be done?

**Comment by busterb** [comment]
It is fastest and easiest to build it on Linux. ReactOS doesn't appear to support running any hypervisors, which is the minimum requirement.

**Comment by sctlfb** [comment]
Hi Brent,
              in case underlying meaning of my question wasn’t clear: could you build a MS3 VM using ReactOS instead of Win28K? ie; I’m not saying use React OS as the OS to compile the VM. I’m saying could you use ReactOS instead of Windows to build the VM?

Sorry if original question not clear.

Interested to hear any feedback

Cheers

Scott

**Comment by bcoles** [comment]
@sctlfb I have no idea, but will take this opportunity to mention that every time I've tried to use ReactOS I've given up before ever getting the drivers for the VMware network interfaces to work. So... there's that.

**Comment by busterb** [comment]
MVP would be getting a ReactOS vagrant box. Doesn't appear anyone has done published one yet: https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=reactos

**Comment by busterb** [comment]
Sorry, I don't think this is going to be viable. Please check out our pre-build binaries!

**Comment by bish0polis** [comment]
https://app.vagrantup.com/henryfbp/boxes/reactos-0.4.13
