### ISSUE TITLE
Ubuntu 1404 installed failed: proftpd

### ISSUE THREAD

**Issue by arthur3672** [rapid7/metasploitable3#289]
Following is the failure code:
  virtualbox-iso:     ================================================================================
    virtualbox-iso:     Error executing action `start` on resource 'service[proftpd]'
    virtualbox-iso:     ================================================================================
    virtualbox-iso:
    virtualbox-iso:     Errno::ENOENT
    virtualbox-iso:     -------------
    virtualbox-iso:     No such file or directory - /etc/init.d/proftpd
    virtualbox-iso:
    virtualbox-iso:     Resource Declaration:
    virtualbox-iso:     ---------------------
    virtualbox-iso:     # In /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/proftpd.rb
    virtualbox-iso:
    virtualbox-iso:      68: service 'proftpd' do
    virtualbox-iso:      69:   action [:enable, :start]
    virtualbox-iso:      70: end
    virtualbox-iso:      71:
    virtualbox-iso:
    virtualbox-iso:     Compiled Resource:
    virtualbox-iso:     ------------------
    virtualbox-iso:     # Declared in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/proftpd.rb:68:in `from_file'
    virtualbox-iso:
    virtualbox-iso:     service("proftpd") do
    virtualbox-iso:       action [:enable, :start]
    virtualbox-iso:       updated true
    virtualbox-iso:       default_guard_interpreter :default
    virtualbox-iso:       service_name "proftpd"
    virtualbox-iso:       enabled true
    virtualbox-iso:       running false
    virtualbox-iso:       masked nil
    virtualbox-iso:       pattern "proftpd"
    virtualbox-iso:       declared_type :service
    virtualbox-iso:       cookbook_name "metasploitable"
    virtualbox-iso:       recipe_name "proftpd"
    virtualbox-iso:     end
    virtualbox-iso:
    virtualbox-iso:     System Info:
    virtualbox-iso:     ------------
    virtualbox-iso:     chef_version=13.8.5
    virtualbox-iso:     platform=ubuntu
    virtualbox-iso:     platform_version=14.04
    virtualbox-iso:     ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    virtualbox-iso:     program_name=chef-solo worker: ppid=1088;start=03:33:58;
    virtualbox-iso:     executable=/opt/chef/bin/chef-solo
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Running handlers:
    virtualbox-iso: [2018-05-13T03:47:00+00:00] ERROR: Running exception handlers
    virtualbox-iso: [2018-05-13T03:47:00+00:00] ERROR: Running exception handlers
    virtualbox-iso: Running handlers complete
    virtualbox-iso: [2018-05-13T03:47:00+00:00] ERROR: Exception handlers complete
    virtualbox-iso: [2018-05-13T03:47:00+00:00] ERROR: Exception handlers complete
    virtualbox-iso: Chef Client failed. 91 resources updated in 13 minutes 01 seconds
    virtualbox-iso: [2018-05-13T03:47:00+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-05-13T03:47:00+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2018-05-13T03:47:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-05-13T03:47:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2018-05-13T03:47:00+00:00] ERROR: service[proftpd] (metasploitable::proftpd line 68) had an error: Errno::ENOENT: No such file or directory - /etc/init.d/proftpd
    virtualbox-iso: [2018-05-13T03:47:00+00:00] ERROR: service[proftpd] (metasploitable::proftpd line 68) had an error: Errno::ENOENT: No such file or directory - /etc/init.d/proftpd
    virtualbox-iso: [2018-05-13T03:47:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    virtualbox-iso: [2018-05-13T03:47:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error executing Chef: Non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* VMware application not found:
* VMware application not found:
* 'vmrun' application not found:
* 'vmrun' application not found:

--> virtualbox-iso: Error executing Chef: Non-zero exit status: 1

==> Builds finished but no artifacts were created.

**Comment by jmartin-r7** [comment]
Please retry your build, you may simply have had a connectivity issue. Also if this continues details of the env are needed to debug further.

Host OS and software versions for packer/virtualbox/vagrant used as well as system spec would be needed.

**Comment by michaeltennis** [comment]
I also meet the same problem above.

I use the Windows 10 home, Virtualbox 5.2.1, packer 1.2.4, vagrant 2.1.1.

As @jmartin-r7 mentioned before, it may be a connectivity issue, I have already try to rebuild many times wtih the good connection condition VPN, however, the result have not changed.

**Comment by kmcyjm** [comment]
Encountered the same issue today. 

System Spec
========

Host OS: Windows 10 Pro, Build 1803
VMWare Workstation Pro 14.1.2
Packer: 1.2.5
Vagrant: 2.1.4

Tried a couple of times, same issue.

The build on Windows 2008 was successful by following the manual step in Github.

**Comment by kmcyjm** [comment]
Both build (win and ubuntu) on Mac OS X 10.12.6 were successful, so the issue is very likely Windows OS related.

**Comment by jmartin-r7** [comment]
This is likely confirmed issue #326

**Comment by jmartin-r7** [comment]
Fixed my #344.
