### ISSUE TITLE
Build error: unknown configuration key

### ISSUE THREAD

**Issue by sjorsng** [rapid7/metasploitable3#290]
## Issue Description

I can build the windows VM but cannot build the Ubuntu VM. It complains about a configuration key missing, though I did not change anything in the configuration files.  Also, I used all the suggested dependency versions.

## Host System
* OS: Ubuntu 16.04.4 LTS (xenial)
* Packer Version: 1.0.0
* Vagrant Version: 1.9.1
* VirtualBox Version:  5.1.14 r112924 (Qt5.5.1)

## Command Output

ubuntu@ubuntu:~/metasploitable3$ ./build.sh ubuntu1404
building ubuntu 1404
Compatible version of VirtualBox found.
Compatible version of packer was found.
Correct version of vagrant was found.
Compatible version of vagrant-reload plugin was found.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

1 error(s) occurred:

* unknown configuration key: "version"
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by jmartin-r7** [comment]
Your issue is `packer 1.0.0`

The ubuntu 14.04 build requires a newer version of packer.  Currently tested working on `packer 1.2.3`.

**Comment by sjorsng** [comment]
I indeed confirm it works with version 1.2.3. I see it is already edited in the [supported versions table](https://github.com/rapid7/metasploitable3/wiki/General-Issues#current-supported-versions), thank you.
