### ISSUE TITLE
Vagrant Up Failed

### ISSUE THREAD

**Issue by xInspectorGadgetx** [rapid7/metasploitable3#293]
## Issue Description
When I try to do **vagrant up win2k8** it states it cannot open the file. I have tried turning off my AV while running it as well as setting full control to the directories but the issue persists.  

## Host System
* OS: Windows 10 Home
* Packer Version: 1.2.3
* Vagrant Version: 2.1.1
* VirtualBox Version: 5.2.12

## Command Output
PS C:\metasploitable3setup\metasploitable3master> vagrant up win2k8
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> win2k8: Box 'metasploitable3-win2k8' could not be found. Attempting to find and install...
    win2k8: Box Provider: virtualbox
    win2k8: Box Version: >= 0
==> win2k8: Box file was not detected as metadata. Adding it directly...
==> win2k8: Adding box 'metasploitable3-win2k8' (v0) for provider: virtualbox
    win2k8: Downloading: metasploitable3-win2k8
    win2k8:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/metasploitable3setup/metasploitable3master/metasploitable3-win2k8
PS C:\metasploitable3setup\metasploitable3master>

**Comment by mashqara** [comment]
Hello.
I had the same issue. Try add box manualy:
(I do this in my 'packer/builds' directory where '.box' file is saved)
(cmd)> vagrant box add --name metasploitable3-win2k8 windows_2008_r2_virtualbox_0.1.0.box
(check correct name of your '.box' file)
After that, run:
(cmd)> vagrant up win2k8

**Comment by jmartin-r7** [comment]
@xInspectorGadgetx the details provided do not clarify if you got a successful output from the build.  The info provided suggest either the box is not created yet or failed to import into the vagrant environment.

Please pull the latest code and retry the build. Also Rapid7 has started providing stable builds from vagrant cloud directly. If you skip the build process, 'vagrant up' should start downloading pre-built images if you do not have a pressing need to build them from scratch.
