### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by askanase** [rapid7/metasploitable3#294]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
* Packer Version:0.10.2
* Vagrant Version: Vagrant 1.9.1
* VirtualBox Version: 5.2.12

this command "vagrant box add packer/builds/windows_2008_r2_virtualbox_0.1.0.box --name=metasploitable3" when successfully with no error.

but whenever i enter the following command: vagrant up

## Command Output for vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

## Command Output for: vagrant up metasploitable3
The machine with the name 'metasploitable3' was not found configured for
this Vagrant environment.

I have tried each of those previous command on the metasploitable3 git-clone directory and and also on ".vagrant.d/boxes/metaploitable3/0/virtualbox/" with the same issues
the directory ".vagrant.d/boxes/metasploitable2/0/virtualbox" contains the following files: 
box.ovf  metadata.json  metasploitable3-win2k8-disk001.vmdk  Vagrantfile
any help with one of this two error will be welcome.

**Comment by 0xvext** [comment]
I am encountering this same issue.

    OS: Debian 9.4
    Packer Version: 1.2.3
    Vagrant Version: Vagrant 1.9.1
    VirtualBox Version:  5.2.12

I successfully set up the Ubuntu version of metasploitable3 with no errors using the automated build script. Instructions indicated to run 'vagrant up' to start it, and I received the same error in the original post when doing so.

'vagrant box list' outputs: metasploitable3-ub1404 (virtualbox, 0)

**Comment by 0xvext** [comment]
Found the following closed issues and referenced workaround

https://github.com/rapid7/metasploitable3/issues/220
https://github.com/hashicorp/vagrant/issues/9090#issuecomment-339935445

**Comment by agptest** [comment]
The issue I was encountering was due to using an instance of Vagrant installed via apt. I removed that version and manually installed from the Vagrant .deb file and the error was resolved. I did not have to apply the manual workaround above.

**Comment by 0xvext** [comment]
The issue on my end was caused by using an instance of Vagrant installed via apt. I removed that version and installed Vagrant via the .deb package on the Vagrant website. This resolved the error I was receiving without needing the manual workaround posted above.

**Comment by jmartin-r7** [comment]
As noted by @0xvext, this is likely a corrupt or misconfigured vagrant install.  Please try removing the installed version and install from https://www.vagrantup.com/downloads.html.
