### ISSUE TITLE
VM not added to VirtualBox

### ISSUE THREAD

**Issue by oldRedFox** [rapid7/metasploitable3#295]
## Issue Description
I was having issues getting vagrant up win2k8 work, which failed with error System error 67 has occurred. I was able to get the command to complete updating the setup_linux_share.bat batch file with the IP assigned to the VM and running the command vagrant up --provision win2k8. However, the VM does not appear in VirtualBox. I found the OVF in C:\users\<mypofile>\.vagrant.d\boxes\metasploitable3-win2k8\0\virtualbox and manually imported it.

## Host System
* OS: Windows 10 Enterprise
* Packer Version: 1.2.3
* Vagrant Version: 2.1.1
* VirtualBox Version: 5.2.8 r121009 QT5.6.2

## Command Output
PS # vagrant up --provision win2k8
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> win2k8: Running provisioner: shell...
    win2k8: Running: scripts/configs/enable_firewall.bat as c:\tmp\vagrant-shell.bat
    win2k8: Ok.
==> win2k8: Running provisioner: shell...
    win2k8: Running: scripts/configs/configure_firewall.bat as c:\tmp\vagrant-shell.bat
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
    win2k8: Ok.
==> win2k8: Running provisioner: shell...
    win2k8: Running: scripts/installs/install_share_autorun.bat as c:\tmp\vagrant-shell.bat
    win2k8:         1 file(s) copied.
    win2k8: The operation completed successfully.
==> win2k8: Running provisioner: shell...
    win2k8: Running: inline PowerShell script
==> win2k8: Running provisioner: shell...
    win2k8: Running: scripts/installs/setup_linux_share.bat as c:\tmp\vagrant-shell.bat
    win2k8: "Linux host not available."
==> win2k8: Running provisioner: shell...
    win2k8: Running: inline PowerShell script

**Comment by jmartin-r7** [comment]
This may have been a failed import due to issues with the powershell build script.  #277 may address the issue.  

Also since the vagrant box is not a linked clone, the VM would only be in the virtualbox catalog while it is deployed, after a successful `vagrant up` and until `vagrant destroy` removes it.

**Comment by jmartin-r7** [comment]
Closing as believed fixed by #277.
