### ISSUE TITLE
Metasploitable3 - 'vagrant up' delivers always errors

### ISSUE THREAD

**Issue by Linuxmaker** [rapid7/metasploitable3#297]
I have build sucessfully with "./build.sh windows2008" Metasploitable3 on a Debian Linux. To start Metasploitable3 with vagrant fails. The same output comes with the variants "vagrant up win2k8 --color 2>&1 | tee -a log.txt" or "vagrant up ub1404 --color 2>&1 | tee -a log.txt"

## Host System
* OS: Debian Stretch
* Packer Version: 1.2.4
* Vagrant Version: 2.0.3
* VirtualBox Version: 5.1.34 r121010 (Qt5.7.1)

## Command Output
vagrant up --color 2>&1 | tee -a log.txt
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Box 'metasploitable3-ub1404' could not be found. Attempting to find and install...
    ub1404: Box Provider: virtualbox
    ub1404: Box Version: >= 0
==> ub1404: Box file was not detected as metadata. Adding it directly...
==> ub1404: Adding box 'metasploitable3-ub1404' (v0) for provider: virtualbox
    ub1404: Downloading: metasploitable3-ub1404
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/downloads/metasploitable3/metasploitable3-ub1404

**Comment by Linuxmaker** [comment]
The deletion of the virtual machine and the entire directory "metasploitable3" with a re-run of the build unfortunately does not help. The said error with "vagrant up" remains unfortunately.

**Comment by iNoSec** [comment]
Same error here

**Comment by iNoSec** [comment]
you must rename your directory in the $HOME/.vagrant.d/boxes/ to the name vagrant search $HOME/.vagrant.d/boxes/metasploitable3-ub1404 for the ubuntu and $HOME/.vagrant.d/boxes/metasploitable3-win2k8 for the windows2k8 and all works fine

There is a problem with the bash script in our case, when it made vagrant box add $packer_build_path/"$os_full"_virtualbox_"$box_version".box --name metasploitable3-$os_short i dont know why the variable os_short isn't find, i will look the script when i have time but not now, you can patch it like i said with renaming vagrant box manually

**Comment by jmartin-r7** [comment]
If you only built the `windows2008` box you would need to execute `vagrant up win2k8` as the config expects both boxes to be registered in vagrant.
