### ISSUE TITLE
VMware provider in vagrant isn't free, please add it to readme

### ISSUE THREAD

**Issue by iNoSec** [rapid7/metasploitable3#298]
Hi all,

This is not an issue but more a request about adding to the readme that we cant built for FREE the vm in vmware because the vagrant plugin is 89$... just for those which dont want to buy it and lose like 1h to make it working but after that SURPRISE you need to pay :( 

Thanks in advance

**Comment by jmartin-r7** [comment]
You can still build the vm using packer, you just can't add it to a vmware environment and use `vagrant up` to manage it without a paid plugin.  This means the work done before the standard build script errors is not wasted execution.  The `box` files would still contain completed VMs in `packer/builds/` and be available for manual start in VMware.

I will try to make some time to update the documentation to make this more clear.  Please feel free to open a PR as well with these details added to docs.

Vagrant is just a convenience feature, usage of vagrant is not required to start run the VMs produced by this repository. If you build the box file you can simply extract it and open the `vmx` in vmware fusion/workstation/esxi.

To build the windows target manually without the build script:
```
packer build -only=vmware-iso packer/templates/windows_2008_r2.json
cd packer/builds/
mkdir extract
cd extract/
tar zxvf ../windows_2008_r2_vmware_0.1.0.box
```
