### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by DeveloppSoft** [rapid7/metasploitable3#30]
Hey rapid7, what about publishing a Dockerfile so we can use docker?

**Comment by Chan9390** [comment]
**Use docker instead of vagrant to install the entire metasploitable 3 setup ?**
There is _no Windows docker image_, so how is it possible to create `Dockerfile` for packaging all the windows based vulnerable apps ? I dont think docker could replace vagrant in this case. Also packaging and distributing custom Windows VMs is against the terms of Microsoft. Thats why vagrant is the only way to setup M3 as of now.

@jbarnett-r7 I would like to know how this will be considered as **enhancement**. @DeveloppSoft Please let me know if I have misinterpreted your issue.

**Comment by DeveloppSoft** [comment]
@Chan9330, you haven't misinterpreted the issue, the goal is to build a docker version of M3.
> There is no Windows docker image, so how is it possible to create Dockerfile for packaging all the windows based vulnerable apps ?
Wrong, have a look at https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/ and https://hub.docker.com/r/microsoft/windowsservercore/
I guess the provided images are not complete version of windows server, but it might be interesting...
Regarding the license issue, you can have a look at the second link. From what I understand, you must run the image on a windows host (might be a VM, I think...).

**Comment by jbarnett-r7** [comment]
So I'm a Docker noob, and just read up on this as well. I think it would be a lot of work, but does seem to be possible with Server 2016, now. If anyone wants to take a stab at it, I think it would be a great addition. But I know for me personally it would be quite a ways off.

**Comment by Chan9390** [comment]
The idea was quite good until I found this:

![image](https://cloud.githubusercontent.com/assets/12944530/24085267/b43906a2-0d1e-11e7-8916-f0410153a93f.png)

Windows containers can only be used on either **Windows Server 2016** or **Windows 10 Pro / Enterprise** (_The free upgrade that people got was Windows 10 Home_)

More details at: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/system-requirements

Is it really worth creating a Docker file for Metasploitable 3 ?

**Comment by DeveloppSoft** [comment]
Yep, I know :cry:
It might be good if you want better performances, but might be too much work for a small improvement (+ needing a special version of windows...).
I'll let you decide.

**Comment by jbarnett-r7** [comment]
Going to close this for now and maybe reconsider when Windows support in Docket improves. If someone wants to take this on feel free :)

**Comment by GabrielTK** [comment]
I'll try to Port it, but I'm new to Docker.

**Comment by GabrielTK** [comment]
USEFUL: https://www.packer.io/docs/builders/docker.html

Also, I think I won't be able to Port it.

**Comment by GabrielTK** [comment]
I think there are no Windows Server 2008 R2 Images on Docker.

**Comment by Chan9390** [comment]
Hey @GabrielTK I think this resource: https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/ will be helpful.
If you want to be more specific on windows containers, check out: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/deploy-containers-on-server

**Comment by Deninc** [comment]
Guys, how about a Docker version for Ubuntu?
