### ISSUE TITLE
Build fails at "vagrant up"

### ISSUE THREAD

**Issue by mybrotheriseric** [rapid7/metasploitable3#302]
## Issue Description
As in title, build consistently fails after adding the box and running command, "vagrant up".  Have tried manual process and build_win2008.ps1 with same results.  Output linked below.

## Host System
* OS: Windows 10
* Packer Version: 1.2.3
* Vagrant Version: 2.1.1
* VirtualBox Version: 5.2.12 r122591 (Qt5.6.2)

## Command Output
[https://hastebin.com/suroketinu.tex](https://hastebin.com/suroketinu.tex)
It appears I don't have enough history for the entire output.  I can run it again if requested, but hope this is enough to troubleshoot since the part that is cut off appears to run successfully.

Edited to include relevant section of output:
```
Build 'virtualbox-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: C:\metasploitable3\packer\templates/../builds/windows_2008_r2_virtualbox_0.1.0.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3-win2k8' (v0) for provider:
    box: Downloading: packer/builds/windows_2008_r2_virtualbox.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/metasploitable3/packer/builds/windows_2008_r2_virtualbox.box
Error adding box to Vagrant. See the above output for any error messages.
At C:\metasploitable3\build_win2008.ps1:127 char:9
+         throw "Error adding box to Vagrant. See the above output for  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.
```

**Comment by jmartin-r7** [comment]
This may be resolved with #277, please pull `master` and retest.

Closing for now feel free to reopen if build on latest code does not address this.
