### ISSUE TITLE
hi guys thx for this awesome build

### ISSUE THREAD

**Issue by nOObseCu** [rapid7/metasploitable3#308]
## Issue Description

i just want to say it works on vmware after 2 day of struggling so this is the issue i face and fix 
1- dont try the ova file of the virtual box will never work ( network issue )
2- dont use last command  vagrant up  its compatible with 3 virtual systems vmware not included.
3- in vmware u dont need vagrant up cos its not compatible so extract box file and open it using vmware when message pop choose i copied and start ur virtual machine 
4- box file will be 6 GB after extract it will be 13.5 GB

**Comment by jmartin-r7** [comment]
Thanks for the feedback.

While the notes are interesting issues here a meant to address problems or feature requests.

On item 1, There are builders for vmware-iso in the packer templates so the ovf in the virtual box object should not be needed for vmware.

On item 2, `vagrant up` is available for use with the VMware Plugin for vagrant, however that is a paid plugin.

On item 3, correct there are notes on #298, about this and we will track updating the readme there.

On item 4, the readme notes `65GB` of storage needed for just this reason VMs are large. :-)

Closing this as not duplicate/NotABug.
