### ISSUE TITLE
Nobody Knows the Trouble I've Seen

### ISSUE THREAD

**Issue by designofhumanity** [rapid7/metasploitable3#310]
![default](https://user-images.githubusercontent.com/2714036/42154045-73d37160-7ded-11e8-80c9-76e1fc02612a.png)

![default](https://user-images.githubusercontent.com/2714036/42153083-b62d6294-7dea-11e8-9699-d3840b703c97.png)

my fix (sorry i don't have time to make my pull request)
![default](https://user-images.githubusercontent.com/2714036/42153198-1a224238-7deb-11e8-85ec-2e23fd0db156.png)
Look at this **path!** pls
![default](https://user-images.githubusercontent.com/2714036/42153227-355cefda-7deb-11e8-8ad3-1f50bce53704.png)
Look at this **path!** pls
![default](https://user-images.githubusercontent.com/2714036/42153259-45c94a4e-7deb-11e8-9f4c-23b007876b54.png)
![default](https://user-images.githubusercontent.com/2714036/42153381-9ff6b7cc-7deb-11e8-8983-95c219bd1de6.png)
![default](https://user-images.githubusercontent.com/2714036/42153763-c210bd8e-7dec-11e8-93c9-2aa522eb05c1.png)
![default](https://user-images.githubusercontent.com/2714036/42154966-c1c0ae72-7def-11e8-8d75-4f10f28133df.png)
**After my correction:**
![default](https://user-images.githubusercontent.com/2714036/42155029-f000b282-7def-11e8-9414-412c861adfa4.png)

**Comment by jmartin-r7** [comment]
There are open pull request to address this issue, closing as a duplicate.

LOL, @bcoles
