### ISSUE TITLE
./build.sh ubuntu1404 GuestAdditions fails on VirtualBox v5.2.14

### ISSUE THREAD

**Issue by TheLinuxNinja** [rapid7/metasploitable3#312]
## Issue Description
./build.sh ubuntu1404 GuestAdditions fails on VirtualBox v5.2.14

Downgrading VirtualBox to 5.2.12 is a workaround.

## Host System
* OS: Arch Linux 07/10/2018 and MacOS 10.13.5
* Packer Version: 1.2.4
* Vagrant Version: 2.1.2
* VirtualBox Version: 5.2.14

## Command Output
The chef recipe that adds VirtualBox GuestAdditions 5.2.14 to Ubuntu 14.04 results in a crash inside the VM.

https://gist.github.com/TheLinuxNinja/df696a102da66dddcb3c153e18735e7e

**Comment by mubix** [comment]
Confirmed, I get the same result

**Comment by jmartin-r7** [comment]
Fixed by #321
