### ISSUE TITLE
Multiple services missing 

### ISSUE THREAD

**Issue by msflover** [rapid7/metasploitable3#314]
## Issue Description
I miss multiple services e.g. elasticsearch, ftp, iis,rdp, etc. I' ve tried with different version of vagrant as you can see in the "Host System" section but without luck.

## Host System
* OS: Ubuntu 18.04
* Packer Version: 1.0.4
* Vagrant Version: 1.9.1, 2.0.2, 2.0.3, 2.1.2
* VirtualBox Version: 5.2.14

## Command Output

Nmap scan report for 192.168.0.59
Host is up (0.00070s latency).
Not shown: 65516 filtered ports
PORT      STATE SERVICE
22/tcp    open  ssh
1617/tcp  open  nimrod-agent
3000/tcp  open  ppp
4848/tcp  open  appserv-http
5985/tcp  open  wsman
8020/tcp  open  intu-ec-svcdisc
8022/tcp  open  oa-system
8027/tcp  open  unknown
8080/tcp  open  http-proxy
8282/tcp  open  libelle
8383/tcp  open  m2mservices
8484/tcp  open  unknown
8585/tcp  open  unknown
9200/tcp  open  wap-wsp
49153/tcp open  unknown
49154/tcp open  unknown
49178/tcp open  unknown
49180/tcp open  unknown
49254/tcp open  unknown

## Update

Just tried with packer 1.2.4. Same problem.

**Comment by dial25sd** [comment]
Solved my problem: The services were running, but after reinstalling the VMs I've seen this in the log:
`    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed port 445 for SMB" dir=in action=block protocol=TCP localport=445 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed port 139 for NetBIOS" dir=in action=block protocol=TCP localport=139 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed port 135 for NetBIOS" dir=in action=block protocol=TCP localport=135 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed Port 3389 for Remote Desktop" dir=in action=block protocol=TCP localport=3389 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed Port 3306 for MySQL" dir=in action=block protocol=TCP localport=3306 
    win2k8: Ok.
`
Turning off the firewall or removing these rules should work.

**Comment by jmartin-r7** [comment]
This is intended function see [Vagrantfile](https://github.com/rapid7/metasploitable3/blob/6b0bac0626bbd5895b23459d66e57882c44aed2e/Vagrantfile#L30-L37).
