### ISSUE TITLE
'non-zero exit status: 36' "[SC] OpenService FAILED 1060:  The specified service does not exist as an installed service."

### ISSUE THREAD

**Issue by derhornspieler** [rapid7/metasploitable3#316]
## Issue Description
Failing to complete build from default build.sh script.  non-zero exit status: 36

## Host System
* OS: macOS High Sierra 10.13.6 (17G65)
* Packer Version: 1.2.5
* Vagrant Version: 2.1.2
* VirtualBox Version: 5.2.14 r123301 (Qt5.6.3)

## Command Output
    virtualbox-iso: processed file: C:\glassfish\glassfish4\pkg\lib\pkg-bootstrap.jar
    virtualbox-iso: processed file: C:\glassfish\glassfish4\pkg\lib\pkg-bootstub.bat
    virtualbox-iso: processed file: C:\glassfish\glassfish4\pkg\lib\pkg-bootstub.sh
    virtualbox-iso: processed file: C:\glassfish\glassfish4\pkg\lib\pkg-client.jar
    virtualbox-iso: Successfully processed 1947 files; Failed processing 0 files
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by 937325203** [comment]
At first , I'm sorry my English is not very good
I have the same exit statuse code
the other issues for statuse code 36 has the same system ,our system is same for macOS latest version.so i guess this issues is because macOS?

**Comment by jmartin-r7** [comment]
This was likely a problem during java installation earlier in the build. Reliable internet connectivity is very important to get a clean build.  I have executed >10 runs in the last 3 days and VM build successfully, when I do see failures it is either connectivity or something the internet *moved*.  Closing as likely network related.

On the bright size Rapid7 has started providing stable builds from vagrant cloud directly.  Please pull the latest code on the `master` branch and `vagrant up` should start downloading pre-built images if you do not have a pressing need to build them from scratch.

**Comment by 937325203** [comment]
I come from China XinJiang. Only through vpn can I access github. it is a Instable link.Please tell me where can i download the pre-built images? Thank you .

**Comment by jmartin-r7** [comment]
See https://github.com/rapid7/metasploitable3#quick-start, or just pull the latest commit on master and call `vagrant up`.  Vagrant will pull the boxes from the vagrant cloud registry @ https://app.vagrantup.com/rapid7/
