### ISSUE TITLE
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36 (windows2008 build)

### ISSUE THREAD

**Issue by derhornspieler** [rapid7/metasploitable3#317]
Failing to complete build from default build.sh script. non-zero exit status: 36

Host System

OS: macOS High Sierra 10.13.6 (17G65)
Packer Version: 1.2.5
Vagrant Version: 2.1.2
VirtualBox Version: 5.2.14 r123301 (Qt5.6.3)

## Command Output
    virtualbox-iso: C:\Users\vagrant>powershell -Command "$body = [System.Text.Encoding]::ASCII.GetBytes('{\"user\":\"kimchy\", \"post_date\": \"2009-11-15T14:12:12\", \"message\": \"Elasticsearch\" }'); $req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.method = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()"
    virtualbox-iso: Exception calling "GetRequestStream" with "0" argument(s): "Unable to connect
    virtualbox-iso: to the remote server"
    virtualbox-iso: At line:1 char:307
    virtualbox-iso: + ... ion/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $strea ...
    virtualbox-iso: +                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso: You cannot call a method on a null-valued expression.
    virtualbox-iso: At line:1 char:342
    virtualbox-iso: + ... req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $strea ...
    virtualbox-iso: +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    virtualbox-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
    virtualbox-iso:
    virtualbox-iso: You cannot call a method on a null-valued expression.
    virtualbox-iso: At line:1 char:381
    virtualbox-iso: + ... eam(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.G ...
    virtualbox-iso: +                                                   ~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    virtualbox-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
    virtualbox-iso:
    virtualbox-iso: Exception calling "GetResponse" with "0" argument(s): "You must provide a
    virtualbox-iso: request body if you set ContentLength>0 or SendChunked==true.  Do this by
    virtualbox-iso: calling [Begin]GetRequestStream before [Begin]GetResponse."
    virtualbox-iso: At line:1 char:398
    virtualbox-iso: + ... am.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()
    virtualbox-iso: +                                                        ~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : ProtocolViolationException
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1

**Comment by jmartin-r7** [comment]
This looks like a failure installing java earlier in the build `JAVA_HOME environment variable must be set!`.  I saw a similar issue reported as #313, I am going to close this a duplicate.

From experience I will suggest this was likely a connectivity issue with the java download you may find earlier in the log output.
