### ISSUE TITLE
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36

### ISSUE THREAD

**Issue by JohnZombie** [rapid7/metasploitable3#319]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:OSX
* Packer Version:1.2.5
* Vagrant Version:2.1.2
* VirtualBox Version:5.2.16 r123759

## Command Output

    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>exit 0
==> virtualbox-iso: Provisioning with shell script: /Users/angelo.pucine/Documents/metasploitable3/packer/templates/../../scripts/installs/setup_jenkins.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>mkdir "C:\Program Files\jenkins"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\jenkins\jenkins.war "C:\Program Files\jenkins"
    virtualbox-iso:         1 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: '"C:\Program Files\jenkins\jenkins.exe"' is not recognized as an internal or external command,
    virtualbox-iso: operable program or batch file.
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\jenkins\jenkins.exe "C:\Program Files\jenkins"
    virtualbox-iso: The system cannot find the file specified.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>"C:\Program Files\jenkins\jenkins.exe" -Service Install
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config jenkins start= auto
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by JohnZombie** [comment]
I am having this issue when trying to build metasploitable3 using the command` ./build.sh windows2008`

**Comment by jmartin-r7** [comment]
Did you attempt rebuild?  This looks like just a resource or timing issue during the build.

**Comment by JohnZombie** [comment]
Hello Jeff,

Yes, attempted it a couple of times and no luck :/. Do you guys have a ova
virtual machine file that I can just load? If not what version of vagrant
and packer do I need in order to run this build correctly?i used the latest
versions.

**Comment by busterb** [comment]
You can grab an image from vagrant cloud if you look. It's difficult to supply an .ova currently because the demo license for Windows auto expires after the image is built, so it's better to build fresh ones.

**Comment by JohnZombie** [comment]
@jmartin-r7  @busterb 

This is the new error I am having:

```
building windows 2008
Compatible version of VirtualBox found.
Virtualbox images will be built.
Compatible version of packer was found.
Correct version of vagrant was found.
Compatible version of vagrant-reload plugin was found.
Requirements found. Proceeding...
Building the Vagrant box for virtualbox...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
    virtualbox-iso: Error downloading: read tcp 10.10.10.7:63916->104.118.220.84:80: read: connection reset by peer
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.
```

**Comment by jmartin-r7** [comment]
This is further network issues, that message is a failure to complete download of the installer ISO.  We recently published the boxes to vagrant cloud.  See latest update to README.md for quick-start if you just want the boxes.  Otherwise if you want to be able to build yourself you will need a more stable internet connection.

If you pull the latest repository `master` you should simply be able to execute `vagrant up` and downloads will begin automatically from vagrant cloud.
