### ISSUE TITLE
vagrant up hangs at "configure_firewall.bat"

### ISSUE THREAD

**Issue by da667** [rapid7/metasploitable3#32]
Hello,

Commendable work on metasploitable 3. Unfortunately I seem to be having an issue provisioning the Server 2008 virtual machine. For reasons unknown to me, "vagrant up" seems to hang at executing "configure_firewall.bat". Specifically, this line:

default: Running: scripts/configs/configure_firewall.bat as c:\tmp\vagrant-shell.bat

since vagrant runs virtualbox in headless mode, I don't have access to a console to see how and what exactly the VM appears to be choking on. Also, for some reason, vagrant rdp failed to work as well. I was however able to use vagrant SSH, and TCP Forwarding to open up an RDP connection to the VM. C:\vagrant-shell.bat DOES exist, and if I run it manually as the vagrant user, it appears to execute with no problem. I can also manually execute the next two batch files "install_elasticsearch.bat" and "install_flags.bat" from the RDP session as well. I have no idea why vagrant up hangs at configure_firewall in particular.

Issue: vagrant up never completes. hangs at "default: Running: scripts/configs/configure_firewall.bat as c:\tmp\vagrant-shell.bat"

Desired outcome: configure_firewall.bat finishes executing; vagrant up finishes executing so that I have a fully functional VM to play with

Environment: 
Host OS: Windows 10 Professional x64, Anniversary Edition
Hypervisor: Virtualbox 5.0.28, with guest extensions installed
Vagrant: 1.8.1
Packer: 0.11.0

**Comment by wchen-r7** [comment]
I had that problem in this PR, but we never merged it: https://github.com/rapid7/metasploitable3/pull/28

We also never figured out the problem. strange.

**Comment by wchen-r7** [comment]
Actually, I might know why.... testing it now

**Comment by wchen-r7** [comment]
Resolved in #28
