### ISSUE TITLE
Problem with build_win2008.ps1

### ISSUE THREAD

**Issue by remix30303** [rapid7/metasploitable3#320]
## Issue Description
I have a problem with running command:  .\build_win2008.ps1. It gives me some errors. I know this issue was posted and my post is a duplicate but none of the help from previous issue helped me. 

## Host System
* OS: Windows 10
* Packer Version: 1.2.5 
* Vagrant Version: newest
* VirtualBox Version: 5.2.8

## Command Output
```
Compatible version of VirtualBox found.
Compatible version of packer found.
You cannot call a method on a null-valued expression.
At C:\Users\XXXX\Desktop\metasploitable3-master\build_win2008.ps1:18 char:5
+     $actualVersion = $actualVersion.split(".")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by jmartin-r7** [comment]
closing as addressed by #277
