### ISSUE TITLE
ubuntu1404 machine can't mount shared folder

### ISSUE THREAD

**Issue by TI-Admin** [rapid7/metasploitable3#322]
## Issue Description
On 'vagrant up' the ub1404 machine can't mount the shared folder.

## Host System
* OS: Linux Mint 18.3
* Packer Version: 1.2.5
* Vagrant Version: 2.0.4
* VirtualBox Version: 5.1.38

## Command Output

==> ub1404: Mounting shared folders...
    ub1404: /vagrant => /home/itsec/metasploitable3
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=900,gid=900 vagrant /vagrant

The error output from the command was:

mount: unknown filesystem type 'vboxsf'

**Comment by jmartin-r7** [comment]
Fixed by #324, this mount is now disabled.
