### ISSUE TITLE
proftpd init.d not found

### ISSUE THREAD

**Issue by dynomite567** [rapid7/metasploitable3#326]
## Issue Description
So, I am having problems setting up the ubuntu vm with my current pc. The issue causing this error is that proftpd cannot be found  (/etc/init.d/proftpd) when Chef is setting everything up.

## Host System
* OS: Windows 10
* Packer Version: 1.2.5
* Vagrant Version: 2.1.2
* VirtualBox Version: 5.2.16 r123759

## Command Output
The output is too long, so I made a gist here: https://gist.github.com/dynomite567/25e0a21bc699456c63f8cfc98eb20531

**Comment by jmartin-r7** [comment]
Did this occur once or on multiple attempts?  Can you verify enough storage was available?  

Looking that the chef output suggest the file was created just before the error on services start, it is possible there was simply not enough storage or there was some resource delay getting the file on disk.

**Comment by dynomite567** [comment]
Sorry for the delayed response. Yes, I have attempted multiple times, and I can assure this error pops up every time. The hard drive has a lot of free space so I cannot quite comprehend that this can be a space issue.

**Comment by dynomite567** [comment]
I decided to test this with a unix type pc (OSX) and it built it just fine, no errors. Could this issue be a windows problem for some reason?

**Comment by jmartin-r7** [comment]
I did a validation test on Windows 10 and reproduced this, I believe you are correct this is some issue in Windows 10, it is possibly a bug in packer or chef when communicating with windows.

**Comment by mekhalleh** [comment]
same error occur ...

![image](https://user-images.githubusercontent.com/5225129/46335968-5f0eac00-c63a-11e8-9321-06059daa2dac.png)

**Comment by deargle** [comment]
https://confluence.atlassian.com/kb/starting-service-on-linux-throws-a-no-such-file-or-directory-error-794203722.html

Windows is adding ^M markers to EOL in `/etc/init.d/proftpd`. ssh'ing into the failed build and running `service proftpd start` throws the same 'file not found' error.

**Comment by deargle** [comment]
I'm submitting a PR with:

```
execute 'remove_carriage_returns' do
  command "sed -i -e 's/\r//g' /etc/init.d/proftpd"
end
```
Added to both proftpd and unrealircd after the creation of the init.d files
