### ISSUE TITLE
build.sh has incorrect packer command for qemu/libvirt/kvm builds

### ISSUE THREAD

**Issue by jmpolom** [rapid7/metasploitable3#329]
## Host System
* OS: Ubuntu 18.04
* Packer Version: 1.0.4
* Vagrant Version: 2.1.2

It appears that in the packer template that build.sh calls the type of the image created for `libvirt` or `kvm` or `qemu` systems has been renamed to simply `qemu` instead of `libvirt-iso`. This presents a problem when following the instructions for automatically or manually building metasploitable 3 vagrant box images according to the instructions in the README file.

If you do `./build.sh ubuntu1404` and have libvirt installed and no VirtualBox present it will attempt to create the qemu image but it will not result in a box getting added to Vagrant because this is not an image defined in the `ubuntu_1404.json` packer template.

Instead the commands both in the README and `build.sh` script need to be updated to issue the packer build command formatted like: `packer build -only qemu packer/templates/ubuntu_1404.json`.

**Comment by jmpolom** [comment]
This is in reference to things as of commit `3040e732ba1aa868f38803964e6b3555295c8f79`

**Comment by jmartin-r7** [comment]
Per the packer documentation `qemu` is the currently supported `packer` build type.
> The Qemu Packer builder is able to create KVM and Xen virtual machine images.

https://www.packer.io/docs/builders/qemu.html

`libvirt-iso` does not exist currently exist as an official packer builder.

**Comment by jmpolom** [comment]
Taking this right out of the README:

### To build manually:

1. Clone this repo and navigate to the main directory.
2. Build the base VM image by running `packer build --only=<provider>-iso ./packer/templates/windows_2008_r2.json` where `<provider>` is your preferred virtualization platform. Currently `virtualbox`, `libvirt`, and `vmware` providers are supported. This will take a while the first time you run it since it has to download the OS installation ISO.

Now I don't know what your interpretation of that step is but to me it would seem I issue `packer build --only=libvirt-iso ./packer/templates/windows_2008_r2.json` and if this is done, it will not work because as you pointed out, `qemu` is the packer builder that's available.

If we take a look in `build.sh` as I said in my original issue at line 113 you'll see `providers="libvirt $providers"` and later on at line 143 the actual packer command gets constructed `if $packer_bin build -only $provider-iso packer/templates/$os_full.json; then`. The full packer command will be `packer build -only libvirt-iso packer/templates/ubuntu_1404.json` and this will not work because it should be `qemu` instead of `libvirt-iso`...

I tried building the qemu/libvirt image with build.sh multiple times and it would not work because of this. I eventually resorted to executing the packer command manually with the proper builder named. This worked.

Please do not close issues before you've even investigated the validity of the claim.

**Comment by jmartin-r7** [comment]
Sorry, you are correct. I misread the issue.

PR incoming if you would like to try it out.
