### ISSUE TITLE
ubuntu 14.04 box build fails if Internet access unavailable

### ISSUE THREAD

**Issue by jmpolom** [rapid7/metasploitable3#330]
This is fairly straightforward. Building the qemu/"kvm"/"libvirt" box for the ubuntu14.04 option will fail if the build system does not have Internet access. It fails at the select and install software step in the Ubuntu installer. Network connectivity is not mentioned as a dependency in the README and if it's required it should be noted. This could be an issue for cases where this image needs to be built offline in an area without network access.

**Comment by jmartin-r7** [comment]
This has been noted in the readme for 2 year.

https://github.com/rapid7/metasploitable3/blame/8be8e16218cbde94dd7c77fdf1d63c2a7f00a750/README.md#L24-L30

```
## Building Metasploitable 3
System Requirements:
* OS capable of running all of the required applications listed below
* VT-x/AMD-V Supported Processor recommended
* 65 GB Available space on drive
* 4.5 GB RAM

Requirements:

* [Packer](https://www.packer.io/intro/getting-started/install.html)
* [Vagrant](https://www.vagrantup.com/docs/installation/)
* [Vagrant Reload Plugin](https://github.com/aidanns/vagrant-reload#installation)
* [VirtualBox](https://www.virtualbox.org/wiki/Downloads), libvirt/qemu-kvm, or vmware (paid license required)
* Internet connection
```

This tool is not designed to build without internet access.
