### ISSUE TITLE
libVirt based for win2k8- ==> qemu: Timeout waiting for SSH.

### ISSUE THREAD

**Issue by Helenbj** [rapid7/metasploitable3#336]
## Issue Description
After running command `PACKER_LOG=1 packer build --only qemu packer/templates/windows_2008_r2.json`, waiting for along time, there comes the error 

> ==> qemu: Timeout waiting for SSH.
> ==> qemu: Deleting output directory...
> Build 'qemu' errored: Timeout waiting for SSH.

`
## Host System
* OS: Ubuntu16.04
* Packer Version: Packer v1.2.5
* Vagrant Version: 1.9.8
* libVirt Version:

## Command Output

> ==> qemu: Timeout waiting for SSH.
> ==> qemu: Deleting output directory...
> Build 'qemu' errored: Timeout waiting for SSH.

**Comment by Helenbj** [comment]
@Secr3ts thanks for your quick reply. However, I have clone the latest version of metasploitable3, where boot_wait in qemu configuration is set to 10m

>  "boot_wait": "10m"

I have already increase it to 20m, bellow is my qemu configuration in .json

```
    {
      "type": "qemu",
      "iso_url": "{{user `iso_url`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_checksum": "{{user `iso_checksum`}}",
      "headless": true,
      "boot_wait": "20m",
      "communicator": "ssh",
      "accelerator": "kvm",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_wait_timeout": "2h",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "disk_size": 61440,
      "format": "qcow2",
      "vm_name": "metasploitable3-win2k8",
      "floppy_files": [
        "{{user `autounattend`}}",
        "{{user `scripts_dir`}}/configs/microsoft-updates.bat",
        "{{user `scripts_dir`}}/configs/win-updates.ps1",
        "{{user `scripts_dir`}}/installs/openssh.ps1",
        "{{user `scripts_dir`}}/installs/install_dotnet45.ps1",
        "{{user `scripts_dir`}}/installs/install_wmf.ps1",
        "{{user `resources_dir`}}/certs/oracle-cert.cer",
        "{{user `resources_dir`}}/certs/gdig2.crt",
        "{{user `resources_dir`}}/certs/comodorsadomainvalidationsecureserverca.crt",
        "{{user `resources_dir`}}/certs/comodorsacertificationauthority.crt",
        "{{user `resources_dir`}}/certs/addtrust_external_ca.cer",
        "{{user `resources_dir`}}/certs/baltimore_ca.cer",
        "{{user `resources_dir`}}/certs/digicert.cer",
        "{{user `resources_dir`}}/certs/equifax.cer",
        "{{user `resources_dir`}}/certs/globalsign.cer",
        "{{user `resources_dir`}}/certs/gte_cybertrust.cer",
        "{{user `resources_dir`}}/certs/microsoft_root_2011.cer",
        "{{user `resources_dir`}}/certs/thawte_primary_root.cer",
        "{{user `resources_dir`}}/certs/utn-userfirst.cer",
        "./resources/drivers/virtio/*"
      ],
      "qemuargs": [
        ["-m", "4096"],
        ["-smp", "2"]
      ]
    }
```

With 20m, the error also occurs

```
==> qemu: Timeout waiting for SSH.
==> qemu: Deleting output directory...
Build 'qemu' errored: Timeout waiting for SSH.
```

**Comment by Secr3ts** [comment]
Ew... I am very sorry i don't use Qemu i have only Windows ( usb key dead you know ). But why you don't try to use VmWare or VirtualBox ?

**Comment by Helenbj** [comment]
@Secr3ts Because there is a project based on KVM needs VNC to access every vm, and it's a big task to transfer everything to VmVare or VirtualBox. Anyhow thanks for your help.

**Comment by Secr3ts** [comment]
Oh okay i *nearly* understand . Me the build is working perfectly (i fixed disk error ) in VmWare. Building take a long time phew. 
Cheers,
Secr3ts.

**Comment by Helenbj** [comment]
I have already build, add and vagrant up ub1404 finally, but cannot figure out win2k8 right now.

**Comment by jmartin-r7** [comment]
Sorry for the long delay getting this looked at.

Please try building with `./build.sh windows2008` or executing `./packer/scripts/virtio-win-drivers.sh` before attempting the packer command.  The `qemu` build still needs some documentation for direct packer builds. There are drivers needed that the build script actually downloads to the local environment here:

https://github.com/rapid7/metasploitable3/blob/f9ce0e42dcff33789a90ffa14071ef05c898157e/build.sh#L114-L115

Testing shows that with a clean checkout of the repository attempting to build immediately with packer commands will result in starting the windows VM instance however the install process does not load the disk drivers to be able to interact with `virtio` disks controllers so it hangs causing the timeout.

**Comment by jmartin-r7** [comment]
Closing as a tested solution is provided in comments.

**Comment by mathiasconradt** [comment]
I'm getting the same error (on Kali Linux), and the provided solution in above comment has on effect, as it already exists.

```
$./packer/scripts/virtio-win-drivers.sh
.virtio-stable.vfd already exists, skipping download.

```
