### ISSUE TITLE
Strange problems after create ub1404 VM succsssfully

### ISSUE THREAD

**Issue by Helenbj** [rapid7/metasploitable3#337]
## Issue Description
I create ub1404 vm using `vagrant up` successfully, and can see a vm called metasploitable3-ub1404 via virt-manager.
However, after click into the vm without any change, there are three problems.

**1. I cannot ping 127.0.0.1 or its ip and other vms in same LAN cannot ping it either, while the ub1404 vm can ping other vms in same LAN.  I have check the value in /proc/sys/net/ipv4/icmp_echo_ignore_all is 0, so the ub1404 vm will respond ping request. The question is if metasploitable3 configured inside not respond ping request from itself or others?**
**2. When I run command `mysql`,  there's an error:**

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

Then I run command ps `aux |grep mysql`, and there is an process record contains:

> /usr/sbin/mysqld --defaults-file=/etc/mysql-default/my.cnf

So I check /etc/mysql-default/my.cnf, and found there are socket configurations of client/mysqld/mysqld_safe:

> socket   = /run/mysql-default/mysqld.sock

while there is a file /etc/mysql/debian.cnf has socket configure too:

> socket      = /var/run/mysqld/mysqld.sock

I havn't change any configuration, my question is why mysql even cannot find the right sock to boot up?

**3. When I use the `auxiliary/scanner/mysql/mysql_login` module of metasploit in Kali, and `run`, there comes error:**

> Unsupported target version of ping.

or

> Unsupported target version of MySQL detected. Skipping.

## Host System

- OS: Ubuntu16.04
- Packer Version: Packer v1.2.5
- Vagrant Version: 1.9.8
- libVirt Version:

## Command Output
Refer to Issue Description.

@OJ @mattreduce @FireFart @Chiggins @bcoles Please help me out, thanks in advance.

**Comment by aether0011** [comment]
Hi, did you manage to fix this?

**Comment by Sliim** [comment]
For the ping issue check iptables rules in ub1404 machine: https://github.com/rapid7/metasploitable3/issues/393 https://github.com/rapid7/metasploitable3/pull/394

**Comment by aether0011** [comment]
Thanks, Sliim. I managed to fix it by editing the network on VirtualBox.
