### ISSUE TITLE
 Builds finished but no artifacts were created

### ISSUE THREAD

**Issue by VenkatRohith** [rapid7/metasploitable3#338]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:
-------------------------------------------------------------------------------------------------------------
In Windows Powershell

    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2350)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm metasploitable3-win2k8 --memory 4096
    virtualbox-iso: Executing: modifyvm metasploitable3-win2k8 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: Could not launch a process for the machine 'metasploitable3-win2k8' (VERR_UNRESOLVED_ERROR)
==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee IUnknown
==> virtualbox-iso: VBoxManage.exe: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 600 of file VBoxManageMisc.cpp
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage.exe: error: Could not launch a process for the machine 'metasploitable3-win2k8' (VERR_UNRESOLVED_ERROR)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 600 of file VBoxManageMisc.cpp

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: Could not launch a process for the machine 'metasploitable3-win2k8' (VERR_UNRESOLVED_ERROR)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 600 of file VBoxManageMisc.cpp

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\Venkat Rohith\Documents\metasploitable3\build.ps1:150 char:10
+          throw "Error building the Vagrant box using Packer. Please c ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.
-------------------------------------------------------------------------------------------------------------------
![error_li](https://user-images.githubusercontent.com/30123945/45305546-2d715c00-b538-11e8-867f-8adaccced372.jpg)

**Comment by jmartin-r7** [comment]
The message at the end of the build stating `finished` is simply noting the script has completed.

It looks like you attempted to execute the full build locally.  The output you provide suggests you have a configuration issue with virtualbox.  A command `packer` tried to execute using `VBoxManage.exe` failed.  Looking closer the failure is for startup of the VM packer expects to build.  This could happen for many reasons however they are all user/environment specific.  You could try the alternative direct packer build method noted in the README.md to execute build manually.

If you are just looking to get the build images vs build and modify them yourself you can also use the quick-start method in README.md.

**Comment by VenkatRohith** [comment]
> The message at the end of the build stating `finished` is simply noting the script has completed.
> 
> It looks like you attempted to execute the full build locally. The output you provide suggests you have a configuration issue with virtualbox. A command `packer` tried to execute using `VBoxManage.exe` failed. Looking closer the failure is for startup of the VM packer expects to build. This could happen for many reasons however they are all user/environment specific. You could try the alternative direct packer build method noted in the README.md to execute build manually.
> 
> If you are just looking to get the build images vs build and modify them yourself you can also use the quick-start method in README.md.
