### ISSUE TITLE
Fix: ./build.sh: line 47: [[: 1,: syntax error: operand expected (error token is ",")

### ISSUE THREAD

**Issue by beechfuzz** [rapid7/metasploitable3#339]
## Issue Description
While running `./build.sh ubuntu1404`, the build script outputs the following errors:

`./build.sh: line 47: [[: 1,: syntax error: operand expected (error token is ",")`
`./build.sh: line 51: [[: 1,: syntax error: operand expected (error token is ",")`

This is due to the build.sh script not cutting out the "," when it compares the vagrant-reload plugin version on line 121.

## Fix

On Line 121, add ` | tr -d ','` immediately after `| tr -d ')'`.  

So, Line 121 will go from: 
`if compare_versions $(vagrant plugin list | grep 'vagrant-reload' | cut -d' ' -f2 | tr -d '(' | tr -d ')') $min_vagrantreload_ver false; then` 

To:
`if compare_versions $(vagrant plugin list | grep 'vagrant-reload' | cut -d' ' -f2 | tr -d '(' | tr -d ')' | tr -d ',') $min_vagrantreload_ver false; then`

**Comment by azerhouani** [comment]
this syntax error still exist on the master branch in line 128.

**Comment by dloco01** [comment]
work thank you very much

**Comment by jmartin-r7** [comment]
Fixed by #370
