### ISSUE TITLE
Build Script build_win2008.ps1 Failing on Syntax Issue

### ISSUE THREAD

**Issue by decidedlygray** [rapid7/metasploitable3#34]
# Issue Description:

Line 114 of `build_win2008.ps1` executes this command:
`cmd.exe /c vagrant box add windows_2008_r2_virtualbox.box --name metasploitable3`

The result in my environment (Win7x64) is:
```
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant: unrecognized option `--name'
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/WORKSPACE/vm/metasploitable3_build/metasploitable3/Vagrantfile
Line number: 0
Message: GetoptLong::InvalidOption: unrecognized option `--name'
```

It appears it doesn't like the --name option, which is odd considering Vagrant's own documentation on that flag (https://www.vagrantup.com/docs/cli/box.html#_name_VALUE).

There is also the a very similar command listed on step 3 of the wiki here (includes an equals sign though): https://github.com/rapid7/metasploitable3/wiki

# Issue Resolution:

The fix is to adjust the syntax of the command, not using the invalid '--name' flag:
`cmd.exe /c vagrant box add metasploitable3 windows_2008_r2_virtualbox.box`

Luckily this is the last step, and the build has technially already completed successfully. So you can just run that command (`vagrant box add metasploitable3 windows_2008_r2_virtualbox.box`) and you're all set.

I know some individuals are currently using either vagrant 1.8.1 or 1.8.6. This issue appears across both versions.

I wanted to put this here because it took me a bit of tinkering to figure out how to fix it. It wasn't until I stumbled on a tutorial on scotch.io that used the alternate syntax that I got it working.

Please validate in a clean environment. If others run into this, I'm happy to submit a PR. Tested on a clean Win7 x64. It's entirely possible I'm doing something wrong, but I can't figure out what that could be.

Cheers

**Comment by jbarnett-r7** [comment]
We're seeing this locally too. Take the --name parameter out does fix it, but I'm not sure that's the best solution. The vagrant box will just have a generic name making it hard to identify. I'm going to look into finding a way to set the name in the script so we can easily identify the box.

**Comment by binarycanary** [comment]
If you use this syntax, are you seeing it named as "metasploitable3"?:

vagrant box add metasploitable3 windows_2008_r2_virtualbox.box

**Comment by jbarnett-r7** [comment]
Yup, that seems to do it. Thank you for the hint! I'll fix that in the build script so we can close this out.
