### ISSUE TITLE
jmx.exe flagged by mcafee as a trojan

### ISSUE THREAD

**Issue by sh33pd0g** [rapid7/metasploitable3#346]
While cloning, Mcafee flagged jmx.exe as a trojan (repository path: /metasploitable3/resources/jmx/). VirusTotal also says jmx.exe is malicious.

## Host System
OS: MacOS High Sierra 10.13.6
Anti-Virus: McAfee End Point Security 10.2.3 

## Command Input
git clone https://github.com/rapid7/metasploitable3.git

## Command Output
Cloning into 'metasploitable3'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 4361 (delta 0), reused 0 (delta 0), pack-reused 4360
Receiving objects: 100% (4361/4361), 248.03 MiB | 1.96 MiB/s, done.
Resolving deltas: 100% (2185/2185), done.
Checking out files: 100% (488/488), done.

## More Detail
https://www.virustotal.com/#/file/0e8fce5694924f7dacdcfe11ca7cc7c235c2f6957f19d9f5f697c9544cb4d71c/detection
<img width="802" alt="screen shot 2018-11-13 at 2 16 01 pm" src="https://user-images.githubusercontent.com/45014554/48437707-188b9180-e750-11e8-8988-a7dad196b9cf.png">

**Comment by jmartin-r7** [comment]
This is false-positive mirroring issue #280, the binary is a service executable to provide for one of the intended vulnerable configurations in the windows host.
