### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054

### ISSUE THREAD

**Issue by hasinhafiz1** [rapid7/metasploitable3#351]
Description
after issuing vagrant up win2k8, the download fails

**Comment by jmartin-r7** [comment]
A simple search for this error `SSL_ERROR_SYSCALL, errno 10054` suggests this was a network connectivity failure.  Looks like some have had luck with updating vagrant.

Closing as not a issue in metasploitable3.
