### ISSUE TITLE
Metasploitable3 ub1404 stuck for hours at VirtualBox Guest Additions: Starting. (Windows 10)

### ISSUE THREAD

**Issue by bdorr1105** [rapid7/metasploitable3#352]
# Issue
Will not move past VirtualBox Guest Additions: Starting. I have done this with the pre-built method as well as the git clone method. Both get stuck in the same exact spot. I was not able to find anyone else with this issue

## Host System
* OS: Windows 10 version 1803 (OS Build 17134.441)
* Packer Version: 1.3.3
* Vagrant Version: 2.2.2
* VirtualBox Version: 5.2.22

## Command Output

> $ curl -O https://raw.githubusercontent.com/rapid7/metasploitable3/master/Vagrantfile && vagrant up
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1550  100  1550    0     0   3100      0 --:--:-- --:--:-- --:--:--  3100
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Importing base box 'rapid7/metasploitable3-ub1404'...
==> ub1404: Matching MAC address for NAT networking...
==> ub1404: Checking if box 'rapid7/metasploitable3-ub1404' is up to date...
==> ub1404: Setting the name of the VM: Metasploitable3-ub1404
==> ub1404: Vagrant has detected a configuration issue which exposes a
==> ub1404: vulnerability with the installed version of VirtualBox. The
==> ub1404: current guest is configured to use an E1000 NIC type for a
==> ub1404: network adapter which is vulnerable in this version of VirtualBox.
==> ub1404: Ensure the guest is trusted to use this configuration or update
==> ub1404: the NIC type using one of the methods below:
==> ub1404:
==> ub1404:   https://www.vagrantup.com/docs/virtualbox/configuration.html#default-nic-type
==> ub1404:   https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type
==> ub1404: Clearing any previously set network interfaces...
==> ub1404: Preparing network interfaces based on configuration...
    ub1404: Adapter 1: nat
    ub1404: Adapter 2: hostonly
==> ub1404: Forwarding ports...
    ub1404: 22 (guest) => 2222 (host) (adapter 1)
==> ub1404: Running 'pre-boot' VM customizations...
==> ub1404: Booting VM...
==> ub1404: Waiting for machine to boot. This may take a few minutes...
    ub1404: SSH address: 127.0.0.1:2222
    ub1404: SSH username: vagrant
    ub1404: SSH auth method: password
    ub1404:
    ub1404: Inserting generated public key within guest...
    ub1404: Removing insecure key from the guest if it's present...
    ub1404: Key inserted! Disconnecting and reconnecting using new SSH key...
==> ub1404: Machine booted and ready!
[ub1404] No installation found.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
The following packages will be upgraded:
  linux-headers-3.13.0-24-generic
1 upgraded, 0 newly installed, 0 to remove and 165 not upgraded.
Need to get 708 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main linux-headers-3.13.0-24-generic amd64 3.13.0-24.47 [708 kB]
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Fetched 708 kB in 0s (1,085 kB/s)
(Reading database ... 97513 files and directories currently installed.)
Preparing to unpack .../linux-headers-3.13.0-24-generic_3.13.0-24.47_amd64.deb ...
Unpacking linux-headers-3.13.0-24-generic (3.13.0-24.47) over (3.13.0-24.46) ...
Setting up linux-headers-3.13.0-24-generic (3.13.0-24.47) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 3.13.0-24-generic /boot/vmlinuz-3.13.0-24-generic
Copy iso file C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.2.22 - guest version is unknown
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.22 Guest Additions for Linux........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.  This may take a while.
VirtualBox Guest Additions: Starting. **<-- STUCK FOR HOURS**

>

**Comment by jmartin-r7** [comment]
#321, disabled installing vm-tools addition on the ubuntu box due needed for compatibility with an older kernel.  It looks like vagrant or virtualbox on your env may be set to auto-install these tools.  This should be disabled in your configuration.

I suspect you have something like the [vagrant-vbguest plugin](https://dzone.com/articles/automatically-download-and) installed, if so please modify your local `Vagrantfile` as per the link to disable the automatic attempt to install tools on the VM.

Closing this as not a bug in Metasploitable3.
