### ISSUE TITLE
Glassfish4 Download Causes Win2k8 Build to Abort

### ISSUE THREAD

**Issue by Eofric** [rapid7/metasploitable3#355]
## Issue Description
This is related to issue #69 and I do have a solution.  Vagrant reports a download exception for glassfish, then complains that it can't find the zip file on Windows (because it didn't download) and then aborts a minute or so later.
The problem seems to be an inability to achieve a successful download of the glassfish4 zip file from http://download.java.net/glassfish/4.0/release/.  I tried downloading the file directly and each time, I only got a partial download of the file.

##Solution
Download glassfish-4.0.zip from https://download.oracle.com/glassfish/4.0/release/index.html and put the zip file into your metaploitable3/resources/glassfish folder.  Edit the setup_glassfish.bat file (scripts/installs) so it looks like this:

mkdir C:\glassfish
copy /Y "C:\vagrant\resources\glassfish\glassfish-4.0.zip" "C:\Windows\Temp\glassfish4.zip"
cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"
copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\admin-keyfile"
copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\domain.xml"
cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"
net start domain1
powershell -Command "Start-Sleep -s 10"
net stop domain1
icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
sc config "domain1" obj= "NT Authority\LOCAL SERVICE"

I was able to achieve a successful build using this approach.

## Host System
* OS: MacOS Mojave 10.14.2
* Packer Version: 1.3.3

* Vagrant Version: 2.2.2
* VirtualBox Version: 6.0

## Command Output
virtualbox-iso: C:\Users\vagrant>mkdir C:\glassfish
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')"  0<NUL
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "An exception occurred
    virtualbox-iso: during a WebClient request."
    virtualbox-iso: At line:1 char:1
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('http://download.java. ...
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: C:\Windows\Temp\glassfish4.zip

**Comment by jmartin-r7** [comment]
This sounds like a problem with internet connectivity on the VM during the build.  The suggested solution is a reasonable personal workaround but not something the project itself should do.

It might be interesting to identify all the remote resources downloaded during the build and to offer an additional script to build a local cache that could be used during the build when a `flag` is set.  Another expansion on the idea would be a tool that provides a menu for the user to select remote objects they would like to cache locally.

**Comment by Eofric** [comment]
Quite possibly.  But of course there are multiple nodes in internet connectivity, not just my end.  I have a pretty good broadband service.  Everything other resource downloaded without issue.  I posted the solution because I have seen others running into the same problem.  I just hope that where there is a problem, the solution helps.
I think your idea of caching the remote resources prebuild has merit.

**Comment by chrisarm** [comment]
@Eofric Your solution helped. Thanks!

**Comment by busterb** [comment]
There's not much we can do here for now, but thanks for the workaround!

**Comment by mathiasconradt** [comment]
> This sounds like a problem with internet connectivity on the VM during the build. 

I'd say it's more of an issue the download servers. I had the same problem with other downloadables, where I then downloaded them manually, put them on one of my servers, and everything went smoothly. So definitely not an issue of my inet connection but more of the download server imo.

See https://github.com/rapid7/metasploitable3/issues/453#issuecomment-595798978 where I had exactly the same problems with the "ManageEngine_DesktopCentral.exe" download.
