### ISSUE TITLE
Win2k8 does not install correctly

### ISSUE THREAD

**Issue by AumCoin** [rapid7/metasploitable3#359]
## Issue Description
I am on a Windows 7 machine.  I used Gnu curl to download metasploitable, using the commands listed in the README.  Everything seemed to go fine.  I spent several hours downloading and installing the mountain of software needed to make it run.  Everything seemed fine until I tried to actually launch the VMs.

Every time Win2k8 launches it says it's already provisioned, though everything seems to work fine.  On the initial launch I noticed that a number of scripts that should have been in C:\startup were giving file not found.  I confirmed they are not present in the VM.  When I launch the VM I am told there is an IP address conflict.  If I reboot the IP address conflict goes away.  I'm not sure what happened here, but I'm pretty sure I did everything as instructed.  I hope I didn't just waste 5 hours...

## Host System
* OS:  Windows 7 SP1
* Packer Version:  Don't know what this is
* Vagrant Version:  Latest as of 1/20
* VirtualBox Version:  Latest as of 1/20

## Command Output

I can no longer access the initial output that occurs on a fresh install, indicating that several .bat files are not in C:\startup as they are supposed to be.

Not sure if this is expected:
==> win2k8: Machine booted and ready!
==> win2k8: Machine already provisioned. Run `vagrant provision` or use the `--p
rovision`
==> win2k8: flag to force provisioning. Provisioners marked to run always will s
till run.

I also get an IP address conflict message on booting Win2k8.  This message is very well known

**Comment by usmcfiredog** [comment]
You do need to download and install packer. It can be downloaded from packer.io. This is required in order to build the VM

**Comment by jmartin-r7** [comment]
Having used the quick-start method your box images should have come from vagrantcloud and `vagrant box list` should show them.  

`vagrant up` where you downloaded the `Vagrantfile` will provision the VMs and start them.

`vagrant global-status` may show you the running VMs if they are already provisioned.

The files you are seeing the VM complain about are actually in the initial box, however they are deleted by first `vagrant up` as the box deploys.

https://github.com/rapid7/metasploitable3/blob/ad11cefb4e1da337fc093049b63e28acd1d9f3e2/Vagrantfile#L40-L42

As to the IP conflict that is likely #328, a known issue where the `Vagrantfile` attempts to assign a specific IP to the ubuntu image for an address range that is not consistent on all virtual enviornment installs. 

https://github.com/rapid7/metasploitable3/blob/ad11cefb4e1da337fc093049b63e28acd1d9f3e2/Vagrantfile#L12

This address is used to attempt to mount a share from the ubuntu VM into the 2k8 system and simulate information obtainable on access to a machine on the network.

Disabling these in the `Vagrantfile` may address your error messages.

**Comment by AumCoin** [comment]
Sorry, you say "The files you are seeing the VM complain about are actually in the initial box, however they are deleted by first vagrant up as the box deploys."

When I was trying to build the images, I got the messages that they had completed building successfully, and it was only after trying to run the boxes again with "vagrant up" that I got those errors.  Is it correct to say (if I understand you correctly) that the scripts were already applied and deleted, and the error message I'm getting is meaningless?

**Comment by AumCoin** [comment]
I'm getting this error, "Linux host not available", and also none of my boxes can ping each other despite being on the same subnet.  I get this on OSX, Windows, Linux, when either building or curl'ing the boxes.  I have tested every combination and in every scenario I encounter various combinations of these issues.

Though I have the boxes up and running I have no way of determining whether anything is set up as it should be.  There were various errors or things that looked like errors during installation, but the items still installed so everything should be ok?  I have no shares on the Windows box.

I also installed a Kali box to pentest against these Metasploitable boxes.  My Kali box also cannot ping the Metasploitable boxes, even though it is also on the same subnet as both of those boxes.

Am I set up right?  Any way to be sure?  How do I make these machines talk to each other?

**Comment by AumCoin** [comment]
I read that Metasploitable can only use NAT with VirtualBox, which I guess means the machines can't ping each other (even though several metasploitable tutorials say to have one machine ping the other)?  Does that literally mean my only option for pentesting with Kali against Metasploitable is to use Kali as a host OS, since there is no way for me to communicate with Metasploitable machines with anything by the host OS?

**Comment by jmartin-r7** [comment]
Yes, if you stop and start the images but do not call `vagrant destroy` the files will already be deleted from the provisioned VM and the message can be ignored.  

As to communication between VMs is all dependent on your local virtualization configuration.  The default selected networks on `vagrant up` should match to defaults for a new virtualbox install and link VM interfaces to your internal NAT network.  This would mean you should be able to ping the ip addresses reported by `ipconfig` and `ifconfig` of the win2k8 and ub1404 respectively from terminals inside the VMs as well as from the virtualization host.  Network configuration is unique to each host however and configurations may not always match.  Adjustments to fine tune networking for vagrant deployed hosts are left the end user as this project cannot anticipate every possible scenario.

**Comment by jmartin-r7** [comment]
Closing as learning opportunity about `vagrant` and VM networking.
