### ISSUE TITLE
Not Working Right Out of the Box on OSX

### ISSUE THREAD

**Issue by AumCoin** [rapid7/metasploitable3#360]
## Issue Description
I could not get Metasploitable to install the batch scripts for the Windows machine properly.  At the time I was on Windows 7.  I installed Debian on my laptop instead, and then installed Metasploitable on that and my MacBook for good measure.  I let it spend what seemed like hours running all these scripts and configuring the machines.

On my MacBook it tells me it's good to go, then I do 'vagrant up' and get a message that it can't copy setup_linux_shares.bat to C:\Windows because the source folder does not exist.

## Host System
* OS:  MacOS High Sierra
* Packer Version:  Latest
* Vagrant Version:  2.1.2
* VirtualBox Version: 5.2.16

## Command Output
==> win2k8: Importing base box 'rapid7/metasploitable3-win2k8'...
==> win2k8: Matching MAC address for NAT networking...
==> win2k8: Setting the name of the VM: metasploitable3_win2k8_1548172743310_97576
==> win2k8: Fixed port collision for 22 => 2222. Now on port 2200.
==> win2k8: Clearing any previously set network interfaces...
==> win2k8: Found default DHCP server from initial VirtualBox install. Cleaning it up...
==> win2k8: Preparing network interfaces based on configuration...
    win2k8: Adapter 1: nat
    win2k8: Adapter 2: hostonly
==> win2k8: Forwarding ports...
    win2k8: 3389 (guest) => 3389 (host) (adapter 1)
    win2k8: 22 (guest) => 2200 (host) (adapter 1)
    win2k8: 5985 (guest) => 55985 (host) (adapter 1)
    win2k8: 5986 (guest) => 55986 (host) (adapter 1)
==> win2k8: Running 'pre-boot' VM customizations...
==> win2k8: Booting VM...
==> win2k8: Waiting for machine to boot. This may take a few minutes...
    win2k8: WinRM address: 127.0.0.1:55985
    win2k8: WinRM username: vagrant
    win2k8: WinRM execution_time_limit: PT2H
    win2k8: WinRM transport: negotiate
==> win2k8: Machine booted and ready!
==> win2k8: Checking for guest additions in VM...
==> win2k8: Setting hostname...
ls
==> win2k8: Configuring and enabling network interfaces...
==> win2k8: Running provisioner: shell...
    win2k8: Running: inline PowerShell script
    win2k8: C:\Windows\system32>netsh advfirewall set allprofiles state on 
    win2k8: Ok.
==> win2k8: Running provisioner: shell...
    win2k8: Running: inline PowerShell script
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 8484 for Jenkins" dir=in action=allow protocol=TCP localport=8484 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 8282 for Apache Struts" dir=in action=allow protocol=TCP localport=8282 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 80 for IIS" dir=in action=allow protocol=TCP localport=80 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 4848 for GlassFish" dir=in action=allow protocol=TCP localport=4848 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 8080 for GlassFish" dir=in action=allow protocol=TCP localport=8080 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 8585 for Wordpress and phpMyAdmin" dir=in action=allow protocol=TCP localport=8585 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Java 1.6 java.exe" dir=in action=allow program="C:\openjdk6\openjdk-1.6.0-unofficial-b27-windows-amd64\jre\bin\java.exe" enable=yes 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 3000 for Rails Server" dir=in action=allow protocol=TCP localport=3000 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 8020 for ManageEngine Desktop Central" dir=in action=allow protocol=TCP localport=8020 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 8383 for ManageEngine Desktop Central" dir=in action=allow protocol=TCP localport=8383 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 8022 for ManageEngine Desktop Central" dir=in action=allow protocol=TCP localport=8022 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 9200 for ElasticSearch" dir=in action=allow protocol=TCP localport=9200 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Open Port 161 for SNMP" dir=in action=allow protocol=UDP localport=161 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed port 445 for SMB" dir=in action=block protocol=TCP localport=445 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed port 139 for NetBIOS" dir=in action=block protocol=TCP localport=139 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed port 135 for NetBIOS" dir=in action=block protocol=TCP localport=135 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed Port 3389 for Remote Desktop" dir=in action=block protocol=TCP localport=3389 
    win2k8: Ok.
    win2k8: C:\Windows\system32>netsh advfirewall firewall add rule name="Closed Port 3306 for MySQL" dir=in action=block protocol=TCP localport=3306 
    win2k8: Ok.
==> win2k8: Running provisioner: shell...
    win2k8: Running: inline PowerShell script
    win2k8: C:\Windows\system32>copy C:\vagrant\scripts\installs\setup_linux_share.bat C:\Windows 
    win2k8: The system cannot find the path specified.
    win2k8: C:\Windows\system32>reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Run /v share /t REG_SZ /d "C:\Windows\setup_linux_share.bat" /f 
    win2k8: The operation completed successfully.
==> win2k8: Running provisioner: shell...
    win2k8: Running: inline PowerShell script
    win2k8: "Linux host not available."
==> win2k8: Running provisioner: shell...
    win2k8: Running: inline PowerShell script

Again, these are just the results from my MacBook.  I had similar problems yesterday on my Windows machine, for which I opened an issue.  You told me to install Packer, after which a fresh reinstall did not resolve the issue.  I have now installed it on two more OSes.  The MacBook is not working.  Haven't tried Ubuntu yet, but I will update when I have had a chance to try that.  I would like to get Metasploitable3 running on some OS some time.  I have now spent a lot of hours on what seems like it should be pretty simple.  I would really appreciate it if anyone could please help me get this working.

**Comment by AumCoin** [comment]
If I use the Quick Start directions (which also did not work on Windows 7), is it still going to have to run all these scripts every time I do vagrant up, or will it just work without all this mess of bash files not beung present?

**Comment by AumCoin** [comment]
I was not able to build the images but I was able to download them from Rapid7 with the curl command given.  Do these already have all the security holes/scripts applied?

**Comment by AumCoin** [comment]
Sorry if that's a stupid question.  Everything seems to have worked right following the Quick Start, and as long as these images are complete with security holes (don't know why they wouldn't be), then I think these 2 issues can be closed (thanks for the help).

**Comment by AumCoin** [comment]
Also wondering, when I do "vagrant up" on my Linux machine (not the same as described above), I get "Linux host not available."  I'm assuming this is going to mess up some critical functionality of Metasploitable.

Is there some way I can fix this?  I have now tried numerous times to get this running on OSX, Linux, Windows.  The only machine it *seems* to be working on is OSX.  I *could* just use my work laptop forever on this, but it would be really cool to also have it working on my Dell laptop, which is running Debian and Windows, neither of which work at all either by building the boxes or 'curl'ing them.  It seems to me this software is broken out of the box on Linux and Windows, as these are vanilla Debian and Windows 7 with nothing extra installed.  If I can fix this error then at least I can use the software on Linux.

**Comment by AumCoin** [comment]
Ok, this is ridiculous.  You can disregard all previous messages.  When I was installing I got "Linux host not available".  Doing some research, one of these Bash scripts that is not working is supposed to set up a share on my Windows machine for W: , targeting the Linux machine with an IP of 172.28.128.3.  I look on my Ubuntu box and I see the IP is in fact 172.28.128.3.  I look at the Windows box and see the IP is 172.28.128.4.  Somehow the Windows box cannot ping the Linux box.  Obviously it cannot create a share.

I have tried installing metasploitable3 on Windows 7, Debian, and OSX, each first by building the images, then by 'curl'ing them.  Only OSX went off without a hitch, but now I can see that it still is not set up correctly.  I'm totally at a loss here how someone is supposed to learn pentesting from this.  I have already spent around 15+ hours just trying to get these VMs working right.  The tutorial I am using to learn pen-testing says I need Metasploitable.

What am I supposed to do here, to get a working environment?  Please tell me what hardware/OS/software combination, exactly, can produce the two boxes as intended, with all of the security flaws applied?  Is there any way to actually get metasploitable3 working on any machine, with any OS, and any combination of Virtualbox/Packer/Vagrant?  I have had zero success so far.

**Comment by AumCoin** [comment]
There must be an easier way that is less bug-prone.  Please help me to get a working Metasploitable environment up.  I have tried every method of obtaining the boxes on every platform, and still have yet to produce a working environment.

**Comment by AumCoin** [comment]
Trying to follow this guide:

https://www.tutorialspoint.com/kali_linux/index.htm

Essentially it requires me to have a Kali box and the Metasploitable boxes running so I can scan them, hack them, etc.  Yet, I cannot ping them.  Both are on the 127.28.128.0/24 net and cannot ping each other.  The Kali box I created cannot see them.  All machines also show one of the adapters having 10.0.2.15 assigned to them (no idea at all where this is coming from).  Are these machines all supposed to be talking?  What is wrong here?

**Comment by jmartin-r7** [comment]
This looks to duplicate #359 closing.  See comments there about virtualization host network.  Will do some additional independent validation and comment there with fundings.
