### ISSUE TITLE
Error building vagrant box using Packer

### ISSUE THREAD

**Issue by S4lm0r3j0** [rapid7/metasploitable3#363]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Windows 10
* Packer Version: 1.3.3
* Vagrant Version: 2.2.3
* VirtualBox Version: 6.0.2

## Command Output

==> virtualbox-iso: Retrieving ISO

1 items:  87.75 MiB / 564.00 MiB  3m42s

    virtualbox-iso: Error downloading: unexpected EOF

==> virtualbox-iso: ISO download failed.

Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:

--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.

Error building the Vagrant box using Packer. Please check the output above for any error messages.

En C:\Users\usuario\EdU\Distros\metasploitable3-master\build.ps1: 150 Carácter: 10

+          throw "Error building the Vagrant box using Packer. Please c ...

+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException

    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by jmartin-r7** [comment]
Based on the details posted this is an failure to download related to your internet access.
> ==> virtualbox-iso: Retrieving ISO
>
>1 items: 87.75 MiB / 564.00 MiB 3m42s
>
>```
>virtualbox-iso: Error downloading: unexpected EOF
>```
>==> virtualbox-iso: ISO download failed.
>
>Build 'virtualbox-iso' errored: ISO download failed.
>
>==> Some builds didn't complete successfully and had errors:

**Comment by faisalkhan0071** [comment]
how to solve it then?

**Comment by Onyeze-code** [comment]
How do we resolve this? I have the same issues as well.
