### ISSUE TITLE
vrgant up VBoxManage.exe: error: Could not rename the directory 'C:\Users\578040\VirtualBox VMs\metasploitable3-ub1404_1549010688782_26729' to 'C:\Users\578040\VirtualBox VMs\Metasploitable3-ub1404' to save the settings file (VERR_ALREADY_EXISTS)

### ISSUE THREAD

**Issue by ganguoyin** [rapid7/metasploitable3#365]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:windows10
* Packer Version:packer_1.3.3_windows_amd64
* Vagrant Version vagrant_2.2.3_x86_64
* VirtualBox Version:VirtualBox-6.0.4-128413-Win

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.
PS C:\Users\578040\desktop\metasploitable3> vagrant up ub1404
Bringing machine 'ub1404' up with 'virtualbox' provider...
==> ub1404: Importing base box 'rapid7/metasploitable3-ub1404'...
==> ub1404: Matching MAC address for NAT networking...
==> ub1404: Checking if box 'rapid7/metasploitable3-ub1404' version '0.1.12-weekly' is up to date...
==> ub1404: Setting the name of the VM: Metasploitable3-ub1404
The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\578040\VirtualBox VMs\metasploitable3-ub1404_1549011344367_56602' to 'C:\Users\578040\VirtualBox VMs\Metasploitable3-ub1404' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3194 of file VBoxManageModifyVM.cpp

**Comment by jmartin-r7** [comment]
> The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

You should just need to cleanup your Virtualbox environment.

**Comment by Rish00760** [comment]
I am having the same issue. i deleted **metasploitable3-ub1404_1549011344367_56602** several times from the C:\Users\578040\VirtualBox VMs and also removed it from the virtualox. but even after that whenever i am trying to bring vagrant up, it is showing me the same error:

BoxManage.exe: error: Could not rename the directory 'C:\Users\578040\VirtualBox VMs\metasploitable3-ub1404_1549011344367_56602' to 'C:\Users\578040\VirtualBox VMs\Metasploitable3-ub1404' to save the settings file (VERR_ALREADY_EXISTS)

I even re-installed virtual box and got the same error after redoing "Vagrant Up"

Also, why is it creating Metasploitable3-ub1404 when we are looking to have a windows_2008 build of metasploitable3??

Any suggestions/solutions are most welcome.

Thanks!

**Comment by jmartin-r7** [comment]
The vagrant file provided in the project provides for two vulnerable VMs, one for windows 2008 and another on ubuntu 14.04.  To bring up just one VM you need to limit the vagrant command.  `vagrant up win2k8` will start just the window VM [see](https://github.com/rapid7/metasploitable3/blob/6b0bac0626bbd5895b23459d66e57882c44aed2e/Vagrantfile).

As to the env issue, this is all virtualbox, vagrant and permissions related, you need to cleanup the virtualbox catalog, vagrant box list and your filesystem.
