### ISSUE TITLE
Autobuild on Windows host of Ubuntu guest fails

### ISSUE THREAD

**Issue by AktivMeasures** [rapid7/metasploitable3#372]
## Issue Description
Windows build completed successfully. Ubuntu build fails near what seems to be the end of the process.

## Host System
* OS: Windows 10
* Packer Version: Most recent
* Vagrant Version: Most recent
* VirtualBox Version: Most recent

## Command Output
    virtualbox-iso:     Compiled Resource:
    virtualbox-iso:     ------------------
    virtualbox-iso:     # Declared in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/flags.rb:38:in `from_file'
    virtualbox-iso:
    virtualbox-iso:     bash("build docker image for 7 of diamonds") do
    virtualbox-iso:       action [:run]
    virtualbox-iso:       default_guard_interpreter :default
    virtualbox-iso:       command nil
    virtualbox-iso:       backup 5
    virtualbox-iso:       returns 0
    virtualbox-iso:       user nil
    virtualbox-iso:       interpreter "bash"
    virtualbox-iso:       declared_type :bash
    virtualbox-iso:       cookbook_name "metasploitable"
    virtualbox-iso:       recipe_name "flags"
    virtualbox-iso:       code "    cd /opt/docker\n    docker build -t \"7_of_diamonds\" .\n    docker run -dit --restart always --name 7_of_diamonds 7_of_diamonds\n"
    virtualbox-iso:       domain nil
    virtualbox-iso:     end
    virtualbox-iso:
    virtualbox-iso:     System Info:
    virtualbox-iso:     ------------
    virtualbox-iso:     chef_version=13.8.5
    virtualbox-iso:     platform=ubuntu
    virtualbox-iso:     platform_version=14.04
    virtualbox-iso:     ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    virtualbox-iso:     program_name=chef-solo worker: ppid=1087;start=17:18:57;
    virtualbox-iso:     executable=/opt/chef/bin/chef-solo
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Running handlers:
    virtualbox-iso: [2019-02-12T17:32:02+00:00] ERROR: Running exception handlers
    virtualbox-iso: [2019-02-12T17:32:02+00:00] ERROR: Running exception handlers
    virtualbox-iso: Running handlers complete
    virtualbox-iso: [2019-02-12T17:32:02+00:00] ERROR: Exception handlers complete
    virtualbox-iso: [2019-02-12T17:32:02+00:00] ERROR: Exception handlers complete
    virtualbox-iso: Chef Client failed. 188 resources updated in 13 minutes 05 seconds
    virtualbox-iso: [2019-02-12T17:32:02+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2019-02-12T17:32:02+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2019-02-12T17:32:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2019-02-12T17:32:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2019-02-12T17:32:02+00:00] ERROR: bash[build docker image for 7 of diamonds] (metasploitable::flags line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '125'
    virtualbox-iso: ---- Begin output of "bash"  "/tmp/chef-script20190212-1092-138rh0a" ----
    virtualbox-iso: STDOUT: Sending build context to Docker daemon  738.8kB
    virtualbox-iso: Step 1/4 : FROM ubuntu:latest
    virtualbox-iso: latest: Pulling from library/ubuntu
    virtualbox-iso: 6cf436f81810: Pulling fs layer
    virtualbox-iso: 987088a85b96: Pulling fs layer
    virtualbox-iso: b4624b3efe06: Pulling fs layer
    virtualbox-iso: d42beb8ded59: Pulling fs layer
    virtualbox-iso: d42beb8ded59: Waiting
    virtualbox-iso: b4624b3efe06: Verifying Checksum
    virtualbox-iso: b4624b3efe06: Download complete
    virtualbox-iso: 987088a85b96: Verifying Checksum
    virtualbox-iso: 987088a85b96: Download complete
    virtualbox-iso: d42beb8ded59: Verifying Checksum
    virtualbox-iso: d42beb8ded59: Download complete
    virtualbox-iso: 6cf436f81810: Verifying Checksum
    virtualbox-iso: 6cf436f81810: Download complete
    virtualbox-iso: 6cf436f81810: Pull complete
    virtualbox-iso: 987088a85b96: Pull complete
    virtualbox-iso: b4624b3efe06: Pull complete
    virtualbox-iso: d42beb8ded59: Pull complete
    virtualbox-iso: Digest: sha256:7a47ccc3bbe8a451b500d2b53104868b46d60ee8f5b35a24b41a86077c650210
    virtualbox-iso: Status: Downloaded newer image for ubuntu:latest
    virtualbox-iso:  ---> 47b19964fb50
    virtualbox-iso: Step 2/4 : MAINTAINER Metasploitable "msfdev@rapid7.com"
    virtualbox-iso:  ---> Running in d6cde8de898d
    virtualbox-iso: Removing intermediate container d6cde8de898d
    virtualbox-iso:  ---> 367b6da05a6a
    virtualbox-iso: Step 3/4 : ADD 7_of_diamonds.zip /home/7_of_diamonds.zip
    virtualbox-iso:  ---> 69a8bf7b75b3
    virtualbox-iso: Step 4/4 : WORKDIR /home
    virtualbox-iso:  ---> Running in ce54343ea243
    virtualbox-iso: Removing intermediate container ce54343ea243
    virtualbox-iso:  ---> 07b6122fc80f
    virtualbox-iso: Successfully built 07b6122fc80f
    virtualbox-iso: Successfully tagged 7_of_diamonds:latest
    virtualbox-iso: 81d89907fa794146d1eb73192da79b87080933bb16b378afaf1ddb58eb1ea726
    virtualbox-iso: STDERR: docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown.
    virtualbox-iso: ---- End output of "bash"  "/tmp/chef-script20190212-1092-138rh0a" ----
    virtualbox-iso: Ran "bash"  "/tmp/chef-script20190212-1092-138rh0a" returned 125
    virtualbox-iso: [2019-02-12T17:32:02+00:00] ERROR: bash[build docker image for 7 of diamonds] (metasploitable::flags line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '125'
    virtualbox-iso: ---- Begin output of "bash"  "/tmp/chef-script20190212-1092-138rh0a" ----
    virtualbox-iso: STDOUT: Sending build context to Docker daemon  738.8kB
    virtualbox-iso: Step 1/4 : FROM ubuntu:latest
    virtualbox-iso: latest: Pulling from library/ubuntu
    virtualbox-iso: 6cf436f81810: Pulling fs layer
    virtualbox-iso: 987088a85b96: Pulling fs layer
    virtualbox-iso: b4624b3efe06: Pulling fs layer
    virtualbox-iso: d42beb8ded59: Pulling fs layer
    virtualbox-iso: d42beb8ded59: Waiting
    virtualbox-iso: b4624b3efe06: Verifying Checksum
    virtualbox-iso: b4624b3efe06: Download complete
    virtualbox-iso: 987088a85b96: Verifying Checksum
    virtualbox-iso: 987088a85b96: Download complete
    virtualbox-iso: d42beb8ded59: Verifying Checksum
    virtualbox-iso: d42beb8ded59: Download complete
    virtualbox-iso: 6cf436f81810: Verifying Checksum
    virtualbox-iso: 6cf436f81810: Download complete
    virtualbox-iso: 6cf436f81810: Pull complete
    virtualbox-iso: 987088a85b96: Pull complete
    virtualbox-iso: b4624b3efe06: Pull complete
    virtualbox-iso: d42beb8ded59: Pull complete
    virtualbox-iso: Digest: sha256:7a47ccc3bbe8a451b500d2b53104868b46d60ee8f5b35a24b41a86077c650210
    virtualbox-iso: Status: Downloaded newer image for ubuntu:latest
    virtualbox-iso:  ---> 47b19964fb50
    virtualbox-iso: Step 2/4 : MAINTAINER Metasploitable "msfdev@rapid7.com"
    virtualbox-iso:  ---> Running in d6cde8de898d
    virtualbox-iso: Removing intermediate container d6cde8de898d
    virtualbox-iso:  ---> 367b6da05a6a
    virtualbox-iso: Step 3/4 : ADD 7_of_diamonds.zip /home/7_of_diamonds.zip
    virtualbox-iso:  ---> 69a8bf7b75b3
    virtualbox-iso: Step 4/4 : WORKDIR /home
    virtualbox-iso:  ---> Running in ce54343ea243
    virtualbox-iso: Removing intermediate container ce54343ea243
    virtualbox-iso:  ---> 07b6122fc80f
    virtualbox-iso: Successfully built 07b6122fc80f
    virtualbox-iso: Successfully tagged 7_of_diamonds:latest
    virtualbox-iso: 81d89907fa794146d1eb73192da79b87080933bb16b378afaf1ddb58eb1ea726
    virtualbox-iso: STDERR: docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown.
    virtualbox-iso: ---- End output of "bash"  "/tmp/chef-script20190212-1092-138rh0a" ----
    virtualbox-iso: Ran "bash"  "/tmp/chef-script20190212-1092-138rh0a" returned 125
    virtualbox-iso: [2019-02-12T17:32:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    virtualbox-iso: [2019-02-12T17:32:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error executing Chef: Non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error executing Chef: Non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\XXXX\Desktop\Virtual Machines\metasploitable3-master\build.ps1:150 char:10
+          throw "Error building the Vagrant box using Packer. Please c ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by jmartin-r7** [comment]
Thank you for reporting, this seems to be impacting all platforms, investigation of cause is ongoing.  I suspect the docker version getting installed by the build is not longer compatible with something in the  chef recipe.
