### ISSUE TITLE
Timeout waiting for SSH. ==> virtualbox-iso: Deregistering and deleting VM... ==> virtualbox-iso: Deleting output directory... Build 'virtualbox-iso' errored: Timeout waiting for SSH.

### ISSUE THREAD

**Issue by Rish00760** [rapid7/metasploitable3#379]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by elreydetoda** [comment]
It looks like the preseed file isn't answer the hostname properly...
![image](https://user-images.githubusercontent.com/10230166/53607682-c56a0d00-3b8d-11e9-8540-f42bab14c979.png)

so...weird thing is, this happened to me the first time I ran it, but then I did Ctrl + C to kill it and then it worked properly the second time...so I have no idea what the condition is that causes this. I ran the windows build beforehand, but that shouldn't cause a condition to not be answered with the preseed file... :upside_down_face: :thinking:

the errors on my screen are from the compare function, but you can ignore them it is doing plugin checking: 
https://github.com/rapid7/metasploitable3/blob/6b0bac0626bbd5895b23459d66e57882c44aed2e/build.sh#L48
https://github.com/rapid7/metasploitable3/blob/6b0bac0626bbd5895b23459d66e57882c44aed2e/build.sh#L52
I will check that out later

**Comment by Rish00760** [comment]
> It looks like the preseed file isn't answer the hostname properly...
> ![image](https://user-images.githubusercontent.com/10230166/53607682-c56a0d00-3b8d-11e9-8540-f42bab14c979.png)
> 
> so...weird thing is, this happened to me the first time I ran it, but then I did Ctrl + C to kill it and then it worked properly the second time...so I have no idea what the condition is that causes this. I ran the windows build beforehand, but that shouldn't cause a condition to not be answered with the preseed file... 🙃 🤔
> 
> the errors on my screen are from the compare function, but you can ignore them it is doing plugin checking:
> [metasploitable3/build.sh](https://github.com/rapid7/metasploitable3/blob/6b0bac0626bbd5895b23459d66e57882c44aed2e/build.sh#L48)
> 
> Line 48 in [6b0bac0](/rapid7/metasploitable3/commit/6b0bac0626bbd5895b23459d66e57882c44aed2e)
> 
>  if [[ ${actual_version[$i]} -gt ${expected_version[$i]} ]]; then 
> 
> [metasploitable3/build.sh](https://github.com/rapid7/metasploitable3/blob/6b0bac0626bbd5895b23459d66e57882c44aed2e/build.sh#L52)
> 
> Line 52 in [6b0bac0](/rapid7/metasploitable3/commit/6b0bac0626bbd5895b23459d66e57882c44aed2e)
> 
>  if [[ ${actual_version[$i]} -lt ${expected_version[$i]} ]]; then 
> 
> I will check that out later

Thanks for taking a look at this but this got resolved. I again ran the packer build for windows Json file and it worked perfectly after this step. What i think is the virtual box image was not downloaded properly the first time so i did that again and it worked for me.

Thanks again and have a great day!
