### ISSUE TITLE
Readme_app and Sinatra not starting correctly.

### ISSUE THREAD

**Issue by usmcfiredog** [rapid7/metasploitable3#380]
## Issue Description
Ubuntu build does not succeed for readme_app and sinatra. This can be verified by doing a netstat -ano and the machine is not listening on 8181 and 3500.

There is no issue building this VM using macOS with VMware Fusion.
## Host System
* OS: Windows 10 1809 (17763.316)
* Packer Version: 1.3.3
* Vagrant Version: 2.2.3
* VMWare Version: 15.0.2 build-10952284

## Command Output
    vmware-iso: Recipe: metasploitable::sinatra
    vmware-iso:   * directory[/opt/sinatra] action create
    vmware-iso:     - create new directory /opt/sinatra
    vmware-iso:     - change mode from '' to '0777'
    vmware-iso:   * directory[/var/opt/sinatra] action create
    vmware-iso:     - create new directory /var/opt/sinatra
    vmware-iso:     - change mode from '' to '0777'
    vmware-iso:   * cookbook_file[/opt/sinatra/Gemfile] action create
    vmware-iso:     - create new file /opt/sinatra/Gemfile
    vmware-iso:     - update content in file /opt/sinatra/Gemfile from none to 9e5024
    vmware-iso:     --- /opt/sinatra/Gemfile    2019-03-01 03:49:52.846927004 +0000
    vmware-iso:     +++ /opt/sinatra/.chef-Gemfile20190301-1124-18h38lh 2019-03-01 03:49:52.846927004 +0000
    vmware-iso:     @@ -1 +1,7 @@
    vmware-iso:     +source 'https://rubygems.org'
    vmware-iso:     +gem 'rack', '2.0.1'
    vmware-iso:     +gem 'sinatra', '2.0.0rc2'
    vmware-iso:     +gem 'erubis'
    vmware-iso:     +gem 'activesupport'
    vmware-iso:     +gem 'obfuscate'
    vmware-iso:     - change mode from '' to '0777'
    vmware-iso:   * cookbook_file[/opt/sinatra/server] action create
    vmware-iso:     - create new file /opt/sinatra/server
    vmware-iso:     - update content in file /opt/sinatra/server from none to be502e
    vmware-iso:     (new content is binary, diff output suppressed)
    vmware-iso:     - change mode from '' to '0777'
    vmware-iso:   * cookbook_file[/etc/init/sinatra.conf] action create
    vmware-iso:     - create new file /etc/init/sinatra.conf
    vmware-iso:     - update content in file /etc/init/sinatra.conf from none to 847bea
    vmware-iso:     --- /etc/init/sinatra.conf  2019-03-01 03:49:52.878930204 +0000
    vmware-iso:     +++ /etc/init/.chef-sinatra20190301-1124-cml8yu.conf        2019-03-01 03:49:52.878930204 +0000
    vmware-iso:     @@ -1 +1,10 @@
    vmware-iso:     +description 'Run vulnerable Sinatra'
    vmware-iso:     +author 'metasploitable3'
    vmware-iso:     +
    vmware-iso:     +start on runlevel [2345]
    vmware-iso:     +chdir /opt/sinatra/
    vmware-iso:     +script
    vmware-iso:     +  echo "Starting sinatra"
    vmware-iso:     +  /opt/sinatra/server
    vmware-iso:     +end script
    vmware-iso:     - change mode from '' to '0777'
    vmware-iso:   * service[sinatra] action enable (up to date)
    vmware-iso:   * service[sinatra] action start
    vmware-iso:     - start service service[sinatra]

    vmware-iso: Recipe: metasploitable::readme_app
    vmware-iso:   * apt_package[git] action install (up to date)
    vmware-iso:   * directory[/opt/readme_app] action create
    vmware-iso:     - create new directory /opt/readme_app
    vmware-iso:     - change mode from '' to '0644'
    vmware-iso:     - change owner from '' to 'chewbacca'
    vmware-iso:     - change group from '' to 'users'
    vmware-iso:   * bash[clone the readme app and install gems] action run
    vmware-iso:     - execute "bash"  "/tmp/chef-script20190301-1124-1a39kgf"
    vmware-iso:   * template[/opt/readme_app/start.sh] action create
    vmware-iso:     - create new file /opt/readme_app/start.sh
    vmware-iso:     - update content in file /opt/readme_app/start.sh from none to ec3bd0
    vmware-iso:     --- /opt/readme_app/start.sh        2019-03-01 03:51:48.400179812 +0000
    vmware-iso:     +++ /opt/readme_app/.chef-start20190301-1124-xkwx1y.sh      2019-03-01 03:51:48.400179812 +0000
    vmware-iso:     @@ -1 +1,6 @@
    vmware-iso:     +#!/bin/sh
    vmware-iso:     +
    vmware-iso:     +cd /opt/readme_app
    vmware-iso:     +bundle install --path vendor/bundle
    vmware-iso:     +bundle exec rails s -b 0.0.0.0 -p 3500
    vmware-iso:   * cookbook_file[/etc/init/readme_app.conf] action create
    vmware-iso:     - create new file /etc/init/readme_app.conf
    vmware-iso:     - update content in file /etc/init/readme_app.conf from none to 168e2a
    vmware-iso:     --- /etc/init/readme_app.conf       2019-03-01 03:51:48.408179812 +0000
    vmware-iso:     +++ /etc/init/.chef-readme_app20190301-1124-uqcimz.conf     2019-03-01 03:51:48.404179812 +0000
    vmware-iso:     @@ -1 +1,9 @@
    vmware-iso:     +description 'Run ReadMe App'
    vmware-iso:     +author 'metasploitable3'
    vmware-iso:     +
    vmware-iso:     +start on runlevel [2345]
    vmware-iso:     +
    vmware-iso:     +script
    vmware-iso:     +    sudo -u chewbacca /opt/readme_app/start.sh
    vmware-iso:     +end script
    vmware-iso:     - change mode from '' to '0644'
    vmware-iso:   * bash[set permissions] action run
    vmware-iso:     - execute "bash"  "/tmp/chef-script20190301-1124-1d01ven"
    vmware-iso:   * service[readme_app] action enable (up to date)
    vmware-iso:   * service[readme_app] action start
    vmware-iso:     - start service service[readme_app]

vagrant@metasploitable3-ub1404:~$ netstat -ano | grep tcp
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:631             0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:57627           0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:32000         0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:8067            0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:6697            0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:6667            0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:46300         127.0.0.1:80            ESTABLISHED keepalive (114.79/0/0)
tcp        0      0 192.168.70.131:22       192.168.70.2:60959      ESTABLISHED keepalive (7205.99/0/0)
tcp        0      0 127.0.0.1:46299         127.0.0.1:80            ESTABLISHED keepalive (114.02/0/0)

**Comment by busterb** [comment]
I'd recommend just not using WIndows 10 and Vmware; it's just not tested quite as well as other variants if you have access to other systems.
