### ISSUE TITLE
Build with smaller disk

### ISSUE THREAD

**Issue by gsagers** [rapid7/metasploitable3#383]
## Issue Description
Just wondering whether it's possible to build with a smaller disk.  The reason for this is hosting the VMs on an OpenStack system which doesn't properly support sparse disks.  Specifically, I'd like to build the ubuntu1404 target at between 4 and 10 GB, and the win2k8 target at 20GB.  I've adjusted the "disk_size" variable in packer/templates/windows_2008_r2.json and ubuntu_1404.json, but they seem to be ignored.

## Host System
* MacOS 10.14.3 Mojave
* Packer Version: 1.1.3
* Vagrant Version: 2.2.4
* VirtualBox Version: 6.0.4 r128413

## Command Output
Didn't see anything in command output that indicates where disk size is set, but have output if desired.

**Comment by jmartin-r7** [comment]
If you would like to offer a PR for some sort of configuration option we would consider inclusion.

Did you adjust all three `disk_size` values in each file?  Each one applies to a different virtualization product vmware/virtualbox/qemu.

**Comment by gsagers** [comment]
Don't have a PR, just curious if I was overlooking something.  I did adjust all three variables identically.

**Comment by jmartin-r7** [comment]
I will see if I can come up with changes needed for a one off smaller build and post back here.

**Comment by busterb** [comment]
I don't think we can support smaller disks for now.

**Comment by gsagers** [comment]
Thanks
