### ISSUE TITLE
Packer,Vagrant & Virtual Box  working versions 

### ISSUE THREAD

**Issue by paulyic** [rapid7/metasploitable3#386]
## Issue Description

I started out with this:

https://www.hackingtutorials.org/metasploit-tutorials/setup-metasploitable-3-windows-10/

 Virtualbox 5.1.14 built halted very quickly with  errors until I upgraded to the 5.2.x  , now l see the VM being built on Virtualbox but it failed to complete the build, giving some missing file errors.

I then tried different versions ( not the latest) of Packer, Vagrant and Virtualbox.   I am seeing so many different kinds of errors that I have stopped documenting it.

Appreciate if someone will share the working versions of Packer, Vagrant and Virtualbox that you have used to successfully built Metasploitable3.

Thank you.
Paul

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by busterb** [comment]
Try checking the wiki for the last working versions. Every once in a while, one of these tools updates and breaks everything else if you don't keep them all in sync with each other. Just keep trying, and happy to hear back positive results.
