### ISSUE TITLE
Error finding port when creating Metasploitable 3

### ISSUE THREAD

**Issue by Haitao1990** [rapid7/metasploitable3#387]
## Host System
* OS: MacOS 10.14
* Packer Version: 1.4.0
* Vagrant Version: 2.2.4
* VirtualBox Version: 5.2.26

## Issue Description
encountered an error when creating the metasploitable 3.

Build 'virtualbox-iso' errored: Error finding port: open /Users/HaitaoHuang/metasploitable3/packer_cache/port/5970: no such file or directory

<img width="1280" alt="Screen Shot 2019-03-26 at 5 21 03 PM" src="https://user-images.githubusercontent.com/23871802/55034583-226dad00-4fec-11e9-95dc-40ebefbeceed.png">
<img width="1280" alt="Screen Shot 2019-03-26 at 5 21 24 PM" src="https://user-images.githubusercontent.com/23871802/55034590-27caf780-4fec-11e9-8b51-cdb6c6448e18.png">

## Command Output
Build 'virtualbox-iso' errored: Error finding port: open /Users/HaitaoHuang/metasploitable3/packer_cache/port/5970: no such file or directory

**Comment by jmartin-r7** [comment]
Please try the stable version of packer, at this time that is `1.3.5`.

**Comment by sachinjung** [comment]
Although I did it on Windows 10 Pro, it might be helpful.
1. Install Vagrant and Vagrant VMware Plugins
2. Install Packer
3. Install VMware Workstation Pro
4. Download the Metasploitable3 github repository as zip
5. Extract the Metasploitable-Master zip where you want to put your machine
6. Run administrative command prompt and go to metasploitable3-master
7. Run the following commands

Microsoft Windows [Version 10.0.19042.1466]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd \Users\mustb\Documents\Virtual Machines\Mabl3

C:\Users\mustb\Documents\Virtual Machines\Mabl3>dir
 Volume in drive C has no label.
 Volume Serial Number is CE73-3024

 Directory of C:\Users\mustb\Documents\Virtual Machines\Mabl3

01/19/2022  09:07 PM    <DIR>          .
01/19/2022  09:07 PM    <DIR>          ..
01/10/2022  10:21 AM    <DIR>          .github
01/10/2022  10:21 AM               105 .gitignore
01/19/2022  09:07 PM    <DIR>          .vagrant
01/10/2022  10:21 AM             6,640 build.ps1
01/10/2022  10:21 AM             7,486 build.sh
01/10/2022  10:21 AM    <DIR>          chef
01/10/2022  10:21 AM             1,783 COPYING
01/10/2022  10:21 AM    <DIR>          iso
01/10/2022  10:21 AM             3,601 LICENSE
01/10/2022  10:21 AM    <DIR>          packer
01/10/2022  10:21 AM             6,006 README.md
01/10/2022  10:21 AM    <DIR>          resources
01/10/2022  10:21 AM    <DIR>          scripts
01/10/2022  10:21 AM             2,297 Vagrantfile
01/10/2022  10:21 AM    <DIR>          versions
               7 File(s)         27,918 bytes
              10 Dir(s)  114,240,036,864 bytes free

C:\Users\mustb\Documents\Virtual Machines\Mabl3>vagrant up --provider vmware_desktop
	This process will pull the vmware image from internet box repository
	If both box are downloaded successfully move to next step

C:\Users\mustb\Documents\Virtual Machines\Mabl3>vagrant up
	This will start the vagrant box

C:\Users\mustb\Documents\Virtual Machines\Mabl3>vagrant provision
	This will provision the virtual machine

Now, Open VMware Workstation
Open virtual machine inside the metasploitable3-master\.vagrant\machines\win2k8 or ub1404\vmware_desktop\45a3b355-f450-4e0d-83f2-18f5bea2ad60 (some random folder)\metasploitable3-win2k8.vmx

Export the virtual machine as OVA if you like or make a copy

Do same for Ubuntu 14.04 virtual machine as well
