### ISSUE TITLE
Use Ansible, Puppet etc. for provisioning

### ISSUE THREAD

**Issue by prateepb** [rapid7/metasploitable3#39]
Given that two objectives of this project are:

1. support multiple operating systems
2. support multiple levels of difficulty

it may be beneficial to consider the use of a more robust provisioning system such as Puppet or Ansible.

I'm going to start looking at Linux support (#37) and would like to consider whether to:

1. just use shell scripts for provisioning
2. use puppet
3. use ansible

The current Windows setup is not idempotent and repeated provisioning will result in errors.

Puppet and ansible have their pros and cons.

**Puppet** - cross platform, no additional requirements on the host but the configuration language is more complex
**Ansible** - very simple YAML configuration, no software required on the guest, but additional dependencies required on the host environment

Both would allow a lot of flexibility in terms of conditional installation or starting of services.

A good example of how ansible can be used is in the [Streisand](https://github.com/jlund/streisand) project.

Before I start with Linux support (#37), it would be great to hear if anyone has a strong opinion either way. Personally, I think Ansible is probably best as long as nobody cares about the extra dependency on the host.

**Comment by Sliim** [comment]
Hi!
Chef is also a good provisioning tool ;)

**Comment by bcook-r7** [comment]
hi @prateepb would you like to take this on? I don't think we're super familiar with using ansible, but it sounds nice, especially the idempotent properties during provisioning.

**Comment by prateepb** [comment]
Sure. Happy to, however, I don't want to impose my pre-conceptions on anyone!  

I've been messing with Linux (#37) and I think that puppet is a better cross-platform option. Ansible is simpler, but it doesn't support Windows as a host control environment. I know chef is also popular, but have no experience of it.

It should be possible to completely abstract all install/provisioning steps across Windows/Linux if that's a goal you're interested in. It does, however, introduce another level of complexity. Personally, I think it's worth it if cross platform is desired.

If you're not familiar with puppet, have a look at https://github.com/prateepb/metasploitable3/tree/trusty/puppet/modules/metasploitable3/manifests

I'll also update #37 with more details

Before I submit a PR, let me know if this a direction that people are happy with.

**Comment by prateepb** [comment]
[Puppet modules](https://forge.puppet.com/) allow you to do some nice stuff e.g the [official chocolately module](https://forge.puppet.com/chocolatey/chocolatey)

**Comment by jbarnett-r7** [comment]
We decided to go with Chef. Brief explanation here: https://github.com/rapid7/metasploitable3/issues/37#issuecomment-286564233

It's starting with the Linux VM, and the plan is to retroactively add it back for the Windows stuff.
