### ISSUE TITLE
 kali 2019 :windows 2008 Script exited with non-zero exit status: 1 

### ISSUE THREAD

**Issue by yujiantt** [rapid7/metasploitable3#390]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System 
* OS:kali 2019.1
* Packer Version:1.3.4
* Vagrant Version:2.2.4
* VirtualBox Version:6.0.4 r128413 

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.
    virtualbox-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 30"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "$req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()"
    virtualbox-iso: Exception calling "GetResponse" with "0" argument(s): "Unable to connect to
    virtualbox-iso: the remote server"
    virtualbox-iso: At line:1 char:108
    virtualbox-iso: + ... host:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()
    virtualbox-iso: +                                                        ~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "$body = [System.Text.Encoding]::ASCII.GetBytes('{\"user\":\"kimchy\", \"post_date\": \"2009-11-15T14:12:12\", \"message\": \"Elasticsearch\" }'); $req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.method = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()"
    virtualbox-iso: Exception calling "GetRequestStream" with "0" argument(s): "Unable to connect
    virtualbox-iso: to the remote server"
    virtualbox-iso: At line:1 char:307
    virtualbox-iso: + ... ion/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $strea ...
    virtualbox-iso: +                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso: You cannot call a method on a null-valued expression.
    virtualbox-iso: At line:1 char:342
    virtualbox-iso: + ... req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $strea ...
    virtualbox-iso: +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    virtualbox-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
    virtualbox-iso:
    virtualbox-iso: You cannot call a method on a null-valued expression.
    virtualbox-iso: At line:1 char:381
    virtualbox-iso: + ... eam(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.G ...
    virtualbox-iso: +                                                   ~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    virtualbox-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
    virtualbox-iso:
    virtualbox-iso: Exception calling "GetResponse" with "0" argument(s): "You must provide a
    virtualbox-iso: request body if you set ContentLength>0 or SendChunked==true.  Do this by
    virtualbox-iso: calling [Begin]GetRequestStream before [Begin]GetResponse."
    virtualbox-iso: At line:1 char:398
    virtualbox-iso: + ... am.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()
    virtualbox-iso: +                                                        ~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : ProtocolViolationException
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.
root@yujian:/metasploitable3-workspace#

**Comment by yujiantt** [comment]
Everybody ace comes quickly

**Comment by jmartin-r7** [comment]
Closing, this issue does not have a clear cause and recent builds are passing.
