### ISSUE TITLE
Malware When Downloading

### ISSUE THREAD

**Issue by JaysonD123** [rapid7/metasploitable3#391]
Looks like someone snuck in a virus called zpevdo.b

Luckily my antivirus caught it. I thought it might have been a false positive but after investigating further it appears to be real.

**Comment by bcoles** [comment]
I doubt it. It is probably a false-positive.

Which file is flagged? Was it `jenkins.exe` ?

* #280
* #196

**Comment by busterb** [comment]
I suspect this was the same as #196
