### ISSUE TITLE
Stuck at Progress: Downloading boxstarter.bootstrapper 2.12.0... 100%

### ISSUE THREAD

**Issue by DIASILEDU** [rapid7/metasploitable3#392]
## Issue Description
Stuck at downloading file. I don't think it's a compatibility issue because it just a download. The task manager is not showing any activity. I'll try compatible version to see if it works.

## Host System
* OS: Windows 10
* Packer Version: 1.4.0
* Vagrant Version: 2.2.4
* VirtualBox Version: 6.0.6

## Command Output
==> virtualbox-iso: Restarting Machine
==> virtualbox-iso: Waiting for machine to restart...
==> virtualbox-iso: #< CLIXML
    virtualbox-iso: VAGRANT-2008R2 restarted.
==> virtualbox-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> virtualbox-iso: Machine successfully restarted, moving on
==> virtualbox-iso: Provisioning with Powershell...
==> virtualbox-iso: Provisioning with powershell script: E:\metasploitable3-master\packer\templates/../../scripts/installs/setup_iis.bat
    virtualbox-iso: Deployment Image Servicing and Management tool
    virtualbox-iso: Version: 6.1.7600.16385
    virtualbox-iso: Image Version: 6.1.7600.16385
    virtualbox-iso: Enabling feature(s)
    virtualbox-iso: The operation completed successfully.
==> virtualbox-iso: Provisioning with windows-shell...
==> virtualbox-iso: Provisioning with shell script: E:\metasploitable3-master\packer\templates/../../scripts/installs/install_boxstarter.bat
    virtualbox-iso: C:\Users\vagrant>chocolatey feature enable -n=allowGlobalConfirmation
    virtualbox-iso: Chocolatey v0.10.8
    virtualbox-iso: Enabled allowGlobalConfirmation
    virtualbox-iso: C:\Users\vagrant>choco install BoxStarter
    virtualbox-iso: Chocolatey v0.10.8
    virtualbox-iso: Installing the following packages:
    virtualbox-iso: BoxStarter
    virtualbox-iso: By installing you accept licenses for the packages.
Progress: Downloading BoxStarter.Common 2.12.0... 100%
Progress: Downloading boxstarter 2.12.0... 100%
Progress: Downloading BoxStarter.WinConfig 2.12.0... 100%
Progress: Downloading boxstarter.bootstrapper 2.12.0... 100%

**Comment by DIASILEDU** [comment]
Using everything that is compatible works.

**Comment by unawann** [comment]
Hello, would you mind to share what you have finally used? I am stuck at the exact same point and did not get it run yet.
Thanks!

**Comment by DIASILEDU** [comment]
You need to uninstall everything required, and installed the compatible
versions mentioned in the wiki. That solved that problem, but now I'm
receiving a JAVA_HOME error message saying that I need to set the
environment variable.
