### ISSUE TITLE
VirtualBox Metasploitable3 - Installation issue - No progress past "Progress: Downloading boxstarter.bootstrapper 2.12.0... 100%"

### ISSUE THREAD

**Issue by JoeAJLaw** [rapid7/metasploitable3#395]
## Issue Description
I have been to the metasploitable3 page on the Rapid7 github. Clicked on the URL's for the required packages, did a fresh install of all of them. Cloned the repository, extracted it from a Zip folder and stored contents elsewhere. Placed Packer.exe inside of the master folder.  

Then ran as an administrator the following command in powershell (The script in the folder I downloaded didn't work due to policy rules on script execution) : "powershell -ExecutionPolicy ByPass -File .\build.ps1 windows2008"

It started executing, which I knew was going to take a long time thanks to the video that you had all provided. However, after over 12 hours of waiting for the powershell to make a change from 
"Progress: Downloading boxstarter.bootstrapper 2.12.0... 100% ". I did a system restart, as I thought maybe something running was conflicting with it. But it keeps getting to the samepoint.

And I don't think the packages are the problem, because when the script is executed it outputs that all the required packages are found. 

Any help to the problem would be greatly appreciated

## Host System
* OS: Windows 10
* Packer Version: 1.4.0
* Vagrant Version: 2.2.4
* VirtualBox Version: 6.0

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

![Capture1](https://user-images.githubusercontent.com/22789766/57217836-9d62b400-6feb-11e9-85a2-23b30efcaec6.JPG)

![Capture](https://user-images.githubusercontent.com/22789766/57217778-74daba00-6feb-11e9-8cae-a86475d3189a.JPG)

**Comment by alexelefth** [comment]
i have the exact same issue

**Comment by peterPP1** [comment]
Same here, but I'm using Win 7.

**Comment by peterPP1** [comment]
Ok, it worked on the following software versions:

    OS: Windows 10
    Packer Version: 1.3.4
    Vagrant Version: 2.0.1
    VirtualBox Version: 5.2.8

**Comment by Asreira** [comment]
I have that  problem with Win 10, sooo... any solution?

**Comment by jmartin-r7** [comment]
Closing stale, #562 updated supported `packer` and `virtualbox` versions, retesting on current versions may show the issue resolved.
