### ISSUE TITLE
Can I fix jre installation process manually  after auto build?

### ISSUE THREAD

**Issue by MerliniKing** [rapid7/metasploitable3#397]
## Issue Description
Because of GFW, jre download failed in auto build process. Can I manually fix it after auto build?

## Host System
* OS: Win10 
* Packer Version: 1.4.1
* Vagrant Version: 2.2.4
* VirtualBox Version: 6.0

## Command Output
 virtualbox-iso: jre8 v8.0.211 [Approved]
    virtualbox-iso: jre8 package files install completed. Performing other installation steps.
    virtualbox-iso: The software license has changed for Java and this software must be licensed for general business use. Please ensure your licensing is compliant before installing.
    virtualbox-iso: Checking to see if local install is already up to date...
    virtualbox-iso: Downloading 32-bit installer
    virtualbox-iso: Downloading jre8
    virtualbox-iso:   from 'https://javadl.oracle.com/webapps/download/AutoDL?BundleId=238727_478a62b7d4e34b78b671c754eaaf38ab'
    virtualbox-iso: Progress: 16% - Saving 11.27 MB of 66.37 MBChocolatey timed out waiting for the command to finish. The timeout
    virtualbox-iso:  specified (or the default value) was '2700' seconds. Perhaps try a
    virtualbox-iso:  higher `--execution-timeout`? See `choco -h` for details.
    virtualbox-iso: The install of jre8 was NOT successful.
    virtualbox-iso: Error while running 'C:\ProgramData\chocolatey\lib\jre8\tools\chocolateyInstall.ps1'.
    virtualbox-iso:  See log for details.
    virtualbox-iso:
    virtualbox-iso: javaruntime-platformspecific v7.0.79.20161125 [Approved]
    virtualbox-iso: javaruntime-platformspecific package files install completed. Performing other installation steps.
    virtualbox-iso:  The install of javaruntime-platformspecific was successful.
    virtualbox-iso:   Software install location not explicitly set, could be in package or
    virtualbox-iso:   default install location if installer.
    virtualbox-iso:
    virtualbox-iso: Chocolatey installed 1/2 packages. 1 packages failed.
    virtualbox-iso:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    virtualbox-iso:
    virtualbox-iso: Failures
    virtualbox-iso:  - jre8 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\jre8\tools\chocolateyInstall.ps1'.
    virtualbox-iso:  See log for details.

**Comment by jmartin-r7** [comment]
The build process must complete all steps successfully and relies on stable internet services.  You can custom modify the packer config and skip the java install however this will also require removing some other install steps that use this JRE to provide vulnerable services.

See https://github.com/rapid7/metasploitable3/blob/6b0bac0626bbd5895b23459d66e57882c44aed2e/packer/templates/windows_2008_r2.json#L202

**Comment by jmartin-r7** [comment]
Closing as answered.
