### ISSUE TITLE
Unable to build metasploitable for windows2008

### ISSUE THREAD

**Issue by code-player** [rapid7/metasploitable3#399]
## Unable to build metasploitable for Windows2008
Initially, I thought of it as something related to permission denied, but even `sudo` didn't help. 

## Host System
* OS: Ubuntu 18.04 LTS
* Packer Version: 1.0.4
* Vagrant Version: 2.0.3
* VirtualBox Version: 6.0.6

## Command Output `./build.sh windows2008`
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error processing command: Error generating elevated runner: Error preparing elevated shell script: scp: ./${env:TEMP}\packer-elevated-shell-5d20b649-e3f8-f910-e9a0-fde9177fed0f.ps1: No such file or directory

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error processing command: Error generating elevated runner: Error preparing elevated shell script: scp: ./${env:TEMP}\packer-elevated-shell-5d20b649-e3f8-f910-e9a0-fde9177fed0f.ps1: No such file or directory

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.

**Comment by code-player** [comment]
Does anyone know a workaround for this? I'm really stuck at this

**Comment by jmartin-r7** [comment]
Suggest trying a packer version `1.3.4` or greater.  Last tested version I had work was `1.3.4` although newer versions may work as well.

**Comment by code-player** [comment]
@jmartin-r7 Thanks for the suggestion. It worked !!!
Cheers :100:

**Comment by jakob-lundberg** [comment]
In the build.sh script it checks for the packer version. But is approves of everything from version "0.10.0". This should maybe be updated to the correct requirement?

**Comment by code-player** [comment]
Yeah, I'd recommend that. 
I already have one PR open I can make the commit in that only?

**Comment by code-player** [comment]
I tried with `packer` and `vagrant` versions `1.4.3` and `2.2.5` respectively.
