### ISSUE TITLE
Ruby errors while installing 

### ISSUE THREAD

**Issue by dogebeets** [rapid7/metasploitable3#40]
This is where the errors start:

> ==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_rails_server.bat as c:\tmp\vagrant-shell.bat
==> default: C:\Windows\system32>copy /Y C:\Vagrant\resources\rails_server\gemrc C:\Users\vagrant\.gemrc 
==> default: 
==> default:         1 file(s) copied.
==> default: 
==> default: C:\Windows\system32>cmd /C "C:\tools\ruby23\bin\gem.cmd install rails -v '4.1.1' --no-ri --no-rdoc" 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: C:\Windows\system32>cmd /C "C:\tools\ruby23\bin\gem.cmd install rake -v '11.3.0' --no-ri --no-rdoc" 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install coffee-script-source -v '1.10.0' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install execjs -v '2.7.0' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install hike -v '1.2.3' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install multi_json -v '1.12.1' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install tilt -v '1.4.1' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sass -v '3.2.19' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sqlite3 -v '1.3.11' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install turbolinks-source -v '5.0.0' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install rdoc -f -v '4.2.2' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install coffee-script -v '2.4.1' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install uglifier -v '3.0.2' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sprockets -v '2.12.4' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install turbolinks -v '5.0.1' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sdoc -v '0.4.2' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install tzinfo-data -v '1.2016.7' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install jbuilder -v '2.6.0' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install coffee-rails -v '4.0.1' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install jquery-rails -v '3.1.4' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install sass-rails -v '4.0.5' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install debug_inspector -v '0.0.2' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install binding_of_caller -v '0.7.2' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install web-console -v '2.1.2' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: C:\Windows\system32>cmd /C C:\tools\ruby23\bin\gem.cmd install minitest -v '5.9.1' --no-ri --no-rdoc 
==> default: ERROR:  While executing gem ... (NoMethodError)
==> default: 
==> default:     undefined method `unpack' for nil:NilClass
==> default: 
==> default: C:\Windows\system32>copy /Y C:\Vagrant\Resources\rails_server\sqlite3-1.3.11-x64-mingw32.gemspec C:\tools\ruby23\lib\ruby\gems\2.3.0\specifications 
==> default:         1 file(s) copied.
==> default: 
==> default: 
==> default: C:\Windows\system32>C:\tools\ruby23\bin\rails.bat _4.1.1_ new "C:\Program Files\Rails_Server" 
==> default: 'C:\tools\ruby23\bin\rails.bat' is not recognized as an internal or external command,
==> default: operable program or batch file.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

Still digging in to this, but if anyone has any hints, please let me know.

**Comment by jbarnett-r7** [comment]
I'm not seeing this issue when building the latest master. Maybe your instance was only partially provisioned and a pre-req wasn't fully installed. I'd recommend starting with a clean provision by doing `vagrant destroy` and then running `vagrant up` again. Let us know if that helps.

**Comment by jbarnett-r7** [comment]
@dogebeets I'm going to close this out. If it's still an issue for you please re-open.
