### ISSUE TITLE
'jenkins.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by bolanleaderibigbe** [rapid7/metasploitable3#401]
I am trying to uninstall Jenkins on Windows 10, i enter the command on cmd
>> jenkins.exe uninstall
I get the error message below.

'jenkins.exe' is not recognized as an internal or external command,
operable program or batch file.

I need help as to why i cant find jenkins.exe on .jenkins

**Comment by jmartin-r7** [comment]
The `jenkins.exe` binary is a wrapper to start services not the default install for Jenkins and is not on the default `PATH`.  You would need to remove manually from the services table and the filesystem.

**Comment by jmartin-r7** [comment]
Not a supported action on an already created metastploitable3 VM.  Recommend manual removal of the jenkins install step if a VM built without this service is desired. Users can customize the services installed during the VM build process.
