### ISSUE TITLE
Cannot download pre-build images 

### ISSUE THREAD

**Issue by code-player** [rapid7/metasploitable3#402]
## Issue Description
There is no download link available at https://app.vagrantup.com/rapid7/ to download pre-build images as mentioned in the Readme file.

**Comment by code-player** [comment]
Can anyone provide valid link to download pre-built images for both windows and ubuntu server?
Thanks

**Comment by globo17** [comment]
After you install vagrant, go to the command line and type this: 
1. vagrant init rapid7/metasploitable3-ub1404 
2. vagrant up

**Comment by code-player** [comment]
Thanks :)

**Comment by code-player** [comment]
I tried the above command, but for windows it says 

> The machine with the name 'win2k8' was not found configured for
> this Vagrant environment.

I got this working for ubuntu1404 maybe because I was parallely working on building packer image once it was successfully built, I added it to my vagrant box.

But I think there should be something else for downloading pre-built images for windows 2008 server.

Please suggest.

**Comment by jmartin-r7** [comment]
See https://github.com/rapid7/metasploitable3#quick-start

a default `Vagrantfile` that should work is provided by the repository at the location noted in the `curl` command.

```
mkdir metasploitable3-workspace
cd metasploitable3-workspace
curl -O https://raw.githubusercontent.com/rapid7/metasploitable3/master/Vagrantfile && vagrant up
```

**Comment by code-player** [comment]
Closing this issue, as I got the packer build successfully. Couldn't test this.
Anyway, thanks for the update

**Comment by acheong08** [comment]
The curl command:
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
Progress: 0% (Rate: 10546/s, Estimated time remaining: 48:32:36)
:( 
Stuck in China with a terrible internet and firewall
