### ISSUE TITLE
Building metasploitable for Windows2008 Fails

### ISSUE THREAD

**Issue by g0nff** [rapid7/metasploitable3#405]
## Issue Description
When attempting to build metasploitable for Windows2008, it fails telling me "Error building the Vagrant box using Packer. Please check the output above for any error messages." I searched around but couldn't find anyone experiencing this exact error. I basically just made sure packer, vagrant, and virtualbox were up to date. I'm not sure if this is the cause, but raw.githubusercontent.com doesn't seem to take me anywhere. Any help is greatly appreciated, as I'm really just getting my feet wet here.

## Host System
* OS: Windows 10
* Packer Version: 1.4.3
* Vagrant Version: 2.2.5
* VirtualBox Version: 6.0.10 r132072

## Command Output
==> virtualbox-iso: Provisioning with shell script: D:\Downloads\metasploitable3-master\packer\templates/../../scripts/configs/vagrant-ssh.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if exist a:\vagrant.pub (copy a:\vagrant.pub C:\Users\vagrant\.ssh\authorized_keys )  else (powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub', 'C:\Users\vagrant\.ssh\authorized_keys')"  0<NUL )
==> virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The remote name could n
==> virtualbox-iso: ot be resolved: 'raw.githubusercontent.com'"
==> virtualbox-iso: At line:1 char:47
==> virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile <<<< ('https://raw.githubuserc
==> virtualbox-iso: ontent.com/mitchellh/vagrant/master/keys/vagrant.pub', 'C:\Users\vagrant\.ssh\a
==> virtualbox-iso: uthorized_keys')
==> virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> virtualbox-iso:     + FullyQualifiedErrorId : DotNetMethodException
==> virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At D:\Downloads\metasploitable3-master\build.ps1:150 char:10
+          throw "Error building the Vagrant box using Packer. Please c ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by g0nff** [comment]
Little more information: i was successfully able to build the ubuntu version, but I'd still really like to get the Windows 2008 version up and running. 

Thanks!

**Comment by pbarry-r7** [comment]
Hey @g0nff.  I'm not an expert with the build process (I use the existing Vagrant boxes mentioned in the "Quick-start" section [here](https://github.com/rapid7/metasploitable3/#quick-start)), but it does look likely that the inability for the system to resolve the link https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub is the issue.  For posterity, if I click that link in my browser here, I do get a public ssh key displayed in my browser windows, which I would expect from clicking a link like that:

```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
```

The `nslookup` utility in powershell will show if the system can resolve a URL name into an IP address.  If you use it on the system where you are attempting to build and you don't see any IP addresses in the "Addresses" output, that would be the problem (and might mean the nameserver configuration for the build system needs to be changed to a nameserver which can resolve the raw.githubusercontent.com URL).

<img width="391" alt="Screen Shot 2019-09-03 at 9 41 48 PM" src="https://user-images.githubusercontent.com/19912177/64221907-10920f00-ce94-11e9-9087-6a9ddb8bad61.png">

**Comment by g0nff** [comment]
Hi there!

I really appreciate the help. Based on what you told me, I realized that the PiHole on my network was preventing me from getting to raw.githubusercontent.com. 

However, now I'm getting a different error when trying to set this up. This happens regardless of whether I'm using the pre-built Vagrant Box, a la the Quick-start section, or the slightly more manual build process I had originally been using. This is the error I'm now receiving:

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: F:\metasploitable3-master\packer\templates/../builds/windows_2008_r2_virtualbox_0.1.0.box
Box successfully built by Packer.
Attempting to add metasploitable3-win2k8 box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'rapid7/metasploitable3-win2k8' (v0) for provider:
    box: Unpacking necessary files from: file://F:/metasploitable3-master/packer/builds/windows_2008_r2_virtualbox_0.1.0.box
    box:
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x Vagrantfile
x box.ovf
x metadata.json
x metasploitable3-win2k8-disk001.vmdk: Write failed
bsdtar.EXE: Error exit delayed from previous errors.
Error adding metasploitable3-win2k8 box to Vagrant. See the above output for any error messages.
At F:\metasploitable3-master\build.ps1:166 char:13
+             throw "Error adding metasploitable3-$os_short box to Vagr ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error adding me...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error adding metasploitable3-win2k8 box to Vagrant. See the above output for any error messages.

Once again, I sincerely appreciate the help!

**Comment by jmartin-r7** [comment]
`metasploitable3-win2k8-disk001.vmdk: Write failed` suggests either it ran out of disk space or a hardware failure.

How much free space does the volume your vagrant install caches to have?

**Comment by g0nff** [comment]
Hi there!

It turns out that the default directory that the vagrant box was unpacking into was on a drive that was lacking space. I changed the default path. Then, it still wouldn't work until I found someone mention online that you need to restart powershell before the changes to your environment variables will be in effect. Once, I restarted powershell, everything went off without a hitch.

I really appreciate the help!
