### ISSUE TITLE
Building windows version fails

### ISSUE THREAD

**Issue by barakat-abweh** [rapid7/metasploitable3#408]
## Issue Description
**Building windows version fails

## Host System
* OS: Debian 9
*Packer Version: 0.10.2
*Vagrant Version: Vagrant 1.9.1
 *VirtualBox Version: 6.0.8

## Command Output
building windows 2008
Compatible version of VirtualBox found.
Virtualbox images will be built.
Compatible version of packer was found.
Correct version of vagrant was found.
Compatible version of vagrant-libvirt plugin was found.
KVM image will be built.
Fetching virtio drivers required for build
.virtio-stable.vfd already exists, skipping download.
Compatible version of vagrant-reload plugin was found.
Requirements found. Proceeding...
Building the Vagrant box for qemu...
qemu output will be in this color.

==> qemu: Downloading or copying ISO
    qemu: Downloading or copying: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
==> qemu: Creating floppy disk...
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../answer_files/2008_r2/Autounattend.xml
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../scripts/configs/microsoft-updates.bat
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../scripts/configs/win-updates.ps1
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../scripts/installs/openssh.ps1
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../scripts/installs/install_dotnet45.ps1
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../scripts/installs/install_wmf.ps1
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/oracle-cert.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/gdig2.crt
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/comodorsadomainvalidationsecureserverca.crt
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/comodorsacertificationauthority.crt
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/addtrust_external_ca.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/baltimore_ca.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/digicert.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/equifax.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/globalsign.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/gte_cybertrust.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/microsoft_root_2011.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/thawte_primary_root.cer
    qemu: Copying: /home/barakat/Downloads/metasploitable3/packer/templates/../../resources/certs/utn-userfirst.cer
    qemu: Copying: ./resources/drivers/virtio/*
==> qemu: Deleting output directory...
Build 'qemu' errored: Error adding file to floppy: name already exists: netkvm.cat

==> Some builds didn't complete successfully and had errors:
--> qemu: Error adding file to floppy: name already exists: netkvm.cat

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.

**Comment by jmartin-r7** [comment]
Your configuration looks to be attempting to building for `qemu/libvirt` however you note Virtualbox as your target.  Please build using the alternative manual packer build process [here](https://github.com/rapid7/metasploitable3#to-build-manually).  The provider needs to be clarified manually when the env provides more than one. 

Also please try packer version `1.3.4` or greater due to configuration syntax requirements.
