### ISSUE TITLE
manually build the img is failed

### ISSUE THREAD

**Issue by skylning** [rapid7/metasploitable3#410]
Hi,i follow the readme guid to build the img,i execute the command "packer build --only=<provider> ./packer/templates/windows_2008_r2.json  and at the end,i got a failed msg as follow,somebody can help me?thanks.

 vmware-iso: Waiting 10m0s for boot...
==> vmware-iso: Connecting to VM via VNC (127.0.0.1:5983)
==> vmware-iso: Error detecting host IP: Unable to find host IP from devices [nat], last error: No host declarations containing nat found
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error detecting host IP: Unable to find host IP from devices [nat], last error: No host declarations containing nat found

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error detecting host IP: Unable to find host IP from devices [nat], last error: No host declarations containing nat found

==> Builds finished but no artifacts were created.

**Comment by ReddingZH** [comment]
I had the same error:
`Build 'vmware-iso' errored: Error detecting host IP: Unable to find host IP from devices [nat], last error: No host declarations containing nat found`

This is packer https://github.com/hashicorp/packer not being able to properly access the virtual NAT network in vmware. In my case packer had troubles with my custom defined virtual NAT network. Configuring VMnet8 back to its default settings (NAT) in the vmware virtual network editor solved the problem for me.

**Comment by jmartin-r7** [comment]
Closing as 'packer` and `vmware` environment issue.
