### ISSUE TITLE
/build.sh windows2008 error - Glassfish

### ISSUE THREAD

**Issue by jorgitux** [rapid7/metasploitable3#411]
## Issue Description
**Building windows version fails

## Host System
* OS: Linux Mint 19.2 (kernel 4.15.0-65-generic)
* Packer Version: 1.4.3
* Vagrant Version: 2.2.5
* VirtualBox Version: 6.0.12 r133076 (Qt5.9.5)

## Command Output
./build.sh windows2008
....
==> virtualbox-iso: Provisioning with shell script: /home/jorgitux/Metasploitable3/packer/templates/../../scripts/installs/setup_glassfish.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>mkdir C:\glassfish
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')"  0<NUL
==> virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The request was
==> virtualbox-iso: aborted: Could not create SSL/TLS secure channel."
==> virtualbox-iso: At line:1 char:1
==> virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('http://download.java. ...
==> virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> virtualbox-iso:     + FullyQualifiedErrorId : WebException
==> virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"
==> virtualbox-iso:
    virtualbox-iso:
==> virtualbox-iso: ERROR: The system cannot find the file specified.
==> virtualbox-iso: C:\Windows\Temp\glassfish4.zip
    virtualbox-iso: 7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
    virtualbox-iso:
==> virtualbox-iso:
==> virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\admin-keyfile"
    virtualbox-iso:         0 file(s) copied.
    virtualbox-iso:
==> virtualbox-iso:
==> virtualbox-iso: System ERROR:
==> virtualbox-iso: The system cannot find the file specified.
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\domain.xml"
==> virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:         0 file(s) copied.
==> virtualbox-iso: The system cannot find the path specified.
==> virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start domain1
==> virtualbox-iso: The service name is invalid.
    virtualbox-iso:
==> virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 10"
==> virtualbox-iso: More help is available by typing NET HELPMSG 2185.
==> virtualbox-iso:
==> virtualbox-iso: The service name is invalid.
    virtualbox-iso:
==> virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net stop domain1
==> virtualbox-iso: More help is available by typing NET HELPMSG 2185.
    virtualbox-iso:
==> virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
    virtualbox-iso: processed file: C:\glassfish
    virtualbox-iso: Successfully processed 1 files; Failed processing 0 files
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 36.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.

**Comment by aether0011** [comment]
I have the same issue too, but I am using vmware on macos.

**Comment by intelburn** [comment]
I am having the same issue on Ubuntu Virtualbox

**Comment by mgeeky** [comment]
Here's what fixed the issue for me.

1. Open up the file:
`scripts/installs/setup_glassfish.bat`

2. And change the second line, from:
```powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')" <NUL```

to:

```powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')" <NUL```

**Comment by aether0011** [comment]
Thanks!

**Comment by jorgitux** [comment]
Thanks!
