### ISSUE TITLE
Unable to ping ub1404 from kali and wink28

### ISSUE THREAD

**Issue by aether0011** [rapid7/metasploitable3#413]
Host System
* OS: macOS
* Packer Version: v1.4.4
* Vagrant Version: 2.2.5
* VirtualBox Version: 6.0.12

Hi all, I couldn't ping the ub1404 within the virtual network after setting it up, both static IP and NAT network didn't help in this case.

Someone posted with the **exact same issue** one year ago, wondering if anybody else came across and managed to fix it? TIA!
https://github.com/rapid7/metasploitable3/issues/337

**Comment by aether0011** [comment]
fixed by changing the network to "host-only adaptor" on virtual box

**Comment by Sliim** [comment]
In my case I had to add an iptables rule to allow ICMP:
https://github.com/rapid7/metasploitable3/issues/393
https://github.com/rapid7/metasploitable3/pull/394
