### ISSUE TITLE
Build Script build_win2008.ps1: Version comparison not working

### ISSUE THREAD

**Issue by HannesBBR** [rapid7/metasploitable3#42]
In Powershell (on W8.1), the build script fails when comparing the versions of e.g. VirtualBox in the `CompareVersions ` function. 

When `$exactMatch` is set to `$True,` the check `$actualVersion -eq $expectedVersion` fails because the strings are split and the resulting lists can't be compared with `-eq`.

This can be fixed by moving the splitting of `$actualVersion` and `$expectedVersion` after the first If-block.

	function CompareVersions ($actualVersion, $expectedVersion, $exactMatch = $False) {
		If ($exactMatch) {
			If ($actualVersion -eq $expectedVersion) {
				return $True
			} else {
				return $False
			}
		}

		$actualVersion = $actualVersion.split(".")
		$expectedVersion = $expectedVersion.split(".")

		for($i=0; $i -le $expectedVersion.length; $i++) {
			If([INT]$actualVersion[$i] -gt [INT]$expectedVersion[$i]) {
				return $True
			}

			If([INT]$actualVersion[$i] -lt [INT]$expectedVersion[$i]) {
				return $False
			}
		}
		return $True
	}

**Comment by jbarnett-r7** [comment]
This is what I get for committing changes without testing them first :). Thank you for the help! I'm still getting used to PowerShell. I'll make the change.
