### ISSUE TITLE
Can't "vagrant up" Windows or Ubuntu box after successful packer build for libvirt

### ISSUE THREAD

**Issue by obitori** [rapid7/metasploitable3#427]
## Issue Description
I can manually build the libvirt version of Metasploitable3 Win2k8 and manually add it to vagrant, but then vagrant up rejects the box this this error:

> The machine with the name 'ms3-win2k8' was not found configured for
this Vagrant environment.

## Host System
* OS:  Ubuntu 19.10 server
* Packer Version:  1.3.4
* Vagrant Version:  2.2.6
* VirtualBox Version:  qemu-system-x86_64 [QEMU emulator version 4.0.0 (Debian 1:4.0+dfsg-0ubuntu9)]

## Command Output
$ PACKER_LOG=1 packer build --only=qemu packer/templates/windows_2008_r2.json 
[[[SNIP -- COMPLETES SUCCESSFULLY]]]
$ vagrant box add packer/builds/windows_2008_r2_libvirt_0.1.0.box --name=ms3-win2k8 --provider=libvirt
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'ms3-win2k8' (v0) for provider: libvirt box: Unpacking necessary files from: file:///home/metasploitable3/packer/builds/windows_2008_r2_libvirt_0.1.0.box
==> box: Successfully added box 'ms3-win2k8' (v0) for 'libvirt'!
$ vagrant up ms3-win2k8
The machine with the name 'ms3-win2k8' was not found configured for
this Vagrant environment.

**Comment by obitori** [comment]
Same problem with Ubuntu 14.04 build:
```
$ packer build --only=qemu packer/templates/ubuntu_1404.json
[[[SNIP -- BUILD PROCEEDS NO ERRORS]]]
    qemu: Chef Client finished, 231/283 resources updated in 09 minutes 42 seconds
==> qemu: Gracefully halting virtual machine...
==> qemu: Converting hard drive...
==> qemu: Running post-processor: vagrant
==> qemu (vagrant): Creating Vagrant box for 'libvirt' provider
    qemu (vagrant): Copying from artifact: output-qemu/metasploitable3-ub1404
    qemu (vagrant): Compressing: Vagrantfile
    qemu (vagrant): Compressing: box.img
    qemu (vagrant): Compressing: metadata.json
Build 'qemu' finished.

==> Builds finished. The artifacts of successful builds are:
--> qemu: 'libvirt' provider box: /home/metasploitable3/packer/templates/../builds/ubuntu_1404_libvirt_0.1.12.box
```
```
$ vagrant box add packer/builds/ubuntu_1404_libvirt_0.1.12.box --name=ms3-ub14 --provider=libvirt
==> box: Box file was not detected as metadata. Adding it directly...
==$ packer build --only=qemu packer/templates/ubuntu_1404.json> box: Adding box 'ms3-ub14' (v0) for provider: libvirt
```
```
$ packer build --only=qemu packer/templates/ubuntu_1404.jsonox: Unpacking necessary files from: file:///home/metasploitable3/packer/builds/ubuntu_1404_libvirt_0.1.12.box
==> box: Successfully added box 'ms3-ub14' (v0) for 'libvirt'!
obitori@anthill:/home/metasploitable3$ vagrant box list
ms3-ub14   (libvirt, 0)
ms3-win2k8 (libvirt, 0)
obitori@anthill:/home/metasploitable3$ vagrant up ms3-ub14
The machine with the name 'ms3-ub14' was not found configured for
this Vagrant environment.
```

**Comment by obitori** [comment]
I was able to repeat the steps on a different Ubunt 19.10 machine (desktop version) and got the same errors.

**Comment by deargle** [comment]
`vagrant up` will look for a device with a matching name in your local `Vagrantfile` to initialize. The vagrantfile points to the box name. You shouldn't be specifying the box name with `vagrant up`. For example, the docs manual build add a box with with command:

   vagrant box add packer/builds/windows_2008_r2_*_0.1.0.box --name=metasploitable3-win2k8

But then `vagrant up win2k8` -- _not_ `metasploitable3-win2k8`. The repo's `Vagrantfile` defines a box wity key `win2k8`, here https://github.com/rapid7/metasploitable3/blob/6a175018246326eac1e90d2146f94f6a685779fd/Vagrantfile#L20

If you're building manually, you can run `vagrant init <boxname>`, which will make a vagrantfile for you pointing to the correct box. Or you can make your own vagrantfile.

**Comment by jmartin-r7** [comment]
Closing as user vagrant env issue.
