### ISSUE TITLE
Backdoor:MSIL/Sorcas

### ISSUE THREAD

**Issue by 4th3LuLz0fIt** [rapid7/metasploitable3#428]
## Issue Description
Issue: The file triggers Windows Defender as a backdoor 
file: C:\Users\KingLulz\OneDrive\Documents\Virtual Machines\metasploitable3-master\metasploitable3-master\resources\jmx\jmx.exe

**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: WIndows 10
* Packer Version:
* Vagrant Version: Vagrant 2.2.6
* VirtualBox Version: VMware15

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by bcoles** [comment]
This is false-positive. See:

* #280
* #346
