### ISSUE TITLE
Ubuntu 1404 Build Fails: ERROR: remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz] (metasploitable::proftpd line 30) had an error: Errno::ENETUNREACH: Network is unreachable

### ISSUE THREAD

**Issue by ahusmc** [rapid7/metasploitable3#430]
## Issue Description
Ubuntu 1404 Build Fails: ERROR: remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz] (metasploitable::proftpd line 30) had an error: Errno::ENETUNREACH: Network is unreachable

## Host System
OS: Windows 10 Pro 10.0.18363
Packer Version: 1.4.5
Vagrant Version: 2.2.6
VirtualBox Version: 6.0.14 r133895 (Qt5.6.2)

## Command Output
virtualbox-iso: Recipe: metasploitable::proftpd
    virtualbox-iso:   * execute[extract proftpd] action nothing (skipped due to action :nothing)
    virtualbox-iso:   * bash[compile and install proftpd] action nothing (skipped due to action :nothing)
    virtualbox-iso:   * remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz] action create_if_missing
    virtualbox-iso:
    virtualbox-iso:     ================================================================================
    virtualbox-iso:     Error executing action `create_if_missing` on resource 'remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz]'
    virtualbox-iso:     ================================================================================
    virtualbox-iso:
    virtualbox-iso:     Errno::ENETUNREACH
    virtualbox-iso:     ------------------
    virtualbox-iso:     Network is unreachable - connect(2) for [2001:858:2:5::5]:21
    virtualbox-iso:
    virtualbox-iso:     Resource Declaration:
    virtualbox-iso:     ---------------------
    virtualbox-iso:     # In /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/proftpd.rb
    virtualbox-iso:
    virtualbox-iso:      30: remote_file "#{Chef::Config[:file_cache_path]}/#{proftpd_tar}" do
    virtualbox-iso:      31:   source "#{node[:proftpd][:download_url]}/#{proftpd_tar}"
    virtualbox-iso:      32:   mode '0644'
    virtualbox-iso:      33:   action :create_if_missing
    virtualbox-iso:      34:   not_if { File.exists?( '/opt/proftpd/sbin/proftpd' ) }
    virtualbox-iso:      35:   notifies :run, 'execute[extract proftpd]', :immediately
    virtualbox-iso:      36:   notifies :run, 'bash[compile and install proftpd]', :immediately
    virtualbox-iso:      37: end
    virtualbox-iso:      38:
    virtualbox-iso:
    virtualbox-iso:     Compiled Resource:
    virtualbox-iso:     ------------------
    virtualbox-iso:     # Declared in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/metasploitable/recipes/proftpd.rb:30:in `from_file'
    virtualbox-iso:
    virtualbox-iso:     remote_file("/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz") do
    virtualbox-iso:       provider Chef::Provider::RemoteFile
    virtualbox-iso:       action [:create_if_missing]
    virtualbox-iso:       default_guard_interpreter :default
    virtualbox-iso:       source ["ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz"]
    virtualbox-iso:       use_etag true
    virtualbox-iso:       use_last_modified true
    virtualbox-iso:       declared_type :remote_file
    virtualbox-iso:       cookbook_name "metasploitable"
    virtualbox-iso:       recipe_name "proftpd"
    virtualbox-iso:       mode "0644"
    virtualbox-iso:       remote_domain nil
    virtualbox-iso:       remote_user nil
    virtualbox-iso:       path "/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz"
    virtualbox-iso:       owner nil
    virtualbox-iso:       group nil
    virtualbox-iso:       checksum nil
    virtualbox-iso:       verifications []
    virtualbox-iso:       not_if { #code block }
    virtualbox-iso:     end
    virtualbox-iso:
    virtualbox-iso:     System Info:
    virtualbox-iso:     ------------
    virtualbox-iso:     chef_version=13.8.5
    virtualbox-iso:     platform=ubuntu
    virtualbox-iso:     platform_version=14.04
    virtualbox-iso:     ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    virtualbox-iso:     program_name=chef-solo worker: ppid=1089;start=01:26:21;
    virtualbox-iso:     executable=/opt/chef/bin/chef-solo
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Running handlers:
    virtualbox-iso: [2019-11-21T01:37:10+00:00] ERROR: Running exception handlers
    virtualbox-iso: [2019-11-21T01:37:10+00:00] ERROR: Running exception handlers
    virtualbox-iso: Running handlers complete
    virtualbox-iso: [2019-11-21T01:37:10+00:00] ERROR: Exception handlers complete
    virtualbox-iso: [2019-11-21T01:37:10+00:00] ERROR: Exception handlers complete
    virtualbox-iso: Chef Client failed. 86 resources updated in 10 minutes 48 seconds
    virtualbox-iso: [2019-11-21T01:37:10+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2019-11-21T01:37:10+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    virtualbox-iso: [2019-11-21T01:37:10+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2019-11-21T01:37:10+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    virtualbox-iso: [2019-11-21T01:37:10+00:00] ERROR: remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz] (metasploitable::proftpd line 30) had an error: Errno::ENETUNREACH: Network is unreachable - connect(2) for [2001:858:2:5::5]:21
    virtualbox-iso: [2019-11-21T01:37:10+00:00] ERROR: remote_file[/tmp/packer-chef-solo/local-mode-cache/cache/proftpd-1.3.5.tar.gz] (metasploitable::proftpd line 30) had an error: Errno::ENETUNREACH: Network is unreachable - connect(2) for [2001:858:2:5::5]:21
    virtualbox-iso: [2019-11-21T01:37:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    virtualbox-iso: [2019-11-21T01:37:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> virtualbox-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error executing Chef: Non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error executing Chef: Non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At C:\Users\ahusm\VirtualBox VMs\metasploitable3-master\build.ps1:157 char:10
+          throw "Error building the Vagrant box using Packer. Please c ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by deargle** [comment]
This error suggests that your VM did not have an internet connection to be able to download ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz as part of the chef provisioning step.

**Comment by ahusmc** [comment]
@deargle That's strange the VM was able to connect to all of the endpoints and download the required resources before this particular chef provisioning step. Any suggestions?

**Comment by deargle** [comment]
Maybe ftp.proftpd.org was down for a minute? Has it failed more than once at that same spot?

**Comment by ahusmc** [comment]
Unfortunately, yes. It failed three times. All in one day though. I can give it another go later today. I wish the R7 guys would put out preconfigured OVAs that we could download.

**Comment by deargle** [comment]
I think the vagrant one _is_ ready to go -- you don't have to build it yourself.

This one: https://github.com/rapid7/metasploitable3/blob/6a175018246326eac1e90d2146f94f6a685779fd/Vagrantfile#L7

**Comment by ahusmc** [comment]
Sweet. Thanks.

**Comment by deargle** [comment]
I'm curious whether you were able to navigate to ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz in a browser from the box where the ubuntu build was failing?

**Comment by ahusmc** [comment]
Hi, @deargle. 

After about two minutes of trying to access the resource at the url, I got the following error. I think something might be wrong with the resource or the provider.

![image](https://user-images.githubusercontent.com/6530557/69890802-b8a94f80-12ac-11ea-9433-a33204b686cb.png)

**Comment by deargle** [comment]
That Alert appears after you click "OK" on "Save File"?

**Comment by ahusmc** [comment]
It might just be my computer. I tried the ftp download on Firefox, Chrome, and Edge, and the download timed out every time. I'll try on a different host and see if I can build the Ubuntu VM.

**Comment by Parveshdhull** [comment]
@ahusmc I also faced this issue, but I seen something like this earlier and I knew that this domain is getting blocked by my ISP. So I tried link using VPN and it worked.
