### ISSUE TITLE
Trojan and Mallware detected in download

### ISSUE THREAD

**Issue by brucemcmillan** [rapid7/metasploitable3#434]
## Issue Description
downloaded zip file and Sophos reports

Troj/Swrort-PQ detected in zip file

Mal/Generic-S Detected in Metaploitable3-master.zip 

<img width="387" alt="Capture" src="https://user-images.githubusercontent.com/4041335/72202884-7ef76700-345c-11ea-8e56-d7621b5c9b8f.PNG">

**Comment by jmartin-r7** [comment]
This is a false positive due to applications used to execute windows services see #196 and #280.  We do submit committed binaries for whitelisting by vendors when flagged however the repository branches for every commit would not scale for this process.
