### ISSUE TITLE
Update http: install_elasticsearch.bat

### ISSUE THREAD

**Issue by bajaguy** [rapid7/metasploitable3#435]
Change download command from:

powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/1.1.1/elasticsearch-1.1.1.zip', 'C:\Windows\Temp\elasticsearch-1.1.1.zip')" <NUL

To:
powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('http://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/1.1.1/elasticsearch-1.1.1.zip', 'C:\Windows\Temp\elasticsearch-1.1.1.zip')" <NUL

## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by technonerd33** [comment]
Still failing, the url needs to also be updated to https://

Snippet from wireshark

> GET /maven2/org/elasticsearch/elasticsearch/1.1.1/elasticsearch-1.1.1.zip HTTP/1.1\r\n
> HTTP/1.1 501 HTTPS Required\r\n

**Comment by bajaguy** [comment]
My mistake, meant to add that. I've done a test build with https and it passed.

**Comment by whaber** [comment]
I was able to fix this via #439

**Comment by jmartin-r7** [comment]
Fixed by #439
