### ISSUE TITLE
Error During Manual Build For Vmware

### ISSUE THREAD

**Issue by nem0n** [rapid7/metasploitable3#437]
An error occurring due to changed made in download link:
![image](https://user-images.githubusercontent.com/25449049/73227238-e55cd480-4140-11ea-9b7d-a4b1d0a915dd.png)

Download link needs to be replaced with https instead of HTTP to solve the problem

Thank you

**Comment by nem0n** [comment]
Now after replacing it's giving error saying "The request was aborted: Could not create SSL/TLS secure channel."

**Comment by deargle** [comment]
https://github.com/rapid7/metasploitable3/issues/435

**Comment by whaber** [comment]
I was able to fix this via #439
