### ISSUE TITLE
 virtualbox-iso: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

### ISSUE THREAD

**Issue by IsaacSxm** [rapid7/metasploitable3#440]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Windows 10
* Packer Version: 1.5.1_windows_amd64.zip
* Vagrant Version: 2.2.7_x86_64.msi
* VirtualBox Version: 6.1.2-135663-Win.exe

I get the same error when i use virtual box.

## Command Output
C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\elasticsearch-1.1.1.zip" -o"C:\Program Files\""
==> vmware-iso:
    vmware-iso:
==> vmware-iso: ERROR: The system cannot find the file specified.
    vmware-iso: 7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
==> vmware-iso: C:\Windows\Temp\elasticsearch-1.1.1.zip
==> vmware-iso:
==> vmware-iso:
==> vmware-iso:
    vmware-iso:
==> vmware-iso: System ERROR:
    vmware-iso: Scanning the drive for archives:
==> vmware-iso: The system cannot find the file specified.
==> vmware-iso: The system cannot find the path specified.
==> vmware-iso: The system cannot find the path specified.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" install"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config "elasticsearch-service-x64" start= auto
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" start"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 30"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "$req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()"
==> vmware-iso: the remote server"
==> vmware-iso: At line:1 char:108
==> vmware-iso: + ... host:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()
==> vmware-iso: +                                                        ~~~~~~~~~~~~~~~~~~
==> vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> vmware-iso:     + FullyQualifiedErrorId : WebException
==> vmware-iso:
    vmware-iso:
chy\", \"post_date\": \"2009-11-15T14:12:12\", \"message\": \"Elasticsearch\" }'); $req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.method = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()"
==> vmware-iso: Exception calling "GetRequestStream" with "0" argument(s): "Unable to connect
==> vmware-iso: to the remote server"
==> vmware-iso: At line:1 char:307
==> vmware-iso: + ... ion/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $strea ...
==> vmware-iso: +                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> vmware-iso:     + FullyQualifiedErrorId : WebException
==> vmware-iso:
==> vmware-iso: You cannot call a method on a null-valued expression.
==> vmware-iso: At line:1 char:342
==> vmware-iso: + ... req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $strea ...
==> vmware-iso: +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vmware-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
==> vmware-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
==> vmware-iso:
==> vmware-iso: You cannot call a method on a null-valued expression.
==> vmware-iso: At line:1 char:381
==> vmware-iso: + ... eam(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.G ...
==> vmware-iso: +                                                   ~~~~~~~~~~~~~~~
==> vmware-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
==> vmware-iso:
==> vmware-iso: Exception calling "GetResponse" with "0" argument(s): "You must provide a
==> vmware-iso: request body if you set ContentLength>0 or SendChunked==true.  Do this by
==> vmware-iso: calling [Begin]GetRequestStream before [Begin]GetResponse."
==> vmware-iso: At line:1 char:398
==> vmware-iso: + ... am.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()
==> vmware-iso: +                                                        ~~~~~~~~~~~~~~~~~~
==> vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> vmware-iso:
==> vmware-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by deargle** [comment]
holy smokes y'all bad at reading open issues

#439 #436 #435

**Comment by IsaacSxm** [comment]
Thanks a lot @deargle . You helped me fix this. Build was successful. 

Build 'vmware-iso' finished.

==> Builds finished. The artifacts of successful builds are:

**Comment by jmartin-r7** [comment]
Fixed by #439
