### ISSUE TITLE
Downloading software using chocolatey in China has timed out, is there any other way (plus the agent can not download)

### ISSUE THREAD

**Issue by Fantomo** [rapid7/metasploitable3#446]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
    vmware-iso: jre8 v8.0.241 [Approved]
    vmware-iso: jre8 package files install completed. Performing other installation steps.
    vmware-iso: The software license has changed for Java and this software must be licensed for general business use. Please ensure your licensing is compliant before installing.
    vmware-iso: Checking to see if local install is already up to date...
    vmware-iso: Downloading 32-bit installer
    vmware-iso: Attempt to get headers for https://javadl.oracle.com/webapps/download/AutoDL?BundleId=241534_1f5b5a70bf22433b84d0e960903adac8 failed.
    vmware-iso:   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://javadl.oracle.com/webapps/download/AutoDL?BundleId=241534_1f5b5a70bf22433b84d0e960903adac8'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
    vmware-iso: Downloading jre8
    vmware-iso:   from 'https://javadl.oracle.com/webapps/download/AutoDL?BundleId=241534_1f5b5a70bf22433b84d0e960903adac8'
    vmware-iso: ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://javadl.oracle.com/webapps/download/AutoDL?BundleId=241534_1f5b5a70bf22433b84d0e960903adac8'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
    vmware-iso: This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
    vmware-iso: The install of jre8 was NOT successful.
    vmware-iso: Error while running 'C:\ProgramData\chocolatey\lib\jre8\tools\chocolateyInstall.ps1'.
    vmware-iso:  See log for details.
    vmware-iso:
    vmware-iso: javaruntime-platformspecific v7.0.79.20161125 [Approved]
    vmware-iso: javaruntime-platformspecific package files install completed. Performing other installation steps.
    vmware-iso:  The install of javaruntime-platformspecific was successful.
    vmware-iso:   Software install location not explicitly set, could be in package or
    vmware-iso:   default install location if installer.
    vmware-iso:
    vmware-iso: Chocolatey installed 1/2 packages. 1 packages failed.
    vmware-iso:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    vmware-iso:
    vmware-iso: Failures
    vmware-iso:  - jre8 (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\jre8\tools\chocolateyInstall.ps1'.
    vmware-iso:  See log for details.

**Comment by bcoles** [comment]
Can you access the web archive?

* http://web.archive.org/web/20200120182706/https://javadl.oracle.com/webapps/download/AutoDL?BundleId=241534_1f5b5a70bf22433b84d0e960903adac8
* http://web.archive.org/web/20200120182706if_/https://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/8u241-b07/1f5b5a70bf22433b84d0e960903adac8/jre-8u241-windows-i586.exe?GroupName=JSC&FilePath=/ESD6/JSCDL/jdk/8u241-b07/1f5b5a70bf22433b84d0e960903adac8/jre-8u241-windows-i586.exe&BHost=javadl.sun.com&File=jre-8u241-windows-i586.exe&AuthParam=1579546026_c5aca16897057919cf17404008d4ae97&ext=.exe

Otherwise, perhaps you could route your network traffic via an inferior country.

**Comment by deargle** [comment]
Does everyone realize that there are prebuilt vagrant boxes? Instructions
at top of readme.

**Comment by qingsword** [comment]
I have the same problem, download these software to the local web server through vpn, and then modify the download path in the install file to own local web server

**Comment by qingsword** [comment]
But I cannot download some components installed by command:(

**Comment by qingsword** [comment]
for example：Here will timeout failure:(
vmware-iso: C:\Users\vagrant>cmd /C "C:\tools\ruby23\bin\gem.cmd install rails -v '4.1.1' --no-ri --no-rdoc"

**Comment by Fantomo** [comment]
> I have the same problem, download these software to the local web server through vpn, and then modify the download path in the install file to own local web server

Yes, my solution is similar to yours, use the foreign server to download and then pull it back to the local

**Comment by jmartin-r7** [comment]
Closing as answered, unfettered internet access is a requirement to build base this repository at this time.  

Files install via chocolatey can be overriden similar to the example below from another project however implementation is left to the user for this project.

https://github.com/rapid7/metasploit-baseline-builder/blob/5d6c29e4a4886da2b47f1e5a53b4888f0430b33d/scripts/chocolatey_installs/python2.bat#L2-L4
