### ISSUE TITLE
Handle incompleted build

### ISSUE THREAD

**Issue by Samega7Cattac** [rapid7/metasploitable3#448]
## Issue Description
Windows even in VM is very unstable on my laptop, sometime it freezes completely and the build process is aborted. is there any way to continue from where I was? (exporting process)
The command output is when I try to run `./build.sh windows2008` again

## Host System
* OS: Arch Linux, 5.5.7-arch1-1
* Packer Version: 1.5.4
* Vagrant Version: 2.2.7
* VirtualBox Version: 6.1.4 r136177

## Command Output
```
...
==> virtualbox-iso: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso?checksum=md5%3A4263be2cf3c59177c45085c0a7bc6ca5 => /run/media/samega7cattac/Data/VMs/metasploitable3/packer_cache/c969d0a251f6f1d43e47e146749928fecb7568ab.iso
Build 'virtualbox-iso' errored: Output directory exists: output-virtualbox-iso

Use the force flag to delete it prior to building.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Output directory exists: output-virtualbox-iso

Use the force flag to delete it prior to building.

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.
```

**Comment by jmartin-r7** [comment]
Unfortunately `packer` is pass or fail for the complete process.

The error noted in this issue refers to a failure by `packer` to cleanup the temporary path at `output-virtualbox-iso` cleanup on script start could be added.
