### ISSUE TITLE
Error starting VM

### ISSUE THREAD

**Issue by mother2110** [rapid7/metasploitable3#45]
I am running this on Ubuntu Mate 16.04 but get this error. I am new to this so any guidance is appreciated.

==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1479314325 --memory 2048
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1479314325 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: 127.0.0.1:5905
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'packer-virtualbox-iso-1479314325' has terminated unexpectedly during startup with exit code 1 (0x1)
==> virtualbox-iso: VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'packer-virtualbox-iso-1479314325' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'packer-virtualbox-iso-1479314325' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by wchen-r7** [comment]
Hi @mother2110, what version is your virtual box? Thanks.

**Comment by tnickb6782** [comment]
Same issue, using virtual box 5.1.6r110634

**Comment by pat-riot** [comment]
Same issue; this is from the automated build (build_win2008.sh).

System:
```
- Debian 8 ('Jesse') Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
- VirtualBox Version 5.1.8 r111374 (Qt5.3.2)
```

VirtualBox was installed from Oracle deb package using dpkg.
I can provide more info it it'll help.  Not a VirtualBox user so not sure what's useful info and what isn't.

**Comment by pat-riot** [comment]
Here's the relevant output from `vboxbugreport`
```
VirtualBox XPCOM Server 5.1.8 r111374 linux.amd64 (Oct 18 2016 15:36:00) release log
00:00:00.000262 main     Log opened 2016-11-16T18:24:22.612227000Z
00:00:00.000266 main     Build Type: release
00:00:00.000286 main     OS Product: Linux
00:00:00.000288 main     OS Release: 3.16.0-4-amd64
00:00:00.000291 main     OS Version: #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)
00:00:00.000327 main     DMI Product Name: <cut>
00:00:00.000340 main     DMI Product Version: 
00:00:00.000456 main     Host RAM: 32166MB (31.4GB) total, 26814MB (26.1GB) available
00:00:00.000464 main     Executable: /usr/lib/virtualbox/VBoxSVC
00:00:00.000466 main     Process ID: 9864
00:00:00.000468 main     Package type: LINUX_64BITS_DEBIAN_8_0
00:00:00.002300 main     IPC socket path: /tmp/.vbox-<cut>-ipc/ipcd
00:00:00.106056 nspr-2   VirtualBox: object creation starts
00:00:00.106142 nspr-2   Home directory: '/home/<cut>/.config/VirtualBox'
00:00:00.109220 nspr-2   NetIfAdpCtlOut: VBoxNetAdpCtl: Error while retrieving link status for vmnet1: VBoxNetAdpCtl: ioctl failed: Operation not supported
00:00:00.111448 nspr-2   NetIfAdpCtlOut: VBoxNetAdpCtl: Error while retrieving link status for vmnet8: VBoxNetAdpCtl: ioctl failed: Operation not supported
00:00:00.112225 nspr-2   NAT: resolv.conf: nameserver <cut>
00:00:00.112245 nspr-2   NAT: resolv.conf: nameserver <cut>
00:00:00.112297 nspr-2   HostDnsMonitor: old information
00:00:00.112306 nspr-2     no server entries
00:00:00.112314 nspr-2     no domain set
00:00:00.112319 nspr-2     no search string entries
00:00:00.112324 nspr-2   HostDnsMonitor: new information
00:00:00.112329 nspr-2     server 1: <cut>
00:00:00.112335 nspr-2     server 2: <cut>
00:00:00.112341 nspr-2     domain: <cut>
00:00:00.112346 nspr-2     search string 1: <cut>
00:00:00.112352 nspr-2     search string 2: <cut>
00:00:00.112357 nspr-2     search string 3: <cut>
00:00:00.112368 nspr-2   HostDnsMonitorProxy::notify
00:00:00.114028 nspr-2   Support driver version mismatch: DriverVersion=0x1a000b ClientVersion=0x280000 rc=VERR_VERSION_MISMATCH
00:00:00.114246 nspr-2   VD: VDInit finished
00:00:00.114739 nspr-2   VirtualBox: object created
00:00:13.280106 main     VirtualBox: object deletion starts
00:00:13.618055 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={0169423f-46b4-cde9-91af-1e9d5b6cd945} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:00:18.280762 main     {00007fb150016ef0} HostPowerServiceLinux::~HostPowerServiceLinux: RTThreadWait() for 5000 ms failed with VERR_TIMEOUT
00:00:18.281109 main     VirtualBox: object deleted
```

**Comment by pat-riot** [comment]
when it doubt....
```
sudo apt-get purge virtualbox-5.1
sudo dpkg -i virtualbox-5.1_5.1.8-111374-Debian-jessie_amd64.deb
```

Fixed the issue in this thread.

**Comment by maximilli4n** [comment]
On kali-rolling, I was having the same issue, after downgrading from virtualbox 5.1.8 to 5.1.6. I think I uninstalled the 5.1.8 incorrectly, and the 5.1.8 kernel modules were conflicting with version 5.1.6. After following these steps, I was able to run build_win2008.sh without errors and finish the build of Metasploitable 3:

1. Uninstalled VirtualBox 5.1.6 by running /opt/VirtualBox/uninstall.sh
2. Uninstalled / purged all packages related to VirtualBox (apt-get list | grep -i virtualbox && dpkg -l | grep -i virtualbox)
3. Re-installed VirtualBox 5.1.6 using ./VirtualBox-5.1.6-110634-Linux_amd64.run

**Comment by mother2110** [comment]
I am using 5.1_5.1.6-110634~Ubuntu~xenial_amd64.deb

**Comment by moj0x0** [comment]
I'm having this same issue on the latest version of Kali Rolling.  I have tried @maximilli4n's suggestions a number of times and have not had any success.  I am running Virtualbox Version 5.1.6 r110634 (Qt5.6.1)

**Comment by chokepoint** [comment]
I also had to purge out virtualbox-dkms packages, and then reinstall with the .run file

**Comment by justarandomuser** [comment]
Same issue with 5.1.10 using Oracle's apt dist under Ubuntu 14.04.

Full purge and reinstall worked for me. Thanks @pat-riot!

**Comment by RobbieTheK** [comment]
Are there any plans to get this to work with a current VirtualBox in the 5.2 series and Ubuntu 17.10?
