### ISSUE TITLE
Unkown Configuration Key: ssh_wait_timeout

### ISSUE THREAD

**Issue by Sergyo97** [rapid7/metasploitable3#451]
## Issue Description
Unkown configuration key: ssh_wait_timeout.
I'm trying to build or validate the .json (windows_2008_r2.json) and no matter what console I'm using either bash or powershell, the error is the same. 

## Host System
* OS: Windows 10
* Packer Version: 1.5.4
* Vagrant Version: 2.2.7
* VirtualBox Version: 6.1

## Command Output
unknown configuration key: "ssh_wait_timeout"; raws is []interface {}{map[string]interface {}{"boot_wait":"10m", "communicator":"ssh", "disk_size":61440, "floppy_files":[]interface {}{"E:\\Metasploitable3\\packer\\templates/../answer_files/2008_r2/Autounattend.xml", "E:\\Metasploitable3\\packer\\templates/../../scripts/configs/microsoft-updates.bat", "E:\\Metasploitable3\\packer\\templates/../../scripts/configs/win-updates.ps1", "E:\\Metasploitable3\\packer\\templates/../../scripts/installs/openssh.ps1", "E:\\Metasploitable3\\packer\\templates/../../scripts/installs/install_dotnet45.ps1", "E:\\Metasploitable3\\packer\\templates/../../scripts/installs/install_wmf.ps1", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/oracle-cert.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/gdig2.crt", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/comodorsadomainvalidationsecureserverca.crt", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/comodorsacertificationauthority.crt", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/addtrust_external_ca.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/baltimore_ca.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/digicert.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/equifax.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/globalsign.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/gte_cybertrust.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/microsoft_root_2011.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/thawte_primary_root.cer", "E:\\Metasploitable3\\packer\\templates/../../resources/certs/utn-userfirst.cer"}, "guest_os_type":"windows7srv-64", "headless":false, "iso_checksum":"4263be2cf3c59177c45085c0a7bc6ca5", "iso_checksum_type":"md5", "iso_url":"http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso", "shutdown_command":"shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"", "ssh_password":"vagrant", "ssh_username":"vagrant", "ssh_wait_timeout":"2h", "tools_upload_flavor":"windows", "vm_name":"metasploitable3-win2k8", "vmx_data":map[interface {}]interface {}{"cpuid.coresPerSocket":"2", "memsize":"4096", "numvcpus":"2", "scsi0.virtualDev":"lsisas1068"}}, map[string]interface {}{"packer_build_name":"vmware-iso", "packer_builder_type":"vmware-iso", "packer_debug":false, "packer_force":false, "packer_on_error":"", "packer_template_path":"E:\\Metasploitable3\\packer\\templates\\windows_2008_r2.json", "packer_user_variables":map[interface {}]interface {}{"autounattend":"E:\\Metasploitable3\\packer\\templates/../answer_files/2008_r2/Autounattend.xml", "box_version":"0.1.0", "iso_checksum":"4263be2cf3c59177c45085c0a7bc6ca5", "iso_checksum_type":"md5", "iso_url":"http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso", "resources_dir":"E:\\Metasploitable3\\packer\\templates/../../resources", "scripts_dir":"E:\\Metasploitable3\\packer\\templates/../../scripts"}}}

 and ctx data is map[interface {}]interface {}(nil)

**Comment by jmartin-r7** [comment]
This has been going back and forth in the packer build for a little while see:
https://github.com/hashicorp/packer/pull/8662

Please try building with a packer version prior to `1.5.2` for now, I will leave this open for a while and any update can be completed once packer settles a bit.

**Comment by usr-redacted** [comment]
Edit line 13 of metasploitable3/packer/templates/windows_2008_r2.json 
from `"ssh_wait_timeout": "2h",` to `"ssh_timeout": "2h",`

Worked for me, building on MacOS 10.15.4, VMWare Fusion 11.5.3, Vagrant 2.2.7 & Packer 1.5.5

**Comment by jmartin-r7** [comment]
This has been addressed upstream with packer version requirements updates. See #562
