### ISSUE TITLE
vegrant not found

### ISSUE THREAD

**Issue by kaal-kali** [rapid7/metasploitable3#452]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1550  100  1550    0     0  43055      0 --:--:-- --:--:-- --:--:-- 43055
bash: vagrant: command not found

**Comment by jmartin-r7** [comment]
`vagrant` is not found on your path if you are attempting to use the `quick-start` you still must install vagrant and virtualization environment such as virtualbox:

>System Requirements:
>
>OS capable of running all of the required applications listed below
>VT-x/AMD-V Supported Processor recommended
>65 GB Available space on drive
>4.5 GB RAM
>Requirements:
>
>Packer
>Vagrant
>Vagrant Reload Plugin
>VirtualBox, libvirt/qemu-kvm, or vmware (paid license required)
>Internet connection
