### ISSUE TITLE
Downloading: packer/builds/windows_2008_r2_qemu_0.1.0.box An error occurred while downloading the remote file.

### ISSUE THREAD

**Issue by mathiasconradt** [rapid7/metasploitable3#454]
## Issue Description

At the end of the successful build via `./build.sh windows2008`, I get this error:

```
box: Downloading: packer/builds/windows_2008_r2_qemu_0.1.0.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

```

No error messages before that in the log. Build want through smoothly, just getting the boxes seems to fail in the end.

## Host System
* OS: Kali Linux Rolling
* Packer Version: 1.3.4
* Vagrant Version: 2.2.5
* VirtualBox Version:  6.1.4_Debian r136177

## Command Output

```
Build 'qemu' finished.

==> Builds finished. The artifacts of successful builds are:
--> qemu: 'libvirt' provider box: /home/jsmith/metasploitable3-2/packer/templates/../builds/windows_2008_r2_libvirt_0.1.0.box
Boxes successfully built by Packer.
It looks like the virtualbox vagrant box already exists. Skipping the build.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'rapid7/metasploitable3-win2k8' (v0) for provider: 
    box: Downloading: packer/builds/windows_2008_r2_qemu_0.1.0.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/jsmith/metasploitable3-2/packer/builds/windows_2008_r2_qemu_0.1.0.box
Error adding box to Vagrant. See the above output for any error messages.
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'rapid7/metasploitable3-win2k8' (v0) for provider: 
    box: Unpacking necessary files from: file:///home/jsmith/metasploitable3-2/packer/builds/windows_2008_r2_virtualbox_0.1.0.box
==> box: Successfully added box 'rapid7/metasploitable3-win2k8' (v0) for 'virtualbox'!
Box successfully added to Vagrant.
---------------------------------------------------------------------
SUCCESS: Run 'vagrant up' to provision and start metasploitable3.
NOTE: The VM will need Internet access to provision properly.
```

**Comment by jmartin-r7** [comment]
Did you have enough free space? This error states it could not find the exported box file on the local file system.

```
Couldn't open file /home/jsmith/metasploitable3-2/packer/builds/windows_2008_r2_qemu_0.1.0.box
Error adding box to Vagrant. See the above output for any error messages.
```

**Comment by mathiasconradt** [comment]
Yes, plenty of space.

**Comment by jmartin-r7** [comment]
sorry I see the error
```
'libvirt' provider box: /home/jsmith/metasploitable3-2/packer/templates/../builds/windows_2008_r2_libvirt_0.1.0.box
```

Import is looking for
```
builds/windows_2008_r2_qemu_0.1.0.box
```

Something may have changed in the way naming is getting determined.

**Comment by mathiasconradt** [comment]
I came across a few issues other with the Windows VM on Kali, incl. the other issue https://github.com/rapid7/metasploitable3/issues/453#issue-576201761 and something else around the NIC adapter / internet connection not working out of the box due to missing virtio  drivers, issues with the packer, so I had to tweak a few files. 

Maybe the above differing is due to some of my changes. I don't recall if I in between resolved that issue above or not, cause I ended up just using the Ubuntu M3, as the Windows built appeared a bit unstable / error-prone. I will try another built today.

**Comment by jmartin-r7** [comment]
We generate the name in the script noting an expected provider as `qemu`, however in `packer` config that value is coming from the {{.Provider}} value by to us a consistent `post-processors` config.
https://github.com/rapid7/metasploitable3/blob/6ef3902e25074fc8cb37d40c0a73cb8b4493cc9c/packer/templates/windows_2008_r2.json#L306

**Comment by mathiasconradt** [comment]
Ok, I adjusted the naming and got it fixed now.
(Running into the next issue now, but that's a different topic.)
