### ISSUE TITLE
pre-built vmware_desktop image only output vmx file

### ISSUE THREAD

**Issue by yuanzhel** [rapid7/metasploitable3#456]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Windows10 Pro
* Packer Version: No, use pre-built version vmware_desktop
* Vagrant Version: 2.2.7
* VirtualBox Version: No, use vmware_workstation 15 pro

## Command Output
Hi, after exec `vagrant up win2k8`, I only got a vmx file in .vagrant/machines/win2k8, I have to manually import it to vmware, want to confirm whether this is the expected behaviour?
Anything I want to mention is between the vagrant up, the output said`WARNING: The VMX file for this box contains a setting that is automatically overwritten by Vagrant
WARNING: when started. Vagrant will stop overwriting this setting in an upcoming release which may
WARNING: prevent proper networking setup. Below is the detected VMX setting:
WARNING:
WARNING:   ethernet0.pcislotnumber = "33"
WARNING:
WARNING: If networking fails to properly configure, it may require this VMX setting. It can be manually
WARNING: applied via the Vagrantfile:
WARNING:
WARNING:   Vagrant.configure(2) do |config|
WARNING:     config.vm.provider :vmware_desktop do |vmware|
WARNING:       vmware.vmx["ethernet0.pcislotnumber"] = "33"
WARNING:     end
WARNING:   end
WARNING:
WARNING: For more information: https://www.vagrantup.com/docs/vmware/boxes.html#vmx-whitelisting
` and `    win2k8: C:\Windows\system32>copy C:\vagrant\scripts\installs\setup_linux_share.bat C:\Windows
    win2k8: The system cannot find the path specified.
` Also please confirm whether this is OK. Thanks!

**Comment by jmartin-r7** [comment]
These warning are known.  They do not represent any issues and can be ignored for the most part.  
```
win2k8: C:\Windows\system32>copy C:\vagrant\scripts\installs\setup_linux_share.bat C:\Windows win2k8: The system cannot find the path specified.
```
The above final warning happens when only one of the VMs is being started.  Or when the IP address of the Ubuntu image is inconsistent with the configured expectations.
