### ISSUE TITLE
Apache Tomcat Vulnerability scan

### ISSUE THREAD

**Issue by jeagle44** [rapid7/metasploitable3#460]
I have multiple servers with Tomcat installed on Windows 2016 servers. When I do a nexus vulnerability scan it says there is an outdated version installed. I have 8.5.51 installed but it is showing 8.5.32.0 installed. Has anyone else seen this issue? Is there a folder or setting that I am missing that is giving me this false positive? Any help is greatly appreciated.

**Comment by bcoles** [comment]
> 
> 
> I have multiple servers with Tomcat installed on Windows 2016 servers. When I do a nexus vulnerability scan it says there is an outdated version installed. I have 8.5.51 installed but it is showing 8.5.32.0 installed. Has anyone else seen this issue? Is there a folder or setting that I am missing that is giving me this false positive? Any help is greatly appreciated.

It depends on how the version check was performed.

By `nexus` do you mean `nessus` or `nexpose` per chance ?

This seems like it would be more of an issue with the vulnerability scanner software than an issue with Metasploitable.

**Comment by Chan9390** [comment]
I think the same. It would be an issue with the vulnerability scanner software.
