### ISSUE TITLE
No usable default provider could be found for your system.

### ISSUE THREAD

**Issue by qingsword** [rapid7/metasploitable3#466]
## Issue Description
No usable default provider could be found for your system.

## Host System
* OS:　Arch K-5.6.14
* Packer Version:  1.5.6
* Vagrant Version:2.2.9
* VMware:15.5

## Command Output
**$ vagrant box add --name ub1404 packer/builds/ubuntu_1404_vmware_0.1.12.box 
$ vagrant box list**
ub1404 (vmware_desktop, 0)

 **$ vagrant up ub1404**
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

 **$ vagrant up ub1404 --provider=VMware**
The provider 'VMware' could not be found, but was requested to
back the machine 'ub1404'. Please use a provider that exists.

Vagrant knows about the following providers: docker, hyperv, virtualbox
 $ vagrant up ub1404 --provider=vmware
The provider 'vmware' could not be found, but was requested to
back the machine 'ub1404'. Please use a provider that exists.

Vagrant knows about the following providers: docker, hyperv, virtualbox

 $ **vagrant box add --name ubuntu1404 packer/builds/ubuntu_1404_vmware_0.1.12.box --provider=vmware**
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'ubuntu1404' (v0) for provider: vmware
    box: Unpacking necessary files from: file:///home/x/metasploitable3-ub/packer/builds/ubuntu_1404_vmware_0.1.12.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: vmware
Provider of box: vmware_desktop

I tried the above commands without success:(

**Comment by jmartin-r7** [comment]
You would need a paid license for the [vagrant vmware plugin](https://www.vagrantup.com/vmware) to use vmware with vagrant.  

Note that you can also download or build the box image and extract it with `tar` to be able to launch the `vmx` file.  This is not optimal, however is does provide a `free` way to interact with the VM.
