### ISSUE TITLE
Error: Failed to prepare build: virtualbox-iso

### ISSUE THREAD

**Issue by bachns** [rapid7/metasploitable3#468]
I got this error when following the instructions, I ran the command: 
```console
.\build.ps1 windows 2008
```

```console
All requirements found. Proceeding...
Building metasploitable3-win2k8 Vagrant box...
Error: Failed to prepare build: "virtualbox-iso"

1 error occurred:
        * Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.
```

**Comment by PeterAdamson** [comment]
I was having the same issue.  The problem was that I was running packer version 1.6.0

I downloaded packer version 1.2.3 and everything worked with that version

**Comment by j-wade** [comment]
Seems like the packer config file in /packer/templates/windows_2008_r2.json was formatted differently for packer 1.6 the below worked for me on Mac.

```on Mac
mv ./packer/templates/windows_2008_r2.json ./packer/templates/windows_2008_r2.json.old
packer fix ./packer/templates/windows_2008_r2.json.old > ./packer/templates/windows_2008_r2.json
./build.sh windows2008

for Win should be
ren packer\templates\windows_2008_r2.json packer\templates\windows_2008_r2.json.old
packer fix packer\templates\windows_2008_r2.json.old > packer\templates\windows_2008_r2.json
.\build.ps1 windows2008

**Comment by Jose-Rdz** [comment]
@j-wade solution works just fine. After executing `packer fix` I also had to change manually the output file encoding to _UTF-8 without BOM_ because `packer build...` threw JSON parsing errors if using original file (encoded in _UCS-2 Little Endian_)

**Comment by Tango-Bravo** [comment]
> I was having the same issue. The problem was that I was running packer version 1.6.0
> 
> I downloaded packer version 1.2.3 and everything worked with that version

Was having this exact issue today with packer v1.6.1. Downgraded to v1.2.3 and its working perfectly.

**Comment by azmacattack** [comment]
I ran into this issue today as well trying to run this command for the vmware version. I ran the command it recommended grabbed the new code it outputted, renamed the old json file to .json.old and saved the outputted code as the win2k8.json file, ran it again and it worked. Just need to update the code for the template to meet the requirements for the latest packer version to avoid this error and causing it to cause issues with the build process.

**Comment by nelbren** [comment]
The solution proposed by @j-wade works in part, however after generating the file, it remains in a different format from **Ascii**, as @Jose-Rdz and @azmacattack say, so it must be converted into **Ascii**, using **Set-Content**, today gave me that problem, and doing different tests, seeing the differences in encoding, I managed to carry out the **process successfully**.
```
move .\packer\templates\windows_2008_r2.json old.json
packer fix .\old.json > new.json
Get-Content new.json | Set-Content -Encoding Ascii  .\packer\templates\windows_2008_r2.json
.\build.ps1
```

**NOTE:** _This is a quick fix, while a more comprehensive solution is found._

**Comment by jiangwenfan** [comment]
已经完美解决问题了。
原因是packer更新之后，不兼容旧的配置文件，使用packer fix命令修复这个旧的配置文件即可。
```
mv ./packer/templates/windows_2008_r2.json  ./packer/templates/windows_2008_r2.json.old 
packer fix ./packer/templates/windows_2008_r2.json.old  > ./packer/templates/windows_2008_r2.json
```
Fix 命令会把修复后的配置输出到标准输出，所以使用重定向将其保存到文件中。

```
root@tony-jarvis:/home/tony/metasploitable3# packer build --only=virtualbox-iso ./packer/templates/windows_2008_r2.json 
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
==> virtualbox-iso: Trying /usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Trying /usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: /usr/share/virtualbox/VBoxGuestAdditions.iso => /usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
....................................
....................................
```

**Comment by leyvatheam** [comment]
okay brothers try this comand 
$ packer fix packer/templates/windows_2008_r2.json > packer/templates/windows_2008_r2.json
and voala, thanks god this devs used packer  thanks devs <3
