### ISSUE TITLE
Vm not visible inside virtualbox console

### ISSUE THREAD

**Issue by webkodex** [rapid7/metasploitable3#47]
Hello, I have successfully installed metasploitable 3  using vagrant & all required files using manual procedure. am using virtualbox Version 5.1.6 r110634. the vagrant status shows machine is running, but i cannot see the machine inside virtualbox console, kindly suggest me a fix. check screenshot.
![capture](https://cloud.githubusercontent.com/assets/15958581/20357431/6860467a-ac41-11e6-8032-c4c58b6ba9c3.PNG)

**Comment by webkodex** [comment]
It Works .Virtual Box should be run as administrator. apologies for confusions

**Comment by jbarnett-r7** [comment]
Thank you for posting the fix. I hadn't seen that issue yet. Good to know how to fix it if anyone else runs into that problem.
