### ISSUE TITLE
VirtualBox version check of the build_win2008.sh script fails on Debian (with solution)

### ISSUE THREAD

**Issue by z0vsky** [rapid7/metasploitable3#48]
## Issue
On a _Kali_ distro (reminder: that's _Debian_ based) with _VirtualBox_ v5.1.6 installed. When trying to build using the `./build_win2008.sh` script, I get the following error message:

> A compatible version of VirtualBox was not found. Currently only 5.1.6 is supported. Please download and install it from https://www.virtualbox.org/wiki/Download_Old_Builds_5_1.

## Diagnosis
The script compares the minimal version of _VirtualBox_ with the one installed on the system using `VBoxManage -v`. The output is piped to _cut(1)_ to get a standard version number so the minimal (hardcoded) version and the installed version can be compared:
```
if compare_versions $(VBoxManage -v | cut -d'r' -f1) $min_virtualbox_ver true; then
    echo "Compatible version of VirtualBox found."
else
    echo "A compatible version of VirtualBox was not found. Currently only 5.1.6 is supported. Please download and install it from https://www.virtualbox.org/wiki/Download_Old_Builds_5_1."
    exit 1
```

While this may work on some systems, it does not work on _Debian_-based system because the version returned by _VBoxManage_ follows this format: `3.2.1_Debianr123456`. For example on my system:
```
VBoxManage -v
5.1.6_Debianr110634
```

## Quick & dirty workarounds
Comment the part of the script that checks the _VirtualBox_ version (or just the related `exit 1` that is executed when the check fails).

## Solution suggestions
Removing the release number \*\*and\*\* the `_Debian` string from `VBoxManage -v` output when checking the versions:

- _Sed(1)_:	`VBoxManage -v | sed -e 's/r.*//g' -e 's/_.*//g'`
- _Cut(1)_:	`VBoxManage -v | cut -d 'r' -d '_' -f1`
- _Awk(1)_/_Mawk(1)_:	`VBoxManage -v | awk -F[r_] '{print $1}'`
- Or even better, using a PCRE RegExp with Grep(1): `VBoxManage -v | grep -Po '^\d.\d.\d'`.

Also, the link in the error message when vagrant is not installed or when the version is not compatible is not correct:

> A compatible version of vagrant was not found. Please download and install it from https://www.virtualbox.org/wiki/Downloads.

It should be:

> A compatible version of vagrant was not found. Please download and install it from https://www.vagrantup.com/downloads.html.

Besides that, everything is working as expected. Thanks for the great work!

**Comment by jbarnett-r7** [comment]
Thank you for the heads up on this. So far we've really only tested on OSX and Windows so finding out about a lot of these small differences between OSes is really valuable. I'm actually working on some fixes to the build script right now so I'll include those changes.

**Comment by z0vsky** [comment]
You're welcome!
I'll probably test it on other OSes and provide feedback when relevant.
