### ISSUE TITLE
problem with vagrant up win2k8

### ISSUE THREAD

**Issue by r3Vibe** [rapid7/metasploitable3#480]
## Issue Description
after going through ./build.ps1 windows2008, i did a vagrant up win2k8 command as instructed. which is giving me some vobxmanage error 

## Host System
* OS: Microsoft Windows [Version 10.0.16299.1087]
* Packer Version: 1.6.2
* Vagrant Version: 2.2.10
* VirtualBox Version: 6.1.12

## Command Output
check the image for command output details
![error](https://user-images.githubusercontent.com/34483820/91811646-76eb7200-ec4d-11ea-9a1f-83ffb98a9ead.jpg)

**Comment by deargle** [comment]
Lol thanks virtualbox for the nigh useless error message. You could try
hand-constructing and running that vboxmanage import command manually and
making educated guesses at which arg is invalid.

**Comment by r3Vibe** [comment]
i am so sorry. it turns out that the ovf file created with build.ps1 was corrupt or incomplete. today i tried building again manually and it worked just fine.
