### ISSUE TITLE
vagrant: undefined local variable or method `win2k8'

### ISSUE THREAD

**Issue by Unknown-0815** [rapid7/metasploitable3#481]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Windows 10 1909
* Packer Version:1.5.0
* Vagrant Version:2.2.10
* VirtualBox Version:5.2.36

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

Hello, i have a problem with "vagrant up" after running ".\build.ps1". After building both targets, i cant open them via "vagrant up". The ouput is:

```
PS C:\metasploitable3-master> vagrant version
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: C:/Users/Andreas/.vagrant.d/boxes/rapid7-VAGRANTSLASH-metasploitable3-win2k8/0/virtualbox/Vagrantfile
Line number: 0
Message: undefined local variable or method `win2k8'
```

Furthermore, i cant check the version of vagrant, because i get the same errorcode, when i type "vagrant version" in the folderpath "C:\metasploitable3-master". This is quite funny:

```
PS C:\metasploitable3-master> vagrant version
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: C:/Users/Andreas/.vagrant.d/boxes/rapid7-VAGRANTSLASH-metasploitable3-win2k8/0/virtualbox/Vagrantfile
Line number: 0
Message: undefined local variable or method `win2k8'
PS C:\metasploitable3-master> cd ..
PS C:\> vagrant version
Installed Version: 2.2.10
Latest Version: 2.2.10

You're running an up-to-date version of Vagrant!
```

I hope anyone of you know this problem and can help me.
Thanks a lot:)

**Comment by Unknown-0815** [comment]
I solved this Problem by editing the VAGRANTFILE "C:/Users/Andreas/.vagrant.d/boxes/rapid7-VAGRANTSLASH-metasploitable3-win2k8/0/virtualbox/Vagrantfile". I changed the following passage

> Vagrant.configure("2") do |config|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.define "vagrant-windows-2008-r2"
    config.vm.box = "windows_2008_r2"
    config.vm.communicator = "winrm"

to 

> Vagrant.configure("2") do |config|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.define "win2k8" do |win2k8|
    win2k8.vm.box = "rapid7/metasploitable3-win2k8"
    win2k8.vm.hostname = "metasploitable3-win2k8"
    config.vm.communicator = "winrm"

At the end of the file i had to insert an "end".
Also i had to reinstall my required programs in other versions. My programs are now installed in the following versions:

- Packer Version:1.5.0
- Vagrant Version:2.1.5
- VirtualBox Version:5.2.44

At this point evething works fine. I hope this Solution can help anyone with these problems. Have fun;)

**Comment by deargle** [comment]
Yes, in fact, that's what the Vagrantfile in the root of the repo does -- https://github.com/rapid7/metasploitable3/blob/b0eaed0ae89c2c2b3b464e19f1a2927988596518/Vagrantfile

Which I guess means the use-case if building via ./build script is to also copy the Vagrantfile from this repo and use that for the vagrant up.
