### ISSUE TITLE
 Deprecated configuration key: 'iso_checksum_type'.

### ISSUE THREAD

**Issue by subhadeep-123** [rapid7/metasploitable3#482]
1 error occurred:
        * Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.

**Comment by deargle** [comment]
@jmartin-r7 , perhaps time to require packer > v1.6, and convert the template to the newer version? This has been coming up a lot on the issues.

**Comment by mattwsutherland** [comment]
@deargle What are the steps for this? How do I convert the template to the newer version?

**Comment by subhadeep-123** [comment]
@mattwsutherland Updating the packer version worked for me, mine is now packer 1.6.2

**Comment by deargle** [comment]
@subhadeep-123 are you saying 1.6.2 _put `iso_checksum_type`  back in_? I don't see that in the [changelog](https://github.com/hashicorp/packer/blob/73e842fab611eeca8605fcee5da5824202c45642/CHANGELOG.md#160-june-09-2020)

@mattwsutherland you would run `packer fix` against the json templates in [this directory](https://github.com/rapid7/metasploitable3/tree/master/packer/templates)

**Comment by jmartin-r7** [comment]
`packer` has evolved the keys and stabilized at this point.  An update in supported versions is pending.

**Comment by subhadeep-123** [comment]
I still have the problem with metasploitable Ubuntu version

**Comment by crab86** [comment]
What has worked for me is doing packer fix packer/templates/ubuntu_1404.json > packer/templates/ubuntu_1404_new.json. Afterwards delete or remove ubuntu_1404.json and rename ubuntu_1404_new.json to ubuntu_1404.json. This worked for the windows box as well.

**Comment by dumdumdugan** [comment]
Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer.  << Still occuring for me

Host OS: Ubuntu 
VMWare 15.5 Pro
VirtualBox: Version 6.1.16 r140961 (Qt5.12.8)
Packer version: 1.6.5
Vagrant version: 2.2.14

I attempted @crab86 fix but I "Permission Denied" even after chmod-ing the json files. At this point I am stuck as to what to do here.

**Comment by subhadeep-123** [comment]
It's all okay now I believe, after `packer fix` the problem is resolved

**Comment by austinogola** [comment]
Hey. Did you fix it? I resolved mine by  updating all the JSON files in the templates

**Comment by TwiztedWisard** [comment]
Hi all, I had this problem when building on windows 10 - using chocolatey I removed and then re installed installed packer version 1.5.5, think it has something to do with the major version change so any <1.6.* should work I beleive. This seemed to get things working for me, hope its of help to someone :)

**Comment by clapashiya** [comment]
I have been getting this error today while running `./build.sh windows2008` as well as `./build.sh ubuntu140`4  inspite of trying all the above mentioned solutions:

> building windows 2008
> Compatible version of VirtualBox found.
> Virtualbox images will be built.
> Compatible version of packer was found.
> Correct version of vagrant was found.
> Compatible version of vagrant-libvirt plugin was found.
> KVM image will be built.
> Fetching virtio drivers required for build
> .virtio-win-0.1.117_amd64.vfd already exists, skipping download.
> Compatible version of vagrant-reload plugin was found.
> Requirements found. Proceeding...
> Building the Vagrant box for qemu...
> Error: Failed to prepare build: "qemu"
> 
> 1 error occurred:
> 	* Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
> against your template to update your template to be compatible with the current
> version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
> detail.

After painstaking troubleshooting the solution that finally worked was
A. Go to  `metasploitable3/packer/templates` folder and make a Backup of it.
B. Open the `windows_2008_r2.json` file in a Text editor and Delete Line Numbers : 6, 45, 88, 139 and 350.
C. Open the `ubuntu_1404.json` in a Text editor and Delete Line Numbers :  6, 39, 77, 122, and 197.

I am attaching the edited JSON files here if you want to simply paste it in the `metasploitable3/packer/templates` folder

[Modified JSON files.zip](https://github.com/rapid7/metasploitable3/files/6539317/Modified.JSON.files.zip)

**Comment by h274zhao** [comment]
I tried the fix mentioned by @crab86. What occurred was a new error 
```
Failed to parse file as legacy JSON template: if you are using an HCL template, check your file extensions; they should be either *.pkr.hcl or *.pkr.json; see the docs for more details: https://www.packer.io/docs/templates/hcl_templates.
Original error: Error parsing JSON: invalid character 'ÿ' looking for beginning of value
At line 1, column 1 (offset 1):
    1: �
```
I also tried other people's fixes mentioned above but none worked. This happens for both ubuntu and windows. I have packer version 1.7.5

**Comment by XDark837** [comment]
ima just use metasploitable 2, 3 is being super cringe and full of issues

**Comment by hasanyousuf** [comment]
> > > > I tried the fix mentioned by @crab86. What occurred was a new error
> > > > ```
> > > > Failed to parse file as legacy JSON template: if you are using an HCL template, check your file extensions; they should be either *.pkr.hcl or *.pkr.json; see the docs for more details: https://www.packer.io/docs/templates/hcl_templates.
> > > > Original error: Error parsing JSON: invalid character 'ÿ' looking for beginning of value
> > > > At line 1, column 1 (offset 1):
> > > >     1: �
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I also tried other people's fixes mentioned above but none worked. This happens for both ubuntu and windows. I have packer version 1.7.5
> > > > Me too, mine is version 1.7.7
> > 
> > 
> > And I tried to use packer version 1.6.2 which is mentioned above by others worked, but meet the same problem.
> 
> Same here, I've been searching for a solution more than a decade :((

I had the same issue with packer version 1.7.8. Changing the encoding to UTF-8 fixed the issue.
