### ISSUE TITLE
VirtualBox Version typo?

### ISSUE THREAD

**Issue by grizlee** [rapid7/metasploitable3#49]
The version check for VirtualBox in the build_win2008.sh script is set to "5.1.9", which isn't available via their repo for Ubuntu 15.04 LTS, the latest version available is 5.1.8.  It's not available on the Downloads page of their site either.  I saw the issue from yesterday regarding the version check looking for 5.1.6, so I was just wondering if someone might have made a typo in correcting the code.  

If this is intentional, I guess my next question would be: How do I get VirtualBox 5.1.9?  

Thanks in advance.

**Comment by jbarnett-r7** [comment]
Fixed. Sorry about that. Do a pull and it should be updated.
