### ISSUE TITLE
Please upload regular OVA files for ease of use

### ISSUE THREAD

**Issue by acheong08** [rapid7/metasploitable3#494]
:)

**Comment by VA2PE** [comment]
I recently built a Win2008-R2 OVA file for VMWare. Here's the file if you want it. The OS is not licensed. You'll have to enter your own key, otherwise it will run in unlicensed mode after the grace period expires.

https://drive.google.com/file/d/1nPSOXJrhh2hglaRy8DD7bTUDvLcyAQtE/view?usp=sharing

**Comment by jmartin-r7** [comment]
Images are updated periodically in vagrantcloud see https://github.com/rapid7/metasploitable3#quick-start.

Automation attempts to replace them weekly however is not always consistent.
