### ISSUE TITLE
gem ssl problem - win2k8

### ISSUE THREAD

**Issue by reeb4x4** [rapid7/metasploitable3#499]
**Issue Description**
Trying tu build win2k8 VM (it doesn't matter if qemu or virtualbox) a obtained error while executing gem on install_rails_server.bat file.

**Host System**
* OS: Ubuntu 20.04 (5.4.0-56-generic)
* Packer Version: 1.3.4+dfsg-4
* Vagrant Version: 2.2.6+dfsg-2ubuntu3
* VirtualBox Version: 6.1.10-dfsg-1~ubuntu1.20.04.1

**Command Output:**
==> qemu: Provisioning with shell script: /home/reeb/Dokumenty/git/metasploitable3/packer/templates/../../scripts/installs/install_rails_server.bat
    qemu:
    qemu: C:\Users\vagrant>copy /Y C:\Vagrant\resources\rails_server\gemrc C:\Users\vagrant\.gemrc
    qemu:         1 file(s) copied.
    qemu:
    qemu: C:\Users\vagrant>cmd /C C:\tools\ruby23\bin\gem.cmd install rails -v '4.1.1' --no-ri --no-rdoc
    qemu: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    qemu:     SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/api/v1/dependencies)
    qemu:
    qemu: C:\Users\vagrant>cmd /C C:\tools\ruby23\bin\gem.cmd install rake -v '11.3.0' --no-ri --no-rdoc
    qemu: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    qemu:     SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/api/v1/dependencies)

... and so one

   qemu:         1 file(s) copied.
    qemu:
    qemu: C:\Users\vagrant>C:\tools\ruby23\bin\rails.bat _4.1.1_ new "C:\Program Files\Rails_Server"
    qemu: operable program or batch file.
==> qemu: Deleting output directory...
Build 'qemu' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> qemu: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.

**Comment by Tristanlogd** [comment]
Had the same exact issues.

**Comment by zjdaniels1985** [comment]
Same issue

**Comment by djlongy** [comment]
same issue. sounds like the windows 2k8 vm doesn't trust the root ca of rubygems.org?
do we need to add it to the trusted root ca before the script can complete?

**Comment by jmartin-r7** [comment]
This has been confirmed, the CA of the latest rubygems.org certificate is issued by a new authority not recognized by default in Window 2008r2.  Testing is in progress for importing the new required CA during packer builds.  For the short term, [quick-start images](https://github.com/rapid7/metasploitable3#quick-start) from vagrant cloud are still available for pre-built images on vmware and virtualbox.

**Comment by Nostradamus900** [comment]
I have the same issue !!! Help please !
