### ISSUE TITLE
How do change expected installation location

### ISSUE THREAD

**Issue by Smank3** [rapid7/metasploitable3#501]
## Issue Description
The automatic installation ran through powershell of metaploitable 3 can't find an original directory. Command run: [./build.ps1](url) windows 2008

## Host System
* OS: W10
* Packer Version:  1.1.6
* Vagrant Version: 2.2.14
* VirtualBox Version: 6.1.16 r140961 (Qt5.6.2)

## Command Output
VirtualBox is not installed (or not in the expected location of C:\Program Files\Oracle\VirtualBox\)

**Comment by jmartin-r7** [comment]
The build script has a variable for where it expects to find virutalbox:

https://github.com/rapid7/metasploitable3/blob/53b1966a80e4a01b2ea506f6206518ae84176665/build.ps1#L8

If you have the virtualbox binaries in a different path you will need to update the location to be able to build from scratch.
