### ISSUE TITLE
vagrant plugin install vagrant-libvirt produces error: conflicting dependencies net-ssh (>= 2.6.5) and net-ssh (= 6.2.0.rc1)

### ISSUE THREAD

**Issue by mb720** [rapid7/metasploitable3#509]
## Issue Description

I've installed Vagrant on Arch Linux 5.10.13 using `sudo pacman -Sy vagrant`.

I'm trying to build a metasploitable image that can be run using QEMU/KVM.

Reading [here](https://stackoverflow.com/questions/42155213/using-vagrant-to-set-up-a-vm-with-kvm-qemu-without-virtualbox#46037150) that I need to install the vagrant-libvirt plugin, I tried so using `vagrant plugin install vagrant-libvirt`. This produces an error though:

      conflicting dependencies net-ssh (>= 2.6.5) and net-ssh (= 6.2.0.rc1)
        Activated net-ssh-6.2.0.rc1
        which does not match conflicting dependency (>= 2.6.5)

        Conflicting dependency chains:
          net-ssh (= 6.2.0.rc1), 6.2.0.rc1 activated

        versus:
          net-scp (= 1.2.1), 1.2.1 activated, depends on
          net-ssh (>= 2.6.5)

        Gems matching net-ssh (>= 2.6.5):
          net-ssh-6.2.0.rc1

Is there a way to fix this?

## Host System
* OS: Arch Linux 5.10.13
* Packer Version: n/a
* Vagrant Version: 2.2.14
* VirtualBox Version: n/a

**Comment by jmartin-r7** [comment]
Unfortunately this is not within the control of this project.  This issues is for [`vagrant-libvirt`](https://github.com/vagrant-libvirt/vagrant-libvirt).
