### ISSUE TITLE
jenkins.exe  is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by FreelancePentester** [rapid7/metasploitable3#51]
"C:\Program Files\jenkins\jenkins.exe"' is not recognized as an internal or external command,
==> default: operable program or batch file.
==> default:
==> default: C:\Windows\system32>sc config jenkins start= auto
==> default: [SC] OpenService FAILED 1060:
==> default:
==> default: The specified service does not exist as an installed service.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:

Stderr from the command:

**Comment by jbarnett-r7** [comment]
It looks like something didn't copy properly in an earlier part of that script. Can you please run `vagrant destroy` and then `vagrant up` to try again from a fresh box?

**Comment by FreelancePentester** [comment]
the same error.

**Comment by atarii** [comment]
AVG detects jenkins.exe as "Trojan horse FileCryptor.EF" so it may be that AV deleted the file before vagrant added it to your metasploitable VM

**Comment by jbarnett-r7** [comment]
@FreelancePentester did this turn out to be an AV issue as @atarii suggested?

**Comment by imparitosh** [comment]
Well for me even after disabling the AV, the issue of Jenkins.exe persist. 

My environment:
OS: Win10
VirtualBox: 5.2.0

The shell does output at the beginning that requisite tools are compatible (the logic is written that way)... Everything goes smooth until the shell dumps Jenkins.exe not found and therefore it could not install the VB image. I am not sure but installed Jenkins. The default folder being C:\Program Files (86) rather than C:\Program Files... will this interrupt the installation?

**Comment by Chan9390** [comment]
Hey @imparitosh , disable the AV, re-clone / download the repository and try running.

**Comment by imparitosh** [comment]
Hey Chan, doesnt work either ways :(
further now when i am trying to build manually, the shell does not dumps anything but states it could not create the artifacts.

**Comment by Chan9390** [comment]
So you mean that there is no output at all. If there is output please comment it.

**Comment by imparitosh** [comment]
If I may suggest, the installation guide shall mention that 
1)AV should be disabled at the time of installation
2) Start-Sleep time under the scripts folder be made 15 against the current setting of 10.

While I started everything from a clean slate again, but am now stuck with "Timeout waiting for the machine to restart". Once again no .box file created.

**Comment by Chan9390** [comment]
Hey @imparitosh why dont you open a new issue ? In it please provide the details (and versions) of the OS and software you are using. Then lets try to solve it.

Timeout for a system to start is set to 2 hrs in `windows_2008_r2.json`. Did you wait for 2 hours for the system to boot ?
