### ISSUE TITLE
Metasploitable download for ARM processors? 

### ISSUE THREAD

**Issue by BrandanN21** [rapid7/metasploitable3#510]
## Issue Description
Cannot install metasploitable in parallels on the new apple m1 arm laptops. Receiving the error that I need an iso or vm with an ARM based OS

## Host System
* MacOS
* Parallels

<img width="479" alt="Screen Shot 2021-02-26 at 8 10 57 PM" src="https://user-images.githubusercontent.com/47616844/109372366-bf878f00-786e-11eb-986b-b6756574550e.png">

**Comment by jmartin-r7** [comment]
This is not supported.

**Comment by BlkPingu** [comment]
So metasploitable is going to die with ARM?

**Comment by jmartin-r7** [comment]
The question here was about metasploitable2 which was a one off custom build virtual machine provided released in 2012 as an OVA, that has been a locked image and will not be updated.

The current iteration metastploitable3 is x86_64, the project will continue to be supported on platforms that support the architecture directly.  For macOS there is no current plan port the VMs to ARM as the public vulnerabilities currently provided examples of vulnerabilities that may or may not even apply to an ARM based system. 

This does not preclude the idea that an ARM target could be added to the metasploitable3 VM set only that there is not a current plan in place for one.
