### ISSUE TITLE
Unable to create metasploitable3 windows2k8

### ISSUE THREAD

**Issue by praveen190** [rapid7/metasploitable3#513]
/build.sh windows2008
building windows 2008
Compatible version of VirtualBox found.
Virtualbox images will be built.
Compatible version of packer was found.
Correct version of vagrant was found.
Compatible version of vagrant-libvirt plugin was found.
KVM image will be built.
Fetching virtio drivers required for build
.virtio-win-0.1.117_amd64.vfd already exists, skipping download.
Compatible version of vagrant-reload plugin was found.
Requirements found. Proceeding...
Building the Vagrant box for qemu...
Error: Failed to prepare build: "qemu"

1 error occurred:
	* Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.

==> Wait completed after 5 microseconds

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.

## Host System
* OS:Kali linux 
* Packer Version:1.6.6
* Vagrant Version:2.2.4
* VirtualBox Version:v6.1.18

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

Please help me with this as soon as possible, I have been struggling last 3 days

**Comment by TwiztedWisard** [comment]
I had this problem, it comes from the way the different versions of packer handle the checksums for the ISOs - 

run this from the metasploitable 3 folder in terminal  `packer fix ./packer/templates/<TEMPLATENAME>.json` where <TEMPLATENAME> is either the windows or the ubuntu template (you will have to do this for both)

the terminal should then spit out the refomatted file to SDTOUT - leave this for a second you will need it shortly

go to metasploitable folder and rename the template file you have just converted to have .bak at the end

for example windows_2008_r2.json.bak

then create a new file with the original file name - windows_2008_r2.json
 
copy and past the output from the packer fix command from the first bracket { to the very last on and make sure there is a new line after it.

save this file then re run the build command.

Some guides will tell you to redirect the output of this command to the .json file - this is where i had problems as there were non printable characters being added to the file and/or the formatting was off so converting in terminal then copying the output is the safest way IMO.

hope this helps :)

**Comment by OumaimaBeny** [comment]
> I had this problem, it comes from the way the different versions of packer handle the checksums for the ISOs -
> 
> run this from the metasploitable 3 folder in terminal `packer fix ./packer/templates/TEMPLATENAME.json` where TEMPLATENAME is either the windows or the ubuntu template (you will have to do this for both)
> 
> the terminal should then spit out the refomatted file to SDTOUT - leave this for a second you will need it shortly
> 
> go to metasploitable folder and rename the template file you have just converted to have .bak at the end
> 
> for example windows_2008_r2.json.bak
> 
> then create a new file with the original file name - windows_2008_r2.json
> 
> copy and past the output from the packer fix command from the first bracket { to the very last on and make sure there is a new line after it.
> 
> save this file then re run the build command.
> 
> Some guides will tell you to redirect the output of this command to the .json file - this is where i had problems as there were non printable characters being added to the file and/or the formatting was off so converting in terminal then copying the output is the safest way IMO.
> 
> hope this helps :)

i can not install it please can u share with me the ova file?

**Comment by TwiztedWisard** [comment]
I’m happy to help you troubleshoot dude! 😁 I think just handing the OVA over defeats the object of the project…what errors are you getting? what system are you using, Linux or Windows? What versions of the required software are you using? 

Here are the steps I took to get it working:
- latest version of windows (version 20H2) fully updated;
- latest version of virtualbox plus extension pack (currently 6.1.22) https://www.virtualbox.org/wiki/Downloads ;
- RESTART!
- I then installed chocolatey (package manager for windows) https://chocolatey.org/install ;
- then I install packer ( choco install packer) needs to be done in an administrator shell
- then install vagrant (choco install vagrant) (again, administrator shell)
- RESTART!
- open another admin shell and run the following: vagrant plugin install vagrant-reload
- get to a directory that you have full permissions (read/write/execute)
- follow the instructions on GitHub for the quick install https://github.com/rapid7/metasploitable3/issues/513?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE3MDc0MjYxMjg6NjA2MjUxMDA%3D#issuecomment-830664339

Start up virtualbox manager and you should see both systems running :D


Hope that’s of some help! If you need any further pointers I will do my best to answer 🙂

**Comment by TwiztedWisard** [comment]
PS I can give you instructions for Linux if that’s better 😁

**Comment by OumaimaBeny** [comment]
> I’m happy to help you troubleshoot dude! 😁 I think just handing the OVA over defeats the object of the project…what errors are you getting? what system are you using, Linux or Windows? What versions of the required software are you using? Here are the steps I took to get it working: - latest version of windows (version 20H2) fully updated; - latest version of virtualbox plus extension pack (currently 6.1.22) https://www.virtualbox.org/wiki/Downloads ; - RESTART! - I then installed chocolatey (package manager for windows) https://chocolatey.org/install ; - then I install packer ( choco install packer) needs to be done in an administrator shell - then install vagrant (choco install vagrant) (again, administrator shell) - RESTART! - open another admin shell and run the following: vagrant plugin install vagrant-reload - get to a directory that you have full permissions (read/write/execute) - follow the instructions on GitHub for the quick install Note that sometimes I had to run the ‘vagrant up’ command 2 times due to an error about running scripts on the windows box, not really sure why I was getting the errors but running that command twice seemed to fix it :) Start up virtualbox manager and you should see both systems running :D Hope that’s of some help! If you need any further pointers I will do my best to answer 🙂
> […](#)
> Sent from my iPhone
> On 1 May 2021, at 18:16, OumaimaBeny ***@***.***> wrote: ﻿ I had this problem, it comes from the way the different versions of packer handle the checksums for the ISOs - run this from the metasploitable 3 folder in terminal packer fix ./packer/templates/TEMPLATENAME.json where TEMPLATENAME is either the windows or the ubuntu template (you will have to do this for both) the terminal should then spit out the refomatted file to SDTOUT - leave this for a second you will need it shortly go to metasploitable folder and rename the template file you have just converted to have .bak at the end for example windows_2008_r2.json.bak then create a new file with the original file name - windows_2008_r2.json copy and past the output from the packer fix command from the first bracket { to the very last on and make sure there is a new line after it. save this file then re run the build command. Some guides will tell you to redirect the output of this command to the .json file - this is where i had problems as there were non printable characters being added to the file and/or the formatting was off so converting in terminal then copying the output is the safest way IMO. hope this helps :) i can not install it please can u share with me the ova file? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your help 
i got this error even if i have the latest version of virtualbox
 Building metasploitable3-win2k8 Vagrant box...
Error: Failed to prepare build: "virtualbox-iso"

1 error occurred:
        * Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.





==> Wait completed after 0 seconds

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
Au caractère C:\metasploitable\metasploitable3-master\build.ps1:157 : 10
+          throw "Error building the Vagrant box using Packer. Please c ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by TwiztedWisard** [comment]
Thank you for sending your output dude 😁 you are 100% facing the issue I did.

If you follow the instructions in my original post, the one that shows you the ‘packer fix’ command it should work after running that…

Building the boxes from source can be tricky. They require very specific build environments and even then they may fail. I only ever got it to work on Windows once and then Linux, I think even then I could only get it to run correctly on Ubuntu…. That’s why I gave the steps on how I got the quick start method on windows to work. It was much easier. 🙂

If you need any further help just ask 😁

**Comment by OumaimaBeny** [comment]
> Thank you for sending your output dude 😁 you are 100% facing the issue I did. If you follow the instructions in my original post, the one that shows you the ‘packer fix’ command it should work after running that… Building the boxes from source can be tricky. They require very specific build environments and even then they may fail. I only ever got it to work on Windows once and then Linux, I think even then I could only get it to run correctly on Ubuntu…. That’s why I gave the steps on how I got the quick start method on windows to work. It was much easier. 🙂 If you need any further help just ask 😁

I did what u said but i got this new error :/ (thank you btw)

Compatible version of VirtualBox found.
Compatible version of Packer found.
Compatible version of Vagrant found.
Compatible version of vagrant-reload plugin found.
All requirements found. Proceeding...
Building metasploitable3-win2k8 Vagrant box...
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
==> virtualbox-iso: Trying C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Trying file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso => C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
==> virtualbox-iso: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso?checksum=md5%3A4263be2cf3c59177c45085c0a7bc6ca5
==> virtualbox-iso: Download failed bad response code: 404
==> virtualbox-iso: error downloading ISO: [bad response code: 404]
Build 'virtualbox-iso' errored after 3 seconds 688 milliseconds: error downloading ISO: [bad response code: 404]

==> Wait completed after 3 seconds 696 milliseconds

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: error downloading ISO: [bad response code: 404]

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
Au caractère C:\metasploitable\metasploitable3-master\build.ps1:157 : 10
+          throw "Error building the Vagrant box using Packer. Please c ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by TwiztedWisard** [comment]
My instant thought on looking at that would be to restart the whole machine and run the build command again, and call it overkill but if I encounter errors I normally destroy the git clone and grab it again. 

After that it would be a bit beyond my experience if I’m honest. If you knew what you were looking for you could compare the new .Json against the old and see if any of the values have been changed like the web addresses pointing to the ISOs.

As I’ve said building the boxes from scratch can be iffy at the best of times and not for the feint hearted IMO.

**Comment by TwiztedWisard** [comment]
On closer inspection try downloading the file manually and see if you can move it to the location it’s looking in for it….apologies, I’m on the move at the moment so didn’t look at it too closely 🤦‍♂️

**Comment by blckraven** [comment]
> 
> 
> > Thank you for sending your output dude 😁 you are 100% facing the issue I did. If you follow the instructions in my original post, the one that shows you the ‘packer fix’ command it should work after running that… Building the boxes from source can be tricky. They require very specific build environments and even then they may fail. I only ever got it to work on Windows once and then Linux, I think even then I could only get it to run correctly on Ubuntu…. That’s why I gave the steps on how I got the quick start method on windows to work. It was much easier. 🙂 If you need any further help just ask 😁
> 
> I did what u said but i got this new error :/ (thank you btw)
> 
> Compatible version of VirtualBox found.
> Compatible version of Packer found.
> Compatible version of Vagrant found.
> Compatible version of vagrant-reload plugin found.
> All requirements found. Proceeding...
> Building metasploitable3-win2k8 Vagrant box...
> virtualbox-iso: output will be in this color.
> 
> ==> virtualbox-iso: Retrieving Guest additions
> ==> virtualbox-iso: Trying C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
> ==> virtualbox-iso: Trying file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
> ==> virtualbox-iso: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso => C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
> ==> virtualbox-iso: Retrieving ISO
> ==> virtualbox-iso: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
> ==> virtualbox-iso: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso?checksum=md5%3A4263be2cf3c59177c45085c0a7bc6ca5
> ==> virtualbox-iso: Download failed bad response code: 404
> ==> virtualbox-iso: error downloading ISO: [bad response code: 404]
> Build 'virtualbox-iso' errored after 3 seconds 688 milliseconds: error downloading ISO: [bad response code: 404]
> 
> ==> Wait completed after 3 seconds 696 milliseconds
> 
> ==> Some builds didn't complete successfully and had errors:
> --> virtualbox-iso: error downloading ISO: [bad response code: 404]
> 
> ==> Builds finished but no artifacts were created.
> Error building the Vagrant box using Packer. Please check the output above for any error messages.
> Au caractère C:\metasploitable\metasploitable3-master\build.ps1:157 : 10
> 
>     * ```
>            throw "Error building the Vagrant box using Packer. Please c ...
>       ```
> 
>     * ```
>            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       
>       * CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
>       * FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.

any updates to this error?
