### ISSUE TITLE
Win2k8 evaluation license issue

### ISSUE THREAD

**Issue by jeremychoi** [rapid7/metasploitable3#517]
## Issue Description
After newly setting up a win2k8 instance with vagrant,  it says the key is expired  (it used to work without an issue). Now when I try reactivation, I get the message like   the key has been blocked. It seems like there's an issue with the trial key. Would there be any other trial key that can be used or any other way to solve this issue?

**Comment by jmartin-r7** [comment]
The trial key is only valid for 180 days from the creation of the VM, you can add your own valid permanent license key to the system, rebuild locally, or re-download the the published vagrant box to get a VM with more recently installed evaluation timer.  Compliance with licensing for the Windows OS is a responsibility of the end user.

**Comment by jeremychoi** [comment]
"re-download the the published vagrant box" => What I mean is, even with the published vagrant box, the trial key is not working.

**Comment by jmartin-r7** [comment]
The box in vagrant cloud has been refreshed and verified, it should now be possible to remove any local box and re-download.
