### ISSUE TITLE
Can I build metasplotable 3 for citrix XenServer? 

### ISSUE THREAD

**Issue by ghalwash** [rapid7/metasploitable3#519]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Citrix Xenserver
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by jmartin-r7** [comment]
The `packer` build process used in the project currently supports creation of VMs for `vmware`, `virtualbox`, `qemu` ( which for packer is also `kvm` I believe ), and `parallels`.

I believe building the images for `qemu/kvm` and importing them to Xen would work.  You may also be able to custom enhance the packer files to target XenServer directly.
