### ISSUE TITLE
Unable to login using the keyboard

### ISSUE THREAD

**Issue by seag33k** [rapid7/metasploitable3#52]
Once I startup metasploitable3 using vagrant up, I am unable to enter the password using the keyboard.  If I start up the VM from the Virtualbox interface I can enter the password.  I am running Windows 10 and VB version 5.16.

**Comment by carbunch** [comment]
You need to be using VirtualBox and extension pack version 5.1.8 in order for the VM to work properly.

**Comment by jbarnett-r7** [comment]
Closing this one out since there haven't been any updates or new reports. Please re-open if it is still an issue.
