### ISSUE TITLE
why do you not share directly iso about virtual machines 

### ISSUE THREAD

**Issue by bartounet16** [rapid7/metasploitable3#524]
Hello.
Coud you explain me why do you not share directly iso about virtual machines ?
it is difficult for noob to create iso whith vagrant and packer

**Comment by jmartin-r7** [comment]
Licensing restrictions limit distribution, the project does seed box images in [vagrantcloud](https://app.vagrantup.com/rapid7).

https://github.com/rapid7/metasploitable3#quick-start

Another community member has also noted you can download these directly without vagrant. https://github.com/rapid7/metasploitable3/issues/447
