### ISSUE TITLE
Installation break

### ISSUE THREAD

**Issue by SecurityEnthusiast** [rapid7/metasploitable3#528]
## Issue Description
Note that I am using the VMware and VirtualBox provisioner: I've been working on this the last few days and it seems to fail at a same point each time.

Command run:  `packer build --only=vmware-iso ./packer/templates/windows_2008_r2_fixed.json` (JSON file fixed by "packer fix" command)

## Host System
* OS: macOS Catalina 10.15.7
* Packer Version: Packer v1.7.2
* Vagrant Version: Installed Version: 2.2.15
* VirtualBox Version: 6.1.22 r144080 (Qt5.6.3) , VMWare Version: Professional Version 12.1.1 (17801503)

## Command Output
I've got this error, but it doesn't break build:

```
    vmware-iso: C:\Users\vagrant>net start "Apache Tomcat 8.0 Tomcat8"
==> vmware-iso: The service name is invalid.
==> vmware-iso:
==> vmware-iso: More help is available by typing NET HELPMSG 2185.
```
however, continue to build until I encounter another error:

```
==> vmware-iso: Provisioning with shell script: /Users/meghdadshamsaei/Documents/MyProgramming/github/metasploitable3/packer/templates/../../scripts/installs/install_devkit.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>mkdir "C:\RubyDevKit"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe', 'C:\RubyDevKit\devkit.exe')"  0<NUL
==> vmware-iso: Exception calling "DownloadFile" with "2" argument(s): "The remote server
==> vmware-iso: returned an error: (403) Forbidden."
==> vmware-iso: At line:1 char:82
==> vmware-iso: + ... pe]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://d ...
==> vmware-iso: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> vmware-iso:     + FullyQualifiedErrorId : WebException
==> vmware-iso:
    vmware-iso:
==> vmware-iso:
==> vmware-iso: ERROR: The system cannot find the file specified.
    vmware-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\RubyDevKit\devkit.exe" -o"C:\RubyDevKit\""
    vmware-iso:
    vmware-iso: 7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
==> vmware-iso: C:\RubyDevKit\devkit.exe
==> vmware-iso:
==> vmware-iso:
    vmware-iso:
==> vmware-iso:
    vmware-iso: Scanning the drive for archives:
==> vmware-iso: System ERROR:
==> vmware-iso: The system cannot find the file specified.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>copy /Y C:\Vagrant\resources\Rails_Server\devkit\dk.rb "C:\RubyDevKit"
    vmware-iso:         1 file(s) copied.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>C:\tools\ruby23\bin\ruby.exe "C:\RubyDevKit\dk.rb" init
    vmware-iso: [INFO] found RubyInstaller v2.3.3 at C:/tools/ruby23
    vmware-iso:
    vmware-iso: Initialization complete! Please review and modify the auto-generated
    vmware-iso: 'config.yml' file to ensure it contains the root directories to all
    vmware-iso: of the installed Rubies you want enhanced by the DevKit.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>C:\tools\ruby23\bin\ruby.exe "C:\RubyDevKit\dk.rb" install
==> vmware-iso: '"C:\RubyDevKit\devkitvars.bat"' is not recognized as an internal or external command,
==> vmware-iso: operable program or batch file.
    vmware-iso: [INFO] Updating convenience notice gem override for 'C:/tools/ruby23'
    vmware-iso: [INFO] Installing 'C:/tools/ruby23/lib/ruby/site_ruby/devkit.rb'
    vmware-iso:
    vmware-iso: C:\Users\vagrant>"C:\RubyDevKit\devkitvars.bat"
==> vmware-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored after 22 minutes 10 seconds: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Wait completed after 22 minutes 10 seconds

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```

**Comment by melbatniji** [comment]
I am facing the same issue. the URL "https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe" which is requested from the install_devkit.bat returns (403) Forbidden status.

Looks like this file is not available at that URL anymore. I am trying to find somewhere else but can't.

If anyone found a solution to this problem. Please post the solution here.

Thanks

**Comment by SecurityEnthusiast** [comment]
> I am facing the same issue. the URL "https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe" which is requested from the install_devkit.bat returns (403) Forbidden status.
> 
> Looks like this file is not available at that URL anymore. I am trying to find somewhere else but can't.
> 
> If anyone found a solution to this problem. Please post the solution here.
> 
> Thanks

You can download it from this link:

`http://lib.orzfly.com/mirrors/windows/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe`

In which file you edit the link to build?

**Comment by melbatniji** [comment]
> > I am facing the same issue. the URL "https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe" which is requested from the install_devkit.bat returns (403) Forbidden status.
> > Looks like this file is not available at that URL anymore. I am trying to find somewhere else but can't.
> > If anyone found a solution to this problem. Please post the solution here.
> > Thanks
> 
> You can download it from this link:
> 
> `http://lib.orzfly.com/mirrors/windows/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe`
> 
> It worked.

The file you suggested was flagged by two vendors on VirusTotal as TrojanDownloader.Banload.
