### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by dio1911** [rapid7/metasploitable3#53]
Following the execution of vagrant up which seems to complete with no errors, i receive the following error messages when attempting to start the VM in Virtual Box:

Failed to open a session for the virtual machine metasploitable3_default_1480289896790_89030.

Callee RC: E_FAIL (0x80004005)

Failed to open a session for the virtual machine metasploitable3_default_1480289896790_89030.

The VM session was aborted.

Result Code: E_FAIL (0x80004005)
Component: SessionMachine
Interface: ISession {7844aa05-b02e-4cdd-a04f-ade4a762e6b7}

Any idea what could be the cause?  I've installed on a Win 7 Professional OS w/16GB RAM and over 100GB of free disk space.

**Comment by jbarnett-r7** [comment]
Are you still seeing issues with this @dio1911 ?

**Comment by dio1911** [comment]
Yes, after trying multiple times to install on several systems I gave up.  It's been a few weeks so I'll dust it off and try again to see if I am successful. Thanks for checking...
 

    On Thursday, January 5, 2017 2:20 PM, jbarnett-r7 <notifications@github.com> wrote:
 

 Are you still seeing issues with this @dio1911 ?—

**Comment by jbarnett-r7** [comment]
@dio1911 Would you happen to have another account called @aldo1901 ? If so, did you get this working as reported in #54 ?

**Comment by aldo1901** [comment]
Oh crap sorry. I did open that I while ago. All good. 

-A

**Comment by phoy** [comment]
I am having this issue as well

**Comment by ahusmc** [comment]
I'm also having the same issue:

PS C:\Users\ahusm\VirtualBox VMs\Metasploitable3> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'metasploitable3'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: Metasploitable3_default_1511382298878_23772
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/ahusm/VirtualBox VMs/Metasploitable3
==> default: Running provisioner: shell...
    default: Running: scripts/configs/enable_firewall.bat as c:\tmp\vagrant-shell.bat
    default: Ok.
==> default: Running provisioner: shell...
    default: Running: scripts/configs/configure_firewall.bat as c:\tmp\vagrant-shell.bat
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.
    default: Ok.

And then I get:

Failed to open a session for the virtual machine Metasploitable3_default_1511382298878_23772

Result Code: | E_FAIL (0x80004005)
-- | --
Component: | SessionMachine
Interface: | ISession {7844aa05-b02e-4cdd-a04f-ade4a762e6b7}

**Comment by hasinhafiz1** [comment]
I have the same issue. Somebody help
