### ISSUE TITLE
help! windows2008 build process error

### ISSUE THREAD

**Issue by yanchingyu** [rapid7/metasploitable3#533]
# Issue Description
I can successfully build .\build.ps1 build ubuntu1404 . 
I downloaded the windows2008.iso from the internet, in the C:\Users\yan\Downloads\metasploitable3-master\packer\templates\windows_2008_r2.json I modify "iso_url": "C:/Users/yan/Downloads/Windows Server 2008 r2.iso"

# Host System
OS:windows10 20H2
packer Version: 1.3.5
virtualbox Version : 6.1.22
vagrant Version : 2.2.16

# Command Output
PS C:\Users\yan\Downloads\metasploitable3-master> vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Fetching micromachine-3.0.0.gem
Fetching vagrant-vbguest-0.29.0.gem
Installed the plugin 'vagrant-vbguest (0.29.0)'!

PS C:\Users\yan\Downloads\metasploitable3-master> vagrant plugin install vagrant-reload
Installing the 'vagrant-reload' plugin. This can take a few minutes...
Installed the plugin 'vagrant-reload (0.0.1)'!

PS C:\Users\yan\Downloads\metasploitable3-master> .\build.ps1 windows2008
Compatible version of VirtualBox found.
Compatible version of Packer found.
Compatible version of Vagrant found.
Compatible version of vagrant-reload plugin found.
All requirements found. Proceeding...
Building metasploitable3-win2k8 Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
    virtualbox-iso: Using file in-place: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Retrieving ISO
    virtualbox-iso: Using file in-place: file:///C:/Users/yan/Downloads/Windows%20Server%202008%20r2.iso
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../answer_files/2008_r2/Autounattend.xml
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../scripts/configs/microsoft-updates.bat
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../scripts/configs/win-updates.ps1
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../scripts/installs/openssh.ps1
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../scripts/installs/install_dotnet45.ps1
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../scripts/installs/install_wmf.ps1
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/oracle-cert.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/gdig2.crt
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/comodorsadomainvalidationsecureserverca.crt
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/comodorsacertificationauthority.crt
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/addtrust_external_ca.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/baltimore_ca.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/digicert.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/equifax.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/globalsign.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/gte_cybertrust.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/microsoft_root_2011.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/thawte_primary_root.cer
    virtualbox-iso: Copying file: C:\Users\yan\Downloads\metasploitable3-master\packer\templates/../../resources/certs/utn-userfirst.cer
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3142)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm metasploitable3-win2k8 --memory 4096
    virtualbox-iso: Executing: modifyvm metasploitable3-win2k8 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: Not Hyper-V CPUID signature: 0x61774d56 0x4d566572 0x65726177 (expected 0x7263694d 0x666f736f 0x76482074) (VERR_NEM_NOT_AVAILABLE).
==> virtualbox-iso: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
==> virtualbox-iso: VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage.exe: error: Not Hyper-V CPUID signature: 0x61774d56 0x4d566572 0x65726177 (expected 0x7263694d 0x666f736f 0x76482074) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: Not Hyper-V CPUID signature: 0x61774d56 0x4d566572 0x65726177 (expected 0x7263694d 0x666f736f 0x76482074) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
位於 C:\Users\yan\Downloads\metasploitable3-master\build.ps1:157 字元:10
+          throw "Error building the Vagrant box using Packer. Please c ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error
    messages.

**Comment by jmartin-r7** [comment]
Duplicates #526 see comments there.
