### ISSUE TITLE
Building Issues

### ISSUE THREAD

**Issue by aldo1901** [rapid7/metasploitable3#54]
Main two issues are in bold. Cannot make heads or tails about the error messages. I'm using Kali to build.

Compatible version of VirtualBox found.
**./build_win2008.sh: line 52: packer-io: command not found**
Compatible version of packer was found.
Correct version of vagrant was found.
Compatible version of vagrant-reload plugin was found.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: ./answer_files/2008_r2/Autounattend.xml
    virtualbox-iso: Copying file: ./scripts/configs/microsoft-updates.bat
    virtualbox-iso: Copying file: ./scripts/configs/win-updates.ps1
    virtualbox-iso: Copying file: ./scripts/installs/openssh.ps1
    virtualbox-iso: Copying file: ./resources/certs/oracle-cert.cer
    virtualbox-iso: Copying file: ./resources/certs/gdig2.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsadomainvalidationsecureserverca.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsacertificationauthority.crt
    virtualbox-iso: Copying file: ./resources/certs/addtrust_external_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/baltimore_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/digicert.cer
    virtualbox-iso: Copying file: ./resources/certs/equifax.cer
    virtualbox-iso: Copying file: ./resources/certs/globalsign.cer
    virtualbox-iso: Copying file: ./resources/certs/gte_cybertrust.cer
    virtualbox-iso: Copying file: ./resources/certs/microsoft_root_2011.cer
    virtualbox-iso: Copying file: ./resources/certs/thawte_primary_root.cer
    virtualbox-iso: Copying file: ./resources/certs/utn-userfirst.cer
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 4271)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1480597523 --memory 2048
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1480597523 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: 127.0.0.1:5917
**==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine** **'packer-virtualbox-iso-1480597523' has terminated unexpectedly during startup with exit code 1 (0x1)**
**==> virtualbox-iso: VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005),** **component MachineWrap, interface IMachine**
**==> virtualbox-iso: Unregistering and deleting virtual machine...**
**==> virtualbox-iso: Deleting output directory...**
**Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage: error: The virtual** **machine 'packer-virtualbox-iso-1480597523' has terminated unexpectedly during startup with** **exit code 1 (0x1)**
**VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap,** **interface IMachine**

**==> Some builds didn't complete successfully and had errors:**
**--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine** **'packer-virtualbox-iso-1480597523' has terminated unexpectedly during startup with exit code 1 (0x1)**
**VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap,** **interface IMachine**

**==> Builds finished but no artifacts were created.**
**Error building the Vagrant box using Packer. Please check the output above for any error messages.**

**Comment by jcase4444** [comment]
The first error is part of an if-else which checks for packer using 2 names "packer-io" and "packer" your system does not have "packer-io" but does have "packer"

`if compare_versions $($packer_bin -v) $min_packer_ver false; then
    echo "Compatible version of $packer_bin was found."
else
    packer_bin=packer
    if compare_versions $($packer_bin -v) $min_packer_ver false; then
        echo "Compatible version of $packer_bin was found."`

I have same build errors using build_win2008.sh and the json on Ubuntu 16.04 with packer 0.12.0, vagrant 1.9.0, and virtualbox 5.1.6

**Comment by w116tjb** [comment]
Having the same issue...

==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2629)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1481214537 --memory 2048
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1481214537 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: 127.0.0.1:5920
**==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'packer-virtualbox-iso-1481214537' has terminated unexpectedly during startup with exit code 1 (0x1)
==> virtualbox-iso: VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine**
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
**Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'packer-virtualbox-iso-1481214537' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine**

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'packer-virtualbox-iso-1481214537' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by jbarnett-r7** [comment]
Is this still an issue? Have you attempted to update to the latest version of all tools (vagrant, packer, VirtualBox)?

**Comment by aldo1901** [comment]
This is what I end up getting when running "vagrant up"


[image: Inline image 1]

**Comment by aldo1901** [comment]
In retrospect, I saw the thread about vagrant up failing and I think I can work with that. I posted this before looking at my VM, which I was able to log into.

**Comment by jbarnett-r7** [comment]
@aldo1901 I don't think the image came through. Can you please re-post it?

**Comment by aldo1901** [comment]
No need. I was able to get things up and running. I read another thread here and my problem was solved. 

-A
