### ISSUE TITLE
Vagrant up doesn´t work for KVM

### ISSUE THREAD

**Issue by bigfoot50** [rapid7/metasploitable3#540]
## Issue Description
Vagrant up doesn´t work for KVM.
Building work perfect.

## Host System
* OS: Centos7
* Packer Version:  1.7.3
* Vagrant Version: 2.2.16
* KVM 

## Command Output
[root@HV2 metasploitable3-master]# vagrant box add --name=metasploitable3-win2k8  packer/builds/windows_2008_r2_libvirt_0.1.0.box 
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3-win2k8' (v0) for provider: 
    box: Unpacking necessary files from: file:///meta/metasploitable3-master/packer/builds/windows_2008_r2_libvirt_0.1.0.box
==> box: Successfully added box 'metasploitable3-win2k8' (v0) for 'libvirt'!
[root@HV2 metasploitable3-master]# vagrant up --provider=libvirt win2k8
Bringing machine 'win2k8' up with 'libvirt' provider...
==> win2k8: Box 'rapid7/metasploitable3-win2k8' could not be found. Attempting to find and install...
    win2k8: Box Provider: libvirt
    win2k8: Box Version: >= 0
==> win2k8: Loading metadata for box 'rapid7/metasploitable3-win2k8'
    win2k8: URL: https://vagrantcloud.com/rapid7/metasploitable3-win2k8
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: rapid7/metasploitable3-win2k8
Address: https://vagrantcloud.com/rapid7/metasploitable3-win2k8
Requested provider: [:libvirt]

**Comment by jmartin-r7** [comment]
When you added the box it was not named the same as the name used in the `Vagrantfile`.

Your comment shows 
> `vagrant box add --name=metasploitable3-win2k8 packer/builds/windows_2008_r2_libvirt_0.1.0.box`

Which should have been
`vagrant box add --name=rapid7/metasploitable3-win2k8 packer/builds/windows_2008_r2_libvirt_0.1.0.box`

As the output suggests the box added is not being detected correctly by vagrant and the project does not currently have a published libvrt version in vagrant cloud.
```
Bringing machine 'win2k8' up with 'libvirt' provider...
==> win2k8: Box 'rapid7/metasploitable3-win2k8' could not be found. Attempting to find and install...
```
