### ISSUE TITLE
VMware support

### ISSUE THREAD

**Issue by bbdoron770** [rapid7/metasploitable3#55]
Hi,
Can I assume that I can build the VM in VirtualBox, export it, and then import it into VMware?

**Comment by jbarnett-r7** [comment]
That is a totally valid way to do it. We're looking at adding VMWare support eventually, but have some other priorities to attend to first. If anyone would like to take a stab at doing it before then that would be great. Just a note, though, there is a paid tool required to provision VMWare boxes with Vagrant.

**Comment by bbdoron770** [comment]
That is totally reasonable. I understand that a project like this needs to prioritise.
What do you mean by "there is a paid tool required to provision VMWare boxes with Vagrant?" I was hoping that I could build and provision the VM using VirtualBox and the other tools, and then export it to VMware and run it like any other VM. Isn't the "vagrant up" command only required on first startup, and vagrant is unnecessary afterwards?

**Comment by kevthehermit** [comment]
If you try to export ova an import to VMware  you will most likely be missing the NIC drivers. You can install them by adding a CDROM and installing vmxnet3 NIC drivers from the vmwaretools iso.

**Comment by usmcfiredog** [comment]
What is the status for adding full VMware support for those of us that have purchased the Vagrant VMware license?
