### ISSUE TITLE
WebException,Microsoft.PowerShell.Commands.InvokeCommandCommand

### ISSUE THREAD

**Issue by horytick** [rapid7/metasploitable3#550]
## Issue Description
I have the problem here, when it comes to " Provisioning with powershell script: ./scripts/configs/vagrant-ssh.ps1", failed.

## Host System
* OS: windows server 2008 r2
* Packer Version:1.3.5
* Vagrant Version:2.1.0
* VMware Version: workstation pro 16

## Command Output
    vmware-iso: VAGRANT-2008R2 restarted.
    vmware-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> vmware-iso: Machine successfully restarted, moving on
==> vmware-iso: Pausing 1m0s before the next provisioner...
==> vmware-iso: Provisioning with Powershell...
==> vmware-iso: Provisioning with powershell script: ./scripts/configs/vagrant-ssh.ps1
    vmware-iso: Invoke-Command : Exception calling "DownloadFile" with "2" argument(s): "The
    vmware-iso: underlying connection was closed: An unexpected error occurred on a send."
    vmware-iso: At C:\Windows\Temp\script-613a0ddb-ee7a-3c3b-7037-efc902206ef4.ps1:15 char:9
    vmware-iso: +         Invoke-Command -ScriptBlock $ScriptBlock -ArgumentList $Argum ...
    vmware-iso: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vmware-iso:     + CategoryInfo          : NotSpecified: (:) [Invoke-Command], MethodInvoca
    vmware-iso:    tionException
    vmware-iso:     + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.Invok
    vmware-iso:    eCommandCommand
    vmware-iso:
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by jmartin-r7** [comment]
As the error message reported: `The underlying connection was closed: An unexpected error occurred on a send`

This is a failure of network connectivity to the VM during the build process. Retry the build.
