### ISSUE TITLE
i am trying to download metasploit3 through provided link on powershell.  link:  invoke.....vagrantfile. but this is not working , problem showing . what should i do ?

### ISSUE THREAD

**Issue by Aadinath1234** [rapid7/metasploitable3#554]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host   ##System
* OS:window10
* Packer [1.7.8](
* Vagrant Version:2.2.18
* VirtualBox Version:6.1

## Command OutputCopy the relevant command output here. : remote name could not be resolved
![1636112561007](https://user-images.githubusercontent.com/93751167/140505714-1999a151-1017-4263-9ea3-398ffcdec6cf.jpg)

If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by bcoles** [comment]
> remote name could not be resolved

This implies that DNS resolution failed. Are you able to resolve `raw.githubusercontent.com` ?

**Comment by Aadinath1234** [comment]
> > remote name could not be resolved
> 
> This implies that DNS resolution failed. Are you able to resolve `raw.githubusercontent.com` ?

**Comment by Aadinath1234** [comment]
No
