### ISSUE TITLE
VirtualBox is not installed (or not in the expected location of C:\Program Files\Oracle\VirtualBox\)

### ISSUE THREAD

**Issue by D3athVlogs** [rapid7/metasploitable3#556]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Windows 10 
* Packer Version: 1.7.8
* Vagrant Version: 2.219
* VirtualBox Version: 6.1

## Command Output

PS C:\Users\matteo\Desktop\metasploitable3-master\metasploitable3-master> .\build.ps1 windows2008

VirtualBox is not installed (or not in the expected location of C:\Program Files\Oracle\VirtualBox\)
Please download and install it from https://www.virtualbox.org/

I have the virtualbox file at E:/Virtualbox, so i thought ill just go to Preferences and just change the Default Machine Folder To C:/Program Files/Oracle but that didnt seem to work.
I dont want to reinstall virtualbox cuz im scared to lose my 3 VMs.

**Comment by jmartin-r7** [comment]
The provided build script is based common defaults, if your environment does not meet these values you can adjust the script.

You can update `build.ps1` locally with your installed location see:

https://github.com/rapid7/metasploitable3/blob/45f273705d4fdaf0ad8c8cffa276a53e04869881/build.ps1#L8
