### ISSUE TITLE
pre-built win2k8 issues

### ISSUE THREAD

**Issue by cgkwork** [rapid7/metasploitable3#557]
How often is the win2k8 vmware_desktop image hosted on Vagrant Cloud built? Seems to indicate weekly, but I downloaded it two days ago (17 Nov 2021) and the image appears to have been built on 19 Sep 2021. The eval license for the OS is expired (so it shuts down an hour after booting). Also, the tomcat8 service is not completely configured and is not starting automatically.

**Comment by jmartin-r7** [comment]
Due to some yanked external sources the build has been failing to publish, a new build pushed this week.

**Comment by cgkwork** [comment]
> Due to some yanked external sources the build has been failing to publish, a new build pushed this week.

Thank you, however the tomcat8 service issue is still there.

**Comment by jmartin-r7** [comment]
@cgkwork, thanks we are aware some services are failing to configure properly, investigation is still ongoing.
