### ISSUE TITLE
checksum error during build

### ISSUE THREAD

**Issue by naterobbified** [rapid7/metasploitable3#56]
Get the following error when attempting to run build_win2008.sh:

root@kali:~/metasploitable3# ./build_win2008.sh 
Compatible version of VirtualBox found.
./build_win2008.sh: line 52: packer-io: command not found
Compatible version of packer was found.
Correct version of vagrant was found.
Compatible version of vagrant-reload plugin was found.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
    virtualbox-iso: Download progress: 1%
    virtualbox-iso: Download progress: 3%
---------------------------SNIP----------------------------
    virtualbox-iso: Download progress: 100%
    virtualbox-iso: Download progress: 100%
    **virtualbox-iso: Error downloading: checksums didn't match expected: 4263be2cf3c59177c45085c0a7bc6ca5**
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.

**Comment by bbdoron770** [comment]
You received a corrupted/incomplete iso. I recommend running the build file again.

**Comment by bcook-r7** [comment]
Yeah, this is an intentional message. Your download was corrupted and you need to try again.
