### ISSUE TITLE
Backslash and Backspace doesn't work

### ISSUE THREAD

**Issue by Eiffelsturm** [rapid7/metasploitable3#560]
## Issue Description
When connected to the M3 Windows version via SSH, I cannot use the Backslash or Backspace button. The Backspace just adds a space. The Backslash is shown in the window, but isn't recognized by the maschine (cd: C:wampalias: No such file or directory). I changed the keyboard layout locally on M3, but it doesn't fix it. I tried it from powershell and Putty. A restart doesn't solve it either. On my host, I'm using the german layout.
## Host System
* OS: Windows 10
* Packer Version: 1.7.8
* Vagrant Version: 2.2.19
* VirtualBox Version: 6.1.30

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.
cd: C:wampalias: No such file or directory

**Comment by jmartin-r7** [comment]
Access via ssh is not the expected usage for this VM, that being stated I tested ssh access using `putty` as a client from a Windows 10 system characters are sent.  The `ssh` service on this host provides a limited `sh` env and starting a `cmd` prompt does have some limitation in character interactions.

This would not be considered an issue for this product as the metastploitable3 project is not author of the ssh server utilized, however if there is a compatibility issue the project likely add some documentation on findings for future users.

You mention changing the keyboard layout in the VM, over ssh the `ssh client` should control what characters are sent to the connection. Can you provide additional details about how your `ssh client` is configured?  If using `putty` what keyboard options are set on the session connection?
