### ISSUE TITLE
Error with VNC

### ISSUE THREAD

**Issue by lkz0ne** [rapid7/metasploitable3#561]
## Issue Description
Error connecting to VNC in instalation of the metasploitable 3.

`## Host System
* OS: 5.15.0-kali2-amd64
* Packer Version: 1.2.3
* Vagrant Version: 2.2.19
* VirtualBox Version: 6.1

## Command Output
![Screenshot_2022-01-05_23-32-47](https://user-images.githubusercontent.com/64380275/148304850-1db99615-5174-4365-a804-35339cdab35d.png)

**Comment by lkz0ne** [comment]
Guys, any idea ?

**Comment by jmartin-r7** [comment]
You report using virtualbox:
> VirtualBox Version: 6.1

However your screenshot suggests that `packer` found `qemu` which would mean `libvirt` was determined to be the virtualization environment available.  Is it possible you have both installed? If so a quick solution would be to remove the libvirt `build` configuration from the packer json files. 

Removing these sections should shift detection to virtualbox:
https://github.com/rapid7/metasploitable3/blob/45f273705d4fdaf0ad8c8cffa276a53e04869881/packer/templates/windows_2008_r2.json#L133-L184
https://github.com/rapid7/metasploitable3/blob/45f273705d4fdaf0ad8c8cffa276a53e04869881/packer/templates/ubuntu_1404.json#L116-L150

**Comment by lkz0ne** [comment]
I not tried, but i solved my problem in another way.
