### ISSUE TITLE
Fails to install when running Vagrant WinRM error

### ISSUE THREAD

**Issue by andyman212** [rapid7/metasploitable3#59]
Run a couple of times elevated Powershell Any Ideas please 

==> default: C:\Windows\system32>rd /s /q C:\axis2
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_backdoors.bat as c:\tmp\vagrant-shell.bat
==> default: C:\Windows\system32>copy C:\vagrant\resources\backdoors\caidao.asp "C:\inetpub\wwwroot"
==> default:
==> default:         1 file(s) copied.
==> default:
==> default: C:\Windows\system32>copy C:\vagrant\resources\backdoors\mma.php "C:\wamp\www"
==> default:         1 file(s) copied.
==> default:
==> default: C:\Windows\system32>copy C:\vagrant\resources\backdoors\meterpreter.php "C:\wamp\www"
==> default:
==> default: The system cannot find the file specified.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:

Stderr from the command:

**Comment by jbarnett-r7** [comment]
It looks like the C:\vagrant\resources\backdoors\meterpreter.php file couldn't be found. Can you verify that file is in the cloned GitHub repo for Metasploitable3? Also, can you manually log in to Metasploitable3 and verify you can access that file.

**Comment by andyman212** [comment]
Thanks for your comment, Yes Cloned Yesterday from Github repo 

Cant start Metasplotable3 get this error 

![image](https://cloud.githubusercontent.com/assets/23129935/21022683/63baedec-bd75-11e6-95a0-4847c85c0a13.png)

**Comment by jbarnett-r7** [comment]
Interesting. I've seen a few people reporting that but have never seen it myself. What version of VirtualBox, packer, and Vagrant are you using?

**Comment by andyman212** [comment]
Vagrant 1.9.1
Packer 0.12.0 x64
virtual box 5.1.10

**Comment by andyman212** [comment]
I have cloned a fresh copy of the files from Github and after running Vagrant up it now completes and does not error still same error when trying to power on the VM. This is how the files look not sure if this is correct.

![image](https://cloud.githubusercontent.com/assets/23129935/21025647/102bb650-bd81-11e6-973c-8609356d19f7.png)

**Comment by jbarnett-r7** [comment]
Thanks for that info. I'm out of date on a few of those. I'll update and rebuild to see if one of them broke something.

**Comment by jbarnett-r7** [comment]
I tried with a few different version combinations and was not able to reproduce the issue with the VM not starting up. I'm on OSX, though. It looks like you're on Windows, which version specifically?

**Comment by Bungie2k** [comment]
i have the same issue on kali linux with all required software from the repo

**Comment by andyman212** [comment]
Working now after removing from virtual box and adding again the location it was pulling from was

C:\Users\Username\AppData\Local\Droid4X\vms

The Working VM was in

C:\Users\Username\VirtualBox VMs

Exported as OVF and imported to VMware only get a blank screen in VMware.

Thanks

**Comment by Bungie2k** [comment]
On Debian is the Vagrant Plugin winrm not included, manual install with:

vagrant plugin install winrm winrm-fs

source: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780036

**Comment by jbarnett-r7** [comment]
@andyman212 Do you think there was a change in default storage location and that is why the error is popping up? Is this specific to Windows?

**Comment by greenhand2learn** [comment]
@Bungie2k 
the next problem with it, how to solve it ?
```
Linux .... 4.8.0-kali2-amd64 #1 SMP Debian 4.8.11-1kali1 (2016-12-08) x86_64 GNU/Linux
Vagrant 1.8.5
packer 0.10.2
virtual box: 5.1.6
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
/usr/share/vagrant/plugins/communicators/winrm/shell.rb:165:in `new_session': uninitialized constant WinRM::WinRMWebService (NameError)
Did you mean?  WinRM::WinRMWMIError
	from /usr/share/vagrant/plugins/communicators/winrm/shell.rb:172:in `session'
	from /usr/share/vagrant/plugins/communicators/winrm/shell.rb:176:in `executor'
	from /usr/share/vagrant/plugins/communicators/winrm/shell.rb:59:in `powershell'
	from /usr/share/vagrant/plugins/communicators/winrm/communicator.rb:107:in `block in ready?'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /usr/share/vagrant/plugins/communicators/winrm/communicator.rb:106:in `ready?'
	from /usr/share/vagrant/plugins/communicators/winrm/communicator.rb:57:in `block in wait_for_ready'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /usr/share/vagrant/plugins/communicators/winrm/communicator.rb:31:in `wait_for_ready'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
	from /home/Charl3s/.vagrant.d/gems/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
```

**Comment by vkrzv** [comment]
I my case meterpreter.php was deleted by antivirus. :)
