### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by MayarBarakat** [rapid7/metasploitable3#601]
## Issue Description
Hay everyone, I am facing this problem after running this command ".\build.ps1 windows2008" .
I have tried a lot and change my VPN and stop windows defender and the error still showing.
would please anyone can help me to solve it?!!

## Host System
* OS: Windows 10 pro
* Packer Version: 1.9.1
* Vagrant Version: 2.3.7
* VirtualBox Version:7.0.8

## Command Output
PS D:\EthicalHackingCourses\resources\metasploitable3-master> .\build.ps1 windows2008

Compatible version of VirtualBox found.
Compatible version of Packer found.
Compatible version of Vagrant found.
Compatible version of vagrant-reload plugin found.
All requirements found. Proceeding...
Building metasploitable3-win2k8 Vagrant box...
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
==> virtualbox-iso: Trying E:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Trying file://E:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: file://E:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso => E:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying https://download.microsoft.com/download/4/1/D/41DEA7E0-B30D-4012-A1E3-F24DC03BA1BB/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
==> virtualbox-iso: Trying https://download.microsoft.com/download/4/1/D/41DEA7E0-B30D-4012-A1E3-F24DC03BA1BB/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso?checksum=md5%3A4263be2cf3c59177c45085c0a7bc6ca5
==> virtualbox-iso: Download failed read tcp 10.2.0.2:53776->23.1.245.9:443: wsarecv: An existing connection was forcibly closed by the remote host.
==> virtualbox-iso: error downloading ISO: [read tcp 10.2.0.2:53776->23.1.245.9:443: wsarecv: An existing connection was forcibly closed by the remote host.]
Build 'virtualbox-iso' errored after 20 minutes 2 seconds: error downloading ISO: [read tcp 10.2.0.2:53776->23.1.245.9:443: wsarecv: An existing connection was forcibly closed by the remote host.]

==> Wait completed after 20 minutes 2 seconds

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: error downloading ISO: [read tcp 10.2.0.2:53776->23.1.245.9:443: wsarecv: An existing connection was forcibly closed by the remote host.]

==> Builds finished but no artifacts were created.
Error building the Vagrant box using Packer. Please check the output above for any error messages.
At D:\EthicalHackingCourses\resources\metasploitable3-master\build.ps1:157 char:10
+          throw "Error building the Vagrant box using Packer. Please c ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error building ...error messages.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error building the Vagrant box using Packer. Please check the output above for any error messages.
![1](https://github.com/rapid7/metasploitable3/assets/63962441/aefd4bd2-f2c9-461f-af78-8e624ba628d9)

**Comment by jmartin-tech** [comment]
Report shows this was an network error during download:
```
Download failed read tcp 10.2.0.2:53776->23.1.245.9:443: wsarecv: An existing connection was forcibly closed by the remote host.
```
