### ISSUE TITLE
Cant login windows2k8

### ISSUE THREAD

**Issue by p01010101** [rapid7/metasploitable3#612]
## Issue Description

.
i cant logon on windows the screen say "Ctrl + Alt + Del" but when i do this nothing happens
## Host System
* OS: MacOS
* Packer Version: Sonoma
* Vagrant Version: 2.4
* VirtualBox Version: 7.0

**Comment by jmartin-tech** [comment]
This is an intentionally vulnerable VM, try other methods of access.

Also note that depending on the virtualization env you may need to ensure you are using the correct keyboard value when crossing from macOS to a Windows VM.
