### ISSUE TITLE
"Script exited with non-zero exit status: 36"

### ISSUE THREAD

**Issue by kaddish314** [rapid7/metasploitable3#616]
hi there. I'm trying to install VMBox on Ubuntu 22.04 via packer build --only=virtualbox-iso ./packer/templates/windows_2008_r2.json

after over 1h of successful process, it fails to complete. this is what's shown:

==> virtualbox-iso: Provisioning with shell script: /home/xoxoxo/metasploitable3-workspace/metasploitable3/packer/templates/../../scripts/installs/setup_apache_struts.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>del "\conf\tomcat-users.xml"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\apache_struts\tomcat-users.xml "\conf\tomcat-users.xml"
==> virtualbox-iso: The system cannot find the file specified.
==> virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:         0 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\apache_struts\server.xml "\conf"
    virtualbox-iso:         1 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config Tomcat8 start= auto
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start "Apache Tomcat 8.0 Tomcat8"
==> virtualbox-iso: The service name is invalid.
==> virtualbox-iso:
==> virtualbox-iso: More help is available by typing NET HELPMSG 2185.
==> virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy C:\vagrant\resources\apache_struts\struts2-rest-showcase.war "\webapps"
    virtualbox-iso:         1 file(s) copied.
==> virtualbox-iso: Provisioning with shell script: /home/xoxoxo/metasploitable3-workspace/metasploitable3/packer/templates/../../scripts/installs/setup_glassfish.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>mkdir C:\glassfish
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')"  0<NUL
==> virtualbox-iso: Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.
==> virtualbox-iso: SecurityProtocolType" due to invalid enumeration values. Specify one of the fol
==> virtualbox-iso: lowing enumeration values and try again. The possible enumeration values are "S
==> virtualbox-iso: sl3, Tls"."
==> virtualbox-iso: At line:1 char:28
==> virtualbox-iso: + [Net.ServicePointManager]:: <<<< SecurityProtocol = [Net.SecurityProtocolType
==> virtualbox-iso: ]::Tls12; (New-Object System.Net.WebClient).DownloadFile('http://download.java.
==> virtualbox-iso: net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')
==> virtualbox-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
==> virtualbox-iso:     + FullyQualifiedErrorId : PropertyAssignmentException
==> virtualbox-iso:
==> virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The underlying connecti
==> virtualbox-iso: on was closed: An unexpected error occurred on a send."
==> virtualbox-iso: At line:1 char:128
==> virtualbox-iso: + [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls
==> virtualbox-iso: 12; (New-Object System.Net.WebClient).DownloadFile <<<< ('http://download.java.
==> virtualbox-iso: net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')
==> virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> virtualbox-iso:     + FullyQualifiedErrorId : DotNetMethodException
==> virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" -y x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish"
    virtualbox-iso:
==> virtualbox-iso:
    virtualbox-iso: 7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
    virtualbox-iso:
==> virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: Scanning the drive for archives:
==> virtualbox-iso: C:\Windows\Temp\glassfish4.zip
    virtualbox-iso:
==> virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\glassfish\admin-keyfile" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\admin-keyfile"
==> virtualbox-iso:
==> virtualbox-iso:
    virtualbox-iso:         0 file(s) copied.
==> virtualbox-iso: System ERROR:
    virtualbox-iso:
==> virtualbox-iso: The system cannot find the file specified.
    virtualbox-iso: C:\Users\vagrant>copy /Y "C:\vagrant\resources\glassfish\domain.xml" "C:\glassfish\glassfish4\glassfish\domains\domain1\config\domain.xml"
==> virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso:         0 file(s) copied.
    virtualbox-iso:
==> virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso: C:\Users\vagrant>cmd.exe /c "C:\glassfish\glassfish4\bin\asadmin.bat create-service domain1"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net start domain1
==> virtualbox-iso: The system cannot find the path specified.
==> virtualbox-iso: The service name is invalid.
==> virtualbox-iso:
==> virtualbox-iso: More help is available by typing NET HELPMSG 2185.
==> virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 10"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>net stop domain1
==> virtualbox-iso: The service name is invalid.
==> virtualbox-iso:
==> virtualbox-iso: More help is available by typing NET HELPMSG 2185.
==> virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>icacls "C:\glassfish" /grant "NT Authority\LOCAL SERVICE:(OI)(CI)F" /T
    virtualbox-iso: processed file: C:\glassfish
    virtualbox-iso: Successfully processed 1 files; Failed processing 0 files
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    virtualbox-iso: [SC] OpenService FAILED 1060:
    virtualbox-iso:
    virtualbox-iso: The specified service does not exist as an installed service.
    virtualbox-iso:
==> virtualbox-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> virtualbox-iso: Cleaning up floppy disk...
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored after 1 hour 17 minutes: Script exited with non-zero exit status: 36. Allowed exit codes are: [0]

==> Wait completed after 1 hour 17 minutes

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 36. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

thanks in advance for your help.

**Comment by jmartin-tech** [comment]
Report above shows this was a network download failure. `The underlying connection was closed`

Relevant snip from above:
```
==> virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The underlying connecti
==> virtualbox-iso: on was closed: An unexpected error occurred on a send."
==> virtualbox-iso: At line:1 char:128
==> virtualbox-iso: + [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls
==> virtualbox-iso: 12; (New-Object System.Net.WebClient).DownloadFile <<<< ('http://download.java/.
==> virtualbox-iso: net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')
==> virtualbox-iso: + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
==> virtualbox-iso: + FullyQualifiedErrorId : DotNetMethodException
```

Validated current build using `master` branch at 68851936 completes Windows2008 creation.
