### ISSUE TITLE
packer in WSL windows cannot retrieve virtualbox VBoxGuestAdditions.iso

### ISSUE THREAD

**Issue by robertchen** [rapid7/metasploitable3#617]
## Issue Description
** Running packer in Windows WSL for virtualbox-iso builder, cannot retrieve virtualbox VBoxGuestAdditions.iso.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Windows 10 pro version 22h2
* Packer Version: 1.10 in WSL Ubuntu 22.04
* VirtualBox Version: 7.14 in windows

## Command Output
Copy the relevant command output here.
$ packer build -only=virtualbox-iso -var-file=ubuntu2204-desktop.json ubuntu.json
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
==> virtualbox-iso: Trying C:\devenv\VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Trying c:\devenv\VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Download failed error downloading 'c:\devenv\VirtualBox/VBoxGuestAdditions.iso'
==> virtualbox-iso: error downloading Guest additions: [error downloading 'c:\devenv\VirtualBox/VBoxGuestAdditions.iso']
Build 'virtualbox-iso' errored after 1 second 599 milliseconds: error downloading Guest additions: [error downloading 'c:\devenv\VirtualBox/VBoxGuestAdditions.iso']

==> Wait completed after 1 second 599 milliseconds

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: error downloading Guest additions: [error downloading 'c:\devenv\VirtualBox/VBoxGuestAdditions.iso']`

$ VBoxManage list systemproperties
API version:                     7_0
Minimum guest RAM size:          4 Megabytes
Maximum guest RAM size:          2097152 Megabytes
...
Maximum Devices per Floppy Port: 2
Default Guest Additions ISO:     C:\devenv\VirtualBox/VBoxGuestAdditions.iso

**Comment by jmartin-tech** [comment]
Is there a reason for running this in a WSL terminal? The project is tested for native OS support, have you tried building using `powershell` or `cmd`?

Note this issue is not within the control of this project as you are invoking `packer` directly, this would be an issue to report to [hashicorp/packer](https://github.com/hashicorp/packer).
