### ISSUE TITLE
I have sam problem so where is answer for this Q ?

### ISSUE THREAD

**Issue by milke-coa** [rapid7/metasploitable3#618]
I have sam problem so where is answer for this Q ?

[pencil3mark](https://github.com/pencil3mark) commented [on Jun 8, 2019](https://github.com/rapid7/metasploitable3/issues/396#issue-453768649)
Issue Description
my network can not get "http://archive.apache.org/dist/axis/axis2/java/core/1.6.0/axis2-1.6.0-war.zip", someone can send me another link, please

_Originally posted by @milke-coa in https://github.com/rapid7/metasploitable3/issues/396#issuecomment-2067662192_

**Comment by jmartin-tech** [comment]
The previous report was just an intermittent download failure in 2019. Now the url is redirecting to a TLS1.2 required path causing failure to download:

```
==> virtualbox-iso: Provisioning with shell script: /media/extra/metasploitable3/packer/templates/../../scripts/installs/setup_axis2.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://archive.apache.org/dist/axis/axis2/java/core/1.6.0/axis2-1.6.0-war.zip', 'C:\Windows\Temp\axis2-1.6.0-war.zip')"  0<NUL
==> virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The request was
==> virtualbox-iso: aborted: Could not create SSL/TLS secure channel."
==> virtualbox-iso: At line:1 char:1
==> virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile('http://archive.apache ...
==> virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> virtualbox-iso:     + FullyQualifiedErrorId : WebException
==> virtualbox-iso:
```

This should be fixed shortly.
