### ISSUE TITLE
Failure at vagrant up - ElasticSearch/WinRM

### ISSUE THREAD

**Issue by binaryAccess** [rapid7/metasploitable3#63]
## Issue Description
Failure occurred after executing vagrant up

## Host System
* OS: Linux kali 4.7.0-kali1-amd64 #1 SMP Debian 4.7.8-1kali1 (2016-10-24) x86_64 GNU/Linux
* Packer Version: 0.12.0
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.10

## Command Output
==> default: The service 'elasticsearch-service-x64' has been installed.
==> default: 
==> default: C:\Windows\system32>sc config "elasticsearch-service-x64" start= auto 
==> default: 
==> default: [SC] ChangeServiceConfig SUCCESS
==> default: C:\Windows\system32>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" start" 
==> default: The service 'elasticsearch-service-x64' has been started
==> default: 
==> default: C:\Windows\system32>powershell -Command "Start-Sleep -s 5" 
==> default: C:\Windows\system32>powershell -Command "$req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()" 
==> default: Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the
==> default: 
==> default:  remote server"
==> default: At line:1 char:124
==> default: + $req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploita
==> default: ble3/'); $req.method = 'PUT'; $req.GetResponse <<<< ()
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : DotNetMethodException
==> default:  
==> default: C:\Windows\system32>powershell -Command "$body = [System.Text.Encoding]::ASCII.GetBytes('{\"user\":\"kimchy\", \"post_date\": \"2009-11-15T14:12:12\", \"message\": \"Elasticsearch\" }'); $req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.method = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()" 
==> default: Exception calling "GetRequestStream" with "0" argument(s): "Unable to connect t
==> default: 
==> default: o the remote server"
==> default: At line:1 char:338
==> default: + $body = [System.Text.Encoding]::ASCII.GetBytes('{"user":"kimchy", "post_date"
==> default: : "2009-11-15T14:12:12", "message": "Elasticsearch" }'); $req = [System.Net.Htt
==> default: 
==> default: pWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.m
==> default: ethod = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream 
==> default: = $req.GetRequestStream <<<< (); $stream.Write($body, 0, $body.Length); $stream
==> default: 
==> default: .close(); $req.GetResponse()
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : DotNetMethodException
==> default:  
==> default: You cannot call a method on a null-valued expression.
==> default: At line:1 char:355
==> default: + $body = [System.Text.Encoding]::ASCII.GetBytes('{"user":"kimchy", "post_date"
==> default: : "2009-11-15T14:12:12", "message": "Elasticsearch" }'); $req = [System.Net.Htt
==> default: pWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.m
==> default: 
==> default: ethod = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream 
==> default: = $req.GetRequestStream(); $stream.Write <<<< ($body, 0, $body.Length); $stream
==> default: .close(); $req.GetResponse()
==> default: 
==> default:     + CategoryInfo          : InvalidOperation: (Write:String) [], RuntimeExce 
==> default:    ption
==> default:     + FullyQualifiedErrorId : InvokeMethodOnNull
==> default:  
==> default: You cannot call a method on a null-valued expression.
==> default: At line:1 char:394
==> default: + $body = [System.Text.Encoding]::ASCII.GetBytes('{"user":"kimchy", "post_date"
==> default: : "2009-11-15T14:12:12", "message": "Elasticsearch" }'); $req = [System.Net.Htt
==> default: pWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.m
==> default: 
==> default: ethod = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream 
==> default: = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close
==> default:  <<<< (); $req.GetResponse()
==> default:     + CategoryInfo          : InvalidOperation: (close:String) [], RuntimeExce 
==> default:    ption
==> default: 
==> default:     + FullyQualifiedErrorId : InvokeMethodOnNull
==> default:  
==> default: Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the
==> default:  remote server"
==> default: At line:1 char:414
==> default: + $body = [System.Text.Encoding]::ASCII.GetBytes('{"user":"kimchy", "post_date"
==> default: : "2009-11-15T14:12:12", "message": "Elasticsearch" }'); $req = [System.Net.Htt
==> default: pWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.m
==> default: ethod = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream 
==> default: = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close
==> default: (); $req.GetResponse <<<< ()
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : DotNetMethodException
==> default:  
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:

Stderr from the command:

**Comment by greenhand2learn** [comment]
i use kali system too. i have the problem with vagrant ip
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
/usr/share/vagrant/plugins/communicators/winrm/shell.rb:165:in `new_session': uninitialized constant WinRM::WinRMWebService (NameError)
Did you mean?  WinRM::WinRMWMIError
	from /usr/share/vagrant/plugins/communicators/winrm/shell.rb:172:in `session'
	from /usr/share/vagrant/plugins/communicators/winrm/shell.rb:176:in `executor'
	from /usr/share/vagrant/plugins/communicators/winrm/shell.rb:59:in `powershell'
	from /usr/share/vagrant/plugins/communicators/winrm/communicator.rb:107:in `block in ready?'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /usr/share/vagrant/plugins/communicators/winrm/communicator.rb:106:in `ready?'
	from /usr/share/vagrant/plugins/communicators/winrm/communicator.rb:57:in `block in wait_for_ready'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /usr/share/vagrant/plugins/communicators/winrm/communicator.rb:31:in `wait_for_ready'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
	from /home/Charl3s/.vagrant.d/gems/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
```

**Comment by jbarnett-r7** [comment]
Are you still having problems with the build? We've pushed a few fixes recently that may have resolved it.

**Comment by jikuja** [comment]
I'm getting same. Using 
* Current master: ef8fed0fd22bfe4
* OS: Debian testing
* Packer: v0.10.2
* Vagrant:  1.9.1
* Virtualbox: 5.1.14

Full log for `vagrant up` https://gist.githubusercontent.com/anonymous/8bdcc2621d9f49869b1c002f59d444ce/raw/2408ba6093a20231a759560db58954f87f1bc64f/elastic.log Seems to be identical with this and #73.

**Comment by a-garcia** [comment]
Hi everyone,

I changed the sleep time from 5 to 30 seconds within the metasploitable3\scripts\installs\install_elasticsearch.bat file. I believe that the original 5 seconds is not enough time for some machines to start elasticsearch and run a successful GetResponse(). 

The specific line that I changed in metasploitable3\scripts\installs\install_elasticsearch.bat file was from this:
powershell -Command "Start-Sleep -s 5"

to this:
powershell -Command "Start-Sleep -s 30"

This is the first time I have ever commented on anything on GitHub, so hopefully this helps with this specific problem.

This is what I am currently using, just in case anyone is wondering.
Packer: 0.12.2
Vagrant: 1.9.1
Virtualbox: 5.1.14

**Comment by jikuja** [comment]
Thanks. That fixed the problem.

**Comment by jbarnett-r7** [comment]
Nice fix, @a-garcia. Definitely sounds like that timer should be increased to have better support for more systems. Would you mind submitting a PR with the change?

**Comment by jikuja** [comment]
How much is enough for waiting time? Should it poll service until it's running and returning 200 for requests?

**Comment by a-garcia** [comment]
@jbarnett-r7, I have attempted to submit the PR, please let me know if you don't see it. I haven't worked on a project in awhile so my git skills are a little rusty. Just kind of started tinkering with metasploitable :).

@jikuja, that sounds like an efficient way of solving that issue. A blanket time frame may not be the most optimal solution. How about a try catch? An issue I see is if for some reason the service does not start for some reason, does the polling functionality eventually stop? I think either way there might have to be some kind of timing mechanism for the given scenarios.
