### ISSUE TITLE
vagrant up failing

### ISSUE THREAD

**Issue by veeyess** [rapid7/metasploitable3#75]
**Issue Description:**
Executing vagrant up fails with the following error, the error starts at #Install Chocolatey

**Host System:**
OS: Windows 10 x64
Vagrant: 1.9.1
Packer: 0.12.1
VirtualBox: 5.1.12 r112440

**Command Output:**

PS C:\Users\XXXXXX\metasploitable3_git> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'metasploitable3'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: metasploitable3_git_default_1482476193913_36700
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/XXXXXX/metasploitable3_git
==> default: Running provisioner: shell...
    default: Running: scripts/installs/chocolatey.cmd as c:\tmp\vagrant-shell.cmd
==> default: The argument 'C:\vagrant\scripts\installs\install_chocolatey.ps1' to the -File parameter does not exist. Pr
ovide the path to an existing '.ps1' file as an argument to the -File parameter.
==> default: Running provisioner: reload...
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/XXXXXX/metasploitable3_git
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: scripts/installs/install_boxstarter.bat as c:\tmp\vagrant-shell.bat
==> default: C:\Windows\system32>chocolatey feature enable -n=allowGlobalConfirmation
==> default: 'chocolatey' is not recognized as an internal or external command,
==> default: operable program or batch file.
==> default:
==> default: C:\Windows\system32>choco install BoxStarter
==> default: 'choco' is not recognized as an internal or external command,
==> default: operable program or batch file.
==> default:
==> default: C:\Windows\system32>chocolatey feature disable -n=allowGlobalConfirmation
==> default: 'chocolatey' is not recognized as an internal or external command,
==> default: operable program or batch file.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:

Stderr from the command:

PS C:\Users\XXXXXX\metasploitable3_git>

**Comment by elitedevx** [comment]
Guest additions has failed to install -- VM won't have access to the shared folder to complete provisioning.

**Comment by derhornspieler** [comment]
Confirming @elitedevx, Guest Additions are failing to install.  I went in an added a CDROM drive, then installed Guest Additions manually.  Seems to have moved past this error.

**Comment by adricnet** [comment]
Adding an optical drive also worked for me. After that a ```vagrant provision``` seems to have picked up the install just fine (next bump axis2). I did not need to manually install Guest Editions.

Thanks for all the awesomeness! :)

**Comment by axcheron** [comment]
This issue come from the Oracle certificate, it expired. 

<img src="https://cloud.githubusercontent.com/assets/5811920/21632969/3e27f81e-d219-11e6-83cd-139f12f0d68e.jpg" width="400px">

To fix this, I modified the `vm-guest-tools.bat` script to get the certificate from the *VBoxGuestAdditions.iso*.

**Before:**
```bash
:virtualbox

:: There needs to be Oracle CA (Certificate Authority) certificates installed in order
:: to prevent user intervention popups which will undermine a silent installation.
cmd /c certutil -addstore -f "TrustedPublisher" A:\oracle-cert.cer

move /Y C:\Users\vagrant\VBoxGuestAdditions.iso C:\Windows\Temp
cmd /c ""C:\Program Files\7-Zip\7z.exe" x C:\Windows\Temp\VBoxGuestAdditions.iso -oC:\Windows\Temp\virtualbox"
cmd /c C:\Windows\Temp\virtualbox\VBoxWindowsAdditions.exe /S
goto :done
```

**After:**
```bash
:virtualbox

move /Y C:\Users\vagrant\VBoxGuestAdditions.iso C:\Windows\Temp
cmd /c ""C:\Program Files\7-Zip\7z.exe" x C:\Windows\Temp\VBoxGuestAdditions.iso -oC:\Windows\Temp\virtualbox"

:: There needs to be Oracle CA (Certificate Authority) certificates installed in order
:: to prevent user intervention popups which will undermine a silent installation.
cmd /c certutil -addstore -f "TrustedPublisher" C:\Windows\Temp\virtualbox\cert\vbox-sha1.cer

cmd /c C:\Windows\Temp\virtualbox\VBoxWindowsAdditions.exe /S
goto :done
```

Now, you can run Packer to create a *.box* image with the VM tools installed ;)

**Comment by leveled** [comment]
I've been having trouble getting the VM provisioned properly, even after installing Guest Additions.  The provisioning process keeps halting here

~~~
    default: Running: scripts/installs/install_boxstarter.bat as c:\tmp\vagrant-shell.bat
==> default: C:\Windows\system32>net start "domain1 GlassFish Server"
==> default: The requested service has already been started.
==> default:
==> default:
==> default: More help is available by typing NET HELPMSG 2182.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

c:\tmp\vagrant-shell.bat

Stdout from the command:



Stderr from the command:
~~~

I've tried totally destroying the VM/vagrant box/etc. recloning the repo and building from scratch but provisioning continues to halt here. Is there anything I can do to fix this?

**Comment by veeyess** [comment]
Same here, fixing the Oracle certificate expiry issue took me further but now I am stuck at a later stage

**Comment by adricnet** [comment]
Ah, for that I made a tiny change to the setup_glassfish script make 7Zip overwrite the glassfish install files, which helped for multiple tries against the same build tree/VM. It's PR #77

**Comment by axcheron** [comment]
Well, that's kind of weird, I don't get this issue:

```bash
==> default: C:\Windows\system32>net start "domain1 GlassFish Server" 
==> default: The domain1 GlassFish Server service is starting.
==> default: The domain1 GlassFish Server service was started successfully.
```

I'm currently running the following versions:

**macOS Sierra 10.12.2** 
**Vagrant 1.9.1**
**Packer 0.12.1**
**VirtualBox 5.1.12 r112440**

**Comment by jbarnett-r7** [comment]
Thank you for posting about this and diagnosing the cause. I'm testing @axcheron changes now and will commit them once I've verified it locally.

**Comment by sporkisfaster** [comment]
Also getting a vagrant up error. Here's what I'm getting:

/home/metasploitable3# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'metasploitable3'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: metasploitable3_default_1484167360795_28726
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Running cleanup tasks for 'reload' provisioner...
==> default: Running cleanup tasks for 'reload' provisioner...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
/usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/communicators/winrm/shell.rb:169:in `new_session': uninitialized constant WinRM::WinRMWebService (NameError)
Did you mean?  WinRM::WinRMWMIError
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/communicators/winrm/shell.rb:176:in `session'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/communicators/winrm/shell.rb:65:in `cmd'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/communicators/winrm/communicator.rb:107:in `block in ready?'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/communicators/winrm/communicator.rb:106:in `ready?'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/communicators/winrm/communicator.rb:57:in `block in wait_for_ready'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/communicators/winrm/communicator.rb:31:in `wait_for_ready'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
	from /root/.vagrant.d/gems/2.3.3/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'

**Comment by bcook-r7** [comment]
Chatting with an Arch linux user a few days ago, we discovered that the version of vagrant that was packaged with that distribution did not actually include winrm support. I would recommend if you can installing vagrant from https://www.vagrantup.com/ or looking at how to add winrm to your particular distribution.

**Comment by sporkisfaster** [comment]
I also added winrm and get the same issue.

**Comment by bcook-r7** [comment]
Did you try something like:
```
vagrant plugin install winrm --plugin-version  1.8.1
```

**Comment by sporkisfaster** [comment]
I tried this line suggested in another issue:

```
vagrant plugin install winrm winrm-fs
```

and just 

```
vagrant plugin install winrm
```

Both seem to have a plugin successfully installed message but same issue.

**Comment by leonteale** [comment]
Also install these packages, otherwise you will encounter errors later on (https://github.com/rapid7/metasploitable3/issues/90 ): 
 
# vagrant plugin install winrm --plugin-version=1.8.1 
# vagrant plugin install winrm-fs --plugin-version=0.4.3
