### ISSUE TITLE
Packer and Vagrant for AWS

### ISSUE THREAD

**Issue by Erreinion** [rapid7/metasploitable3#76]
## Issue Description
Versions of the build files so that it can be built on AWS. AWS does have a Win 2008 R2 AMI available.

**Comment by Erreinion** [comment]
After much research, it appears that one simply needs the correct Win2k8 AMI and to edit the Packer config to point to AWS. I will transfer to the forums to discuss the best AMI to use.

**Comment by SpaceShipDev** [comment]
@Erreinion did this transfer to the forums happen, I'm keen to follow the AWS thread. Metasploitable in a VPC is a key need for most nowadays.

**Comment by rbeede** [comment]
https://github.com/jocic/AWS.Metasploitable3

Only https://github.com/jocic/AWS.Metasploitable3/blob/master/packer/templates/ubuntu_1404.json
