### ISSUE TITLE
build_win2008.ps1 Failing version check

### ISSUE THREAD

**Issue by sible777** [rapid7/metasploitable3#78]
## Issue Description
The CompareVesrion function fails for me at the exact match check.
This is similar to issue #48 which was closed. However the updated version of the script does not work for me. It could be something weird on my system, not sure. 

I did make a small change to the script and got it to work, see below:
```
function CompareVersions ($actualVersion, $expectedVersion, $exactMatch = $False) {
    If ($exactMatch -eq $True) {
    	Write-Host "Exact Match"
        If ($actualVersion -eq $expectedVersion) {
            return $True
        } else {
            return $False
        }
    }
... snip ...
``` 

I simply changed `If ($ExactMatch) {` to `If ($ExactMatch -eq $True) {` which fixed the error I was having.

Again, this may just be some quirk on my system in particular, I'm not sure.

## Host System
* OS: Windows 7
* Packer Version: 0.12.1
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.12r112440

**Comment by infosec-intern** [comment]
I'm not a developer on this, but I think line 37 in build_win2008.ps1 has the problem. --exactMatch inside the If conditional sends the string "--exactMatch" to the CompareVersions. I got the script working by removing one of these dashes

You can add `Write-Host "Inside exactMatch ($exactMatch)"` under line 10 and check to see if this is the problem. If you see something like below, then you and I are running into the same issue:
`Actual VBox version: 5.1.12
Expected VBox version: 5.1.10
Inside exactMatch (--exactMatch)`

The new edited line should look like
`If (CompareVersions -actualVersion $vboxVersion -expectedVersion $virtualBoxMinVersion -exactMatch $False) {`

I'll try to make a pull request tonight

**Comment by jbarnett-r7** [comment]
Thank you for fixing this one @infosec-intern!
