### ISSUE TITLE
vagrant up ? problem

### ISSUE THREAD

**Issue by vmwaretv** [rapid7/metasploitable3#83]
## Issue Description
Firstly build the packer. \ Windows_2008_r2.json
Vagrant box add after. \ Windows_2008_r2_virtualbox.box --name = metasploitable3
Finally, I run the vagrant up commands, but how do I resolve the vagrant up error?

## Host System
OS: Windows 10 Build 1607
Packer Version: packer_0.12.1_windows_amd64
Vagrant Version: vagrant_1.9.1
VirtualBox Version: Version 5.1.10 r112026 (Qt5.6.2)

## Command Output
PS D:\metasploitable3> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'reload' provisioner could not be found.
* The 'reload' provisioner could not be found.

**Comment by Sliim** [comment]
Hello,
you need to install the `reload` vagrant plugin.
```
vagrant plugin install vagrant-reload
```

**Comment by vmwaretv** [comment]
Thanx I did and result

C:\HashiCorp\Vagrant\bin>**_vagrant plugin install vagrant-reload_**
The directory where plugins are installed (the Vagrant home directory)
has a space in it. On Windows, there is a bug in Ruby when compiling
plugins into directories with spaces. Please move your Vagrant home
directory to a path without spaces and try again.

And try again, same result :( 

PS D:\metasploitable3> **_vagrant up_**
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'reload' provisioner could not be found.
* The 'reload' provisioner could not be found.

PS D:\metasploitable3>

**Comment by Sliim** [comment]
Install failed?
```
The directory where plugins are installed (the Vagrant home directory)
has a space in it. On Windows, there is a bug in Ruby when compiling
plugins into directories with spaces. Please move your Vagrant home
directory to a path without spaces and try again.
```

**Comment by vmwaretv** [comment]
I was install default.
I use guide this video for vargant install. 
[Video](https://www.youtube.com/watch?v=d6MBW9MoIDk)

**Comment by Sliim** [comment]
The **plugin** installation failed. See error message.

**Comment by vmwaretv** [comment]
I know and see but. How to fix this problem ?.
How to solve Plugin-in install problem ?
I was fresh install Windows 10 Pro.
I was fresh install vagrant and other component.
And always same problem. plugin-in install.

**Comment by Sliim** [comment]
Where is your vagrant home directory? If the path contains space(s), you need to:
- Move the vagrant home dir to an other folder without any spaces (the absolute path for vagrant home directory should not contains any spaces, as mentioned in the error message).
- (optional) Set the `VAGRANT_HOME` env var to the new path.

This should fix your issue.

This is not a metasploitable3 issue but a ruby/windows bug.
http://bfy.tw/9ZhN

**Comment by vmwaretv** [comment]
thax for help. I did solwe this problem.

C:\Users\**## User Name**\.vagrant.d
