### ISSUE TITLE
Vagrant up Error

### ISSUE THREAD

**Issue by JoGosGitHub** [rapid7/metasploitable3#84]
## Issue Description
Vagrant up fails at this point after executing WinRM.
I'm already using the new version with the WinRm 1.8.1 fix.

## Host System
* OS: Win7 x64
* Packer Version: 0.12.1
* Vagrant Version: 1.9.0
* VirtualBox Version: 5.1.12

## Command Output

```
INFO warden: Calling OUT action: #<Proc:0x498e70@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::Call:0x43081c8>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckVirtualbox:0x43081e0>
 INFO warden: Recovery complete.
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x45c3300>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: undefined method `split' for nil:NilClass
```

Please find the detailed log file [here](https://gist.github.com/JoGosGitHub/a6060b9d7e1c5ae85db6d33ab72ac89e)

and the Vagrant screen output [here](https://gist.github.com/JoGosGitHub/40bce02cfb4c8cc7d33ec8d6d941c412).

**Comment by jbarnett-r7** [comment]
Have you tried re-building recently? Are you still seeing this problem?

**Comment by JoGosGitHub** [comment]
thx @jbarnett-r7 , it's working.
Btw. I'm using the recommended Vagrant 1.9.1 Version.
