### ISSUE TITLE
Build Script usage of comparison function bug

### ISSUE THREAD

**Issue by DonkeyShoot** [rapid7/metasploitable3#86]
## Issue Description
The function in the powershell build script is called as follows (line 38): 
`If (CompareVersions -actualVersion $vboxVersion -expectedVersion $virtualBoxMinVersion --exactMatch $False)`
which sets the value of exactMath to "--exactMatch" instead of $False. 

The correct usage is: 
`If (CompareVersions -actualVersion $vboxVersion -expectedVersion $virtualBoxMinVersion -exactMatch $False)`

Secondly, I had to manually install the guest additions for virtualbox to make the shared folder link work for the vagrant scripts.

**Comment by jbarnett-r7** [comment]
This one was fixed with PR #79. Please try grabbing the latest code and see if that fixes it for you. Let us know if you're still seeing issues.
