### ISSUE TITLE
Problem with powershell

### ISSUE THREAD

**Issue by AgoraSecurity** [rapid7/metasploitable3#87]
## Issue Description
I can't execute the powershell

## Host System
* OS: Windows 10 Home. Version 1607
* Packer Version: Packer v0.12.2
* Vagrant Version: Vagrant 1.9.1
* VirtualBox Version: Versión 5.1.14 r112924 (Qt5.6.2)

## Command Output

C:\Users\Agora\Desktop\metasploitable3-master\metasploitable3-master>powershell -executionpolicy bypass -File build_win2008.ps1
No se puede llamar a un método en una expresión con valor NULL.
En C:\Users\Agora\Desktop\metasploitable3-master\metasploitable3-master\build_win2008.ps1: 17 Carácter: 5
+     $actualVersion = $actualVersion.split(".")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by OneLostHero** [comment]
I am having this problem as well, any ideas?

**Comment by jbarnett-r7** [comment]
I haven't tested personally, but I'm guessing this is related to having a non-English version of Windows. You could alter the script to work with the output you are getting from the command and that should make it work. All that method is doing is splitting up the version numbers between the "."

**Comment by OneLostHero** [comment]
I do have an english version of windows...
Could you list an example to fix the issue?

**Comment by jbarnett-r7** [comment]
Oh, interesting. Maybe the output of the -v option got changed for one of the versions it's checking. I'd need to see the full stack trace from the error to see which one is broken. Can you please post the full output from running the script?

**Comment by OneLostHero** [comment]
http://i.imgur.com/xrcGtLj.png

**Comment by busterb** [comment]
Try running:
`cmd.exe /c "C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" -v`

and

`cmd.exe /c "packer" -v`

Sounds like we're possibly not dealing with when these commands return an empty string because the tool is either not installed, or not in the path.

**Comment by OneLostHero** [comment]
Unless it's requiring VBox to be in the C drive? Mines in the D. everything else seems to be functioning correctly

**Comment by OneLostHero** [comment]
http://i.imgur.com/qym35Xn.png
Reinstalled VBox to C Drive

**Comment by OneLostHero** [comment]
Reinstalling Vagrant right not to c drive, will post results.

**Comment by jbarnett-r7** [comment]
Looks like @bcook-r7 is correct, we're not handling the empty strings correctly. We actually have error messages that indicate that the install location of things like VirtualBox aren't working properly, but if we don't handle the empty string I guess they never get shown. I'll have to update the script to handle that.

**Comment by OneLostHero** [comment]
http://i.imgur.com/qq2VeYb.png


After changing the directory of vagrant and Vbox to my C drive from my D drive
Everything seems to be working well now, thanks guys!

**Comment by OneLostHero** [comment]
Glad i could help a little! haha

**Comment by AgoraSecurity** [comment]
I also installed some stuff on D drive. I will reinstall and let you know.

**Comment by DarenIles** [comment]
I just changed the script to point to my vagrant location which wasn't in c:\hashicorp.  Seems to work from there.

**Comment by Chan9390** [comment]
@AgoraSecurity Any updates ?

**Comment by AgoraSecurity** [comment]
I forget to post the update.

Basically, when I reinstall everything on the C drive it worked.

I guess the script could be improved to detect on what drive the software is installed, or you could just install everything in C. :)

**Comment by spiderK3633** [comment]
i think itis the script problem,and i follow AgoraSecurity way to try.i make it
