### ISSUE TITLE
Vagrant up errors - Kali

### ISSUE THREAD

**Issue by spyder-7** [rapid7/metasploitable3#90]
## Issue Description
Tried, vagrant provision but didn't work

## Host System
* OS: Kali rolling
* Packer Version: 0.10.2
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.1.12

## Command Output
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- winrm (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/communicators/winrm/shell.rb:9:in `block in <top (required)>'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/communicators/winrm/shell.rb:8:in `<top (required)>'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/registry.rb:27:in `get'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/machine.rb:246:in `communicate'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/machine.rb:140:in `initialize'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/vagrantfile.rb:79:in `new'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:635:in `machine'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:210:in `block in with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:209:in `map'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:209:in `with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/commands/provision/command.rb:29:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:274:in `cli'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/bin/vagrant:122:in `<top (required)>'
	from /usr/bin/vagrant:22:in `load'
	from /usr/bin/vagrant:22:in `<main>'

**Comment by network23** [comment]
I had the same error message on Kali, try `gem install winrm` 
But I still get an error when I do `vagrant up`:

`/usr/lib/ruby/2.3.0/rubygems/specification.rb:2161:in `method_missing': undefined method `this' for #<Gem::Specification:0x2aff375676cc vagrant-1.9.1> (NoMethodError)
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:462:in `host'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:185:in `block in action_runner'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:33:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:445:in `hook'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:694:in `unload'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/bin/vagrant:125:in `ensure in <top (required)>'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/bin/vagrant:125:in `<top (required)>'
	from /usr/bin/vagrant:22:in `load'
	from /usr/bin/vagrant:22:in `<main>'`

**Comment by jikuja** [comment]
if running vagrant 1.9.1 install different plugin versions
vagrant plugin install winrm --plugin-version=1.8.1
vagrant plugin install winrm-fs --plugin-version=0.4.3

**Comment by Chan9390** [comment]
@spyder-7 Any updates after following the solution mentioned by @jikuja ?

**Comment by network23** [comment]
^ This worked for me. Thanks jikuja ^_^

**Comment by Taojune** [comment]
vagrant plugin install winrm
vagrant plugin install winrm-fs
vagrant up 
ok!!!

**Comment by Chan9390** [comment]
Closing the issue, as the above steps seems to resolve the error. Please reopen if you find some errors.
