### ISSUE TITLE
Vagrant up failing wamp - C:\Documents and Settings: Access Denied

### ISSUE THREAD

**Issue by 05zacwhi** [rapid7/metasploitable3#92]
## Issue Description
I am currently attempting to get metasploitable3 working for my university project but every time I commit vagrant up in Powershell it gets to up to installing wamp and fails I have tried different 64-bit operating systems, and I have tried cloning metasploitable3 from github with multiple no success. I have tried the auto install and the manual method as well.

## Host System
* OS: Windows 10 64-bit
* Packer Version: 0.12.2
* Vagrant Version: 1.9.2
* VirtualBox Version: 5.1.14

## Command Output
https://gist.github.com/05zacwhi/6a8d4af5197d2b153eff2571d9931243

**Comment by acicalla** [comment]
I am also getting the same issue. It appears that sourceforge is no longer hosting the file. 
Exception calling "DownloadFile" with "2" argument(s): "The remote server retur
ned an error: (404) Not Found."
At line:1 char:47
+ (New-Object System.Net.WebClient).DownloadFile <<<< ('http://sourceforge.mirr
orservice.org/w/wa/wampserver/WampServer 2/WampServer 2.2/wampserver2.2d-x64.ex
e', 'C:\Windows\Temp\wampserver2.2.d-x64.exe')

**Comment by acicalla** [comment]
You can try updating /scripts/installs/install_wamp.bat with a working location https://downloads.sourceforge.net/project/wampserver/WampServer%202/WampServer%202.2/wampserver2.2d-x64.exe

**Comment by 05zacwhi** [comment]
Thanks that worked :)
