### ISSUE TITLE
killed it in the end while exporting .ovf file 

### ISSUE THREAD

**Issue by marxenegls** [rapid7/metasploitable3#95]
## Issue Description
Second time it ran it ran completely had to edit the 2008-r2.iso's url and the <timezone> entry i left the lingo cause i have a qwerty but i presume europeans with azerty may have to keep it in mind to adapt locale settings ,I watched it in extacy run in Vbox ,installing and adding extra packages ,I quickly paused norton this time both anti virus which by the way complained of trojan and smart firewall .It Glitched when i terminated the .ovf export process and i lost everything. 
: ( 

...dont do it folks , be patient and wait it out, i'm gonna give it another go

## Host System
* OS:
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output:

PS C:\Users\marx\metasploitable\metasploitable3> packer build windows_2008_r2.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: file:///C:/Users/marx/metasploitable/metasploitable3/packer_cache/75e529d96d
6b175622512cf0a1bc55a5d1677e6a9d3b913fe95c65b6aa41770d.iso
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: ./answer_files/2008_r2/Autounattend.xml
    virtualbox-iso: Copying file: ./scripts/configs/microsoft-updates.bat
    virtualbox-iso: Copying file: ./scripts/configs/win-updates.ps1
    virtualbox-iso: Copying file: ./scripts/installs/openssh.ps1
    virtualbox-iso: Copying file: ./resources/certs/oracle-cert.cer
    virtualbox-iso: Copying file: ./resources/certs/gdig2.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsadomainvalidationsecureserverca.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsacertificationauthority.crt
    virtualbox-iso: Copying file: ./resources/certs/addtrust_external_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/baltimore_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/digicert.cer
    virtualbox-iso: Copying file: ./resources/certs/equifax.cer
    virtualbox-iso: Copying file: ./resources/certs/globalsign.cer
    virtualbox-iso: Copying file: ./resources/certs/gte_cybertrust.cer
    virtualbox-iso: Copying file: ./resources/certs/microsoft_root_2011.cer
    virtualbox-iso: Copying file: ./resources/certs/thawte_primary_root.cer
    virtualbox-iso: Copying file: ./resources/certs/utn-userfirst.cer
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3925)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1488875913 --memory 4096
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1488875913 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: rdp://127.0.0.1:5991
==> virtualbox-iso: Waiting 2m0s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Connected to SSH!
==> virtualbox-iso: Uploading VirtualBox version info (5.1.14)
==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
==> virtualbox-iso: Provisioning with shell script: ./scripts/installs/vm-guest-tools.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if not exist "C:\Windows\Temp\7z920-x64.msi" (powershell -Command "(New-Object Syst
em.Net.WebClient).DownloadFile('http://www.7-zip.org/a/7z920-x64.msi', 'C:\Windows\Temp\7z920-x64.msi')"  0<NUL )
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>msiexec /qb /i C:\Windows\Temp\7z920-x64.msi
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if "virtualbox-iso" EQU "vmware-iso" goto :vmware
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if "virtualbox-iso" EQU "virtualbox-iso" goto :virtualbox
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>move /Y C:\Users\vagrant\VBoxGuestAdditions.iso C:\Windows\Temp
    virtualbox-iso: 1 file(s) moved.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x C:\Windows\Temp\VBoxGuestAdditions.iso -o
C:\Windows\Temp\virtualbox"
    virtualbox-iso:
    virtualbox-iso: 7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
    virtualbox-iso:
    virtualbox-iso: Processing archive: C:\Windows\Temp\VBoxGuestAdditions.iso
    virtualbox-iso:
    virtualbox-iso: Extracting  32Bit
    virtualbox-iso: Extracting  32Bit\Readme.txt
    virtualbox-iso: Extracting  64Bit
    virtualbox-iso: Extracting  64Bit\Readme.txt
    virtualbox-iso: Extracting  AUTORUN.INF
    virtualbox-iso: Extracting  OS2
    virtualbox-iso: Extracting  OS2\VBoxControl.exe
    virtualbox-iso: Extracting  OS2\VBoxGuest.sys
    virtualbox-iso: Extracting  OS2\VBoxReplaceDll.exe
    virtualbox-iso: Extracting  OS2\VBoxService.exe
    virtualbox-iso: Extracting  OS2\gengradd.dll
    virtualbox-iso: Extracting  OS2\libc06.dll
    virtualbox-iso: Extracting  OS2\libc061.dll
    virtualbox-iso: Extracting  OS2\libc062.dll
    virtualbox-iso: Extracting  OS2\libc063.dll
    virtualbox-iso: Extracting  OS2\libc064.dll
    virtualbox-iso: Extracting  OS2\libc065.dll
    virtualbox-iso: Extracting  OS2\libc066.dll
    virtualbox-iso: Extracting  OS2\readme.txt
    virtualbox-iso: Extracting  OS2\vboxmouse.sys
    virtualbox-iso: Extracting  VBoxLinuxAdditions.run
    virtualbox-iso: Extracting  VBoxSolarisAdditions.pkg
    virtualbox-iso: Extracting  VBoxWindowsAdditions-amd64.exe
    virtualbox-iso: Extracting  VBoxWindowsAdditions-x86.exe
    virtualbox-iso: Extracting  VBoxWindowsAdditions.exe
    virtualbox-iso: Extracting  autorun.sh
    virtualbox-iso: Extracting  cert
    virtualbox-iso: Extracting  cert\VBoxCertUtil.exe
    virtualbox-iso: Extracting  cert\vbox-sha1.cer
    virtualbox-iso: Extracting  cert\vbox-sha256-r3.cer
    virtualbox-iso: Extracting  cert\vbox-sha256.cer
    virtualbox-iso: Extracting  runasroot.sh
    virtualbox-iso:
    virtualbox-iso: Everything is Ok
    virtualbox-iso:
    virtualbox-iso: Folders: 4
    virtualbox-iso: Files: 28
    virtualbox-iso: Size:       58956946
    virtualbox-iso: Compressed: 59369472
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "TrustedPublisher" C:\Windows\Temp\virtualbox\cert\vbo
x-sha1.cer
    virtualbox-iso: TrustedPublisher
    virtualbox-iso: Certificate "CN=Oracle Corporation, O=Oracle Corporation, L=Redwood Shores, S=California, C=US" adde
d to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c C:\Windows\Temp\virtualbox\VBoxWindowsAdditions.exe /S
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>goto :done
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>msiexec /qb /x C:\Windows\Temp\7z920-x64.msi
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/vagrant-ssh.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if exist a:\vagrant.pub (copy a:\vagrant.pub C:\Users\vagrant\.ssh\authorized_keys
)  else (powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/mitchell
h/vagrant/master/keys/vagrant.pub', 'C:\Users\vagrant\.ssh\authorized_keys')"  0<NUL )
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/disable-auto-logon.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
/v AutoAdminLogon /d 0 /f
    virtualbox-iso: The operation completed successfully.
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/enable-rdp.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>netsh advfirewall firewall add rule name="Open Port 3389" dir=in action=allow proto
col=TCP localport=3389
    virtualbox-iso: Ok.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fD
enyTSConnections /t REG_DWORD /d 0 /f
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/update_root_certs.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\addtrust_external_ca.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=AddTrust External CA Root, OU=AddTrust External TTP Network, O=AddTrust AB, C=SE" ad
ded to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\baltimore_ca.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\digicert.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US" added to sto
re.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\equifax.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "OU=Equifax Secure Certificate Authority, O=Equifax, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\globalsign.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\gte_cybertrust.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=GTE CyberTrust Global Root, OU="GTE CyberTrust Solutions, Inc.", O=GTE Corporation,
C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\microsoft_root_2011.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Was
hington, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\thawte_primary_root.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", O
U=Certification Services Division, O="thawte, Inc.", C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\utn-userfirst.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=UTN-USERFirst-Object, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt L
ake City, S=UT, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Preparing to export machine...
    virtualbox-iso: Deleting forwarded port mapping for the communicator (SSH, WinRM, etc) (host port 3925)
==> virtualbox-iso: Exporting virtual machine...
    virtualbox-iso: Executing: export packer-virtualbox-iso-1488875913 --output output-virtualbox-iso\packer-virtualbox-
iso-1488875913.ovf
==> virtualbox-iso: Error exporting virtual machine: VBoxManage error: 0%...CANCELED
==> virtualbox-iso: VBoxManage.exe: error: Appliance write failed
==> virtualbox-iso: VBoxManage.exe: error: File not accessible or erroneous file contents
==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interf
ace IAppliance
==> virtualbox-iso: VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleExportAppliance(struct HandlerArg *)"
 at line 1258 of file VBoxManageAppliance.cpp
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error exporting virtual machine: VBoxManage error: 0%...CANCELED
VBoxManage.exe: error: Appliance write failed
VBoxManage.exe: error: File not accessible or erroneous file contents
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleExportAppliance(struct HandlerArg *)" at line 1258 of fil
e VBoxManageAppliance.cpp
Cleanly cancelled builds after being interrupted.
PS C:\Users\marx\metasploitable\metasploitable3> 
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

**Comment by marxenegls** [comment]
another thing, after vagrant box add .bx --name and vagrant up the network host only nic will complain if other vboxes are using it ,typically it will craete a second one but the vbox wont start cause of invalid settings ,which turn out to be the video mem in virtualbox ,raising them to 100 did the trick for me .. I'm following the video on you tube by webpawnized the man is god sent.

**Comment by Chan9390** [comment]
Hey @marxenegls Please **mention host system details** along with the *free space on your hard disk*. From the above error message `virtualbox-iso: VBoxManage.exe: error: Appliance write failed` it is possible that lack of space could have caused the problem.
