### ISSUE TITLE
Vagrant up fails installing chocolatey with VirtualBox 5.1.16

### ISSUE THREAD

**Issue by e4ch** [rapid7/metasploitable3#97]
## Issue Description
I upgraded VirtualBox from 5.1.14 to 5.1.16 and got the error that chocolatey cannot get installed with an error message that the file from parameter -File in folder c:\vagrant\scripts\installs\install_chocolatey.ps1 cannot be found.
I don't have that folder (Vagrand is in c:\HashiCorp\Vagrant\ and in Vagrant there is no scripts folder).
This somehow comes from the command in chocolatey.cmd, which runs the parameter -File "%systemdrive%\vagrant\scripts\installs\install_chocolatey.ps1"
I don't know why this is working with VirtualBox 5.1.14, but it fails with VirtualBox 5.1.16.

## Host System
* OS: Windows 10 Pro trial 64-bit build 1607 (anniversary)
* Packer Version: 0.12.3 64-bit Win (unverified)
* Vagrant Version: 1.9.2 (unverified)
* VirtualBox Version: 5.1.16

## Command Output
vagrant up
output from someone else (I have already downgraded VirtualBox again): see http://pastebin.com/F5TSS3NB

**Comment by DarenIles** [comment]
I had same issue.  Upgrading to 5.1.18 resolved the issue.  Must be a bug in virtualbox.

**Comment by busterb** [comment]
Yep. I had issues building meterpreter on a shared drive as well. Looks to be related to these two regressions:

Shared Folders: fixed case insensitive filename access (5.1.16 regression; Windows guests only; bug #16549)
Shared Folders: fixed access to long pathes (5.1.16 regression; Windows guests only; bugs #14651, #16564)
